### ISSUE TITLE
P.377 nginx 설정파일 질문

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#100]
안녕하세요! P.377의 내용을 실습 도중 문제가 생겨 질문드립니다!
![nginx](https://user-images.githubusercontent.com/36075136/71399689-d1b4de80-2667-11ea-8d1f-5bf223407059.png)
책의 그림 10-9와 동일하게 작업하였으나
![nginx2](https://user-images.githubusercontent.com/36075136/71399720-eb562600-2667-11ea-83c0-9e5d7638ed9e.png)
해당 변수를 찾을수 없다고 출력됩니다.

include /etc/nginx/conf.d/service-url.inc

부분이 그림 10-9와 다르기에 해당 경로로 들어가 확인하였으나
존재하지 않습니다. ㅠㅠ

**Comment by jojoldu** [comment]
@RATSENO 제보 감사합니다!
include /etc/nginx/conf.d/service-url.inc 설정이 좀 더 뒤장에서 진행되는데 캡쳐에는 미리 포함되어있었던것 같습니다 ㅠ
해당 설정을 제거해주시면 됩니다!
10장 후반부에 해당 설정을 어떻게 추가하는지 나오니 제거 부탁드립니다 :)

**Comment by IMHOJEONG** [comment]
저도 같은 오류가 나서 보니 
밑에 코드는 있으니 $service_url만 http://localhost:8080으로 바꾸어서 진행하면 될 거 같습니다.

**Comment by RATSENO** [comment]
@jojoldu @IMHOJEONG 코멘트 감사합니다.
조언해 주신대로 수정하여 실행되었습니다 ^^
