### ISSUE TITLE
p.363 CodeDeploy 배포

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#102]
363page까지 실습해본 결과 travis-ci와 codedeploy 배포까지 성공하였는데

EC2 도메인을 접속하려고 하니 접속이 되지 않아서

step2의 nohup.out을 확인하여 

![image](https://user-images.githubusercontent.com/49624922/71423944-68b58100-26d0-11ea-8180-9d5ccba56d33.png)

위 사진과 같이 오류를 확인했는데

메모리 누수로 인한 오류가 발생하여 나타난 오류라는 것을 알게되어서

구글링을 통해 

JAVA_OPTS="-Djava.awt.headless=true -server -Xms256m -Xmx512m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC -Dfile.encoding=utf-8"

다음과 같은 메모리를 늘려주는 명령어를

![image](https://user-images.githubusercontent.com/49624922/71423977-c518a080-26d0-11ea-88a3-62a4de0e5b48.png)

최상단에 입력해주어 실행하면 된다는 정보를 얻어서 실행해보았는데

똑같은 오류가 나오네요 ㅜ

혹시 해결방법이 있을까요?

**Comment by jinyeanseok** [comment]
step1/deploy.sh를 실행하면 도메인이 정상적으로 실행이됩니다.

그러면 메모리 누수가 아닌거 아닌가요?

너무 어렵네요 ㅜㅜ

step1의 deploy.sh를 실행하면 정상적으로 되고
scripts/deploy.sh를 step2의 환경으로 옮기면 메모리 누수 에러가 발생하고..

그리고 궁금한게 있는데요

혹시 step2 환경에서 적용했던 deploy.sh를 

step1 환경에서 적용한 deploy.sh를 사용해도

자동배포가 될까요?

**Comment by jinyeanseok** [comment]
해결했습니다!!!

**Comment by jojoldu** [comment]
@jinyeanseok 앗 해결하셨다니 다행입니다 ㅠ

**Comment by slo-ow** [comment]
> 해결했습니다!!!

저는 step1 의 deploy.sh 를 실행하면 메모리 누수 에러가 발생 하는데 어떻게 해결 하셨는지 공유좀 해 주실수 있을까요?

**Comment by slo-ow** [comment]
저는 위의 코드를 넣어도 계속 메모리 부족 현상이 있어서
swapfile 을 만들어서 해결 했습니다.
https://aws.amazon.com/ko/premiumsupport/knowledge-center/ec2-memory-swap-file/
https://gethlemn.tistory.com/21
위와 같은 현상을 겪으시는 분들이 계시다면 이곳을 참조 하셔서 해결 하시기를 바랍니다.

**Comment by naldal** [comment]
감사합니다 많은 도움 받았습니다...
