### ISSUE TITLE
[질문] EC2에서 소셜 로그인하기 질문

### ISSUE THREAD

**Issue by loverman85** [jojoldu/freelec-springboot2-webservice#103]
안녕하세요

ec2에서 소셜로그인 하기 하다가 안되서요ㅠㅠ 로그인 화면은 가지만 로그인이 되지않아요ㅠ

java.sql.SQLSyntaxErrorException: (conn=544) Table 'springboot1.hibernate_sequence' doesn't exist

이라는 에러가 발생되네요.. 뭐가 문제일까요??
<img width="1631" alt="스크린샷 2019-12-25 오후 6 02 13" src="https://user-images.githubusercontent.com/22947274/71440586-faf56d80-2740-11ea-89db-3a1210544b26.png">

**Comment by loverman85** [comment]
스스로 다시 보면서 해결했습니다.
혹시 다른분들에게 도움이 될까 남깁니다.
여러가지 문제가 있었는데 결과적으로는 테이블 생성을 잘못했던게 문제였습니다.

첫번째 User entity에 @GeneratedValue(strategy = GenerationType.IDENTITY) 
strategy 를 빼먹었고, extends BaseTimeEntity 를 빼먹었네요..

그리고 table 생성할때
로컬에서 돌린 hibernate 로그로 했는데.. 전 mysql 버전으로 바꾸는 설정을 하지 않아서 테이블생성할때 이상하게 생성되었던 거네요ㅠ
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

결론은 User entity를 빼먹은 부분 다시 작성하고 myslq 문법으로 출력되도록 설정하고 로컬에서 돌려 테이블 다시 생성해주어서 해결했습니다ㅠㅠ

**Comment by jojoldu** [comment]
@loverman85 네! 스프링 부트 2.0 이 되면서 여러 부분들이 변경이 되었는데요 :)
해당 부분도 크게 변경된 부분중에 하나입니다.

좀 더 자세히 알고 싶으시면 예전에 포스팅했던 https://jojoldu.tistory.com/295 를 참고해보시면 좋을것 같습니다!
