### ISSUE TITLE
EC2 프로젝트 배포 관련 질문입니다.

### ISSUE THREAD

**Issue by osj4532** [jojoldu/freelec-springboot2-webservice#104]
안녕하세요
처음에 ./gradlew test로 테스트를 해보면
![image](https://user-images.githubusercontent.com/38102670/71445321-06a25d80-275c-11ea-96bd-06a34d1e434c.png)
이와 같이  shoutdown 메세지가 출력됩니다. 
build success가 출력되서 다음 과정을 진행해도 
책에서 말하는 ClientRegistrationRepository that could not be found 에러가 발생하지 않습니다.

그후 oauth.properties를 추가하면
![image](https://user-images.githubusercontent.com/38102670/71445639-8e896700-275e-11ea-9800-08114316c30b.png)
위와 같이 나옵니다. 이런 문제를 어떻게 해결해야 하는지 알려주시면 정말 감사하겠습니다;

감사합니다.

**Comment by jojoldu** [comment]
@osj4532 안녕하세요 :)
해당 이슈가 요 이슈 (https://github.com/jojoldu/freelec-springboot2-webservice/issues/97#issuecomment-568990445) 와 같은 이슈인것 같습니다 :)
확인 부탁드립니다.

**Comment by osj4532** [comment]
앗 정말 감사합니다. ㅜㅜ

**Comment by jojoldu** [comment]
@osj4532 넵 감사합니다 :)
