### ISSUE TITLE
[1판] p.393 switch.sh의 \$service_url 오타 수정

### ISSUE THREAD

**Issue by IMHOJEONG** [jojoldu/freelec-springboot2-webservice#105]
switch.sh의 echo "set \$service_url~~ 로 되어있는 것을 echo "set $service_url~~로 바꾸어야 할 거 같습니다.

**Comment by jojoldu** [comment]
앗 이슈 제거하면 될까요? ㅎㅎ

**Comment by IMHOJEONG** [comment]
네 제가 이미 있는 거 확인 못하고 올려서 죄송합니다 ㅠㅠ
