### ISSUE TITLE
p.73 테스트코드가 작동안합니다 ㅠ

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#106]
[https://okky.kr/article/664463](OKKY에도 질문올렸는데 답변자 말로는 final필드 초기값 문제라고 합니다)

안녕하세요 스프링부트 책으로 실습중에 안되는게 있어서 여기에 질문남깁니다..
책 73페이지 테스트가 자꾸 실패하는데 롬복이 컴파일이 안돼서 실패하는거 같기도하고(이 경우에는 이유를 모르겠습니다. 의존성도 확인했고 플러그인설정, enable annotation도 확인 결과 이상없었습니다), dto에서 final 필드에 아무 값을 넣지 않은채로 만들어서 그런거 같기도 한데... 책에 나온 코드대로 그대로 하는데 테스트 실패하는 이유를 모르겠습니다..

(dto에서 Delombok한 후에 테스트하니까 통과합니다... 이유를 모르겟네요 롬복이 작동안하는건지..)

**Comment by jojoldu** [comment]
안녕하세요 :)
혹시 그레이들 버전을 한번 체크해보시겠어요?

https://github.com/jojoldu/freelec-springboot2-webservice#%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%99%98%EA%B2%BD-%EC%A0%90%EA%B2%80
