### ISSUE TITLE
118페이지  예제 문의 드립니다

### ISSUE THREAD

**Issue by zuctoma85** [jojoldu/freelec-springboot2-webservice#107]
h2-console에서  insert 실행 후 

http://localhost:8080/api/v1/posts/1 로 접속했을 때 이렇게 나옵니다..

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 26 15:03:38 KST 2019
There was an unexpected error (type=Internal Server Error, status=500).
No converter found for return value of type: class kr.co.toto.web.dto.PostsResponseDto

콘솔창에는 
Hibernate: select posts0_.id as id1_0_0_, posts0_.author as author2_0_0_, posts0_.content as content3_0_0_, posts0_.title as title4_0_0_ from posts posts0_ where posts0_.id=?
2019-12-26 15:03:38.374  WARN 3844 --- [nio-8080-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: No converter found for return value of type: class kr.co.toto.web.dto.PostsResponseDto]

이렇게 뜨구요 어떤게 문제인지 몰라 문의 드립니다

**Comment by jojoldu** [comment]
@zuctoma85 님 안녕하세요 :)
에러 메세지만 봐서는 어떻게 코드를 작성하신지 알수가 없어 추측밖에 할수가 없고요 :)
실제 작성하신 프로젝트를 Github에 올려주셔서 Github 주소를 알려주시면 확인후 말씀드리겠습니다.

**Comment by zuctoma85** [comment]
> @zuctoma85 님 안녕하세요 :)
> 에러 메세지만 봐서는 어떻게 코드를 작성하신지 알수가 없어 추측밖에 할수가 없고요 :)
> 실제 작성하신 프로젝트를 Github에 올려주셔서 Github 주소를 알려주시면 확인후 말씀드리겠습니다.

git에 올렸고
https://github.com/zuctoma85/freelec-springboot2-webservice
입니다~ 감사합니다

**Comment by jojoldu** [comment]
@zuctoma85 님 확인했는데요 :)

아래와 같이 @Getter, @NoArgsConstructor 가 누락되어서 오류가 발생했습니다.

![image](https://user-images.githubusercontent.com/7760496/71465771-d234ad00-2800-11ea-92dd-d9dce26703b7.png)

검증은 아래의 테스트 코드를 추가해서 확인해보았습니다 :)

```
@Test
    public void Posts_조회된다() throws  Exception {
        //given
        Posts savePosts = postsRepository.save(Posts.builder()
                .title("title")
                .content("content")
                .author("author")
                .build());

        String url = "http://localhost:"+ port + "/api/v1/posts/" + savePosts.getId();

        HttpEntity<String> requestEntity = new HttpEntity<>("");

        //when
        ResponseEntity<PostsResponseDto> responseEntity = restTemplate.exchange(url, HttpMethod.GET, requestEntity, PostsResponseDto.class);

        //then
        assertThat(responseEntity.getStatusCode()).isEqualTo(HttpStatus.OK);
    }
```

@RestController를 사용한다는 것은 **객체를 JSON으로 변환**해서 반환하는 것을 의미하는데요.
JSON 변환시 **기본 생성자와 Getter 메소드**가 없으면 JSON 컨버터는 어떻게 변환해야할지 알수가 없습니다.
그래서 이 둘은 꼭 필요하니 **API 응답용 DTO에선 필수로** 추가 부탁드려요 :)

**Comment by zuctoma85** [comment]
> @zuctoma85 님 확인했는데요 :)
> 
> 아래와 같이 @getter, @NoArgsConstructor 가 누락되어서 오류가 발생했습니다.
> 
> ![image](https://user-images.githubusercontent.com/7760496/71465771-d234ad00-2800-11ea-92dd-d9dce26703b7.png)
> 
> 검증은 아래의 테스트 코드를 추가해서 확인해보았습니다 :)
> 
> ```
> @Test
>     public void Posts_조회된다() throws  Exception {
>         //given
>         Posts savePosts = postsRepository.save(Posts.builder()
>                 .title("title")
>                 .content("content")
>                 .author("author")
>                 .build());
> 
>         String url = "http://localhost:"+ port + "/api/v1/posts/" + savePosts.getId();
> 
>         HttpEntity<String> requestEntity = new HttpEntity<>("");
> 
>         //when
>         ResponseEntity<PostsResponseDto> responseEntity = restTemplate.exchange(url, HttpMethod.GET, requestEntity, PostsResponseDto.class);
> 
>         //then
>         assertThat(responseEntity.getStatusCode()).isEqualTo(HttpStatus.OK);
>     }
> ```
> 
> @RestController를 사용한다는 것은 **객체를 JSON으로 변환**해서 반환하는 것을 의미하는데요.
> JSON 변환시 **기본 생성자와 Getter 메소드**가 없으면 JSON 컨버터는 어떻게 변환해야할지 알수가 없습니다.
> 그래서 이 둘은 꼭 필요하니 **API 응답용 DTO에선 필수로** 추가 부탁드려요 :)

자세한 답변 감사합니다~~~
