### ISSUE TITLE
[질문] 358p ~ 360p 배포 자동화 구성 deploy.sh 관련

### ISSUE THREAD

**Issue by osj4532** [jojoldu/freelec-springboot2-webservice#108]
안녕하세요. 책 잘 보면서 공부하고 있습니다.
다름이 아니라 배포 자동화 스크립트가 부분부분 작동이 안돼는 것 같아서 질문 드립니다.
다른 것들은 잘 작동 하는 것같은데 구동중인 애플리케이션 판별 후 if - else - fi 부분과
마지막 줄 nohup부분이 동작을 안하는 것 같습니다. 새 버전을 실제로 push후에 수동으로 kill후 nohup명령어를 적용하면 작동 되는데 자동으로 배포가 되지 않아서 질문드립니다.
감사합니다 :)

혹시 몰라서 codedeploy-agent.log 파일 부분도 첨부해 봅니다.
![image](https://user-images.githubusercontent.com/38102670/71476123-da9fde80-2826-11ea-9d91-492359c175f1.png)

**Comment by jojoldu** [comment]
@osj4532 님 안녕하세요 :)
혹시 /opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log 의 전체 파일도 올려주실수있으실까요?

**Comment by osj4532** [comment]
안녕하세요 :)
여기서 로그 파일을 볼수 있는 건 처음 알았습니다. 말씀하신 로그파일 사진입니다.
![image](https://user-images.githubusercontent.com/38102670/71555717-a15bae80-2a72-11ea-9d44-38c0d273fcea.png)

혹시 몰라서 다른 것들도 남겨 놓겠습니다.
[oauth, real-db 위치]
![image](https://user-images.githubusercontent.com/38102670/71555821-5726fd00-2a73-11ea-8898-6b238b308f7b.png)

[deploy.sh 안에 nohup 부분]
![image](https://user-images.githubusercontent.com/38102670/71555848-99503e80-2a73-11ea-82a6-4dc86f929b02.png)

제가 보기엔 책이랑 똑같이 따라한거 같은데 어떤 문제가 있는지 알려주시면 정말 도움이 많이 될거 같습니다. 감사합니다. 연말 즐겁게 보내세요.

**Comment by jojoldu** [comment]
@osj4532 님! 위에 로그를 보니 아래와 같이 에러 메세지가 나와있는데요 :)

![image](https://user-images.githubusercontent.com/7760496/71766014-8db2bb00-2f3e-11ea-903b-8444a8e6c50a.png)

역슬래시 (\) 가 없으면 **아래줄은 같은 줄로 인식을 못합니다**

deploy.sh에 있는 nohup 에 책과 동일하게 역슬래시들을 다 넣어보시겠어요?

**Comment by osj4532** [comment]
감사합니다. 역슬래시 넣으니까 nohup문제는 해결 했는데 kill에서 오류가 나서 삽질하다보니 projectname에서 오류 찾고 해결했습니다.

**Comment by jojoldu** [comment]
@osj4532 고생하셨습니다!
