### ISSUE TITLE
[질문] p.190 ~ p.192 쪽 google 로그인 관련

### ISSUE THREAD

**Issue by SimJunSik** [jojoldu/freelec-springboot2-webservice#109]
책 따라서 잘 하다가 마지막 확인하는 부분에서 구글 로그인을 했을 때
user가 계속 null로 나옵니다. db에도 저장이 안되구요

session에 저장이 안되서 계속 null로 나온건지 어쩐건지..
오타가 있는건 아닌데 어느부분에서 잘못되었을까요 ㅠㅠ

**Comment by SimJunSik** [comment]
조금만 더 살펴보고 올릴 걸 그랬네요. 해결 됐습니다! 아 그리고 책 정말 잘 보고 있습니다 감사합니다

**Comment by jojoldu** [comment]
@SimJunSik 앗 아닙니다 :) 편하게 올려주세요!
해결하시느라 고생하셨습니다 :)

**Comment by zhtmr** [comment]
저도 지금 세션이 작동안하는것 같아서 찾아왔는데 관련 답변이 없네요 ㅠㅠㅠㅠㅠ
