### ISSUE TITLE
p.206 네이버 로그인 application-oauth.properties 관련

### ISSUE THREAD

**Issue by shbaek** [jojoldu/freelec-springboot2-webservice#11]
p.206 네이버 로그인 application-oauth.properties 파일

기존) spring.security.oauth2.client.registration.naver.**redirect_uri_template**={baseUrl}/{action}/oauth2/code/{registrationId}

변경) spring.security.oauth2.client.registration.naver.**redirect-uri**={baseUrl}/{action}/oauth2/code/{registrationId}

네이버 로그인 테스트 중에 기존 코드대로 로그인이 안되서 아래 방법으로  로그인 성공해서 이슈 등록 합니다.

**Comment by jojoldu** [comment]
@shbaek 앗? 다시 실습해서 확인해보겠습니다!

**Comment by jojoldu** [comment]
@shbaek 님! 혹시 사용하시는 스프링 부트 버전이 어떤거신가요?
2.1.7 버전에서 테스트할때는 redirect_uri_template 로도 가능은 한데요! 
(물론 Deprecated 되어서 redirect-uri 사용하시는게 맞습니다!)

혹시 다른 버전을 사용중이실까요?

**Comment by shbaek** [comment]
아 현재 스프링 부트 버전 2.2 버전으로 진행 하고 있습니다.  ^^

**Comment by jojoldu** [comment]
@shbaek 아! 넵넵 이 책의 모든 코드가 2.1.7 기준으로 되어있는데,
아마도 해당 설정이 2.2에서 삭제된것 같습니다 :)
하지만 말씀하신대로 redirect-uri 값이 2.1.7 ~ 2.2 모두에서 사용되는 값이니 3쇄에서는 반영해놓겠습니다 :)
정말 좋은 제보 감사드립니다!
