### ISSUE TITLE
page 181 질문입니다

### ISSUE THREAD

**Issue by S-Onix** [jojoldu/freelec-springboot2-webservice#110]
4번의 설명을 보면 마지막 목록에 **POST 메소드이면서** 라고 작성해주셨는데 POST 메소드라는 것은 어디서 알수있는 부분인가요?

**Comment by jojoldu** [comment]
@S-Onix 앗 ㅠ 죄송합니다 해당 부분은 오타입니다 ㅠ
POST 메소 제한 코드가 들어갔다가 빠지면서 설명 부분은 같이 안빠져서 누락되었습니다 ㅠ
해당 텍스트는 무시해서 봐주세요!
