### ISSUE TITLE
.travis.yml zip 명령어 관련 질문입니다.

### ISSUE THREAD

**Issue by irerin07** [jojoldu/freelec-springboot2-webservice#113]
책 버전 yml
before_deploy:
  - zip -r com.tistory.irerin07-webservice *

책에 나온대로 작성한 yml은 다음과 같은 에러가 발생했습니다.
![image](https://user-images.githubusercontent.com/39554427/71539541-ebfcfe00-2980-11ea-8c9f-022bfa9102c4.png)

구글에서 zip 명령어를 검색해보니 

$zip –r filename.zip directory_name 과 같이 작성하라고 나와서 

수정한 yml
before_deploy:
  - zip -r com.tistory.irerin07-webservice.zip *

위와 같이 수정을 하니 문제 없이 빌드가 되었습니다.

제가 수정한대로 사용해도 문제가 없을까요?

그리고 왜 책에 나온 코드를 사용하면 계속 에러가 나는걸까요?

**Comment by jojoldu** [comment]
음 이상하네요
일단 작성하신 코드에서 zip -r com.tistory.irerin07-webservice.zip * 는 올바른 방식이 아닙니다
검색해서 나오신것처럼 
**디렉토리 네임**을 지정해야하는데 수정하신 코드는 **zip파일을 지정하셨지않나요** ? 
위 코드가 빌드가 되어도 압축 해제했을때 AWS Code Deploy에서 지정하는 path와 달라서 문제가 있을것으로 보이는데, 아마 직접 배포해서 에러로그를 보셔야 될것 같습니다.

제 생각엔 현재 **프로젝트명에 .을 추가하셔서 path상에 문제가 계속 발생하는것 같습니다**

보편적으로 프로젝트 명에 .을 추가하진 않습니다.
.은 패키지에서 나타내기 위함이지,
프로젝트에서는 흔히말하는 대시(-)와 소문자로 사용되니 깃헙 저장소를 irerin07-webservice 로 새로 생성해서 진행해보시는게 좀 더 나으실것 같다고 생각됩니다.

**Comment by irerin07** [comment]
@jojoldu 
그럼 우선 저장소명을 변경하여 다시 진행해보겠습니다!
빠른 답변 감사합니다!

**Comment by jojoldu** [comment]
@irerin07 넵넵! 혹시나 안되시면 다시 남겨주세요!
감사합니다 :)
