### ISSUE TITLE
P.104 첫줄 오타, P.134 3번째 줄 오타

### ISSUE THREAD

**Issue by ddojai** [jojoldu/freelec-springboot2-webservice#114]
P.104 첫줄 오타
as-is :
deliveryDao.update(billing);
to-be :
billingDao.update(billing);

**Comment by ddojai** [comment]
P.134 3번째 줄 오타
as-is:
estRestTemplate
to-be:
TestRestTemplate

**Comment by jojoldu** [comment]
@ddojai 님 제보 감사합니다 :)
위 이슈는 3쇄에 정상적으로 반영될 예정입니다 :)
