### ISSUE TITLE
[질문] p388 profile.sh

### ISSUE THREAD

**Issue by loverman85** [jojoldu/freelec-springboot2-webservice#116]
안녕하세요 이제 거의다 끝나가네요!ㅎㅎ
궁금한게 있는데요~

profile.sh 에서 쉬고있는 profile 을 찾는중에

if [ ${RESPONSE_CODE} -ge 400 ]
  then
    CURRENT_PROFILE=real2
  else
    CURRENT_PROFILE=$(curl -s http://localhost/profile)
  fi

이 조건문을 보면 에러가 발생한 경우 CURRENT_PROFILE을 real2 로 해주는데..
혹 이유가 있나요? 아니면 그냥 real1으로 붙도록 하려고 한건가요??

**Comment by jojoldu** [comment]
@loverman85 님 거의  다 오셨네요 :)
말씀하신대로 이슈가 있을 경우 real1에 배포하기 위해서 강제로 현재 포트를 real2로 두는 정책을 사용했습니다 :)
