### ISSUE TITLE
p.129 어색한 문장 수정

### ISSUE THREAD

**Issue by joshua-qa** [jojoldu/freelec-springboot2-webservice#117]
동욱님 안녕하세요 :)

챕터 4 진행 중에 교정이 필요한 부분이 보여서, 제보드리려고 합니다.
자세한 내용은 아래를 참고 부탁드립니다~

- 페이지 : 129페이지 (챕터4, 서버 템플릿 엔진과 머스태치 소개)
- 판수 : 초판 1쇄

- 수정 필요한 내용

로직 코드를 사용할 수 없어 View의 역할과 서버의 역할을 명확하게 분리됩니다.
-> 로직 코드를 사용할 수 없어 View의 역할과 서버의 역할을 명확하게 분리합니다.
(혹은 '로직 코드를 사용할 수 없어 View의 역할과 서버의 역할이 명확하게 분리됩니다.' 도 무난할 듯 합니다)

그럼 확인 부탁드립니다!
감사합니다.

**Comment by joshua-qa** [comment]
페이지 번호로 검색해보니 없길래 이것도 제보하면 좋을 것 같아서 하나 추가해봅니다. ㅎㅎ
`143 페이지`의 5번째 줄
```
자 그럼 생성된 index.js를 머스테치 파일이 쓸 수 있게 footer.mustache에 추가하겠습니다.
```
개인적으로는 146페이지에 나오는 문장처럼 '그럼'으로 시작하는 쪽이 조금 더 어울리지 않나 싶어요~
'그럼 생성된 index.js를 머스테치 파일이 쓸 수 있게 footer.mustache에 추가하겠습니다.'

3쇄 나오면 알려주시기로 했으니, 저도 그 전까지 이것저것 발견하면 이슈로 올려보도록 하겠습니다~ :)

**Comment by jojoldu** [comment]
오 넵넵 감사합니다 :)
일단 3쇄가 인쇄가 시작되어서요 ㅠ 해당 부분은 4쇄에 녹여보겠습니다 :)
감사합니다!
