### ISSUE TITLE
ProfileControllerTest 실패

### ISSUE THREAD

**Issue by irerin07** [jojoldu/freelec-springboot2-webservice#119]
![image](https://user-images.githubusercontent.com/39554427/71585633-9e3bed80-2b5a-11ea-8087-d81f966eee8d.png)

default가 반환이 되지 않고 oauth가 반환되었다면서 테스트가 계속 실패합니다.

왜 자꾸 테스트를 통과하지 못하는걸까요...

/profile로 api 호출을 했을때 profile에 oauth가 담겨있는 경우인 것 같은데..

문제를 고치지 못하여 질문 드립니다.ㅠㅠ

**Comment by jojoldu** [comment]
@irerin07 님 질문 감사합니다 :)
프로젝트 코드를 확인해봤는데 **테스트용 properties에 oauth를 포함**하고 계세요

![image](https://user-images.githubusercontent.com/7760496/71638655-dcdfbe00-2ca8-11ea-9112-99df73dba1f2.png)

여기서 incldue=oauth를 제거하셔야만 됩니다 :)

실제 제가 책에서 사용중인 테스트용 properties 코드입니다.

```
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.h2.console.enabled=true
spring.session.store-type=jdbc

# Test OAuth

spring.security.oauth2.client.registration.google.client-id=test
spring.security.oauth2.client.registration.google.client-secret=test
spring.security.oauth2.client.registration.google.scope=profile,email
```

include는 **실제 서비스에서 사용될 코드**에서만 사용됩니다 :)

**Comment by irerin07** [comment]
@jojoldu 
으어어어어어 ㅠㅜ 이럴수가...정말 감사합니다.

**Comment by jojoldu** [comment]
@irerin07 고생하셨습니다 :)
