### ISSUE TITLE
p.61 @RequestMapping 설명 오타

### ISSUE THREAD

**Issue by jaeyeonling** [jojoldu/freelec-springboot2-webservice#12]
맨 위 "예전에는 @RequestMapping(method = RequestMethod.GET)으로 사용되었습." 에서 "사용되었습."에 "니다" 라는 말이 빠진 것 같습니다!

**Comment by jojoldu** [comment]
앗??? 헉 그건 심한 오타네요 ㅠㅠ 정말 죄송합니다
제보 감사합니다!
