### ISSUE TITLE
네이버 로그인이 안됩니다. ㅠㅠ

### ISSUE THREAD

**Issue by ssooya90** [jojoldu/freelec-springboot2-webservice#121]
![image](https://user-images.githubusercontent.com/45329122/71591245-fd0b6200-2b6e-11ea-9a07-451f3331624f.png)

화면에 로그인버튼 클릭 후 네이버 약관 동의하면 위와 같은 에러가 표시됩니다.

화면에서는 아래와 같이 표시됩니다.
![image](https://user-images.githubusercontent.com/45329122/71591307-380d9580-2b6f-11ea-88d7-bbe613a98ea0.png)

구글은 잘 됐는데, 네이버는 오류가 나네요..ㅠㅠ
스프링부트는 오류 발생 시 원인 찾는게 어려운 것 같습니다.ㅜㅜ

**Comment by ssooya90** [comment]
![image](https://user-images.githubusercontent.com/45329122/71591504-f29d9800-2b6f-11ea-9576-17559d010c79.png)

새벽에 하다보니.. implement Serializble을 빠뜨렸네요..
해결했습니다 ㅎ

**Comment by jojoldu** [comment]
@ssooya90 앗 넵넵 :) 고생하셨습니다!
