### ISSUE TITLE
p.100 MySQL5InnoDBDialect  가 비활성화 되어있는데 괜찮은가요?

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#122]
`spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect` 
![p100](https://user-images.githubusercontent.com/48509269/71611005-1b0dac80-2bd9-11ea-9bb1-cd384ab75a85.jpg)

여기서 `MySQL5InnoDBDialect` 이 부분에 선이 그어져있습니다

**Comment by jojoldu** [comment]
@zhtmr 님 질문 감사합니다 :)
해당 이슈는 https://github.com/jojoldu/freelec-springboot2-webservice/issues/67#issuecomment-566523952 에 상세히 담아두었는데요.
2.1.9에서 deprecated가 되긴했지만 옵션에서 사용못하는건 아니며
현재 2.2.2 버전까지 테스트 결과 해당 설정을 사용하지 않으면 정상적으로 MySQL 쿼리가 생성되질 않습니다.

상세한 내용은 위 링크를 참고해주세요 :)

**Comment by zhtmr** [comment]
@jojoldu 엄청빠른답변 감사합니다
