### ISSUE TITLE
p106~107 에서 @Autowired보다 @RequiredArgsConstructor를 권장하셨는데.. 이유를 잘 모르겠습니다 ㅠ

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#123]
`@RunWith(SpringRunner.class)
@SpringBootTest 
public class PostsRepositoryTest {

    @Autowired
    PostsRepository postsRepository;

    @After
    public void cleanup(){
        postsRepository.deleteAll();
    }

    @Test
    public void 게시글저장_불러오기(){
        //given
        String title="테스트 게시글";
        String content="테스트본문";
     
        postsRepository.save(Posts.builder()
                .title(title)
                .content(content)
                .author("123@gmail.com")
                .build());

        //when
        List<Posts> postsList = postsRepository.findAll();

        //then
        Posts posts = postsList.get(0);
        assertThat(posts.getTitle()).isEqualTo(title);
        assertThat(posts.getContent()).isEqualTo(content);

    }
}`

이 테스트 코드에서 @autowired 대신 private final로 지정하고 @RequriedArgsConstructor로 했는데 왜 안되는지 모르겠습니다.

**Comment by jojoldu** [comment]
@zhtmr 앗 안녕하세요!
테스트 코드에서는 @Autowired를 써야합니다.
책에서의 말은 **실제 프로덕션 코드에서 생성자 DI를 써야한다는걸 의미**합니다.
(프로덕션 코드란 src/main에 있는 코드를 얘기해요)

생성자 DI를 쓰는 이유는 여러가지가 있는데, 그 중 가장 대표적인 이유가 **스프링 없이도 테스트 코드를 작성할 수 있어야 하기 때문**입니다.

@Autowired로 구성되어 있으면 스프링이 없으면 테스트를 작성하지 못하는데요.
이렇게 되면 다른 프레임워크로 전환도 어려우며, **테스트 속도가 너무 느립니다**.
스프링을 이용한 테스트가 100개 이상만 되어도 몇분씩 걸리게 되는데요.
실제 현업에서는 팀마다 천개 이상의 테스트가 수행되기 때문에 스프링이 꼭 필요한 테스트와 그렇지 않은 테스트를 분리해서 작성합니다.

그리고 이미 스프링팀에서도 필드인잭션 (@Autowired를 필드에 직접 선언한 방법)을 쓰지 말라고 권고하고 있습니다.
굳이 쓸 필요가 없겠죠?

> 좀 더 자세한 내용은 [mimul님의 글](https://www.mimul.com/blog/di-constructor-injection/#%EC%99%9C-constructor-injection%EC%9D%84-%EA%B6%8C%EC%9E%A5%ED%95%98%EB%82%98 을 참고해주세요.

**Comment by sangeon22** [comment]
테스트 코드 작성하다가 저도 궁금했는데 바로 답변이 있네요 감사합니다 ㅎㅎ
