### ISSUE TITLE
P257 Window putty 연결

### ISSUE THREAD

**Issue by puroldev** [jojoldu/freelec-springboot2-webservice#124]
Host name에 ec2-user@퍼블릭DNS 을 넣으면 접속이 되는데
Host name에 탄력적 IP 주소를 넣게 되면  타임아웃이 뜨는데.. 혹시 안되는 이유가 있는건가요..?
![질문](https://user-images.githubusercontent.com/57317512/71637722-acd6f180-2c8d-11ea-8ab4-3898555e3c77.PNG)

**Comment by jojoldu** [comment]
@puroldev 앗 이렇게만 봐서는 잘 모르겠고요 ㅠ
설정 전체 스샷을 찍어서 보여주시면 도움이 될것 같습니다 :)

**Comment by puroldev** [comment]
> @puroldev 앗 이렇게만 봐서는 잘 모르겠고요 ㅠ
> 설정 전체 스샷을 찍어서 보여주시면 도움이 될것 같습니다 :)

![image](https://user-images.githubusercontent.com/57317512/71670237-b1e19100-2db2-11ea-9608-5da030be0031.png)

SSH 설정을 위치무관으로 하면 접속이 되는데, 내 IP로 했을시에 접속이 안되고 있습니다..이것도 제가 
다른 설정을 잘못해줘서 그런가요?ㅠㅠ

**Comment by puroldev** [comment]
음..제가 노트북을 모바일 핫스팟을 이용해서 연결해서 안되는건 아니겠죠?

**Comment by jojoldu** [comment]
@puroldev 앗... 핫스팟이면 ㅠ ip가 계속 변경될거에요 ㅠ
핫스팟 연결하시면 내 IP 등록을 매번 해주셔야됩니다 ㅠ

**Comment by jojoldu** [comment]
말씀하셨듯이 위치무관이면 된다는건
현재 IP와
허용된 IP가 매치되지 않다는 의미라서요 ㅠ
