### ISSUE TITLE
intellij에서 RDS접속 오류 질문

### ISSUE THREAD

**Issue by Conatuseus** [jojoldu/freelec-springboot2-webservice#125]
안녕하세요 jojoldu님.
새해복 많이 받으세요.

intellij에서 RDS접속하는 것이 이틀전에는 됬는데 어제부터 갑자기 안되더라구요.
혹시 이유를 알 수 있을까요...?
첫번째 사진은 connect 시도했을 때,
두번째 사진은 RDS 보안 설정입니다.
MYSQL/aurora에 제 IP가 추가 되어있는 상태입니다.

![image](https://user-images.githubusercontent.com/22893111/71638910-e7ea1c80-2caf-11ea-958d-5c7b81a5b28c.png)

![image](https://user-images.githubusercontent.com/22893111/71638903-b2453380-2caf-11ea-9f9e-82811ae355b3.png)

**Comment by Conatuseus** [comment]
도저히 해결하지 못해 RDS 새로 생성하니 되네요.
하지만 어떤 경우에 저런 상황이 일어나는지 알고싶어요 ㅠㅠ

**Comment by jojoldu** [comment]
@Conatuseus 님 안녕하세요!
혹시 집에서 하실때 와이파이 사용하시나요?
와이파이를 쓰신다면 인터넷 접속시마다 IP가 변경되어서 계속해서 IP를 변경해야될 수 있습니다!
