### ISSUE TITLE
알 수 없는 에러 발생하여 질문 드립니다.

### ISSUE THREAD

**Issue by irerin07** [jojoldu/freelec-springboot2-webservice#127]
인텔리제이에서 커밋 푸쉬를 하여 배포를 한 뒤에 퍼블릭 DNS로 접속을 하면

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jan 01 23:56:22 KST 2020
There was an unexpected error (type=Internal Server Error, status=500).
java.util.zip.ZipException: invalid code lengths set

위와 같은 에러 화면만 보입니다.

분명 잘 되던 프로젝트였는데 갑자기 해당 에러가 나서 당혹스럽네요..
Travis에서도 문제 없이 빌드가 되고 CodeDeploy에도 잘 올라가는데 계속 저 에러만 보이네요..

![image](https://user-images.githubusercontent.com/39554427/71642702-c9594500-2cf2-11ea-98e8-5dfe5b236f66.png)
step2의 nohup.out에서는 위와 같은 에러 메세지가 출력이 되는데 전혀 갈피를 잡을수가 없네요..

어느 부분부터 수정을 해봐야 좋을지 알려주시면 정말 감사드리겠습니다..ㅜㅜ

++추가
로그를 한참 뒤적거리다가 다음과 같은 메세지를 발견했습니다.
![image](https://user-images.githubusercontent.com/39554427/71657667-27823880-2d84-11ea-98e0-713bfd54b53b.png)

cp $REPOSITORY/zip/*.jar $REPOSITORY/ 이 부분에서 permission denied가 발생하여 생기는 에러 같은데 이 부분은 해결을 어떻게 해야 할까요?ㅜㅜ

**Comment by jojoldu** [comment]
@irerin07 2개 사진의 에러가 서로 다른것 같은데요!

1) 머스테치 관련 에러로 로그가 나오는데 혹시 로컬에서는 정상적으로 실행되어서 로그인까지 되시나요?
2) 두번째는 nohup.out 권한이 없다고 하면 기존에 있던 nohup.out을 한번 삭제하시고 다시 배포를 진행해보셔도 될것 같습니다.

**Comment by irerin07** [comment]
@jojoldu 위의 에러 메세지는 처음 글을 올리던 당시 vim nohup.out에서 확인한 에러 메세지이고 아래쪽은 몇시간 전 codedeploy의 로그파일에서 확인한 에러 메세지 입니다. 

![image](https://user-images.githubusercontent.com/39554427/71664467-67551a00-2d9c-11ea-8a18-3c753c2b5df2.png)

로컬에서는 문제없이 되고 있습니다. 

두번째는 

cp $REPOSITORY/zip/*.jar $REPOSITORY/ 이 코드를

sudo cp $REPOSITORY/zip/*.jar $REPOSITORY/ 이렇게 바꾸니 

![image](https://user-images.githubusercontent.com/39554427/71665347-e3049600-2d9f-11ea-9293-a57f6786e4b9.png)

이런 에러 메세지와

![image](https://user-images.githubusercontent.com/39554427/71665358-f0ba1b80-2d9f-11ea-9c5e-e8bf64c6e11d.png)

이런 에러 페이지가 나오네요...

도대체 무엇이 문제인지 모르겠습니다..

심지어 nohup.out파일은 생성되지도 않는 상황이라 말씀해주신 방법은 실행 할 방법도 없구요..ㅜㅜ

**Comment by irerin07** [comment]
@jojoldu 
안녕하세요!
일단 CodeDeploy 에플리케이션을 삭제, 재생성 하고 재배포를 하니 다시 정상적으로 구동이 되는것을 확인했습니다.
Build하고 배포하는 과정에서 뭔가 문제가 있었던 듯 합니다.
도움 주셔서 감사합니다!

**Comment by jojoldu** [comment]
@irerin07 
위에서 sudo로 넣으시면 **root권한**으로 파일이 생성되어서 이후에 모든 스크립트가 동작하지 않을거에요!
sudo는 위험한 명령어인지라 웬만하면 사용하지 않으시길 추천드립니다!

정상적으로 잘되셨다니 다행입니다 :)
