### ISSUE TITLE
안녕하세요 code deploy로 배포시 폴더 생성을 어떻게 해야할지 질문드립니다.

### ISSUE THREAD

**Issue by ljh0326** [jojoldu/freelec-springboot2-webservice#128]
현재 책을 읽고 Code Deploy를 이용한 배포까지 진행했습니다. 
그런데 제가 프로젝트를 다른프로젝트로 진행하고 있어서
index라는 폴더를  ./index 생성해야 하는데 script 밑에 deploy.sh에서 sudo mkdir ./index를 넣어봐도 안생기더라구요, 어떻게 하면 codeDeploy 가 폴더를 생성하게 할 수 있을까요?

**Comment by ljh0326** [comment]
![test](https://user-images.githubusercontent.com/17944004/71644163-51e1e080-2d07-11ea-9e04-c23f39e80b68.PNG)

**Comment by ljh0326** [comment]
원래 autocomplete 프로젝트가 실행하면서, 캐시폴터랑 index폴더를 만드는데 권한이 없어서 폴더를 못만드는것 같습니다. 어떤식으로 해결할 수 있을까요?

**Comment by jojoldu** [comment]
@ljh0326 음 일단은 로그를 보여주시지 않으셔서 ㅠ 권한이 없다는건 사실 추측으로 보이구요 :)
 /opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log 에 있는 로그를 한번 확인해보시겠어요?
실제로 권한이 없어서 안된다면 해당 로그에 권한이 없다는 에러가 남았을거에요!

그리고 ./ << 라는 경로는 **상대경로**이며 이 기준은 **파일의 디렉토리가 아니라**, **실행하는 process의 위치**가 기준입니다.
설령 권한 문제가 아니더라도 deployment-archive에는 안생길것 같습니다.

별도의 절대경로 path로 디렉토리를 생성하시는게 좋을것 같습니다
