### ISSUE TITLE
1판 p.270 그림 7-5 오타 (추정)

### ISSUE THREAD

**Issue by Rok93** [jojoldu/freelec-springboot2-webservice#129]
그림7-5에서   DB 인스턴스 이름을  'freelect-springboot2-webservice' 로 적혀있는데

freelec 뒤에 't'가 붙는게 오타인지 아닌지 헷갈립니다. (전까지는 freelec 으로만 썼던것 같아 질문드립니다)

**Comment by jojoldu** [comment]
@Rok93 앗 오타 맞습니다!
제보 감사합니다 :)
