### ISSUE TITLE
[질문] p.311 deploy.sh 실행 시 로그가 다릅니다.

### ISSUE THREAD

**Issue by bluumin** [jojoldu/freelec-springboot2-webservice#132]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: p.310 코드까지 모두 작성했고, deploy.sh 실행을 했는데 책의 내용과 다르게 나옵니다. 이 전에 올라온 다른글( #99 )을 참고해서 따라해봤는데 같은 에러가 납니다.

### 오류 로그

어떤 오류인지 캡쳐해주세요.

<img width="1242" alt="스크린샷 2020-01-05 오전 12 51 13" src="https://user-images.githubusercontent.com/45994870/71768111-97e0b380-2f56-11ea-80e4-91ea59d00fe3.png">

<img width="1610" alt="스크린샷 2020-01-05 오전 12 59 27" src="https://user-images.githubusercontent.com/45994870/71768137-df673f80-2f56-11ea-8079-c821c5f1fadc.png">

**Comment by jojoldu** [comment]
![image](https://user-images.githubusercontent.com/7760496/71779788-dd57bc00-2ffc-11ea-9ccc-f31a50916058.png)

위 메세지는 서버에 git clone으로 프로젝트 받으신 뒤에 **서버에 있는 코드를 직접 고치셨기 때문에 발생한** 메세지입니다.
clone 받으신 프로젝트를 삭제하신 뒤, 다시 git clone 받아서 실행해보시면 될것 같습니다!

**Comment by bluumin** [comment]
앗 그렇군요. 답변 감사드립니다.
좋은 책 내주셔서 감사합니다! 책 정말 잘 보고 있습니다ㅎㅎ
좋은 하루 되세요!

**Comment by jojoldu** [comment]
@bluumin 잘봐주셔서 감사합니다 :)
