### ISSUE TITLE
p.141

### ISSUE THREAD

**Issue by minjae2021** [jojoldu/freelec-springboot2-webservice#134]
UI 화면의 등록 버튼에 기능을 추가하는 js 파일을 만드는데 기능이 적용되지 않는 오류입니다.
등록됬다는 팝업창과 함께 등록이 되야하는데 등록이 되지 않습니다.
처음 js파일을 생성할때 인텔리제이에서 'js file are supported by idea ultimate'라는 경고문이 떴는데 이거랑 관련있는 걸까요??

var index = {
    init : function () {
        var _this = this;
        $('#btn-save').on('click', function () {
             _this.save();
        });
    },
    save : function () {
        var data = {
            title: $('#title').val(),
            author: $('#author').val(),
            content: $('#content').val()
        };

        $.ajax({
            type: 'POST',
            url: '/api/v1/posts',
            dataType: 'json',
            contentType:'application/json; charset=utf-8',
            data: JSON.stringify(data)
        }).done(function(){
            alert("글이 등록되었습니다.");
            window.location.href = '/';
        }).fail(function (error){
            alert(JSON.stringify(error));
        });
    }
};

index.init();

이건 작성한 index.js 파일입니다.
화면까지는 잘 나오는데 js파일에서 막히네요.
좋은 책 써주셔서 잘 공부하고 있었는데 어디서 오류가 났는지 궁금합니다!!

**Comment by tkdgusl94** [comment]
static.js.app 폴더를 만들때 static/js/app으로 입력하셨나요?

저도 저 부분에서 막혔었는데 폴더 만들때 static.js.app으로 만들었다가 수정했어요!

**Comment by minjae2021** [comment]
답변주셔서 감사해요!! 근데 폴더를 static/js/app로 다시 만들어봐도 안되네요ㅜㅜ
왜 그런걸까요...

**Comment by jojoldu** [comment]
@minjae2021 앗 안녕하세요
아래 양식에 맞춰서 질문남겨주시겠어요?
프로젝트 코드를 봐야할것 같습니다 :)

어떤 오류인가요?
오류설명:

프로젝트 주소
Github에 오류가 난 프로젝트를 올려주세요.

Github URL:
오류 로그
어떤 오류인지 캡쳐해주세요.

**Comment by minjae2021** [comment]
오류설명: P141 UI 화면의 등록 버튼에 기능을 추가하는 js 파일을 만드는데 기능이 적용되지 않는 오류입니다.
프로젝트 주소:
https://github.com/minjae2021/ex0/blob/master/src/main/resources/static/js/app/index.js

일단 실행은 되서 오류 로그는 뜨지 않습니다.

**Comment by jojoldu** [comment]
@minjae2021 님 안녕하세요 :)
일단 여기서는 왜 안되는지 메세지를 **2군데서 이미 신호를 주고 있는데요**

1) 인텔리제이 에러 로그

![image](https://user-images.githubusercontent.com/7760496/71779979-da11ff80-2fff-11ea-8fa3-8f1440cc3200.png)

2) 크롬 개발자 도구

![image](https://user-images.githubusercontent.com/7760496/71779978-cd8da700-2fff-11ea-8e04-41ad7f09ac75.png)

자세히 이유를 찾아보면

![image](https://user-images.githubusercontent.com/7760496/71779985-e9914880-2fff-11ea-89c6-b54cf4edd110.png)

GetMapping과 같이 Controller에서 URL 매핑을 담당하는 어노테이션에 **명확하게 주소가 없으면 Controller에 매핑되지 않는 요청은 모두 해당 메소드로**갑니다.
index.js 요청 역시 Controller가 매핑된 요청이 아니니 자연스레 helloResponseDto로 요청이 갔다보니 name과 amount가 파라미터에 없다는 오류가 발생했습니다.

해결책은

1) helloResponseDto 메소드를 제거하거나

2) 해당 메소드의 **명확한 URL 주소**를 써주시면 될것 같습니다.

그리고 크롬 개발자 도구로 디버깅 하는 방법을 잘 아시면 이런 문제를 확인하는데 도움 되실거에요!

[생활코딩의 크롬 디버깅 방법](https://opentutorials.org/course/580/2865)을 꼭 익혀보세요

**Comment by minjae2021** [comment]
헉 인텔리제이에 에러 로그가 있었네요ㅜㅜ 꼼꼼하게 못봐서 죄송해요ㅠㅠ
helloResponseDto의 GetMapping에 url주소 추가하니까 실행됬어요!! 감사합니다!!

**Comment by jojoldu** [comment]
@minjae2021 넵 감사합니다 :)
