### ISSUE TITLE
[실습오류] p.305

### ISSUE THREAD

**Issue by Rebwon** [jojoldu/freelec-springboot2-webservice#136]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: p.305쪽을 보고 외부 security파일을 등록하여 ./deploy.sh를 실행하였는데 아래와 같이 에러 로그가 발생합니다. 실습은 vim /home/ec2-user/app/application-oauth.properties를 생성 후 Security Config를 붙여넣기 한 후에 1쇄 책과 동일하게 deploy.sh를 수정을 했습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/Rebwon/freelec-springboot2-webservice

### 오류 로그

ignoring input and appending output to ‘nohup.out’
./deploy.sh: line 51: -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties: No such file or directory
[ec2-user@freelec-springboot2-webservice step1]$ ./deploy.sh: line 52: /home/ec2-user/app/step1/freelec-springboot2-webservice-1.0-SNAPSHOT.jar: cannot execute binary file

![4](https://user-images.githubusercontent.com/31135322/72025640-1bcece80-32bc-11ea-8312-7e9ce4c5c1c1.PNG)
![2](https://user-images.githubusercontent.com/31135322/72025644-1f625580-32bc-11ea-8e04-ba9009895e51.PNG)
![3](https://user-images.githubusercontent.com/31135322/72025646-212c1900-32bc-11ea-9fa4-a22606f7d702.PNG)

**Comment by jojoldu** [comment]
@Rebwon 안녕하세요!
음 제가 봤을때는 deploy.sh에 **라인별로** 역슬래시 (```\```) 가 빠진것 같습니다.
역슬래시 (```\```)가 있어야 **다음 라인도 같은 줄로 인식**을 하는데요.
혹시 deploy.sh 파일을 볼수있다면 좀더 쉽게 확인이 가능할것 같습니다 :)

**Comment by Rebwon** [comment]
@jojoldu deploy.sh파일을 올렸습니다. 확인 부탁드려요.
