### ISSUE TITLE
[오타 제보] p.173

### ISSUE THREAD

**Issue by tkdgusl94** [jojoldu/freelec-springboot2-webservice#137]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타):  저장 버튼

* to-be (교정): 생성 버튼

172쪽의 그림에는 생성 버튼이라고 되어 있는데 173쪽 맨 위에는 저장 버튼이라고 되어 있네요. ㅎㅎ
정말 사소한거지만 제보 해봅니다. ^^

**Comment by jojoldu** [comment]
@tkdgusl94 앗 감사합니다 :) 말씀하신 내용 다음 인쇄시 반영하겠습니다!
