### ISSUE TITLE
[실습 오류] p.110

### ISSUE THREAD

**Issue by YoongJaeSong** [jojoldu/freelec-springboot2-webservice#139]
### helloControllerTest에러

오류설명: Post 등록까지 코드를 완성하고 Test case까지 성공했습니다.
어쩌다 helloControllerTest도 돌리게 됐는데 이때 #130과 같은 error가 발생했습니다.
@ Transactional도 정상적으로 입력했는데 어떤 문제인지 잘 모르겠습니다.

어째서 helloController에서 postsApiController 때문에 발생하는지 모르겠습니다.
### 프로젝트 주소

* Github URL: https://github.com/YoongJaeSong/springboot-webservice

### 오류 로그
![image](https://user-images.githubusercontent.com/36692385/71821241-f6cc3700-30d4-11ea-81b1-3f626ba70262.png)

**Comment by Rebwon** [comment]
WebMvcTest 애노테이션을 붙이시면 대응되는 컨트롤러 클래스도 넣어주셔야 합니다.
WebMvcTest(controllers = HelloController.class) 이런식으로요.

**Comment by YoongJaeSong** [comment]
@Rebwon 알려주셔서 정말 감사합니다. 덕분에 해결했습니다.
