### ISSUE TITLE
[질문] 무중단 배포까지 완료 했는데 글을 등록하면 403 에러가 납니다.

### ISSUE THREAD

**Issue by bluuminn** [jojoldu/freelec-springboot2-webservice#145]
안녕하세요 동욱님!

현재 책에 있는 모든 실습을 끝낸 상태인데요

글을 작성하고 등록 버튼을 누르면

![image](https://user-images.githubusercontent.com/45994870/71945576-90493500-320a-11ea-81bb-ffd66267c58f.png)

위와 같은 403 에러가 발생합니다.

혹시 user의 권한 문제인가 싶어서

![image](https://user-images.githubusercontent.com/45994870/71945979-a7d4ed80-320b-11ea-8b58-2dbb37b1934a.png)

위와같이 update문을 이용하여 is_role 필드의 값을 Y로 주었는데도 403에러가 발생합니다ㅠ
어떤 부분이 문제일까요..?

그리고 질문이 한가지 더 있습니다!

제가 만든 페이지에 다른 친구들이 접근해서 로그인을 해도 user테이블을 조회해보면 localhost랑 제 아이디 이렇게 총 2개밖에 조회되지 않습니다.
현재 상태로는 이렇게 되는게 맞는 건지 궁금합니다!

**Comment by bluumin** [comment]
위 글을 작성할 때는 select * from user; 를 했을 때 테이블 생성시 작성했던 필드 값이랑 다른 필드들이 조회가 됐었는데요.

database 선택을 다시 한번 한 후 user 테이블 조회 하니 테이블 생성시 작성했던 필드값들이 잘 조회가 됐습니다.

그리고나서 원하는 유저의 role 필드의 값을 이전에 작성했던 것처럼 update문을 이용하여 직접 GUEST에서 USER로 변경 했습니다.

![image](https://user-images.githubusercontent.com/45994870/71946570-91c82c80-320d-11ea-87f8-e016bb3d8369.png)

페이지 새로고침 후 글 작성 및 등록을 해봤으나 여전히 403 에러가 나타납니다 ㅠㅠ
뭐가 문제인걸까요...?

그리고 다른 친구들이 로그인해도 user 테이블 조회시에 localhost랑 제 아이디만 나타난다고 했었는데 table 조회가 정상적으로 되고 나니 이전에 친구들이 로그인했던 아이디도 조회가 되는 것을 확인했습니다!

**Comment by jojoldu** [comment]
@bluumin 님 안녕하세요 :)

1) 일단 현재 @bluumin 님의 코드에서 문제는 없어보이고요 :)
확인해봤는데, 현재 코드에서는 **로그인만 하면 회원의 등급은 GUEST** 입니다.
시큐리티 설정은 글 등록이나 기타 글에 관련된 기능들이 모두 **USER** 권한이어야 됩니다.
처음 가입하시고 글 등록을 원하는 사용자는 GUEST에서 USER로 권한을 변경해주시고
**로그아웃 이후에 다시 로그인**을 해주셔야 됩니다.

결국 권한 체크가 **세션 기반**인데요.
세션은 **로그인했을때 한번 저장됩니다**
User 테이블을 아무리 업데이트해도, User의 권한은 로그인할때 당시로만 세션에 저장되어있으니 재로그인을 하시면 정상적으로 글 등록이 가능하실거에요 :)

**새로고침은 의미가 없습니다**. :)

**Comment by bluumin** [comment]
@jojoldu 님 답변 감사드립니다!

답변해주신 내용 참고해서 시도를 해봤습니다...!

하지만 지금은 로그인을 하면...

![image](https://user-images.githubusercontent.com/45994870/72075715-a274c180-3337-11ea-856b-052355c07083.png)

위와 같은 화면이 나타나고 메인 페이지로 넘어가지 않습니다.
주소 마지막에 있는 /login 부분을 지우면 로그인이 되어있지 않은 메인페이지로 이동이 됩니다.. 

무엇이 문제일까요..?

가입하지 않은 다른 아이디로도 로그인 해봤으나 똑같이 로그인 페이지로 이동이 됩니다..ㅠㅠ

웹 브라우저의 쿠키랑 세션을 모두 지우고 시도 해봐도 똑같네요...ㅠㅠ

**Comment by jojoldu** [comment]
@bluuminn 님 안녕하세요! 혹시 해당 프로젝트 로컬에서 실행해서 테스트하실땐 로그인이 잘 되시나요?
현재 제가 해당 프로젝트를 복사하여서

1) 로컬에서 실행
2) ec2 에서 실행했을때는 둘다 잘되어서요

혹시 로컬에서 먼저 한번 테스트를 해보시고, 로컬에서 잘되신다면
**구글과 네이버 OAuth 정보에 ec2 주소가 등록되어있는지** 확인해보시겠어요?
한번 캡쳐해주셔도 좋을것같습니다!

**Comment by bluuminn** [comment]
@jojoldu 님 안녕하세요! 답변해주셔서 감사합니다!

동욱님 말씀대로 로컬에서 테스트를 해봤더니 로컬에서는 로그인도 잘 되고 글 작성도 잘 됩니다!

그래서 구글과 네이버에 OAuth 정보가 잘 등록되어있는지 확인을 해봤습니다.

제가 볼 때는 문제가 없어보이는데 동욱님이 보시기엔 어떠신가요..?
아래에 사진 첨부 하겠습니다. 확인 부탁드립니다 ㅠㅠ

네이버
![image](https://user-images.githubusercontent.com/45994870/72217096-2368ce80-356d-11ea-82c3-3fa2a5e3b4e1.png)

구글
![image](https://user-images.githubusercontent.com/45994870/72217097-2794ec00-356d-11ea-942c-4af94a4f9d42.png)

**Comment by jojoldu** [comment]
@bluuminn 님 OAuth 설정은 문제가 없어보이네요!
음 일단 확인해보고 싶은것은

첫번째는
 
![image](https://user-images.githubusercontent.com/7760496/72256657-0acfe580-364d-11ea-889b-2784c439f9d9.png)

위 화면에에서 Naver나 Google을 클릭하면 로그인이 되시나요?

두번째는
1) 로컬도 잘되고
2) Oauth 토큰도 잘 설정되어있다면

로컬과 운영의 남은 차이점은
application-oauth.properties 인데요.

로컬이 아니라 **서버에 저장하신 application-oauth.properties 정보**를 **구글과 네이버의 client-id와 client-secret만 제거한채로** 남겨주시면 설정에 오타가 있는지 확인해보겠습니다.

> client-id와 client-secret는 정상적이라는 가정하에 다른 값들을 확인해봅니다.

**Comment by bluuminn** [comment]
@jojoldu 님 안녕하세요!! 계속 답변 달아주셔서 감사드립니다 ㅠㅠ

제가 이전에 권한 문제로 글 작성이 되지 않을 때 user 테이블의 role 컬럼명을 roles로 수정을 했었었는데요..

이 후 로그인이 제대로 되지 않아서 혹시 그 부분이 문제가 되나 싶어 다시 roles에서 role로 변경을 했습니다.
변경 하고 나서도 위의 로그인 문제가 계속해서 나타났었는데..

며칠이 지나고 오늘 다시 로그인을 시도해보니 정상적으로 로그인도 잘 되고, 글 작성도 잘 됩니다...!

![image](https://user-images.githubusercontent.com/45994870/72416579-5b188600-37ba-11ea-8f9e-c8eb9e697c69.png)

컬럼명이 문제였던 걸까요..?
지금은 잘 되는 것 같습니다... 긴 시간 도움주셔서 정말 감사드립니다!

좋은 책 써주셔서 감사합니다! 많은 도움이 됐습니다 ㅎㅎ

그리고 새해 복 많이 받으세요 동욱님! 행복한 한 해 되셨으면 좋겠습니다!

**Comment by jojoldu** [comment]
@bluuminn 앗 잘되신다니 다행입니다! ㅎㅎ
실제 원인이 어떤것이였는지 저도 궁금하네요! ㅎㅎ
민구님도 올 한해 복 많이 받으세요! :)
