### ISSUE TITLE
[오류] p.95 테스트 코드 작성시 오류

### ISSUE THREAD

**Issue by hw01208** [jojoldu/freelec-springboot2-webservice#147]
안녕하세요. 먼저 좋은 책 내주셔서 감사합니다. 책에 적힌 것처럼  만드는 재미를 느껴보려 노력하는 학생입니다.. 정말 초보지식만 가지고 공부하고 있는 사람이라 검색하며 찾아보고 아무리 해결하려고 해도 도저히 해결이 안되어 여쭙게 되었습니다..ㅜㅜ
예제 파일도 그대로 가져다 써도 실행이 안되구요.

### 어떤 오류인가요? 
차근차근 따라가며 실습 중 95p 테스트 코드에서 자꾸 에러가 납니다.
 
### 오류내용
Error creating bean with name 'com.aaa.book.springboot.domain.posts.PostsRepositoryTest': Unsatisfied dependency expressed through field 'postsRepository'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'domain.posts.PostsRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.aaa.book.springboot.domain.posts.PostsRepositoryTest': Unsatisfied dependency expressed through field 'postsRepository'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'domain.posts.PostsRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)} 

 
책/실습코드대로 하면 Posts 클래스랑 PostsRepository 인터페이스를 임포트 하라고 해서 import domain.posts.*; 이렇게 임포트를 해놨는데요. 못 찾는 건지 아니면 정말 다른 곳에서 에러가 난건지 답답하네요.ㅜㅜ 감사합니다.

###
![00](https://user-images.githubusercontent.com/59275390/71961526-d4542e00-323a-11ea-953a-5c1e02754112.png)
 

![01](https://user-images.githubusercontent.com/59275390/71961555-e9c95800-323a-11ea-9b88-5846ffe2d309.png)

![02](https://user-images.githubusercontent.com/59275390/71961575-fbaafb00-323a-11ea-982b-48ceaeb18664.png)

**Comment by jojoldu** [comment]
@hw01208 앗 네!
요번 이슈는 없어도 괜찮은데 다음에는 **깃헙 프로젝트 URL도 함께 주시면 확인하기가 쉬워서** 함께 첨부 부탁드리겠습니다 :)

일단 p.57에 있는 항목을 다시 확인해보시면 좋을것 같은데요 :)

![image](https://user-images.githubusercontent.com/7760496/71974074-e9898680-3253-11ea-9ea4-2abfda797be9.png)

패키지구조를 보면 Application.java 하위에 domain 패키지가 존재하지 않습니다 :)
아래와 같이 패키지와 클래스 위치를 수정해보시겠어요?

![image](https://user-images.githubusercontent.com/7760496/71974122-0a51dc00-3254-11ea-8267-c5defec49e6f.png)

**Comment by hw01208** [comment]
앗 ㅜㅜ 잘 해결됐습니다! 앞으로 더 꼼꼼히 읽어야 겠네요 ... ㅎㅎ 감사합니다 :) 좋은 하루 되세요!

**Comment by jojoldu** [comment]
@hw01208 아고 잘해결되셔서 다행입니다!
편하게 질문주셔도 됩니다!
