### ISSUE TITLE
[오류] p.290 쿼리 실행 이후 Access denied

### ISSUE THREAD

**Issue by donghyeon-dev** [jojoldu/freelec-springboot2-webservice#148]
오류설명
create table 쿼리를 실행하려고 하면 Access denied for user to database mysql이라고
계속해서 db에 접근이 불가능한데 어떻게 해결할 수 있을까요??

![image](https://user-images.githubusercontent.com/53686581/71971330-b93ee980-324d-11ea-9d16-9c4a179210ac.png)

**Comment by jojoldu** [comment]
@donghyeon-dev 앗 안녕하세요
혹시 기존에 쿼리가 잘 수행되다가 특정 시기부터 안되셨던걸까요?
제가 직접 접속해볼수가 없어서 추측으로 말씀드려야겠지만

1) 기존에 되던데 갑자기 안된다
노트북의 IP가 변경된걸수 있습니다.
RDS의 보안 그룹에 가셔서 인바운드에 내IP 등록을 한번더 해주시면 됩니다.
와이파이, 핫스팟 등 **동적으로 IP가 할당되는 경우에**는 매번 작업하시기 전에 한번씩 IP 체크를 해주시면 좋습니다

2) 처음 시작부터 안된다
* 1과 마찬가지로 일단 인바운드 IP를 먼저 확인해보시고요.
* 인바운드 IP가 잘 등록되어있다면 ID와 패스워드를 확인해주세요.
패스워드를 모르신다면 https://aws.amazon.com/ko/premiumsupport/knowledge-center/reset-master-user-password-rds/ 를 참고하여 재설정 해주셔도 됩니다.

만약 위 방법 다 안된다면 다시 RDS를 생성해보시는것도 좋습니다

**Comment by donghyeon-dev** [comment]
IP가 계속 변경되서 그랬군요ㅠㅠ
친절한 답변 정말 감사합니다!!!

**Comment by jojoldu** [comment]
@donghyeon-dev 아고 넵넵! 감사합니다 :)
