### ISSUE TITLE
[오류] p.297 ./gradlew test 실행 시 권한 에러.

### ISSUE THREAD

**Issue by ssooya90** [jojoldu/freelec-springboot2-webservice#149]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: git clone 후, 테스트 검증 시 권한 에러 발생가 발생합니다.

sudo su로 전환 한 뒤 명령어를 입력해도 같은 오류가 발생합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/ssooya90/springboot-book

### 오류 로그

![git](https://user-images.githubusercontent.com/45329122/71986534-fcaa4f80-326f-11ea-971f-52a0a0eab471.PNG)

**Comment by ssooya90** [comment]
바로 뒷장에 있었네요.. 구글링 한참했는데...ㅜ.ㅜ 해결했습니다.

**Comment by jojoldu** [comment]
@ssooya90 아고 ㅠ 고생하셨습니다!
