### ISSUE TITLE
[오류] p.110 PostsApiControllerTest.java 오류

### ISSUE THREAD

**Issue by taehee-kim-dev** [jojoldu/freelec-springboot2-webservice#150]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명:

p.110 PostsApiControllerTest.java까지 

책에 있는 그대로 타이핑했는데 

org.springframework.web.client.RestClientException: Error while extracting response for type [class java.lang.Long] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token

와 같은 오류가 납니다.

// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.8.3'

추가해서 해봤는데도 소용없네요ㅠ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/taehee-kim-dev/springboot_practice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![캡처](https://user-images.githubusercontent.com/53412998/71999080-21102700-3284-11ea-8d6c-e788b2eef118.PNG)

**Comment by Rebwon** [comment]
저도 똑같은 이슈가 있었는데, PostsApiController 클래스에 PutMapping이 아닙니다. PostMapping으로 고쳐서 테스트를 시도해보세요.

**Comment by monkeyDugi** [comment]
@Rebwon 
정말 PostMapping으로 하면 되네요. 왜 그런거죠?? 이걸로 1시간 동안.. ㅜㅜ

**Comment by taehee-kim-dev** [comment]
> @Rebwon
> 정말 PostMapping으로 하면 되네요. 왜 그런거죠?? 이걸로 1시간 동안.. ㅜㅜ

저는 4시간 이상.. ㅋㅋㅋㅋㅋㅋ

**Comment by nugurejeil** [comment]
@Rebwon 
감사합니다 ㅠㅠ 저도 덕분에 해결되었습니다 ㅠㅠㅠ 단순 오타인걸까요...

**Comment by taehee-kim-dev** [comment]
> @Rebwon
> 감사합니다 ㅠㅠ 저도 덕분에 해결되었습니다 ㅠㅠㅠ 단순 오타인걸까요...
> @taehee-kim-dev 이미 해결된 이슈였네요 ㅎㅎ
> #13

아 이미 해결된 이슈였군요.. 사전에 검색했는데 못봤나봅니다 ㅜㅠ

**Comment by jojoldu** [comment]
@monkeyDugi, @taehee-kim-dev, @nugurejeil 아고 죄송합니다 ㅠ
책에 오타가 있어 정말 고생하셨을것 같습니다 ㅠ 
좀 더 꼼꼼하게 챙기지 못해 죄송합니다 ㅠ
이후에 혹시 추가 이슈가 있으시면 편하게 이슈 남겨주세요!

**Comment by gunkim0318** [comment]
이것 때문에 저 3일 동안 고민했습니다 ㅠㅠ

**Comment by PAPION93** [comment]
감사합니다..

**Comment by taeho** [comment]
감사합니다..

**Comment by LeeHyukJe** [comment]
와... 너무하네요 ㅠㅠㅠ
이겄때문에 몇시간을 해멨는데 ㅠㅠㅠ
이번주에 새로 산 책인데 정정이 되지 않았네요....

**Comment by gimdongwon** [comment]
ㅋㅋㅋㅋ 전 하루..^^ 3일 보신분 보고 위안삼아 갑니닼ㅋㅋㅋ
