### ISSUE TITLE
[질문] p.300, 301 pgrep 명령어 질문

### ISSUE THREAD

**Issue by tkdgusl94** [jojoldu/freelec-springboot2-webservice#151]
안녕하세요.
8.2장 진행하다가 궁금한 사항이 생겨서 질문 드립니다.

배포 스크립트 만들기 파트에서

CURRENT_PID=${pgrep -f ${PROJECT_NAME}*.jar)
이 부분이 잘 이해가 되지 않습니다.

또한, p.301의 코드설명에서는
CURRENT_PID=${pgrep -f springboot-webservice)

이렇게 표기가 되어 있는데 혹시 오타인건지, 아니면 ${PROJECT_NAME}*.jar 결과가 springboot-webservice인건지 잘 모르겠습니다.

CURRENT_PID 부분부터 if ~ else ~ fi 부분까지 코드 의미가 기존 수행 중이던 스프링 부트 애플리케이션을 종료하는 것으로 알고 있는데, ./deploy.sh 명령어를 여러번 실행해봐도 PID를 찾았다는 메세지를 보지 못했습니다.

혹시나 해서 netstat -ntlp | grep :9090 명령어로 프로세스 이름이 무엇인지 찾아봤는데, 프로세스 이름이 java 라는 것을 확인할 수 있었습니다.

<img width="696" alt="스크린샷 2020-01-09 오전 2 07 13" src="https://user-images.githubusercontent.com/46221990/71999487-d642df00-3284-11ea-9448-92c3b0bae43f.png">

기억이 잘 나지 않아서 그러는데 실습하는 과정에서 혹시 프로세스 이름을 명명하는 부분이 있었나요?
있었다면 다시 한 번 가르쳐 주시면 감사하겠습니다!

프로젝트 github 주소 : https://github.com/tkdgusl94/spring_boot_tutorial

**Comment by jojoldu** [comment]
@tkdgusl94 앗 제보 감사합니다!
301 페이지에 있는 springboot-webservice는 오타입니다 ㅠ
설명문에 들어가야할 내용은 코드와 동일하게 CURRENT_PID=${pgrep -f ${PROJECT_NAME}*.jar) 맞습니다.

**Comment by tkdgusl94** [comment]
넵넵! 이슈 올리고 혼자 끙끙 앓다가 해결 했던 문제였는데, 오타가 맞긴 맞았군요. ㅎㅎ

감사합니다!^^

**Comment by jojoldu** [comment]
@tkdgusl94 아고 ㅠ 정말 고생하셨을거라 생각되어 죄송한 마음 뿐입니다 ㅠ
이슈나 질문 언제든 편하게 올려주세요!

**Comment by rkaehdaos** [comment]
제가 했을때는  CURRENT_PID=${pgrep -f ${PROJECT_NAME}*.jar) 이것도 안되더군요
정규식 표현이라서 바로 *이 먹지 않는 것 같습니다.
다음처럼 로 해서 돌아갔습니다.
```
CURRENT_PID=${pgrep -f ${PROJECT_NAME}.*.jar)
```

**Comment by jojoldu** [comment]
@rkaehdaos 아고 ㅠㅠ 감사합니다!

**Comment by index79** [comment]
CURRENT_PID=${pgrep -f ${PROJECT_NAME}.*.jar) < -- 오타 발견!!

CURRENT_PID=$(pgrep -f ${PROJECT_NAME}.*.jar)< -- 수정 후 정상 작동

**Comment by index79** [comment]
그리고 빌드 할때마다 jar 파일이 계속 생성되어서

echo "> 프로젝트Build 시작"

rm $REPOSITORY/$PROJECT_NAME/build/libs/* <-- 추가 해주시면 편합니다 ^^
