### ISSUE TITLE
[질문] p.307 RDS 테이블 생성

### ISSUE THREAD

**Issue by dkyou7** [jojoldu/freelec-springboot2-webservice#153]
1. 테스트 코드 수행 시 로그로 생성되는 쿼리를 사용하면 됩니다.
- 이 부분에 대한 설명 부탁드리겠습니다.

2. 테스트 코드를 수행하면 다음과 같이 로그가 발생하니 create table부터 복사하여 RDS에 반영합니다.
- 반영을 어떻게 해야하나요? '반영합니다.'의 방법론을 잘 모르겠습니다!

3. p.308의 RDS 반영 소스코드도 어떻게 반영해아 하는지 설명 부탁드립니다.

좋은 책 내주셔서 감사합니다!

**Comment by jojoldu** [comment]
@dkyou7 앗 위에서 @tkdgusl94 님이 잘 설명해주셨는데요 :)

테스트 코드에서 로그가 보일려면 show-sql 옵션을 추가하시면 됩니다

![image](https://user-images.githubusercontent.com/7760496/72067957-5caffd00-3327-11ea-980b-2ea9e04a931c.png)

아마도 src/**main**에만 옵션이 있고 src/**test**에는 없어서 테스트 코드에서 발생하지 않았던것 같습니다 :)

**Comment by zhtmr** [comment]
> @dkyou7 앗 위에서 @tkdgusl94 님이 잘 설명해주셨는데요 :)
> 
> 테스트 코드에서 로그가 보일려면 show-sql 옵션을 추가하시면 됩니다
> 
> ![image](https://user-images.githubusercontent.com/7760496/72067957-5caffd00-3327-11ea-980b-2ea9e04a931c.png)
> 
> 아마도 src/**main**에만 옵션이 있고 src/**test**에는 없어서 테스트 코드에서 발생하지 않았던것 같습니다 :)

약간 다른 질문인데요.. 로컬에서 H2로 진행할때는 JPA가 자동으로 테이블도 만들어줬는데 왜 RDS로 할때는 테이블을 쿼리로 직접 만들어줘야 하나요??
