### ISSUE TITLE
[오류] p.301 배포 스크립트

### ISSUE THREAD

**Issue by tkdgusl94** [jojoldu/freelec-springboot2-webservice#154]
### 오타

* as-is (오타): JAR_NAME=$(ls -tr $REPOSITORY/ | grep *.jar | tail -n 1)

* to-be (교정): JAR_NAME=$(ls -tr $REPOSITORY/ | grep .jar | tail -n 1)

배포 스크립트 실행 중 계속 오류가 생겨서 명령어를 일일이 실행해봤는데, grep *.jar -> grep .jar 해야할 듯 해서 제보드립니다.

아래 사진에서 버전을 올리면 2개 이상의 .jar 파일이 생기는데,
2개 이상일 때 grep *.jar 명령어가 안 먹히는 듯 합니다.

제가 잘못 알고 있을 수도 있으니 한 번 확인해주세요. ^^

<img width="647" alt="스크린샷 2020-01-09 오후 2 10 08" src="https://user-images.githubusercontent.com/46221990/72040050-a5959080-32ea-11ea-9c1b-ed58f1d377bf.png">

**Comment by jojoldu** [comment]
@tkdgusl94 님 제보 감사합니다!
말씀하신대로 ```*.```이 제거되어 jar만 있는게 맞습니다 ㅠ
