### ISSUE TITLE
[실습오류] p.306 vim에서 deploy.sh 실행시 원하는 결과가 나오지 않습니다.

### ISSUE THREAD

**Issue by Rok93** [jojoldu/freelec-springboot2-webservice#157]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: vim에서 app 폴더에 application-oauth.properties 파일 생성후 IntelliJ(로컬) 값을 그대로 붙여넣은 뒤, 
deploy.sh 코드 수정 후   deploy.sh 실행 하였으나 교재에 적혀있는 결과값이 나오지를 않습니다.
다음 질문글을 보고 ' \ ' 고려해서 여러번 수정해봤는데, 원하는 결과값이 안나와서 질문드립니다. 
(정상적으로 실행시에는  (1판기준) p.306 과 같이 나타남) 

### 프로젝트 주소
[springboot-webservice 깃헙](https://github.com/Rok93/springboot-webservice)

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: (girignore 에 지정된 파일이라 커밋이 안되어있습니다.)

### 오류 로그
<img width="945" alt="deploay sh 실행시 오류" src="https://user-images.githubusercontent.com/47850258/72085742-2e431980-3349-11ea-8b54-f9b9fc32095b.png">

### deploy.sh
<img width="883" alt="deploy sh 코드" src="https://user-images.githubusercontent.com/47850258/72085743-2e431980-3349-11ea-8174-1bec010b3c00.png">

### application-oauth
<img width="1041" alt="application-oauth properties" src="https://user-images.githubusercontent.com/47850258/72085959-8a0da280-3349-11ea-8582-c913b85429ce.png">

**Comment by bongdong2** [comment]
전 일단 이렇게 해 봤는데 됐어요. 

nohup java -jar \
        -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties \
        $REPOSITORY/$JAR_NAME 2>&1 &

**Comment by bongdong2** [comment]
![image](https://user-images.githubusercontent.com/24599350/72125057-721a3b00-33aa-11ea-904e-d5b6f73d50fa.png)

**Comment by Rok93** [comment]
감사합니다! 제가 본문 내용을 잘못이해해서 결과부분이 터미널창에 바로 출력되는건줄 알았습니다. 
nohup.out  들어가서 내용 확인하니 결과창이 똑같이 나왔네요 !!! 

도움주셔서 감사합니다

**Comment by jojoldu** [comment]
@Rok93 아고 고생하셨습니다 :)
