### ISSUE TITLE
[질문] p.100 MySQL5InnoDBDialect 가 비활성화 되어있는 것에 대한 질문

### ISSUE THREAD

**Issue by 2doSilver** [jojoldu/freelec-springboot2-webservice#158]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 
p.100에서 설정하는 MySQL5InnoDBDialect 가 비활성화 되어있습니다.
같은 내용에 대한 질문 답변을 봤는데 2.1.10부터 못써서 추가 설정을 해줘야 한다고 봤는데
저는 책대로 현재 2.1.7 버전으로 쓰고 있습니다. 그런데도 MySQL5InnoDBDialect 가 비활성화 되어있어서 질문드립니다.
```
buildscript {
    ext {
        springBootVersion = '2.1.7.RELEASE'
    }
    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group 'com.2dosilver.study'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.projectlombok:lombok')
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('com.h2database:h2')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

### 오류 로그

![image](https://user-images.githubusercontent.com/25738138/72108385-cefbfe00-3376-11ea-8789-a896999d3d43.png)

**Comment by jojoldu** [comment]
@2doSilver 님 안녕하세요 :)
해당 질문에 대한 답변이 기존에 올라와있어서 공유드립니다 :)

https://github.com/jojoldu/freelec-springboot2-webservice/issues/67#issuecomment-566523952

**Comment by 2doSilver** [comment]
@jojoldu 님 안녕하세요~
우선 제가 질문 올린거 본문에 이미 같은 질문에 대해서 찾아봤다고 기재해놨습니다! 
그리고 제 질문 본문이랑 캡쳐랑 보시면 스프링부트 버전이 2.1.7인데도 불구하고 MySQL5InnoDBDialect가 비활성화 되어있어서 말씀드린 거였습니다~ 다시 확인 부탁드립니다.
혹시 제가 스프링부트 버전을 지정해도 그 버전대로 작동하지 않는 건가요?
혹은 제가 쓴 본문을 보셨는데도 해당 질문 답변을 공유해주신거라면 링크에서 p.100에서 지정하는 설정은 2.1.9까지는 된다고 되어있고, 2.1.10부터 추가 설정을 해줘야 한다고 되어있는데 그 내용을 제가 잘못이해한건지도 문의드립니다.

**Comment by ggomjae** [comment]
혹시 해결하셨나요? 저도 2.1.9 여도 MySQL5InnoDBDialect 비활성화여서 2.1.7로 내렸는데 그것도 비활성화가 되네요...

**Comment by jojoldu** [comment]
@2doSilver 비활성화라는게 Deprecated를 말씀하신다면 2.1.9까지 Deprecated는 아닙니다.

![image](https://user-images.githubusercontent.com/7760496/73834285-c64ff800-484e-11ea-84f0-465046da30fa.png)

2.1.10부터 Deprecated이며, 2.2.2까지는 Deprecated라 하여도 **옵션으 정상적으로 작동**합니다.
비활성화 된다는게 어떤 의미인지 잘모르겠습니다 ㅠ

1) 기능이 안된다는 말씀이신가요?
2) 아니면 Deprecated 된다는 말씀이신가요?

**Comment by ryubato** [comment]
> 1. 기능이 안된다는 말씀이신가요?
> 2. 아니면 Deprecated 된다는 말씀이신가요?

지나가는 제가 볼땐 `deprecated` 의미인것 같습니다. ^^ 참고로 `deprecated` 되면서 `storage_engine` 설정 항목이 추가 된것 같습니다. `MySQL`를 선택하는 경우 `storage_engine` 기본값은 `MyISAM` 이라 다음과 같이 설정하면 되겠습니다.

```properties
spring.hibernate.dialect.storage_engine=innodb
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
```

**Comment by jojoldu** [comment]
@ryubato 답변 감사합니다 :)
다만, 말씀하신대로 storage_engine 옵션을 추가해도 생성되는 쿼리는 **InnoDB가 아니라 MyISAM 로 create table 쿼리가 생성**됩니다 :)

> show_sql 옵션으로 생성되는 쿼리를 확인해보시면 좋을것 같아요 :)

실제로 사용하실려면 아래처럼 **MySQL57Dialect** 를 사용하면 됩니다 (storage_engine 사용여부와 관계 없이 작동됩니다)

```
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
```

다만 이렇게 할경우 MySQL57 버전 외에 어떻게 작동될지 테스트가 안되어 있기도 하고, **이에 대해 상용 서비스에서 성능 테스트나 기타 오랜시간 운영 테스트를 해온게 아니기 때문에** 
저는 2.1.9까지 스프링부트 버전과 MySQL5Dialect 에 대해서만 책에서 가이드하고 그이상 가이드를 드리진 않습니다 :)

**Comment by ryubato** [comment]
> 다만, 말씀하신대로 storage_engine 옵션을 추가해도 생성되는 쿼리는 InnoDB가 아니라 MyISAM 로 create table 쿼리가 생성됩니다 :)

확인해보니 말씀대로 `engine=MyISAM` 라고 나오네요!  아주 간단히 확인할 수 있는데 눈이 아닌 추측만으로 확인하고 지나치는 습관에 대한 교훈을 다시금 새깁니다. 감사합니다!

**Comment by jojoldu** [comment]
@ryubato 앗 아닙니다 :) 답변 감사합니다 :)

**Comment by 2doSilver** [comment]
@jojoldu 답변 감사합니다! 👍
