### ISSUE TITLE
p.111 ApiControllerTest 작성 후 기존 HelloControllerTest 깨짐

### ISSUE THREAD

**Issue by hello-sangsik** [jojoldu/freelec-springboot2-webservice#16]
p.111 
ApiControllerTest 작성 => 전체 테스트시 HelloControllerTest 실패
관련없는 ApiController 의 빈 생성을 시도하면서  연관된 빈을 제대로 주입받지 못해 테스트가 깨집니다. 
뒷장에서 추가되는건 확인했습니다만 중간중간 전체 테스트를 돌려보는 분들을 위해서
처음 작성 시 WebMvcTest의 범위를 명시해주는게 어떨까합니다.
```
@WebMvcTest(HelloController.class)
```

**Comment by jojoldu** [comment]
@hello-sangsik 와! 좋은 아이디어입니다
중간중간 실행하는걸 제가 잊고 있었네요 :)
정말 감사드립니다!
말씀하신건은 3쇄 찍을때 포함 바로하겠습니다!

**Comment by hello-sangsik** [comment]
@jojoldu 피드백 감사합니다!

**Comment by jalhagosipuda** [comment]
정말 감사합니다. 게시글 등록부분 하다가 전체 실행하였는데 헬로 부분 2개가 오류나길래 대체 무슨 문제인가 했는데
저렇게 다시 명시해주고 메인파일 가서 jpa관련 주석처리해주니까 정상적으로 돌아갔습니다.
