### ISSUE TITLE
[오류] p.306 deploy.sh 실행시 오류가 발생합니다.

### ISSUE THREAD

**Issue by Rok93** [jojoldu/freelec-springboot2-webservice#160]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

처음에는  #82 와 유사한 증상이 나타나서 deploy.sh와 properties 파일들에 오타 없는지 계속 점검하면서 변경하면서 실행하였습니다.  그런데 교재에서도 또 Issue에도 안올라온 오류가 발생했는데 한참을 해결 못해서 이렇게 질문드립니다.

### 어떤 오류인가요?
deploy.sh 실행시 nohup.out 파일에서 결과 확인시에  

#### The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.
라는 오류가 발생합니다. 앞서 사용했던 포트가 종료되지않고 계속 사용되는거 같은데 ... 이걸 어찌 해결해야할지 모르겠습니다. 

오류설명: 

### 프로젝트 주소
Github에 오류가 난 프로젝트를 올려주세요.

* Github URL:  https://github.com/Rok93/springboot-webservice

#### The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

**(지금 질문 외에 추가적으로 질문드리고 싶습니다.)** 
외부 Security 파일 등록 후 deploy.sh 실행하면 p.306과 같이 결과창이 떠야한다고 했는데, 
제 결과창에는 
(1) o.s.b.w.embedded.tomcat.TomcatWebServer : ......  
(2) com.@@@@@.Application : .....      
이 두개만 출력되고, 아래의 나머지 3줄은 출력이 안되는데..  이러면 문제가 있는건지 궁금합니다. 

어떤 오류인지 캡쳐해주세요.

### nohup.out 결과창
<img width="1680" alt="오류 내용" src="https://user-images.githubusercontent.com/47850258/72168712-061eed80-3411-11ea-995a-67e661ac4029.png">

### deploy.sh
<img width="1102" alt="deploy sh 실행화면" src="https://user-images.githubusercontent.com/47850258/72168746-1b941780-3411-11ea-88f8-acd8f4bd4eb1.png">

###  application-real-db.properties
<img width="1672" alt="application-real-db properties" src="https://user-images.githubusercontent.com/47850258/72168783-2e0e5100-3411-11ea-9410-eb10726789e2.png">

### 실행결과
<img width="1680" alt="실행결과" src="https://user-images.githubusercontent.com/47850258/72168767-251d7f80-3411-11ea-89ba-971991636f4e.png">

**Comment by Rok93** [comment]
추가적으로 #99 와 유사하게   실행시에 real-db 를 읽어오지 못하는 것 같습니다.

<img width="1666" alt="실행결과 (real-db 누락)" src="https://user-images.githubusercontent.com/47850258/72199275-0c4ab380-347d-11ea-825e-fcc3edbde8a8.png">

**Comment by jojoldu** [comment]
@Rok93 음 처음 생성하신 서버인데 8080이 사용중이라고 에러가 발생하시는거죠?
일단은 아래와 같이 java 프로세스가 어떤게 있는지 확인해보시고요

```
netstat -ntlp | grep :8080
```

![image](https://user-images.githubusercontent.com/7760496/72257201-62228580-364e-11ea-9b7a-992ae7f2bb14.png)

여기서 실행중인 프로세스가 있다면  kill을 하신 뒤에 다시 배포를 해보시는걸 추천드립니다.

일단 배포가 정상적으로 된 이후에 db 문제를 해결하시는게 좋아보입니다!
한꺼번에 같이 하면 오히려 더 오해가 생겨서 어려울수 있습니다.

배포가 잘되시면 이후에 

1) application-real-db.properties 파일에 오타가 없는지
2) deploy.sh에서 application-real-db.properties 파일을 nohup 명령어에 잘 등록하였는지 확인해보시면 될것 같습니다.

**Comment by Rok93** [comment]
동욱님 조언해주신대로 8080 포트 사용중인 확인해서 kill 한 후에, deploy.sh 오타(탭 공백 제거) 하니까,  RDS 연동까지 문제없이 진행됐습니다.  감사합니다!

**Comment by jojoldu** [comment]
@Rok93 고생하셨습니다!
