### ISSUE TITLE
[오류] p.303page command not found

### ISSUE THREAD

**Issue by ggomjae** [jojoldu/freelec-springboot2-webservice#162]
오류설명: CURRENT_PID 에 들어가지않습니다. 
개인적인 생각 : Project ID 가 소문자 , 대문자로 있다는게 문제가 있을 것같기도합니다.

1.
![2222](https://user-images.githubusercontent.com/43604493/72204082-71bb9600-34b7-11ea-993f-1af17c133fb6.JPG)

2.
![33333](https://user-images.githubusercontent.com/43604493/72204087-8435cf80-34b7-11ea-911c-84ee2f8bc687.JPG)

3.
![44444444444444444444](https://user-images.githubusercontent.com/43604493/72204091-90ba2800-34b7-11ea-9598-6a17670ecf76.JPG)

4.
![5](https://user-images.githubusercontent.com/43604493/72204093-957edc00-34b7-11ea-9997-e1a5ebd94278.JPG)

**Comment by jojoldu** [comment]
@ggomjae 님 안녕하세요!
해당 deploy.sh 파일을 통째로 올려주시면 문법체크를 한번 해보겠습니다 :)
이미지로만 되어있으면 폰트나 색상에 가려져 제대로 확인이 어려워서요 ㅠ

**Comment by ggomjae** [comment]
cd /home/ec2-user/app/step1/SpringBoot-webservice

echo "> Git pull"

git pull

echo "> 프로젝트 build 시작"

./gradlew build

echo "> step1 디렉토리로 이동"

cd /home/ec2-user/app/step1

echo ">Build 파일복사 "

cp /home/ec2-user/app/step1/SpringBoot-webservice/build/libs/*.jar /home/ec2-user/app/step1

echo "> 현재 구동중인 애플리케이션 pid 확인"


CURRENT_PID=$(pgrep -f springboot-webservice*.jar)

echo " 현재 구동중인 애플리케이션 pid : $CURRENT_PID"

if [ -z "$CURRENT_PID" ]; then
        echo "> 현재 구동중인 애 X 종 X."
else
        echo "> kill -15 $CURRENT_PID"
        kill -15 $CURRENT_PID
        sleep 5
fi

echo "> 새 애플리케이션 배포"

JAR_NAME=$(ls -tr /home/ec2-user/app/step1/ | grep .jar | tail -n 1)

echo "> JAR NAME: $JAR_NAME"
nohup java -jar \
        -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties \  /home/ec2-user/app/step1/$JAR_NAME 2>&1 &


---------------------------------------------------------------------
대 소문자 문제도 있을 것같아서 이렇게 코딩했고 넘어갔습니다 ! 하지만 
305page도 지금 문제가 있는데요. 이렇게 하고 나서

실행시키니까   
error: Your local changes to the following files would be overwritten by merge:
Please, commit your changes or stash them before you can merge

이런 오류가떠서 stash를 해도 안되네요 흑흑 

그래도 책 ! 재밌게보고 있습니다! 감사합니다

**Comment by soohoonlee** [comment]
@ggomjae 님 올리신 이미지와 맨 밑에 올려주신 쉘 파일이 약간 다른데요.
혹시 이미지로 올리신게 맞다면 공백때문에 2번에 올리신 command not found가 발생하지 않았을까 합니다.

'CURRENT_PID = ' 와 'JAR_NAME = ' 을
'CURRENT_PID=' 와 'JAR_NAME='으로 바꾸시면 조금 괜찮아질 것 같습니다.

**Comment by ggomjae** [comment]
> @ggomjae 님 올리신 이미지와 맨 밑에 올려주신 쉘 파일이 약간 다른데요.
> 혹시 이미지로 올리신게 맞다면 공백때문에 2번에 올리신 command not found가 발생하지 않았을까 합니다.
> 
> 'CURRENT_PID = ' 와 'JAR_NAME = ' 을
> 'CURRENT_PID=' 와 'JAR_NAME='으로 바꾸시면 조금 괜찮아질 것 같습니다.

앗 이미 책 끝냈습니다. 감사합니다 !!!

**Comment by jojoldu** [comment]
@ggomjae 앗 다 끝내셨군요! 고생하셨습니다!
@soohoonlee 답변 감사합니다 :)
