### ISSUE TITLE
[오류] p.112 에서  "Entity의 필드 중 일부만 사용하므로 굳이 모든 필드를 가진 생성자가 필요하지 않다" 라고 하셨는데 이해가 잘 안됩니다...

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#163]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 112페이지 PostResponseDto 부분에서 "Entity의 필드 중 일부만 사용하므로 굳이 모든 필드를 가진 생성자가 필요하지 않다" 라고 하셨는데 이해가 잘 안됩니다...

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

`@Getter
@NoArgsConstructor 
@Entity 
public class Posts {
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Long id;

    @Column(length = 500, nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String content;

    private String author;

    @Builder 
    public Posts(String title, String content, String author){
        this.title=title;
        this.content=content;
        this.author=author;
    }`

위에 처럼 Post 클래스에 id, title, content, author 필드밖에 없는데 이걸 PostResponseDto에서 모두 사용한 것 아닌가요?? 

`@Getter
public class PostsResponseDto {
    private Long id;
    private String title;
    private String content;
    private String author;

    public PostsResponseDto(Posts entity) {
        this.id = entity.getId();
        this.title = entity.getTitle();
        this.content = entity.getContent();
        this.author = entity.getAuthor();
    }
}`

**Comment by jojoldu** [comment]
@zhtmr 님 안녕하세요 :)
해당 내용은 뒤에서 진행될 **생성시간, 수정시간**을 고려한 내용입니다.
비단 이 프로젝트뿐만 아니라 어느 프로젝트라도 Entity를 그대로 반환해서 사용하지는 않고 필요한 필드만 일부 받아서 사용합니다.
이유는 기존에 올라온 질문에 남겨놓은 답글 (https://github.com/jojoldu/freelec-springboot2-webservice/issues/138#issuecomment-571998458)이 있어 참고하시면 좋을것 같습니다 :)

**Comment by zhtmr** [comment]
@jojoldu 답변 감사합니다. 그런데 제가 이해를 잘 못한것 같습니다.ㅠㅠ 
PostResponseDto를  
`public PostsResponseDto(Long id, String title, String content,String author ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.author = author;
    }
`
왜 이렇게 만들면 안되는건가요??

**Comment by jojoldu** [comment]
@zhtmr 아! 말씀하신대로 구현해도 무방합니다!
다만 **특정 객체로 바로 생성이 가능하다면 해당 객체만 받는게 낫다**라는 의미입니다.
물론 둘다 (객체로 주입, 필드 하나씩 주입) 선언해서 상황에 따라 골라 사용도 많이 합니다 :)

언급해주신 방법대로 하게 되면 호출하는쪽에서는 다음처럼 구현하게 됩니다.

```java
new PostsResponseDto(entity.getId(), entity.getTitle(), entity.getContent(), entity.getAuthor());
```

필요한 모든 서비스 혹은 컨트롤러에서 다 이렇게 호출해야합니다.
굳이 생성자에서 Entity 로 받는 코드만 있으면 new PostsResponseDto(entity); 로만 사용이 가능한데 하나씩 다 선언할 필요는 없을거라 생각됩니다 :)
