### ISSUE TITLE
[오류] p.303page 오류

### ISSUE THREAD

**Issue by ggomjae** [jojoldu/freelec-springboot2-webservice#164]
### 어떤 오류인가요?

오류설명:  302 page 까지 잘되다가 gitignore이 작동안되는걸알고 캐시 제거뒤에 다시 commit push하고 실행했는데 충돌이 일어나서 다시 깃을 clone 해서 해봤더니 이런 오류가 뜹니다. 보니까 build부근에 fixed untracked files 생기고 나서부터 문제가 생긴것 같아 clean -f 도해보고 별짓 해봤는데 감이 안잡힙니다. 

### 오류 로그
1. 
![질문1](https://user-images.githubusercontent.com/43604493/72215731-5c4b7800-355a-11ea-90d9-5b3dcfc5dba8.JPG)

2.
![결과qweqweqwe](https://user-images.githubusercontent.com/43604493/72215732-5e153b80-355a-11ea-8fb1-814b68612269.JPG)

3.
![으으ㅡㅇ으으으](https://user-images.githubusercontent.com/43604493/72215733-60779580-355a-11ea-84d0-be009803b199.JPG)

4.  deploy.sh 입니다. 

cd /home/ec2-user/app/step1/SpringBoot-webservice

echo "> Git pull"

git pull

echo "> 프로젝트 build 시작"

./gradlew build

echo "> step1 디렉토리로 이동"

cd /home/ec2-user/app/step1

echo ">Build 파일복사 "

cp /home/ec2-user/app/step1/SpringBoot-webservice/build/libs/*.jar /home/ec2-user/app/step1

echo "> 현재 구동중인 애플리케이션 pid 확인"

CURRENT_PID=$(pgrep -f springboot-webservice*.jar)

echo " 현재 구동중인 애플리케이션 pid : $CURRENT_PID"

if [ -z "$CURRENT_PID" ]; then
        echo "> 현재 구동중인 애 X 종 X."
else
        echo "> kill -15 $CURRENT_PID"
        kill -15 $CURRENT_PID
        sleep 5
fi

echo "> 새 애플리케이션 배포"

JAR_NAME=$(ls -tr /home/ec2-user/app/step1/ | grep .jar | tail -n 1)

echo "> JAR NAME: $JAR_NAME"
nohup java -jar \
        -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties \  /home/ec2-user/app/step1/$JAR_NAME 2>&1 &

어떤 오류인지 캡쳐해주세요.

**Comment by jojoldu** [comment]
@ggomjae 님 안녕하세요!
음 일단 build 디렉토리는 매번 gradle build시 생성되는곳이라 제거하시는게 좋을것같은데요!
아래와 같이 한번 해보시겠어요?

1) 프로젝트의 build 디렉토리를 삭제한다
2) 삭제한 후 git commit & push를 시도한다
3) github에서 build 디렉토리가 제거된걸 확인한다
4) 확인되면 gitignore에 build 디렉토리를 등록한다

이렇게 하시면 이후에는 build 디렉토리가 추가될일은 없을거에요

====================================
위와 별개로 현재 deploy.sh에서

```
CURRENT_PID=$(pgrep -f springboot-webservice*.jar)
```
는 아래와 같이 변경하셔야할것 같습니다.

```
CURRENT_PID=$(pgrep -f SpringBoot-webservice*.jar)
```

=====================================

위에서 캡쳐해주신 사진이 2개인데요

* 1번 사진은 어떤게 에러로그로 보신건가요?
git pull 했을때 fatal: not a git repository를 에러로 보셨다면, 이는 당연한 일입니다.
git pull은 **git 프로젝트 내부에서만 작동**합니다.
step1 디렉토리는 git 프로젝트가 아니고 step1/SpringBoot-webservice 디렉토리가 git 프로젝트라 git pull이 정상작동할거에요!

* 2번사진은 1번과 별개로 다시 서버 초기화 후에 deploy.sh를 실행했더니 발생한건일까요?
만약 그렇다면 처음 언급했던대로 build 디렉토리 삭제후에 **step1디렉토리**부터 다시 생성해서 시작해보시는게 좋을것 같습니다 :)

**Comment by ggomjae** [comment]
한번 해보겠습니다! 감사합니다!

**Comment by jojoldu** [comment]
@ggomjae 넵!
