### ISSUE TITLE
[오타 제보] p.115 Update 쿼리 수행 부분

### ISSUE THREAD

**Issue by nugurejeil** [jojoldu/freelec-springboot2-webservice#165]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타): 안녕하세요~! p.115 Update 쿼리 수행 테스트를 진행중이었는데요, 분명 책을 보면서 순서대로 차근 차근 코드를 작성했는데 PostsApiControllerTest 클래스를 다 작성하고 보니,
PostUpdateRequestDto 클래스 작성 부분과, Posts 클래스에서 update 메서드 작성 부분이 책에서 누락된것 같습니다. 깃 저장소를 보고 제게 부족한 코드를 수정하니 정상적으로 테스트가 되는데요, 제 책에서는 이 코드 작성 부분이 없어서요 ㅠㅠ 혹시 제가 실수로 앞부분에서 코드를 지나쳤는지 한참 찾아봤지만 책에는 없었습니다 ㅠ 의도적으로 누락 되었던건지 궁금합니다. 제가 보고 있는 책은 초판 2쇄본입니다. 감사합니다!

* to-be (교정): PostUpdateRequestDto.class, Posts.update()

**Comment by jojoldu** [comment]
@nugurejeil 제보 감사합니다 ㅠ
해당 내용이 3쇄에 반영될 예정입니다!
불편을 드려서 정말 죄송합니다 ㅠ

**Comment by nugurejeil** [comment]
@jojoldu 
넵 확인 감사합니다~!! :)
