### ISSUE TITLE
[오류] p.311 curl localhost:8080시 나타나는 에러

### ISSUE THREAD

**Issue by dkyou7** [jojoldu/freelec-springboot2-webservice#166]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: nohup.out에서는 8080 로그가 잘나타나는데
`curl localhost:8080` 입력시 다음과 같은 에러가 발생합니다.
```bash
"timestamp":"2020-01-13T02:08:37.565+0000","status":500,"error":"Internal Server Error","message":"Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.SQLGrammarException: Unable to acquire JDBC Connection","path":"/"
```
### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/dkyou7/freelec-springboot2-webservice2

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/26649731/72229955-a46ba880-35f5-11ea-8023-e0ead13c8b09.png)

**Comment by jojoldu** [comment]
@dkyou7 앗 안녕하세요
혹시 curl 날리시고 nohup.out 에는 에러로그가 보이시지 않으신가요?
지금 봐서는 JPA로 DB접근시 안되고 있는것 같은데요!

> 여담이긴한데 application-real.properties 에 dialect=org.hibernate.dialect.MySQL5Dialect 로 옵션을 넣으셨던데 MySQL5InnoDBDialect 를 사용하셔야 합니다!

**Comment by dkyou7** [comment]
@jojoldu 님 답변 감사합니다! 
![image](https://user-images.githubusercontent.com/26649731/72301197-7051bf80-36a9-11ea-88e9-b105ee7ed916.png)

처럼 데이터베이스가 존재하지 않는다고 나오는데 use freelec 설정을 ec2에서도 해줘야 하는건가요???
첫 실습이라 어렵기만하네요ㅠㅠ 빠른 답변 감사합니다!

![image](https://user-images.githubusercontent.com/26649731/72301231-8a8b9d80-36a9-11ea-8b3b-74569fcb8226.png)

**Comment by dkyou7** [comment]
#171 번에서 동일 에러를 해결하였습니다. 

> CURRENT_PID=$(pgrep -f freelec-springboot2-webservice*.jar) 처럼 변수명을 직접 써주었더니 해결되었습니다.
