### ISSUE TITLE
[오류] p.363 Travis CI에서 scripts/*.sh : No such file or directory

### ISSUE THREAD

**Issue by apalsl** [jojoldu/freelec-springboot2-webservice#167]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 
step2에 deploy.sh를 제작하고 .travis.yml 파일을 수정 후 실행하였는데 CI에서 scripts/*.sh : No such file or directory가 발생합니다. zip에 파일배포까지는 잘 동작하였습니다.

deploy.sh 위치는 /home/ec2-user/app/step2/zip/scripts에 포함시켰습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/apalsl/hree-webservice

### 오류 로그

![image](https://user-images.githubusercontent.com/25685341/72247054-7018dc00-3637-11ea-85ce-cc2baafc0cc8.png)

**Comment by jojoldu** [comment]
@apalsl 앗? 책에서도 scripts를 **서버에 저장하라고는 하지 않았을거에요**!
서버에 저장하는것은 step1까지이며 step2부터는 **프로젝트에 있어야 합니다**
당연하지만 **travisci는 외부 서비스이니 ec2 서버에 직접 접근이 안됩니다**
9.5절에 있는 그림 9-43을 보시면 아시겠지만 IntelliJ로 열어놓은 프로젝트입니다.
즉, **프로젝트에 scripts 디렉토리와 스크립트를 포함**시키시면 됩니다 :)

![image](https://user-images.githubusercontent.com/7760496/72256203-f5a68700-364b-11ea-8335-94128923730e.png)

**Comment by apalsl** [comment]
어쩐지 하면서도 scripts를 안만들었는데 어떻게 찾는건지 의문이었습니다.
책에 사진이 작게 Output과 scripts가 같이 있었는데 제가 놓친부분이 있는것같네요. 답변 감사합니다.

**Comment by jojoldu** [comment]
@apalsl 아고 ㅠ 사진이 작아서 죄송합니다 ㅠ
프로젝트에 생성한다는 멘트 한줄을 추가했다면 덜 고생하셨을텐데 죄송합니다 ㅠ
이후에도 혹시나 궁금한게 있으시면 편하게 이슈남겨주세요!
