### ISSUE TITLE
[오류] p.189 userName 표기 관련

### ISSUE THREAD

**Issue by iumoum** [jojoldu/freelec-springboot2-webservice#169]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 기존에 올라왔지만 해결되지 않은 문제입니다. 세션에 담은 userName의 값이 제대로 표기되지 않는 것입니다. userName이라는 키워드가 어딘가에서 사용되고 있는 것 같았습니다. 확인해보니 제 컴퓨터 로그인할 때 (윈도우 키 + L 누르고 잠금 해제 할 때 나오는 이름)이 표기됩니다. 해당 변수명을 다른 변수로 바꿨을 때는 로그인 후 받아온 name 값이 정상적으로 표기됩니다. 내부에서 어떤일이 벌어지는 지 궁금해서 질문합니다!

관련있는 이슈 : #70

**Comment by iumoum** [comment]
혹 저자님의 컴퓨터 이름이 이동욱으로 되어있는지도 궁금합니다.

**Comment by aegis1920** [comment]
저도 똑같은 이슈가 발생하네요. 변수가 "UserName"이나 "Username"과 같이 대소문자 구별없는 "username" 문자열이면 이런 이슈가 발생합니다. 참고로 저의 현재 OS가 윈도우 10인데 그럴 수가 없겠지만 윈도우의 환경변수 %USERNAME%과 관련이 있어 맥OS와는 다른가 싶기도 하고...

**Comment by jojoldu** [comment]
@iumoum 님 안녕하세요!
저는 맥 OS를 사용중이라 해당 이슈가 재현되지가 않습니다 ㅠ
윈도우 OS에서만 발생하는것 같습니다 ㅠ
@aegis1920 님이 말씀하신대로 윈도우를 서버로 인식해서 서버 환경변수에서 username을 쓰고 있어서 그럴수도 있을것 같다는 **추측**만 드네요!

**Comment by mkshin96** [comment]
저도 같은 이슈가 발생해서 jmustache github에 이슈 남겼습니다.
https://github.com/samskivert/jmustache/issues/118

나중에 답변 달린다면 참고하시면 좋을 것 같습니다!

**Comment by gus-an** [comment]
저도 이게 의아했어요! 3 가지 구글 계정으로 로그인 했는데 모두 윈도우의 %userName% 결과가 표기되더라구요~! 
코드상에서 userName 말고 다른 변수명으로 설정하니깐 정상작동하네요~!

**Comment by jojoldu** [comment]
@mkshin96 님이 제보해주신 내용으로 답변이 된것 같아 해당 이슈는 종료하겠습니다 ^^;
(윈도우의 환경변수 이슈였습니다)
