### ISSUE TITLE
[실습문의] 110p.PostApiControllerTest 등록 테스트

### ISSUE THREAD

**Issue by G1Kwon** [jojoldu/freelec-springboot2-webservice#174]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 110p.PostApiControllerTest 등록 테스트 실패 문의입니다. 
                처음 오류를 확인 후 기존 이슈들에서 해결책을 주신 어노테이션 변경을 해봤습니다.
                그러나 PostApiController.java 에서 @PostMapping 으로 바꾸고 난 뒤에도 
                기존과 같은 토큰 에러가 나고 있습니다... 풀스캔으로 테스트를 돌려도 
                @PutMapping으로 설정할때와 동일한 문제가 있습니다.
                몇번 확인 해봐도 오타는 없는 것 같아서 제가 작성한 코드의 어떤 부분에서 문제가 있었는지 
                다른 분들의 조언을 구하고자 합니다.
                미리 감사드립니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/G1Kwon/freelec-springboot2-webservice.git

### 오류 로그

 Error while extracting response for type [class java.lang.Long] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]
org.springframework.web.client.RestClientException: Error while extracting response for type [class java.lang.Long] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]

**Comment by leeshinyook** [comment]
저도 그 부분에서 동일한 에러가 발생했었는데요.
Test의 Long부분 => Object로 바꿔서 해결했던것 같아요

**Comment by G1Kwon** [comment]
@leeshinyook 저도 다른 이슈사례를 보고 
테스트 소스를 ResponseEntity<Object> ... Object.class

원 소스에서 Long을 Object로 바꾸면 404가 나오지 않으신가요?

**Comment by G1Kwon** [comment]
지금 제 깃에 올라가있는 소스를 디버그 찍으면 
ResponseEntity<Long> responseEntity = restTemplate.postForEntity(url, requestDto, Long.class);
가 실행시 

springframework 내부의 httpheaders.java 
Unable to evaluate the expression Method threw 'java.lang.NullPointerException' exception. 는 오류를 1차로 일으키고 

	@Override
	public <T> ResponseEntity<T> postForEntity(String url, @Nullable Object request,
			Class<T> responseType, Object... uriVariables) throws RestClientException {

		RequestCallback requestCallback = httpEntityCallback(request, responseType);
		ResponseExtractor<ResponseEntity<T>> responseExtractor = responseEntityExtractor(responseType);
		return nonNull(execute(url, HttpMethod.POST, requestCallback, responseExtractor, uriVariables));
	}

PostforEntity구성뒤에 바로 exception일으키네요..

public abstract class ReflectiveCallable {
    public Object run() throws Throwable {
        try {
            return runReflectiveCall();
        } catch (InvocationTargetException e) {
            throw e.getTargetException();
        }
    }

이부분 도와주실분 계신가요..?

**Comment by hoonpig** [comment]
저도 이부분에서 에러가나는데...

Long 부분으로 실행하면 json 에러가 발생하고,
Object 로 변경하면 getStatusCode 부분에 400에러가 떨어집니다..

이래저래 찾아봐서 put > post 로 변환해봐도 마찬가지네요;;

**Comment by kwonmory** [comment]
해결방법으로 
PostsApiController.java 파일 내
`@PostMapping("/api/v1/posts")
    public Long save(@RequestBody PostsSaveRequestDto requestDto) {
        return postsService.save(requestDto);
    }`
보시면  PutMapping 에서 PostMapping 으로 바꿔주세요. 그럼 테스트에 성공합니다.

**Comment by gblee87** [comment]
저도 @kwonmory  님 방법으로 테스트에 성공했습니다.
다만 왜 그런지 원인을 알고 싶네요.
(전반적인 이해가 부족하다 보니 하나하나 헤딩을 해요 ㅠ.ㅜ)

**Comment by hoonpig** [comment]
저도 posts 로 변경했는데 안되길래 자세히 소스를 보니 오타가 있었더라구요...

long을 object 로 변경하지않고, post 로만 변경해줘도 테스트가 잘 진행이 됩니다.

**Comment by kwonmory** [comment]
이유는 간단한거같아요.
테스트할 때 post method 으로 테스트한다고 메서드 postForEntity  를 사용했는데 호출한 컨트롤러 메서드가 post method 를 따르지않아서 그런가봐요

**Comment by G1Kwon** [comment]
아...... 바보같은 오타로 @PostMapping으로 되었음에도 컨트롤러를 못탔네요...

@PostMapping("/api/v1/posts")가 맞는 구성인데 제 소스는
@PostMapping("/api/vi/posts") 로 되어 있어서 메서드 자체를 못탔습니다..

이런..

도움 주신분들 정말 감사드립니다!!!

**Comment by fftl** [comment]
@G1Kwon 

@PostMapping("/api/v1/posts")가 맞는 구성인데 제 소스는
@PostMapping("/api/vi/posts") 로 되어 있어서 메서드 자체를 못탔습니다.. 

=>이거보고 확인해보니 똑같은 실수가.. ㅎㅎㅎ 감사합니다.

**Comment by sbdyzjdla** [comment]
@PostMapping("/api/v1/posts")가 맞는 구성인데 제 소스는
@PostMapping("/api/vi/posts") 로 되어 있어서 메서드 자체를 못탔습니다..

저도 ㅋㅋㅋㅋ 
어처구니 없는 실수를 했네요 감사합니다~

**Comment by YoungKyonYou** [comment]
와
@PostMapping("/api/v1/posts")
@PostMapping("/api/vi/posts")
이게 진짜 미쳤네 ㅡㅡ 저도 이거 찾느라 한참 고생했네요

**Comment by craftowen** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 
사람이 다 비슷하네요..
오타 힌트 감사합네다..

**Comment by kiosk123** [comment]
@PutMapping으로 컨트롤러에서 설정되어 있는데 post메소드로 클라이언트에서 보내려니 에러발생하네요 
테스트 코드에서 postForEntity 메소드 대신에 다음과 같이 수정해서 주시면 잘 동작합니다.
```
HttpEntity<PostsSaveRequestDto> request = new HttpEntity<>(requestDto);
ResponseEntity<Long> responseEntity = restTemplate.exchange(url, HttpMethod.PUT, request, Long.class);
```

**Comment by suin0730** [comment]
저는 @PostMapping("/api/v1/ports")으로 오타냈네요.... 다들 주의하세요!

**Comment by alalshow** [comment]
저는 Test 코드 짤 때 

String url = "http://localhost:" + port + "/api/v1/posts" + updateId;
String url = "http://localhost:" + port + "/api/v1/posts/" + updateId; 

경로문자를 하나 빼먹어서 같은 오류가 났네요~

**Comment by yoonho0922** [comment]
> 아...... 바보같은 오타로 @PostMapping으로 되었음에도 컨트롤러를 못탔네요...
> 
> @PostMapping("/api/v1/posts")가 맞는 구성인데 제 소스는
> @PostMapping("/api/vi/posts") 로 되어 있어서 메서드 자체를 못탔습니다..
> 
> 이런..
> 
> 도움 주신분들 정말 감사드립니다!!!

=> 저도 소름돋게 v1 이 아니라 vi로 돼있더라구요!? 책에 오타도 아닌데 어떻게 다 vi로 쓰셨는지....
감사합니다 이것 때문에 계속 삽질했네요

**Comment by jyos1426** [comment]
헐 난 아니겠지..했는데... 저도...

**Comment by choikangjae** [comment]
저도 맨 처음에 따라쳐보고 테스트 잘 통과되길래 그 다음에 다시 다 지우고 생각하면서 따라쳤는데 이 오류뜨길래 뭔가 했더니 저도 vi로 적어놨었네요 ㅋㅋㅋ

**Comment by khanian** [comment]
controller는 제대로 변경 했지만 
@PostMapping("/api/v1/posts") 
그래도 나길래 봤더니 ....... 테스트에서 
String url = "http://localhost:" + port + "/api/vi/posts"; // ㅋㅋㅋㅋㅋ 이런 만행을....
String url = "http://localhost:" + port + "/api/v1/posts"; //수정해서 성공. 
감사합니다. ㅋㅋㅋㅋ

**Comment by rlarudgkswkd** [comment]
ㅋㅋㅋㅋㅋ다들똑같은 ㅋㅋㅋㅋ v1이랑 vi 정말 사소하지만 중요하네요

**Comment by Pushpull7381** [comment]
헐 저도 그거때문이었어요,,,, 손가락이 움직이는대로 쳤더니 vi라고 입력해놨네요ㅋㅋㅋㅋㅋㅋㅋ큐ㅠㅠㅠㅠㅠ😭

**Comment by chicker94** [comment]
감사합니다.. 저는 post라고 썻네요..

**Comment by chlcken2** [comment]
_### * vi -> v1 오타가 아닌 다른 문제로 생기시는 분들 참고하세요_

저는 h2 설정에 대한 문제로 인해 발생한 에러입니다.
build.gradle과 application.properties에 아래와 같이 설정 합니다.

**-build.gradle-**
implementation 'org.springframework.boot:spring-boot-starter-jdbc'
runtimeOnly 'com.h2database:h2'

**-application.properties-**
spring.datasource.url=[h2 경로]
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
**spring.jpa.hibernate.ddl-auto: create**    <-- **_이부분으로 인해 오류 났었음_**

<hr>

```
application.properties에서 
spring.jpa.hibernate.ddl-auto: create 를 추가합니다.
```
저 같은 경우는 ddl-auto 선언이 되어있지 않아 test코드에서 새로운 테이블을 만들어야 하는데 h2에서 만들지 못한 오류 였습니다.
