### ISSUE TITLE
[오타 제보] p.113에서 update 메소드를 왜 Posts 에다가 만드나요??

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#175]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타): 

`  @Transactional
    public Long save(PostsSaveRequestDto requestDto) {
        return **postsRepository.save**(requestDto.toEntity()).getId();
    }

    @Transactional
    public Long update(Long id, PostsUpdateRequestDto requestDto) {
        Posts posts = postsRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("해당 사용자가 없습니다. id=" + id));

        **posts.update**(requestDto.getTitle(), requestDto.getContent());

        return id;
    }

    @Transactional
    public void delete (Long id) {
        Posts posts = postsRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("해당 사용자가 없습니다. id=" + id));

        **postsRepository.delete(posts);**
    }

    @Transactional(readOnly = true)
    public PostsResponseDto findById(Long id) {
        Posts entity = **postsRepository.findById(id)**
                .orElseThrow(() -> new IllegalArgumentException("해당 사용자가 없습니다. id=" + id));

        return new PostsResponseDto(entity);
    }

    @Transactional(readOnly = true)
    public List<PostsListResponseDto> findAllDesc() {
        return **postsRepository.findAllDesc().**stream()
                .map(PostsListResponseDto::new)
                .collect(Collectors.toList());
    }
}`

* to-be (교정):

service 패키지에 있는 delete, find, save 메소드들은 PostsRepository에서 실행하는데 update만 posts에 따로 만들어서 실행하는 이유가 있는건가요?

**Comment by Rebwon** [comment]
객체지향 프로그래밍에서 클래스의 상태를 변경하는 것은 자기 자신이 해야할 일이라고 나와있습니다. 그렇기 때문에 update메서드가 Posts 도메인 안에 있는 것입니다.

**Comment by jojoldu** [comment]
@zhtmr 책에서도 언급되어있지만, update는 JPA에서 **조회된 상태에서 변경된 값이 있으면 트랜잭션 끝난 시점에 자동 반영**됩니다.

@Rebwon 님이 말씀하신대로 객체지향 프로그래밍에서 객체의 상태 변경은 **그 객체가 해야할 일**이기 때문이며, 기존에 JPA가 없던 시절에는 객체가 본인의 값을 변경하는데도, 매번 DB에 update 쿼리를 일으켜야되서 이 원칙을 지키기 힘들었습니다.
JPA가 이를 지원해준뒤로 DB를 사용하는 애플리케이션에서도 객체지향이 가능하게 된것입니다 :)

**Comment by rlska105** [comment]
마지막 Annotation  @Transactional(readOnly = true) 여기서 readOnly가 안불러와지는데 어떻게 하면 되는지 알 수 있을까요~??

**Comment by jojoldu** [comment]
@rlska105 안녕하세요 :) 혹시 해당 어노테이션이 spring의 어노테이션 맞나요?
javax 의 어노테이션이 아닌지 확인 해보시겠어요?
