### ISSUE TITLE
[오류] p.115 Post update 기능 테스트

### ISSUE THREAD

**Issue by cupjoo** [jojoldu/freelec-springboot2-webservice#176]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: PostApiController에서 update 기능 테스트에서 오류가 발생합니다. Long 타입의 인스턴스를 deserialize 할 수 없어서 발생한 오류라 하는데 자바 기본 지식이 부족하다 보니 해결이 조금 어렵네요...

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/cupjoo/sample-board

### 오류 로그
![1](https://user-images.githubusercontent.com/30645938/72442471-ec561f80-37ef-11ea-92e3-f75cb85c9363.PNG)
![2](https://user-images.githubusercontent.com/30645938/72442473-eeb87980-37ef-11ea-98cd-7402b8a5e13a.PNG)

**Comment by emiling** [comment]
안녕하세요 p.113에서 `Posts_수정된다` 함수에서 동일한 에러가 발생했는데 어떻게 해결하셨나요?
