### ISSUE TITLE
[오류] p.281 부분의 내용이 잘 이해되지 않습니다ㅠㅠ;;

### ISSUE THREAD

**Issue by nugurejeil** [jojoldu/freelec-springboot2-webservice#177]
### 어떤 오류인가요?

오류설명:
안녕하세요! 책 잘 보고 있습니다~ 오류는 아니고 확인차 질문 드리고 싶은게 있습니다.

p. 281 내용중, EC2에 사용된 보안 그룹의 ID를 복사해서, 
RDS 보안 그룹의 인바운드로 추가하는 작업을 진행중인데요! (그림 7-25)

여기서 '**RDS 보안 그룹의 인바운드로 추가**' 한다는 것의 의미는,

p. 239 에서 나오는 그림 6-19 보안 그룹 추가 부분에 새로 추가한다는 의미인가요?
RDS 콘솔에서 아무리 찾아봐도 RDS 보안 인바운드와 관련된 부분을 찾을 수가 없어서요 ㅠㅠ
이렇게 하니깐 인텔리제이 database 플러그인과 연결에 성공하긴 했는데 
제가 잘 한 것인지 정확하지 않아서 질문드립니다!

**Comment by jojoldu** [comment]
@nugurejeil 앗 아닙니다!
EC2의 보안그룹 ID를 복사하여
RDS의 보안그룹 인바운드에 추가합니다!
보안그룹은 RDS 화면 메인에 존재합니다!

![image](https://user-images.githubusercontent.com/7760496/73836124-f1881680-4851-11ea-8084-e5ec07ab79cf.png)

여기를 클릭하여 추가하시면 됩니다 :)

**Comment by yonggyeom** [comment]
질문은 RDS 보안그룹 인바운드를 어디에 추가하냐고 물어보셨는데.. 왜 다른 답변을 하신건지요..

이 부분은 저 말고 다른 독자분들도 전부 헷갈린 부분일 듯 합니다.. 명확한 설명 부탁드립니다.
