### ISSUE TITLE
[오류] p.300 ~ p.301

### ISSUE THREAD

**Issue by nugurejeil** [jojoldu/freelec-springboot2-webservice#178]
### 어떤 오류인가요?

오류설명: 
안녕하세요! vim으로 ~/app/git/deploy.sh 파일을 다 작성하고 :w 로 저장을 하려고 하면

<img width="497" alt="스크린샷 2020-01-16 오후 4 02 56" src="https://user-images.githubusercontent.com/6160290/72503601-75686780-387f-11ea-999e-f6ec7bf15b2a.png">

이렇게 경고가 뜨면서 저장이 안됩니다 ㅠ 혹시 해결방법이 있을까요??

**Comment by nugurejeil** [comment]
다 끄고 다시 vim 을 열어서 작성하니 저장되었습니다..... ㅠㅠ ㅋㅋㅋ

**Comment by benny-coding** [comment]
저도 같은 문제 발생하였는데 ~/app 디렉토리 안에 git 디렉토리를 생성해준 후에 저장하니 저장이 되었습니다. 
git 디렉토리가 존재하지 않아 발생한 문제였던 것 같은데 책에서는 해당 예제를 제가 못찾은 것인지 발견하지를 못했습니다!
