### ISSUE TITLE
[오류] p.288 쿼리 실행 오류

### ISSUE THREAD

**Issue by hw01208** [jojoldu/freelec-springboot2-webservice#179]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

ALTER DATABASE freelec
CHARACTER SET = 'utf8mb4'
COLLATE = 'utf8mb4_general_ci';

쿼리 실행시 
-
Error executing SQL statement. Can't create/write to file './freelec/db.opt' (Errcode: 2 "No such file or directory") - Connection: freelec: 40ms
-
라는 오류가 납니다. 책에 적힌 chracter_set_database, collation_connection 외에도 collation_database, collation_server 등 RDS 파라미터 그룹 수정도 책에 나온대로 따라한 것 같은데 무엇이 문제인지 찾기가 힘드네요..ㅠㅠ

오류설명: 
### 프로젝트 주소 
Github에 오류가 난 프로젝트를 올려주세요. 
* Github URL: https://github.com/hw01208/freelec-springboot2-webservice

### 오류 로그

![00](https://user-images.githubusercontent.com/59275390/72504933-32f45a00-3882-11ea-8401-9f3e6d3d1f33.PNG) 

![01](https://user-images.githubusercontent.com/59275390/72505237-e1000400-3882-11ea-9100-ace37dfb8278.PNG)

![02](https://user-images.githubusercontent.com/59275390/72505376-2ae8ea00-3883-11ea-87ba-722f1bd2387e.PNG)
 
어떤 오류인지 캡쳐해주세요.

**Comment by clignancourt** [comment]
데이터베이스명을 freelec_springboot2_webservice 이걸로 해보세요

**Comment by hw01208** [comment]
답변감사합니다. 여전히 같은 오류가 뜨네요! ㅠㅠ show variables like 'c%';, select @@time_zone, now();과 같은 다른 명령어는 실행이 잘 됩니다만 저 명령어만 되질 않네요..

**Comment by hw01208** [comment]
으앗 해결됐습니다! 감사합니다 clignancourt님 :) 좋은 하루 되세요.

**Comment by jojoldu** [comment]
@hw01208 앗 고생하셨습니다 ㅠ

@clignancourt 답변 감사합니다 :)
