### ISSUE TITLE
p141. p153 index.js

### ISSUE THREAD

**Issue by gracelove91** [jojoldu/freelec-springboot2-webservice#18]
p141에서는 var index = ... 로 하다가 p.153에서는 var main = ... 으로 바뀌는데 
설명에는 update function을 하나 추가하겠다는 말 밖에 없어서 독자들이 약간 좀 헷갈리지않을까 싶습니다..!

**Comment by jojoldu** [comment]
앗 넵넵 
index나 main으로 다 통일해서 진행해야하는데 중간에 변경해서 그렇게 된 것 같습니다 ㅠ 
제보 감사합니다!

**Comment by gracelove91** [comment]
@jojoldu  뭔가 오픈소스 기여하는 것같고 ㅋㅋ 기분좋네요 ㅋㅋ 특히 p.103~ 페이지였나 비즈니스코드가 어디에 위치해야하는지 설명해주신 것보고 어렴풋이 알던 객체지향적으로 코딩하라는 게 어떤 건지 조금이나마 이해할 수 있어서 좋았어요! 좋은 책 내주셔서 감사합니다!

**Comment by jojoldu** [comment]
@gracelove91 아고 ㅠ 좋게 봐주셔서 고맙습니다 ㅠ
깃헙 이슈로 오타제보 받기를 잘한것 같다는 생각이 드네요 ㅎㅎ;
말씀하신대로 객체지향 프로그래밍이라고 하면 상속 위주로 하거나, 웹 애플리케이션에서는 객체지향으로 하지 않는 경우를 너무 많이 봐서 꼭 언급하고 싶었던 챕터였습니다.
도움이 되셨다고 해주셔서 적길 정말 잘한것 같네요 ㅎㅎ;
제보도, 칭찬도 정말 감사드립니다!
