### ISSUE TITLE
[오류] p.383페이지 ProfileControllerTest 빌드 성공실패

### ISSUE THREAD

**Issue by apalsl** [jojoldu/freelec-springboot2-webservice#180]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명:
ProfileControllerUnitTest 까지 테스트 성공했습니다.
그러나 그 다음 ProfileControllerTest에서 기대값이 Default인데 oauth가 계속 나와서 테스트를 실패합니다. 현재는 그냥 ProfileControllerTest를 제거한 후 진행 중인데 제가 무엇을 잘못했는지 모르겠습니다.

### 프로젝트 주소

* Github URL: https://github.com/apalsl/hree-webservice

### 오류 로그

![image](https://user-images.githubusercontent.com/31984624/72505743-e6118300-3883-11ea-991b-999830613227.png)

**Comment by jojoldu** [comment]
@apalsl 기존에 올라온 이슈와 중복되어서 해당 이슈의 답변을 링크로 전달드립니다 :)

https://github.com/jojoldu/freelec-springboot2-webservice/issues/119
