### ISSUE TITLE
스프링 부트 공부 다음 스텝 질문

### ISSUE THREAD

**Issue by fwantastic** [jojoldu/freelec-springboot2-webservice#181]
먼저 이런 좋은 책을 만들어 주셔서 감사합니다. 스프링 부트 예제를 보며 best practice와 몰랐던 것들을 보고 많은 도움이 되었습니다. REST API를 좀 더 깊게 파고 싶은데 책의 예제는 아무래도 심플한 예제이다 보니 이런 저런 궁금한 것들이 많은데 적당한 예제를 찾기가 힘드네요. 예로 도메인 엔티티에 nested objects가 있다면 dto에 전부 다 포함해서 반환하는게 일반적인지, dto에 nested objects를 포함해서 반환했는데 frontend에서 save post 콜을 할때 request dto는 그걸 또 빼고 받는건지 등등...
혹시 real world 예제로 추천해주실만한 깃헙 리포나 링크, 아니면 블로그가 있으신가요?

**Comment by jojoldu** [comment]
@fwantastic 님 좋은 질문 감사합니다 :)

저는 보통 3개 정도의 강좌를 추천드리는데요!

1) 국내 JPA 의 아버지이신 김영한님의 인프런 JPA 풀코스 강좌 - https://www.inflearn.com/roadmaps/149
2) 네이버 / MS 의 개발자이신 백기선님의 스프링부트 Rest API 강좌 - https://www.inflearn.com/course/spring_rest-api
3) 자바지기 박재성님의 클린코드 / TDD 등 더 좋은 소프트웨어 가기 위한 오프라인 강좌 - https://edu.nextstep.camp/

위 3개중에 가장 필요하신걸 먼저 들어보시고 나머지 들도 기회가 된다면 꼭 수강하시길 추천드립니다 :)
