### ISSUE TITLE
[오타 제보] p.245

### ISSUE THREAD

**Issue by iumoum** [jojoldu/freelec-springboot2-webservice#187]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타): EIP가 공개되어있음.

* to-be (교정): 해당 EIP를 제거하시고 다음 인쇄 때 안나오도록 수정해야 할 것 같습니다.

**Comment by jojoldu** [comment]
@iumoum 앗! 제보 감사합니다 :)
