### ISSUE TITLE
[오타 제보] p.105

### ISSUE THREAD

**Issue by G-ONL** [jojoldu/freelec-springboot2-webservice#188]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

안녕하세요. 우선 좋은 책 만들어주셔서 너무 감사합니다.

너무 재밌게 잘 읽고 있습니다. 이렇게 책을 빠르게 읽었던 경험이 얼마 없는데 기분이 좋네요.

우선 저의 책은 1판입니다. 

### 오타

* as-is (오타): service 패키지에 생성합니다.

* to-be (교정): service.posts 패키지에 생성합니다.

혹은

뒤에 PostsService 구현을 확인해보니 그곳은 service 패키지안에서 import를 해오더라구요.

그러면 그림3-14가 바뀌어야지 않을까 생각이 듭니다.

그림 3-14에서는 service.posts 패키지 밑에 PostsService가 있습니다.

감사합니다.

**Comment by jojoldu** [comment]
@G-ONL 앗 제보 감사합니다 :)
