### ISSUE TITLE
[오류] p.305 외부 Security 파일 등록하기

### ISSUE THREAD

**Issue by hw01208** [jojoldu/freelec-springboot2-webservice#189]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?
p.305~306 오류입니다. 
p.304의 교재와 같은 오류가 나서 '외부 Security 파일 등록하기' 부분을 실습하고 있는데요.
deploy.sh를 실행하고 nohup.out을 실행하니 'invalid or corrupt jarfile' 라는 오류가 납니다.
이전에 310p까지 진행을 잘 하다가 311p에서 에러가 나서 챕터8부터 다시 하는 중입니다.
갑자기 여기서 왜 이런 에러가 나는지 잘 모르겠네요..ㅜㅜ

### 오류 로그

어떤 오류인지 캡쳐해주세요.

[ deploy.sh 파일 ]
![06](https://user-images.githubusercontent.com/59275390/72870267-03829900-3d2b-11ea-8f15-3d27483241bc.PNG)

[ deploy.sh 파일 실행 ]
![00](https://user-images.githubusercontent.com/59275390/72870083-822b0680-3d2a-11ea-9a9d-94428297a049.PNG)

[ nohup.out 파일 ]
![01](https://user-images.githubusercontent.com/59275390/72870099-8ce59b80-3d2a-11ea-9f56-b5d6247e92c1.PNG)

[ 디렉토리 app ]
![02](https://user-images.githubusercontent.com/59275390/72870144-a5ee4c80-3d2a-11ea-82ab-006ddba51c45.PNG)

[ application-oauth.properties 파일 ]
![03](https://user-images.githubusercontent.com/59275390/72870177-bd2d3a00-3d2a-11ea-8aa1-89d0dd48f40b.PNG)

[ 로컬의 application-oauth.properties 파일 ]
![04](https://user-images.githubusercontent.com/59275390/72870199-d0d8a080-3d2a-11ea-8656-e76e1145b831.PNG)
** 복사 붙여넣기 해서 오타는 없을 거예요

[ 디렉토리 step1 ]
![05](https://user-images.githubusercontent.com/59275390/72870232-e8b02480-3d2a-11ea-9145-2ad53bd403d2.PNG)

**Comment by jojoldu** [comment]
@hw01208 님 안녕하세요!
코드를 올려주시면 좋겠지만 ㅠ
application.properties와 applicatoin-oauth.properties 사이에 콤마와 스페이스가 함께 있는데요!
스페이스 없이 콤마만 넣으셔야됩니다!
스페이스가 있으면 개별로보게되어서요!

**Comment by hw01208** [comment]
@jojoldu 
답변 감사합니다 ! 다음부터는 꼭 코드 올리도록 하겠습니다. 문제도 잘 해결되어서 너무 감사드립니다ㅠㅠ.
피드백에서는 스페이스가 있으면 개별로 본다고 되어있는데 p.310에 보면 deploy.sh를 개선하는 과정에서 classpath:/application.properties, /home/ec2-user 라고 되어있습니다. p.305에 보면 띄어쓰기가 없는데요. 오타인 듯 싶어서 코멘트 남깁니다!

**Comment by jojoldu** [comment]
@hw01208 아고 ㅠ 제보 감사합니다! :)
