### ISSUE TITLE
p.110 Junit Test 실습 오류

### ISSUE THREAD

**Issue by yanghhh1** [jojoldu/freelec-springboot2-webservice#19]
105page PostApiController.java 에서 save가 @PutMapping으로 되어 있는데 

110page junit test 코드에는 
ResponseEntity<Long> responseEntity = testRestTemplate.postForEntity(url, requestDto, Long.class);
라고 되어 있습니다.

테스트 자체가 post로 넘기니까 method 불가 에러(405)가 납니다. 

Put을 Post로 바꾸던지 junit code를

HttpEntity<PostsSaveRequestDto> entity = new HttpEntity<PostsSaveRequestDto>(postsSaveRequestDto);
		ResponseEntity<Long> responseEntity = testRestTemplate.exchange(url, HttpMethod.PUT, entity, Long.class);
로 바꿈이 좋겠네요... 

초보자를 위한 책인데.. 실습코드는 문제없이 나왔으면 좋은데 아쉽네요

**Comment by jojoldu** [comment]
@yanghhh1 님 실습코드 오류 죄송합니다 ㅠ
해당 이슈는 기존에 언급된것과 같은 이슈 (https://github.com/jojoldu/freelec-springboot2-webservice/issues/13) 인데요.
테스트 코드를 고치는게 아닌 Controller 코드가 PutMapping -> PostMapping으로 변경되어야 합니다.
말씀하신대로 초보자를 위한 책인데 실습 오류는 정말 죄송합니다 ㅠ
다음 인쇄시에 다 정상반영해서 내놓도록 하겠습니다 ㅠ 정말 죄송합니다

**Comment by yanghhh1** [comment]
감사합니다. 이미 올라온 이슈네요 
항상 블로그 보면서 좋은 정보 받아갑니다.
