### ISSUE TITLE
[./gradlew test 오류] p.297

### ISSUE THREAD

**Issue by monkeyDugi** [jojoldu/freelec-springboot2-webservice#191]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: EC2 서버에 소스 클론하고 테스트 검증단계입니다.
./gradlew test를 실행 하면 오류가 발생합니다.
gradle 버전은 4.10.2이고 스프링부트 버전도 .2.1.7 버전입니다.
밑에 사진은 저의 버전 입니다.
![2](https://user-images.githubusercontent.com/53487385/72900371-1ae17680-3d6b-11ea-8c9f-604c04cd391e.PNG)

### 오류 로그
![1](https://user-images.githubusercontent.com/53487385/72900415-2c2a8300-3d6b-11ea-94fc-c01e45078aca.PNG)

**Comment by leeshinyook** [comment]
PostRepositoryTest에 있는 import javafx.geometry.Pos 부분 지워보세요!

**Comment by monkeyDugi** [comment]
@leeshinyook
아직 해보진 않았는데 그 부분이 뭐죠??

**Comment by jojoldu** [comment]
@monkeyDugi 캡쳐에 나와있는 메세지입니다!

![image](https://user-images.githubusercontent.com/7760496/73836906-a8d15d00-4853-11ea-9e05-6d9bfed98cd1.png)

보시면 PostRepositoryTest 에 3번째 라인에 위 import문이 있다는 의미이구요
해당 import문이 문제가 있다는 메세지입니다!
해당 라인을 삭제해보시겠어요?

**Comment by monkeyDugi** [comment]
> @monkeyDugi 캡쳐에 나와있는 메세지입니다!
> 
> ![image](https://user-images.githubusercontent.com/7760496/73836906-a8d15d00-4853-11ea-9e05-6d9bfed98cd1.png)
> 
> 보시면 PostRepositoryTest 에 3번째 라인에 위 import문이 있다는 의미이구요
> 해당 import문이 문제가 있다는 메세지입니다!
> 해당 라인을 삭제해보시겠어요?

감사합니다.. 저는 왜 저런 로그를 제대로 보지 못할까요 ㅜㅜ 다음엔 꼭 더 살펴볼게요!!

**Comment by jojoldu** [comment]
@monkeyDugi 아고 아닙니다 :) 고생하셨습니다!
