### ISSUE TITLE
[오류] p.212 기존 테스트에 시큐리티 적용하기

### ISSUE THREAD

**Issue by superbly** [jojoldu/freelec-springboot2-webservice#192]
### 어떤 오류인가요?

오류설명: 
P.212 전체 테스트를 실행하면 책에는 7건이 실패하는데 저는 4건만 실패하고 나머지는 패스합니다. 

왜 책과 다른 결과가 나오는지 찾아 보았는데 제 프로젝트의 main/resources/ application.properties에서는 spring.profiles.include=oauth (처음 책에서도 oauth 설정할 때 real-oauth가 아닌 oauth로 나와있음)라고 되어있고 동욱님 깃 소스를 보면 spring.profiles.include=real-oauth라고 되어 있었습니다.

real-oauth 로 수정후 테스트 돌려보니 정상적으로 7건이 실패합니다.

application.properties에서 oauth와 real-oauth의 정확한 차이점이 궁금합니다.

### 오류 로그

![스크린샷 2020-01-23 오전 9 42 35](https://user-images.githubusercontent.com/40204800/72947301-edc1b200-3dc4-11ea-9860-c338506ed7b2.png)

![스크린샷 2020-01-23 오전 9 42 51](https://user-images.githubusercontent.com/40204800/72947324-ffa35500-3dc4-11ea-8f1c-3e1b6483a11f.png)

![스크린샷 2020-01-23 오전 9 45 43](https://user-images.githubusercontent.com/40204800/72947393-35e0d480-3dc5-11ea-9827-cbb0a86aab10.png)

![스크린샷 2020-01-23 오전 9 46 04](https://user-images.githubusercontent.com/40204800/72947402-3bd6b580-3dc5-11ea-97cf-652658fddf40.png)

**Comment by jojoldu** [comment]
@superbly 님 안녕하세요!
제 코드는 아래와 같이 **시크릿 값을 제외한 나머지 코드를 보여주기** 위한 용도로 사용되어있습니다.
real-oauth를 사용한 이유는 실습하실분들이 사용할 oauth는 아래와 같이 **복사해가시라는**의미로 둬야하니, 다른 이름을 써야해서 사용한 것 뿐입니다.
실제로는 oauth가 되어야만 맞습니다.

![image](https://user-images.githubusercontent.com/7760496/73838489-22b71580-4857-11ea-915a-a0114a23c7e2.png)

**Comment by ByungJun25** [comment]
@jojoldu 님, @superbly 님 안녕하세요!

다름이 아니라 저 또한 실습중 test가 통과하기에 그에 대해 알아보았습니다.
https://github.com/spring-projects/spring-boot/issues/7668#issuecomment-327542094

위 이슈를 보면 알 수 있듯이 현재 `spring.profiles.include` 코드는 `@SpringBootTest` 어노테이션을 사용할 경우, 적용이 되기 때문에 저 어노테이션이 적용된 테스트는 통과하게 됩니다.

통과하지 못한 테스트를 보게되면, `@WebMvcTest` 를 사용하였기에 `spring.profiles.include` 가 적용되지 않았고 다른 테스트는 책의 설명대로 권한문제로 인해 테스트가 실패하게됩니다.

감사합니다.

**Comment by ByungJun25** [comment]
@jojoldu 님 안녕하세요!

실습 도중 저 또한 Test가 통과되는 부분이 있어서 질문이 있습니다.

https://github.com/spring-projects/spring-boot/issues/7668#issuecomment-327542094

위 링크에서 설명을 보면 `spring.profiles.include` 값은 `@SpringBootTest` 를 통한 설정에도 적용이 된다고 나와있습니다.
그래서 Test 코드를 보니, 실패한 코드는 `@WebMvcTest` 를 사용하였거나, 권한문제로 실패하는 것뿐이였습니다. 

그럼 `@SpringBootTest` 를 이용한 테스트의 경우에는 `spring.profiles.include` 값이 적용되는 것인 아닌가요? 

감사합니다.

**Comment by JaeHyeonKim19** [comment]
@ByungJun25 님 안녕하세요!

저도 같은 내용으로 궁금해서 검색하다가 병준님의 글을 읽게되었는데요. 그러면 병준님 의견으로는 7개가 아니라 4개의 테스트가 fail되는게 맞다는 말씀이신거죠??

**Comment by jojoldu** [comment]
@ByungJun25 님 의견 감사합니다 :) 말씀해주신것에 동의합니다 ^^
@superbly 답변이 없으셔서 해당 이슈는 종료하겠습니다 :)
