### ISSUE TITLE
[오타 제보] 105p 그림 3-14

### ISSUE THREAD

**Issue by fuhaha** [jojoldu/freelec-springboot2-webservice#193]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타
* 오류설명 
책내용상 service directory애 PostService.java가 배치되여야함 
* as-is (오타):
service.posts
* to-be (교정):
service

**Comment by jojoldu** [comment]
@fuhaha 앗 제보 감사합니다 :)
