### ISSUE TITLE
[오타 제보] 105p PostsApiController 소스코드

### ISSUE THREAD

**Issue by fuhaha** [jojoldu/freelec-springboot2-webservice#194]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타
* 오류내용
PostsApiController.java 소스코드에 12Line '@PutMapping("/api/v1/posts")'
sample code 내용상 Put이 아닌 Post 인것이 맞음
* as-is (오타):
@PutMapping("/api/v1/posts")
* to-be (교정):
@PostMapping("/api/v1/posts")

**Comment by jypweback** [comment]
저도 해당건때문에 한참을 헤맸습니다..ㅜㅜ

**Comment by jojoldu** [comment]
@fuhaha 님 제보 감사합니다 :)
이미 올라온건이라 중복이슈로 두겠습니다 :)

https://github.com/jojoldu/freelec-springboot2-webservice/issues/6
