### ISSUE TITLE
[오류] p.397 step2 어플리케이션 실행 중 문제

### ISSUE THREAD

**Issue by padoling** [jojoldu/freelec-springboot2-webservice#196]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

안녕하세요! 책을 따라 실습을 전부 끝마쳤고 다른 오류는 전혀 없었습니다.
다만 애플리케이션 실행 여부를 확인했을 때 p.397처럼 step3 애플리케이션 2개만 실행되고 있는 것이 아니라, 이전에 실행시켰던 step2 애플리케이션까지 여전히 실행되고 있는 것을 발견했습니다.
제가 코드를 잘못 작성해서 그런 것인지, 원래 step2 애플리케이션을 강제 종료시키지 않으면 계속 실행되고 있는 게 맞는 건지 궁금해서 질문 올립니다!

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/padoling/springboot2-guide

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![bandicam 2020-01-23 17-15-50-369](https://user-images.githubusercontent.com/33655848/72967187-16b56780-3e04-11ea-98bd-16c706bf6930.jpg)

**Comment by jojoldu** [comment]
@padoling 님 안녕하세요!
질문하신대로 step2에서 실행중인 애플리케이션은 ```kill``` 명령어로 강제종료하시면 됩니다 :)
step2와 step3의 포트를 서로 다르게 해놓았기 때문에 step2로 인해서 step3이 안되는 일은 피하도록 책의 예제를 구성하였는데요 :)

step3까지 잘 실행되셨다면 2는 끄셔도 됩니다!
3이 잘안되면 2를 참고해서 수정할수도 있어 이 부분을 강제종료하는건 책에 포함시키지는 않았습니다 :)
