### ISSUE TITLE
[오타 제보] 389p.몇페이지 stop.sh

### ISSUE THREAD

**Issue by ggomjae** [jojoldu/freelec-springboot2-webservice#198]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타): 

* to-be (교정): #!/user/bin/env bash , ABSPATH  = $(readlink -f $0)  

두줄이 빠졌습니다.

**Comment by jojoldu** [comment]
@ggomjae 아고 실습에는 포함하고 책에는 포함시키지 않았네요 ㅠ
제보 감사합니다!

```
#!/usr/bin/env bash
```
