### ISSUE TITLE
[오류] p.113 에서 findById 메소드위에는 @Transactional 안쓰여져 있던데 이유가 궁금합니다..

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#199]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명:

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/48509269/73118165-eac8ec00-3f93-11ea-9cbb-6d16dd03e657.png)

책 113페이지에서 update 메소드 위에는 @Transactional 어노테이션이 붙어있는데 findById 메소드위에는 안붙어있는 이유가 있는건가요?

**Comment by choiasher** [comment]
@transactional 어노테이션은 ACID 트랜잭션 특성중의 하나인 atomicity를 보장하기 위해서 사용하는데, Read는 원자성 보장이 되지 않아도 됩니다. 
즉, 읽기 전용이 아닌 서비스 계층에서 중첩된 트랜잭션이 있는 경우에 사용하는 어노테이션이기 때문에 생략되어도 무방합니다.

[https://stackoverflow.com/questions/22200458/transactional-on-a-jparepository](https://stackoverflow.com/questions/22200458/transactional-on-a-jparepository)

> If you have a nested transaction from your service layer which is not read only, then it would use that one, and you will effectively disregard this annotation.

**Comment by MinhoLee93** [comment]
@transactional은 해당 logic 내부에서 error가 날경우에 데이터베이스를 rollback 해주려고 선언하기때문에, 단순히 조회하는 query는 rollback 할 필요가 없어서 아닐까요??

**Comment by jojoldu** [comment]
@zhtmr 님 안녕하세요!

@MinhoLee93 님의 말씀대로 findById는 굳이 트랜잭션이 필요한 로직이 아니라 포함되어있지 않습니다 :)
