### ISSUE TITLE
p101. 오타

### ISSUE THREAD

**Issue by evan-hwang** [jojoldu/freelec-springboot2-webservice#20]
맨 아랫줄에 @Transactionl -> @Transactional
으로 오타가 있습니다~!

책 읽고 있는데 너무 너무 잘 쓰셨네요.
제가 본 스프링부트 서적 중에 제일 잘 읽히고 좋습니다!! ㅎㅎ

**Comment by jojoldu** [comment]
@id1992 앗 감사합니다 ㅠㅠ
오타 제보를 받고 난뒤로 정말 죄송한 마음 뿐이네요 ㅠㅠ
제보 정말 감사드려요!

**Comment by id1992** [comment]
아니에요 ㅎㅎㅎ 이렇게 이슈에서 즉각 즉각 피드백해주셔서 보는데는 전혀 문제 없습니다!!

**Comment by jojoldu** [comment]
@id1992 아고 격려 감사합니다 ㅠㅠ
열심히 피드백 드릴게요!
