### ISSUE TITLE
[오류] p.306 deploy.sh 실행 시 결과가 다른 문제 발생

### ISSUE THREAD

**Issue by benny-coding** [jojoldu/freelec-springboot2-webservice#200]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 

이동욱님 안녕하세요! 
nohup.out 확인 중 책과 다른 결과를 출력하여 전달 드립니다!

#### 실행화면
![image](https://user-images.githubusercontent.com/41322259/73121733-96883100-3fc0-11ea-979c-12fe0bd5ff3c.png)

#### 실행 후 vim nohup.out 실행 시
![image](https://user-images.githubusercontent.com/41322259/73121676-eb777780-3fbf-11ea-841c-a6b422c85d97.png)

deploy.sh 실행 시
306 페이지의 
o.a.c.c.C.[Toccat].[localhost].[/] : Initializing Spring DispatcherServlet : 'dispatcherServlet'
o.s.web.servlet.DispatcherServlet : Initialzing Servlet 'dispatcherServelt'
o.s.web.servlet.DispatcherServlet : Completed initialization in 25 ms

위 내용이 출력이 안되고 있습니다 nohup.out 파일에서 안 나오고 있는데 제가 어떤 부분을 빼먹은 것일까요..? ㅜㅜ

**Comment by jojoldu** [comment]
@benny-coding 님 안녕하세요! :)
보여주신 로그상으로는 스프링 부트가 잘 실행된것 같습니다 :)
저역시 2.1.9 이상의 버전에서는 아래와 같이 로그가 보입니다 :)

![image](https://user-images.githubusercontent.com/7760496/73839723-04064e00-485a-11ea-97b4-a57d43e9e9b4.png)

스프링부트 버전상의 차이인것 같습니다 :)

**Comment by benny-coding** [comment]
너무 감사합니다~! ㅎㅎ
