### ISSUE TITLE
[오타 제보] p.183 OAuth2UserService 타입 명시

### ISSUE THREAD

**Issue by cupjoo** [jojoldu/freelec-springboot2-webservice#202]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타
![제목 없음](https://user-images.githubusercontent.com/30645938/73153438-2c35d480-4117-11ea-93cc-dab39bd1a51e.png)
기능 상으로는 문제가 없으나 IntelliJ에서는 타입을 명시해줄 것을 권고하고 있네요. 의미가 있을진 모르겠는데 다음과 같이 형을 명시해주는 것은 어떤가요?

* as-is (오타):
`OAuth2UserService delegate = new DefaultOAuth2UserService();
`
* to-be (교정):
`OAuth2UserService<OAuth2UserRequest, OAuth2User> delegate = new DefaultOAuth2UserService();
`

**Comment by jojoldu** [comment]
@cupjoo 좋은 제안 감사합니다 :)
말씀하신대로 명시적으로 선언하는게 더 좋아보입니다 :)
