### ISSUE TITLE
[오류] p.72

### ISSUE THREAD

**Issue by YeongSeonLee** [jojoldu/freelec-springboot2-webservice#203]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요? 

오류설명: 72p의 name이 initialized가 되어있지 않다고 나오네요

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/YeongSeonLee/springboot2-webservice.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![p 72](https://user-images.githubusercontent.com/50314000/73153735-4fad4f00-4118-11ea-98ae-38dbd72e0bef.PNG)

**Comment by alicesister1** [comment]
#2 해보셨나요?

**Comment by YeongSeonLee** [comment]
> #2 해보셨나요?
못 찾아서 다시 공부할겸 처음부터 다시 만들고 있습니다....  :(

> Task :cleanTest UP-TO-DATE
> Task :compileJava FAILED
/Users/rick/IdeaProjects/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/HelloResponseDto.java:11: error: variable name not initialized in the default constructor
    private final String name;
                         ^
/Users/rick/IdeaProjects/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/HelloResponseDto.java:12: error: variable amount not initialized in the default constructor
    private final int amount;
                      ^
2 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 0s
2 actionable tasks: 1 executed, 1 up-to-date

빨간 색으로 오류? 는 안뜨는데 HelloRestponseDtoTest를 Run 하는데 실패하네요 

전에 이클립스에서 스프링을 조금 해봐서 대충만 알아서 이유를 찾고 있네요 ...

**Comment by YeongSeonLee** [comment]
> #2 해보셨나요?

이게 타고 들어갈 수 있는거네요 

저는 저걸로 해결 후, 95p 정도 진행 하다가 되돌아가 보니 오류가 떠서 질문 했었는데요 결국 찾지 못해서 다시 공부할

겸 처음부터 만들었습니다. 

모르고 계속 intellij 업데이트를 진행해서 뭔가 충돌이 생긴거 같기도 하고.... 이유는 제 실력으론 못찾아서... 최근 3.2로 진행했더니 win에서 plugin이 로딩되지 않는 이슈가 생겨 proxy도 바꿔보고 했으나 해결하지 못해서 몇일동안 삽질 후 전부 지우고 2.3 버전에서 다시 진행중입니다. 신경 써주셔서 감사합니다!! 
ps. 그리고 다시 72p 저 이슈때문에 다시 와서 찾았습니다. 다시 감사합니다~~😊

**Comment by YeongSeonLee** [comment]
제가 컴퓨터가 2개가 있어서 깃을 이용해서 재 오픈시 저런 오류가 나는 거 같습니다.  그리고 72p gradle  버전 역시
YeongSeonui-MacBookPro:freelec-springboot2-webservice rick$ ./gradlew wrapper --gradle-version 4.10.2
bash: ./gradlew: Permission denied
로 안됩니다....

**Comment by alicesister1** [comment]
https://stackoverflow.com/a/17669566

실행권한이 없다고 뜨네요
`chmod +x gradlew` 후에 다시 실행해보세요

**Comment by YeongSeonLee** [comment]
> https://stackoverflow.com/a/17669566
> 
> 실행권한이 없다고 뜨네요
> `chmod +x gradlew` 후에 다시 실행해보세요

아... 제가 찾았어야하는 건데 감사합니다. 윈도우와 맥 둘 사용 중인데 윈도우에서 바로 링크걸어주신 걸로 하니 되었습니다. 그리고 맥에서도 chmod~ 이걸 쓰니 역시 되었구요. 감사합니다. 

하지만 제가 처음 질문 드렸던 might not have been initialized 이 초기화 되어있지 않다는게 전혀 모르겠네요... HelloResponseDto 클래스에서 private final로 초기화 하는 부분일 텐데... 기존에 처음 작성할 때는 잘 되었는데 git에서 pull 한 뒤, 저런 문제가 생기니 뭐가 문제인지 모르겠습니다. 배움이 부족한가보네요 혹시나 아시겠으면 가르침 부탁 드립니다...

**Comment by alicesister1** [comment]
받아서 확인해보니 롬복에 필요한 프로젝트 설정이 빠져있네요. 
책 69~70 페이지에 자세하게 써있으니 참고하셔서 진행하시면 될 것 같네요.
설정 후 HelloController 테스트가 패스되는 것을 확인했습니다.

**Comment by YeongSeonLee** [comment]
안된다고 프로젝트를 지웠다가 버전 낮췄다가 하느라 롬복 저걸 프로젝트마다 진행해야된다는데 그걸 빼먹고 안했나보네요 저도 말씀해주신거 해보니까 되네요 감사합니다..... 저는 Event Log를 못본건지 저렇게 떠있으니 신기하네요 프로그래밍이 모르면 바보가 되는 이 기분이 참 기분 좋지 않으면서, 해결하고 나면 시원한 이 느낌이 재밌네요. 기초적인 부분이라 슬프긴하지만 그래도 이렇게 실력이 늘어가는 거라 자위하며 정진하겠습니다. 

신경써주셔서 감사합니다. 혹시나 조심스럽게 다음 오류가 생긴다면 다시 도움을 요청할 수 있는지 기대하며 이번 이슈를 마칩니다.

다시 한번 감사합니다.
