### ISSUE TITLE
[오타 제보] p.323 오타 수정

### ISSUE THREAD

**Issue by bipowi** [jojoldu/freelec-springboot2-webservice#204]
Travis CI 웹서비스 설정 내

### 오타

* as-is (오타): 왼쪽 위에 [계정명 -> Settings] ...

* to-be (교정): 오른쪽 위에 [계정명 -> Settings]

**Comment by jojoldu** [comment]
@bipowi 아고 ㅠㅠ 제보 감사합니다!
