### ISSUE TITLE
[오류] p.111

### ISSUE THREAD

**Issue by sleep76** [jojoldu/freelec-springboot2-webservice#207]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?
PostsUpdateRequestDto
클래스를 찾을수가 없습니다.

오류설명: 

교재내용을 따라 가고 있는데요. 111p 에 
PostsUpdateRequestDto 를 사용하는데
책 내용에서는 아직 생성한적 없는 클래스인걸요?
IDE 에서도 찾을수 없다고 클래스 생성 하겠냐고 하는데
아무리 앞뒤로 찾아봐도 해당 클래스 생성 하는 부분이 없네요.
바로 테스트 코드로 넘어가는데 심지어 테스트 코드에서도 
PostsUpdateRequestDto 클래스 사용하는데요.
어찌된 건가요?

**Comment by jypweback** [comment]
해당 클래스가 교재에 명시되어있지않내요.

**Comment by MinhoLee93** [comment]
일단 여기를 참고해서 진행하시면 될 것 같아요 :)

https://github.com/jojoldu/freelec-springboot2-webservice/blob/master/src/main/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto.java

**Comment by sleep76** [comment]
진행이야 뭐 코드 수정하면 할수 있습니다. 다만 책을 그대로 따라 가다가는 반드시 문제가 될수 있는 부분이라 어떻게든 수정해야 할 부분이라고 생각합니다
-------- 원본 이메일 --------발신: Minho Lee <notifications@github.com> 날짜: 20/2/2  오후 2:06  (GMT+09:00) 받은 사람: jojoldu/freelec-springboot2-webservice <freelec-springboot2-webservice@noreply.github.com> 참조: sleep76 <sleepz@yonsei.ac.kr>, Author <author@noreply.github.com> 제목: Re: [jojoldu/freelec-springboot2-webservice] [오류] p.111 (#207) 일단 여기를 참고해서 진행하시면 될 것 같아요 :)

https://github.com/jojoldu/freelec-springboot2-webservice/blob/master/src/main/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto.java



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jojoldu/freelec-springboot2-webservice/issues/207?email_source=notifications\u0026email_token=AJHG6Y7GM3O26YTHHIFMG6LRAZIEDA5CNFSM4KMON6R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKRN6OI#issuecomment-581099321",

"url": "https://github.com/jojoldu/freelec-springboot2-webservice/issues/207?email_source=notifications\u0026email_token=AJHG6Y7GM3O26YTHHIFMG6LRAZIEDA5CNFSM4KMON6R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKRN6OI#issuecomment-581099321",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jojoldu** [comment]
@sleep76 님 제보 감사합니다 :)
해당 내용은 3쇄에 포함되어 나갈 예정입니다ㅠ 불편을 드려 죄송합니다 ㅠ
