### ISSUE TITLE
[오타 제보] p.330 사용자 이름 부분 오타 발견

### ISSUE THREAD

**Issue by benny-coding** [jojoldu/freelec-springboot2-webservice#209]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타
그림 9-8 엑세스 유형 선택에서 사용자 이름 부분 

* as-is (오타): freelect-travis-deploy

* to-be (교정): freelec-travis-deploy

입니다!

**Comment by jojoldu** [comment]
@benny-coding 앗! 제보 감사합니다 :)
