### ISSUE TITLE
p.181 갓동욱님 시큐리티설정 중 궁금한 게 있습니다!

### ISSUE THREAD

**Issue by gracelove91** [jojoldu/freelec-springboot2-webservice#21]
보통 js, 이미지 등등과 같은 정적리소스들은 webignoring 으로 시큐리티필터를 안타게 한다는 걸로 알고있는데요
왜 permitAll()로 설정하셨는지 궁금합니다!

**Comment by jojoldu** [comment]
@gracelove91 님 안녕하세요!
질문 감사합니다 :)
일단 2가지 방식에 큰 차이가 있진 않구요!
webignoring 을 쓰기 위해선 HttpSecurity 외에 WebSecurity 설정이 추가로 필요합니다 :)
그래서 실습하실떄 한눈에 다 보시기 어려우실것 같아 하나의 설정으로 몰았구요 :)
만약 상세하게 기능을 나누고 싶으시다면 말씀하신대로 WebSecurity.ignoring() 설정으로 진행하셔도 좋습니다
WebSecurity.ignoring() 을 쓰는게 좀 더 구조적으로 좋은 패턴이며,
이 책에서는 코드를 좀 더 보기쉽게 하기 위해 HttpSecurity 에 몰았던것 뿐입니다^^;

**Comment by gracelove91** [comment]
크으.. 상세한 설명 감사합니다!!

**Comment by jojoldu** [comment]
아고 질문 및 제보 정말 감사드립니다 :)
