### ISSUE TITLE
[오타 제보] p.142

### ISSUE THREAD

**Issue by kimjunghak** [jojoldu/freelec-springboot2-webservice#210]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타): index.init();  ,  var index = {}

* to-be (교정): main.init();  ,  var main = {}

p141에는 첫 문장이 var main으로 시작하는데 p142에서는 var index를 선언하였다고 해서 헷갈려서 github 코드 참고하니깐 var main & main.init()으로 되어있네요 어느 것이 오타인지는 헷갈리지만 github 소스코드 기준으로 제보해봅니다.

**Comment by jojoldu** [comment]
@kimjunghak 앗 제보 감사합니다!
말씀하신 내용이 맞습니다 :)
