### ISSUE TITLE
[오류] p.113 PostsUpdateRequestDto.java는 어디에?

### ISSUE THREAD

**Issue by camel-master** [jojoldu/freelec-springboot2-webservice#211]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명:PostsService.java 작성 시 PostsUpdateRequestDto Class가 필요하지만 
책에는 해당하는 class의 source가 제공되지 않아 github에서 내려 받은 source
내용을 참고하여 작성하였습니다. 책만 보고 따라갈 수 있도록 PostsUpdateRequestDto.java
code도 추가 되었으면 합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by gimdongwon** [comment]
없네요! ㅎㅎ
