### ISSUE TITLE
[오류] p.305 Unable to access jarfile

### ISSUE THREAD

**Issue by monkeyDugi** [jojoldu/freelec-springboot2-webservice#212]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: application-oauth.properties 추가하면서 deploy.sh의 스크립트 변경하면서 생긴 에러입니다. 비슷한 내용이 좀 있었지만 조금 달라서 질문 드립니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
먼저 오류는 아니고 경고가 뜨는데 빨간 박스 부분이 이상이 없는 건가요??
![1](https://user-images.githubusercontent.com/53487385/73461884-3fb69900-43be-11ea-9bd0-1c366ae0a437.PNG)

빌드 후 nohup.out을 확인해보면 아래와 같은 에러가 발생합니다.
![캡처](https://user-images.githubusercontent.com/53487385/73539152-16eedc00-4470-11ea-886b-dda5decad4a1.PNG)

deploy.sh 내용입니다.
![캡처](https://user-images.githubusercontent.com/53487385/73539211-3554d780-4470-11ea-89b1-b18431fc5fd4.PNG)

**Comment by monkeyDugi** [comment]
![캡처](https://user-images.githubusercontent.com/53487385/73586455-b6ec4a00-44f0-11ea-9818-b60478bd65c1.PNG)
해결 하였습니다. \ 요 표시가 한줄로 연결하는 거라는데 저는 일자로 쭉 나열해서 안되었나봅니다.
이렇게 책 처럼 똑같이 하니까 되네요...

**Comment by jojoldu** [comment]
@monkeyDugi 앗 해결되셔서 다행입니다 ㅎㅎ
고생하셨습니다!

**Comment by heygwangjin** [comment]
덕분에 해결 했습니다. 감사합니다!

**Comment by jinugi214** [comment]
감사합니다!

**Comment by hyejinU** [comment]
저도 덕분에 해결했습니다 감사합니다!
