### ISSUE TITLE
[오류] p.89

### ISSUE THREAD

**Issue by camel-master** [jojoldu/freelec-springboot2-webservice#213]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 
    -2쇄 기준이며 p.114의 테스트를 진행하는 중 update가 되지 않아 test 실패.
    -확인결과 p.89의 소스에서 다음의 update 메소드가 누락된 것을 발견

    public void update(String title, String content) {
        this.title = title;
        this.content = content;
    }

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by MinhoLee93** [comment]
아래 내용을 참고하시면 될 것 같아요 :)

#15

**Comment by jojoldu** [comment]
@camel-master 제보 감사합니다!
@MinhoLee93 님이 얘기하신대로 update 메소드가 누락되었습니다 ㅠ
오타가 있어서 정말 죄송합니다 ㅠ
