### ISSUE TITLE
application.properties파일에 대한 질문입니다. 오류는 아닙니다.

### ISSUE THREAD

**Issue by monkeyDugi** [jojoldu/freelec-springboot2-webservice#214]
application.properties 파일은 로컬에서 사용하는 h2 테스트 DB용으로 사용하는 것으로 알고 있는데
왜 서버의 deploy.sh에 굳이 설정을 하나요??
테스트 해봤는데 없어도 서버는 이상없이 동작 하더라구요

**Comment by jojoldu** [comment]
@monkeyDugi 앗 지금은 로컬의 설정들만 포함되지만, 이후에는 어떤 설정들이 **운영에서만 필요할지 알수 없습니다**
좀 더 크리티컬한 보안키나, 암호화 키 등이 언제든 **운영에서만** 사용될수 있기 때문에 웬만해선 운영용으로 별도로 관리하시는게 편하실거라 생각되어요 :)

**Comment by monkeyDugi** [comment]
> @monkeyDugi 앗 지금은 로컬의 설정들만 포함되지만, 이후에는 어떤 설정들이 **운영에서만 필요할지 알수 없습니다**
> 좀 더 크리티컬한 보안키나, 암호화 키 등이 언제든 **운영에서만** 사용될수 있기 때문에 웬만해선 운영용으로 별도로 관리하시는게 편하실거라 생각되어요 :)

감사합니다!!!

**Comment by jojoldu** [comment]
@monkeyDugi 감사합니다 :)
