### ISSUE TITLE
[오류] p.109 Json parsing Error

### ISSUE THREAD

**Issue by css9596** [jojoldu/freelec-springboot2-webservice#215]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?
오류설명: PostsApiControllerTest 코드 작성 후 Test시 에러 발생
 //when
ResponseEntity<Long> responseEntity = restTemplate.postForEntity(url, requestDto, Long.class);

이 부분에서..
JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token
 at [Source: (PushbackInputStream); line: 1, column: 1]

이런 에러가 발생했습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/css9596/CSSFirstWebService

### 오류 로그
![p 109 Console Error](https://user-images.githubusercontent.com/38674670/73589994-802e2800-4520-11ea-8f24-e8219a0becfa.jpg)

**Comment by daknichu** [comment]
#194 번 이슈의 오타가 원인 인듯 합니다.

**Comment by jojoldu** [comment]
@css9596 앗 책의 오타였습니다 ㅠㅠ 오해를 드려서 정말 죄송합니다 ㅠ

@daknichu 님 답변 감사합니다 :)
