### ISSUE TITLE
[오류] p.326 Travis CI Build 에러

### ISSUE THREAD

**Issue by dkyou7** [jojoldu/freelec-springboot2-webservice#217]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: 빌드 에러가 발생합니다!

![image](https://user-images.githubusercontent.com/26649731/73634725-30c53480-46a5-11ea-8ca5-eba6af9d324e.png)

다음과 같이 접근 권한 에러가 발생하는데요. #75 와 동일 에러인듯 해서 저도 travis.yml 파일에 
```yml
before_install:
  - chomod +x gradlew
```
을 추가하였지만 계속해서 같은 에러가 발생합니다. 

1. 추가 방법을 알려주시면 감사하겠습니다.
2. `.travis.yml` vs `travis.yml` 에 대해 알려주세요. 책에는 `.travis.yml` 으로 표기되어있습니다.
3. 본인 메일 주소를 입력하라고 하셨는데, ""을 붙여서 입력하나요? 아니면 그냥 입력하나요? 너무 기초적인 질문이라 죄송합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL:  https://github.com/dkyou7/freelec-springboot2-webservice/blob/master/travis.yml

**Comment by hoonpig** [comment]
전 좀 다른에러가나네요;;;

Hibernate: drop table if exists posts
2020-02-03 08:58:50.363  INFO 4577 --- [       Thread-7] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-02-03 08:58:50.365  INFO 4577 --- [       Thread-7] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table if exists posts
Hibernate: drop table if exists user
2020-02-03 08:58:50.370  INFO 4577 --- [       Thread-9] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
Hibernate: drop table if exists user
2020-02-03 08:59:00.007 ERROR 4577 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed

위와같은에러가나는데;;;흠...찾기힘드네요

**Comment by hoonpig** [comment]
해결했습니다..
와 저도 이거인줄은 몰랐는데..

before_install:
  - chmod +x gradlew

이옵션 추가해서 성공했네요...

**Comment by dkyou7** [comment]
@hoonpig 님, 해결 되셨다니 다행이네요..!
> 혹시 제 github url 과 동일한 코드인지 확인한번 해주실 수 있나요?

**Comment by dkyou7** [comment]
```cmd
/home/travis/.travis/functions: line 351: ./gradlew: Permission denied
The command "eval ./gradlew assemble " failed. Retrying, 2 of 3.
/home/travis/.travis/functions: line 351: ./gradlew: Permission denied
The command "eval ./gradlew assemble " failed. Retrying, 3 of 3.
/home/travis/.travis/functions: line 351: ./gradlew: Permission denied
The command "eval ./gradlew assemble " failed 3 times.
The command "./gradlew assemble" failed and exited with 126 during .
Your build has been stopped.
```
chmod 코드를 제거하면 이런 에러가 나오네요.

```cmd
0.09s$ chomod +x gradlew
No command 'chomod' found, did you mean:
 Command 'chmod' from package 'coreutils' (main)
chomod: command not found
The command "chomod +x gradlew" failed and exited with 127 during .
Your build has been stopped.
```
chmod 코드 추가시 이런 에러가 납니다.

**Comment by dkyou7** [comment]
# 자체해결하였습니다.

> 부끄럽게도 test 파일 에러 실패로 인해 오류가 났던 것이었습니다. 자문 자답을 하자면
1. 추가 방법을 알려주시면 감사하겠습니다.
- Github URL: https://github.com/dkyou7/freelec-springboot2-webservice/blob/master/.travis.yml
2. .'travis.yml vs travis.yml' 에 대해 알려주세요. 책에는 '.travis.yml' 으로 표기되어있습니다.
- '.travis.yml'이 맞습니다.
3. 본인 메일 주소를 입력하라고 하셨는데, ""을 붙여서 입력하나요? 아니면 그냥 입력하나요? 너무 기초적인 질문이라 죄송합니다.
- "" 없이 입력합니다.
