### ISSUE TITLE
[오류] springSecurityFilterChain 오류

### ISSUE THREAD

**Issue by kimjunghak** [jojoldu/freelec-springboot2-webservice#219]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: ClientRegistrationRepository 이 필요하다고 해요..

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/kimjunghak/webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

***************************
APPLICATION FAILED TO START
***************************

Description:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'clientRegistrationRepository' in 'OAuth2ClientRegistrationRepositoryConfiguration' not loaded because OAuth2 Clients Configured Condition registered clients is not available

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:62548', transport: 'socket'

Process finished with exit code 1

**Comment by kimjunghak** [comment]
네이버 로그인은 나중에 해볼려고 아직 구현하지 않았는데 그게 문제가 될 수도 있나요?

**Comment by kimjunghak** [comment]
잘못 적용했었네요...

**Comment by jojoldu** [comment]
@kimjunghak ㅎㅎ;; 해결하셔서 다행입니다!

**Comment by Hae-Riri** [comment]
저 혹시 어디가 잘못되셨던건지 알 수 있을까요?
