### ISSUE TITLE
[오류] p.106 PostsService 에러

### ISSUE THREAD

**Issue by ParkSale** [jojoldu/freelec-springboot2-webservice#221]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: PostService파일에서 return postsRepository.save(requestDto.toEntity()).getId(); 부분에서
Inferred type 'S' for type parameter 'S' is not within its bound; should extend 'com.sale.springboot.domain.posts.Posts' 라는 에러가 발생합니다

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: https://github.com/ParkSale/SaleSpringBootProject

### 오류 로그

어떤 오류인지 캡쳐해주세요.
Testing started at 오후 10:32 ...
> Task :cleanTest UP-TO-DATE
> Task :compileJava FAILED
C:\Users\����\IdeaProjects\SaleSpringBootProject\src\main\java\com\sale\springboot\service\posts\PostsService.java:18: error: method save in interface CrudRepository<T,ID> cannot be applied to given types;
        return postsRepository.save(requestDto.toEntity()).getId();
                              ^
  required: S
  found: Object
  reason: inferred type does not conform to upper bound(s)
    inferred: Object
    upper bound(s): Posts
  where S,T,ID are type-variables:
    S extends Posts declared in method <S>save(S)
    T extends Object declared in interface CrudRepository
    ID extends Object declared in interface CrudRepository
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by jojoldu** [comment]
@ParkSale 님 혹시 아래와 같이 설정하신 이유가 있으실까요?

![image](https://user-images.githubusercontent.com/7760496/73840155-e4bbf080-485a-11ea-9823-b54f4deec87e.png)

책에서는 반환 타입을 Posts로 명시했어서요 :)
Object 타입을 하시면 정상적으로 작동하지 않습니다!
수정해주시면 정상작동할거에요 :)
