### ISSUE TITLE
[오류] p.356

### ISSUE THREAD

**Issue by monkeyDugi** [jojoldu/freelec-springboot2-webservice#222]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명:
p.356까지 .travis.yml과 appspec.yml 파일 만들고 push하면 에러가 발생합니다.
바로 전 단계인 S3에 파일 전송 챕터까지는 잘 되었습니다. 그 후 위의 두 파일 수정 및 생성하고 에러가 발생합니다.
Travis CI 로그를 보면 캡쳐와 같이 오류 로그가 발생합니다. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![1](https://user-images.githubusercontent.com/53487385/73754287-871a9c00-47a7-11ea-9203-090d7eb22255.PNG)

**Comment by jojoldu** [comment]
@monkeyDugi AWS Key에 S3 권한만 추가된것 같습니다 :)
책 내용 참고하셔서 Code Deploy 권한도 추가되어있는지 확인해보시겠어요?

**Comment by monkeyDugi** [comment]
> @monkeyDugi AWS Key에 S3 권한만 추가된것 같습니다 :)
> 책 내용 참고하셔서 Code Deploy 권한도 추가되어있는지 확인해보시겠어요?

답변 감사합니다!! 
권한이라고 하시면 역할을 말씀하시는 것 같은데요
![3](https://user-images.githubusercontent.com/53487385/73841798-af190680-485e-11ea-96d7-33ffd87110a4.PNG)
![4](https://user-images.githubusercontent.com/53487385/73841809-b2ac8d80-485e-11ea-83c5-1e765fded514.PNG)


![캡처](https://user-images.githubusercontent.com/53487385/73841684-6e20f200-485e-11ea-96a0-895f0c922aa8.PNG)

이 부분을 말씀하시는 건가요?? 다 되어있는데요 ㅜㅜ 

https://github.com/monkeyDugi/springboot2-webservice
.travis.yml과 appspec.yml 링크입니다.

**Comment by monkeyDugi** [comment]
해결 하였습니다.
원인은 콘솔의 리젼과 소스의 리젼이 달랐습니다.
감사합니다!

**Comment by jojoldu** [comment]
@monkeyDugi 아고 고생하셨습니다 리전이 다른 문제가 종종 발생하는것 같습니다 ㅠ
