### ISSUE TITLE
[오류] p.118페이지

### ISSUE THREAD

**Issue by akima9** [jojoldu/freelec-springboot2-webservice#223]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

http://localhost:8080/api/v1/posts/1 접속하면
아래와 같은 화면이 나옵니다.
---------------------------------------------------------------------------------------------------
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Feb 05 14:27:12 KST 2020
There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'GET' not supported
---------------------------------------------------------------------------------------------------

### 프로젝트 주소

* Github URL: https://github.com/akima9/springboot2-book

### 오류 로그

어떤 오류인지 캡쳐해주세요.
2020-02-05 14:54:05.275  WARN 5252 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]

**Comment by jojoldu** [comment]
@akima9 님 안녕하세요 :)
오타가 보이네요 :)

![image](https://user-images.githubusercontent.com/7760496/73840452-8e02e680-485b-11ea-9a31-7775575d4c8f.png)

vi가 아닌 v1로 해주시면 될것 같습니다 :)

**Comment by akima9** [comment]
@jojoldu 헛.. 감사합니다!!
