### ISSUE TITLE
[오류] p.365 베포 에러

### ISSUE THREAD

**Issue by dkyou7** [jojoldu/freelec-springboot2-webservice#224]
### 어떤 오류인가요?

오류설명: 베포 완료 후 Travis CI, Bucket 모두 정상 성공하였지만 접속할 수 없는 상황입니다.

![image](https://user-images.githubusercontent.com/26649731/73818626-1750f380-4831-11ea-9874-a60bc8d02d01.png)

권한이 거부되었다는데 어떻게 해결해야하나요?

**Comment by jojoldu** [comment]
@dkyou7 님 배포 파일의 권한이 root인듯 보이는데요!

```/home/ec2-user/app/step2/``` 으로 가셔서 ```ls -al```로 jar 파일의 권한이 어떻게 되어있는지 확인해보시겠어요?

app디렉토리 혹은 step2 디렉토리 혹은 jar 등의 권한이 ```ec2-user```가 아닌 다른 권한인것으로 보입니다!
계속 안되신다면 step2 디렉토리를 다 삭제하신 뒤 다시 진행해보시는것도 좋은 방법입니다 :)

**Comment by dkyou7** [comment]
@jojoldu 님, 빠른 답변 감사드립니다.
말씀해 주신대로 권한 확인해보았더니 말씀주신대로 root 권한임을 확인하였습니다.
![image](https://user-images.githubusercontent.com/26649731/73896651-f509b500-48c6-11ea-89aa-7f850c4c372d.png)
그렇다면 root 권한을 ec2-user 권한으로 변경하는 명령어는 어떤 것일지 알려주실 수 있나요??

좋은 책 내주셔서 감사합니다.

**Comment by dkyou7** [comment]
나름 구글링해서 권한 변경 문법이 
```cmd
sudo chown ec2-user ec2-user freelec-springboot2-web~~~
```
이라는 것을 알게 되었는데요, 적용 후

![image](https://user-images.githubusercontent.com/26649731/73897926-fd63ef00-48ca-11ea-9e69-c40067c2a861.png)

된 권한으로 다시 푸쉬 해보았으나 여전히 같은 문제를 가지고 있습니다.

**Comment by dkyou7** [comment]
![image](https://user-images.githubusercontent.com/26649731/73899312-95fc6e00-48cf-11ea-96bb-b83008588dcf.png)

`nohup.out`의 권한이 거부되었다는 로그가 있어 권한을 ec2-user 로 바꾸어주었으나 이번엔 `Travis CI`에서 빌드 실패가 발생하였습니다.

![image](https://user-images.githubusercontent.com/26649731/73899359-bc220e00-48cf-11ea-9534-78bac5dcae12.png)

**Comment by dkyou7** [comment]
### 2. step2 삭제 후 다시 시도 결과 공유

- 결론부터 말씀드리면 **실패**입니다. 이유는 아직 찾지 못했습니다.

![image](https://user-images.githubusercontent.com/26649731/73901036-f0e49400-48d4-11ea-91f9-2dec6725b561.png)

로그도 정상 출력 되는걸로 나오고 `Travis`, `codedeploy` 모두 성공으로 되어있습니다. 

권한 또한 ec2-user로 정상 출력 되고 있습니다.

![image](https://user-images.githubusercontent.com/26649731/73901160-546ec180-48d5-11ea-8053-d229cf7bd7f3.png)


도와주세요 @jojoldu 님!!

**Comment by dkyou7** [comment]
### 3. 개발 수정 중 이상한 사항 발견
- 8.5절부터 차근차근 다시 실습하던 도중 이상한 점을 발견하였습니다. `8.5절`에서 `./deploy.sh` 를 진행하고 aws를 접속하면 이전 버전의 .jar가 실행되는 것 같습니다. 아직 원인은 파악하지 못하였습니다.

**Comment by dkyou7** [comment]
nohup.out의 로그를 보고 db쪽에 문제가 있다는 것을 알게 되었습니다.

![image](https://user-images.githubusercontent.com/26649731/73910414-9ce8a800-48f2-11ea-8ecf-7f4e02315a26.png)

하지만 정확한 해결방법은 아직 찾지 못했습니다.

**Comment by dkyou7** [comment]
> nohup.out의 로그를 보고 db쪽에 문제가 있다는 것을 알게 되었습니다.
> 
> ![image](https://user-images.githubusercontent.com/26649731/73910414-9ce8a800-48f2-11ea-8ecf-7f4e02315a26.png)
> 
> 하지만 정확한 해결방법은 아직 찾지 못했습니다.

build.gradle에 compile을 추가해주었습니다. p.309쪽에 나와있습니다.

해결된 줄 알았으나 이번엔 `freelec-springboot2-webservice` db가 존재하지 않는다는 에러가 발생하였습니다.

![image](https://user-images.githubusercontent.com/26649731/73911879-6f9df900-48f6-11ea-9186-29b4556df05b.png)

정확한 해결방법은 아직 찾지 못했습니다.

**Comment by dkyou7** [comment]
> > nohup.out의 로그를 보고 db쪽에 문제가 있다는 것을 알게 되었습니다.
> > ![image](https://user-images.githubusercontent.com/26649731/73910414-9ce8a800-48f2-11ea-8ecf-7f4e02315a26.png)
> > 하지만 정확한 해결방법은 아직 찾지 못했습니다.
> 
> build.gradle에 compile을 추가해주었습니다. p.309쪽에 나와있습니다.
> 
> 해결된 줄 알았으나 이번엔 `freelec-springboot2-webservice` db가 존재하지 않는다는 에러가 발생하였습니다.
> 
> ![image](https://user-images.githubusercontent.com/26649731/73911879-6f9df900-48f6-11ea-9186-29b4556df05b.png)
> 
> 정확한 해결방법은 아직 찾지 못했습니다.

### 4. 에러 해결 사례 공유
- 어제부터 쭉 잡고있었던 에러가 드디어 원인을 파악하여 자체 해결하였습니다.
- 저와 같은 사례가 없길 기도하며 제가 겪었던 에러를 공유하고자합니다.
   - `freelec-springboot2-webservice`가 도대체 왜 없는가를 찾아보았는데 rds에 등록된 database의 이름은 

![image](https://user-images.githubusercontent.com/26649731/73913359-2f407a00-48fa-11ea-9fb9-04ff6eed0c37.png)

`freelec_springboot2_webservice` 였습니다.

`application-real-db.properties`의 db 이름을 수정해주어 해결하였습니다.
- p.310 에서 database이름을 작성하실 때 **주의**하시길 바라며 이만 마칩니다.

**Comment by dudgh9661** [comment]
8.5절부터 차근차근 다시 실습하던 도중 이상한 점을 발견하였습니다. 8.5절에서 ./deploy.sh 를 진행하고 aws를 접속하면 이전 버전의 .jar가 실행되는 것 같습니다. 아직 원인은 파악하지 못하였습니다.

해당 문제는 어떻게 해결하셨나요?
