### ISSUE TITLE
[오류] p.110  401 UNAUTHORIZED 질문

### ISSUE THREAD

**Issue by kimjeongae** [jojoldu/freelec-springboot2-webservice#227]
### 어떤 오류인가요?

오류설명: 

expected:<[200 OK]> but was:<[401 UNAUTHORIZED]>
Expected :200 OK
Actual   :401 UNAUTHORIZED

com.skykimpro.book.springboot.web.PostsApiControllerTest.Posts_등록된다 
위 함수에 401 UNAUTHORIZED이 발생하면서 오류가 나는데요

assertThat(responseEntity.getStatusCode()).isEqualTo(HttpStatus.OK);
이 코드에서 상태코드가 200과 달라서 나는거 같습니다.
개발환경은 윈도우 입니다.

권한관련 문제인듯 한데 -- 소스를 봐도 잘 모르겠습니다. 답변 부탁드립니다!!

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 
https://github.com/kimjeongae/springboot2-webservice

### 오류 로그
![제목 없음](https://user-images.githubusercontent.com/17589405/73916264-792c5e80-4900-11ea-834b-c61d81114b9b.png)

어떤 오류인지 캡쳐해주세요.

**Comment by MinhoLee93** [comment]
@kimjeongae  401 error는 아마도 spring-security dependency가 build.gradle에 선언되어 있어서 그럴꺼에요.. 해당 오류 무시하시고 진행하시려면 주석처리 한번 해보세요! security 관련 내용은 좀더 뒷장에 나오더라구요 ㅎㅎ

**Comment by kimjeongae** [comment]
> @kimjeongae 401 error는 아마도 spring-security dependency가 build.gradle에 선언되어 있어서 그럴꺼에요.. 해당 오류 무시하시고 진행하시려면 주석처리 한번 해보세요! security 관련 내용은 좀더 뒷장에 나오더라구요 ㅎㅎ

감사합니다^^!!!! 
build.gradle을 진행된 페이지안에 있는 것들로만 정리하고 다시 돌려보니까 정상적으로 테스트 되네요
괜히 꽤부리다가 시간을 흘러버린 듯 하네요 ㅎ ㅏ ㅎ ㅏ.... ..

**Comment by jojoldu** [comment]
@MinhoLee93 님 대신해서 답변해주셔서 감사합니다 :)

@kimjeongae 님 질문 감사합니다 :) 스프링 시큐리티는 의존성만 추가해도 **기본적으로 권한이 활성화**되어버립니다.
그래서 설정없이 그대로 그레이들에 추가하시면 위와 같은 이슈가 발생합니다 :)

**Comment by lkwa201** [comment]
> @kimjeongae 401 error는 아마도 spring-security dependency가 build.gradle에 선언되어 있어서 그럴꺼에요.. 해당 오류 무시하시고 진행하시려면 주석처리 한번 해보세요! security 관련 내용은 좀더 뒷장에 나오더라구요 ㅎㅎ

이 부분 때문에 많은 구글링을 했는데... 이제서 해결되었네요...
그리고 조금 더 테스트 해본 결과 oauth2 이것도 제거해줘야 합니다.
