### ISSUE TITLE
[오류] 무중단 배포 완료 후 글 등록 이슈

### ISSUE THREAD

**Issue by dkyou7** [jojoldu/freelec-springboot2-webservice#228]
### 1. 어떤 오류인가요?

#145 와 동일한 이슈인데요, 마지막 글에서는 해결방법에 대한 이슈 없이 몇일 지나서 재접속시 해결되었다고 나왔습니다. 저도 같은 이슈를 겪고 있는데 해결방법을 정확히 알고싶어 질문 올리게 되었습니다.

* Github URL: https://github.com/dkyou7/freelec-springboot2-webservice

### 2. 오류 로그

1. 기존 에러와 동일 이슈입니다.
![image](https://user-images.githubusercontent.com/26649731/73994174-0078e100-4998-11ea-9b0b-a4c7a67f7453.png)

2. user 권한으로 업데이트도 해주었습니다.
![image](https://user-images.githubusercontent.com/26649731/73994191-0ec6fd00-4998-11ea-9409-a5554f3b5efb.png)

**Comment by dkyou7** [comment]
현재 `OAuthAttributes.java` 에서 임시로 

![image](https://user-images.githubusercontent.com/26649731/73994735-f0620100-4999-11ea-8bc0-93b3f857f67c.png)

이런 방식으로 entity()를 구성하여주었더니 글 작성이 가능합니다. 이게 해결 방법인지는 모르겠지만 좀더 나은 해결 방법이 있다면 가르쳐주시면 감사하겠습니다.

**Comment by monkeyDugi** [comment]
저도 동일한 에러가 발생하는데 저는 그렇게 임시방편 해도 안되네요

**Comment by jojoldu** [comment]
@dkyou7 님 질문 감사합니다 :)
책을 보시면 ```/api``` URL 접근이 가능한 사용자는 USER 권한을 가진 사용자만 가능하게 코드가 소개 되어있습니다 :)
책에서는 권한 변경에 대한 어드민 페이지까지 구성은 하지 않고, H2 console에서 권한을 변경해서 테스트하도록 소개 되어있는데요 :)

가입만 하면 기본 사용자 권한이 GUEST라서 글 등록이 안되셨을거에요!
모든 가입자가 글 작성 권한을 가져도 무방하신걸 원하셨다면  위와 같이 코드를 작성해도 상관 없습니다 :)
만약 그게 아니시라면 특정 사용자의 권한을 변경하는 어드민 페이지를 구성해보시는것도 좋은 경험이 될것 같습니다 :)
