### ISSUE TITLE
질문. @LoginUser 전까지 실습을 진행했는데, 궁금한 부분이 있습니다!

### ISSUE THREAD

**Issue by gracelove91** [jojoldu/freelec-springboot2-webservice#23]
````java
public class CustomOAuth2UserService {
...
@Override
    public OAuth2User loadUser(OAuth2UserRequest userRequest) throws OAuth2AuthenticationException {
 httpSession.setAttribute("user", new SessionUser(user));
}
...
}
````

````java
public class IndexController {
...
 @GetMapping("/")
    public String index(Model model) {
...
        User user = (User) httpSession.getAttribute("user");

        if(user != null) {
            model.addAttribute("userName", user.getName());
        }
...
    }
...
}
````
책에서는
`CustomOAuth2UserService`클래스에는 세션에 SessionUser 타입을 담고,
`IndexController` 클래스에는 세션에서 꺼냈는데 이걸 SessionUser타입으로 형변환을 하지 않고 User타입으로 형변환하는데..(#22 ) 이렇게하면 500에러가 납니다 ㅠ 

SessionUser타입으로 형변환해서 SessionUser 타입으로 받으면 잘 작동됩니다.. 실습오류인지 ㅠ 아니면 제가 뭘 잘못하고있는건지 궁금합니다 어딜 봐야될까요?

**Comment by jojoldu** [comment]
@gracelove91 앗!! 은모님 죄송합니다 ㅠ 제가 잘못된 예제로 만든 코드를 드렸네요 ㅠ
아래 코드처럼 SessionUser로 형변환 하는것이 맞습니다.
```
SessionUser user = (SessionUser) httpSession.getAttribute("user");
```

User로 변환하면 안되는 이유에 대해서 언급하려다 잘못 말씀드렸습니다 ㅠ
오해를 일으켜 죄송합니다 ㅠ

**Comment by gracelove91** [comment]
아닙니다! 이렇게 바로바로 알려주시는데요! 감사합니다!

**Comment by jojoldu** [comment]
아고 ㅠㅠ 감사합니다! ㅠ 앞에 언급했던 이슈에서도 코드 반영했습니다 :)
좋은제보 정말 감사드립니다!
