### ISSUE TITLE
[오류] p.116 application.properties 파일에 옵션추가하면 unused property 라고 뜹니다

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#230]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/48509269/74014475-199e8380-49d2-11ea-94aa-47fe3e813515.png)

노란전구 클릭해서 
![image](https://user-images.githubusercontent.com/48509269/74014514-33d86180-49d2-11ea-901c-83c963715505.png)

suppress 하니까 활성화 되긴 하는데..

 이렇게 해도 되는건가요?

왜 application.properties에 적는 내용들은 unused로 뜨는건지 모르겠습니다.

**Comment by jojoldu** [comment]
@zhtmr 님 안녕하세요 :)
인텔리제이 커뮤니티 버전에서는 스프링에서 사용하는 설정에 대해서는 인식을 못합니다 :)
(인텔리제이 정책상 변경이 안됩니다. 유료버전인 얼티메이트 버전을 사용해야만 합니다)
언유즈드가 뜨는건 당연한것이라, 유료 버전을 사용하시면 정상적으로 사용되는 설정으로 등장할거에요 :)

**Comment by progress0407** [comment]
오 ㅎㅎ.. 궁금하던건데 감사합니다 !
