### ISSUE TITLE
[오류] p.62

### ISSUE THREAD

**Issue by interstander** [jojoldu/freelec-springboot2-webservice#234]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!
--검색에 안보이길래 질문 드려봅니다.
## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 테스트 코드를 따라서 작성중인데.
mvc.perform(get("/hello"))
                .andExpect(status().isOk())
                .andExpect(content().toString(hello));

이 부분에서  get()하고 status(), content()가 에러가 납니다.
가능한 책하고 버전은 똑같이 하며 혹시 잘못한 데가 있나 싶어서 코드를 받아서 복사했는데.

상단에 
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
 이것도 임포트가 안됩니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/interstander/freelec-springboot2-webservice.git

//오류가 있는 상태로 커밋해서 푸시해 두었습니다.

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![질문](https://user-images.githubusercontent.com/33653240/74036531-c9d6b100-49ff-11ea-8617-7333f77bb5da.JPG)

**Comment by dkyou7** [comment]
@interstander 님, 
```
import static org.hamcrest.Matchers.is;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
```
코드를 import 쪽에 붙여넣기 해보시겠어요?

**Comment by interstander** [comment]
이클립스에 따로 작성후 붙여 넣어도 에러가 안없어지고 
임포트된 이름은 검은색으로 비활성화 되어 보입니다.

**Comment by interstander** [comment]
불여 넣기 하고 컴퓨터를 재부팅하니까 되네요..
감사합니다.

**Comment by jojoldu** [comment]
@dkyou7 님 답변 감사합니다 ㅠㅠ

@interstander 님 해결하시느라 고생하셨습니다 :)

**Comment by tlsrid88** [comment]
저도 같은 오류가 있었는데요.
왜 이런 문제가 나타나는지 알 수 있을까요 ??
