### ISSUE TITLE
[오류] p.311

### ISSUE THREAD

**Issue by camel-master** [jojoldu/freelec-springboot2-webservice#235]
### 어떤 오류인가요?

오류설명:
deploy시도 후 nohup.out  을 확인해보니 org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration 에 있는 springSecurityFilterChain을 사용하려면 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' 타입의 빈이필요한데 찾을 수 없어 application을 시작할 수 없다고 나옵니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

![image](https://user-images.githubusercontent.com/60163768/74071803-3e354280-4a48-11ea-9e86-9c7b608beaf3.png)

**Comment by camel-master** [comment]
자답입니다. 

분명 뭔가 빼먹었을 거라고 생각하고 과거부터 더듬어 가다 보니 application-oauth.properties가 빠져있는 것을 확인했습니다. 중요한 정보가 들어있어 .ignore에 등록해 놓았기 때문에 서버에도 다시
생성했어야 했는데 깜박했네요.

**Comment by jojoldu** [comment]
@camel-master 아고 고생하셨습니다 ㅎㅎ
그래도 ignore에 미리 제거하시는건 좋은 습관이신것 같습니다 :)
이게 습관이 안되면 중요한 정보가 Github에 올라가 **프로젝트 자체를 삭제해야될수도 있습니다**
주요 코드가 한번이라도 Github에 올라가면 코드를 제거해도 **Github 히스토리**에 남게 되어서 탈취가 가능해서요 :)
좋은습관 가지셔서 다행입니다 :)
