### ISSUE TITLE
[오류] 102

### ISSUE THREAD

**Issue by NDjust** [jojoldu/freelec-springboot2-webservice#236]
### 어떤 오류인가요?

오류설명: h2-console page

### 프로젝트 주소

**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/NDjust/freeiec-springboot2-webservice

### 오류 로그

 h2-console 페이지 not-found가 뜨네요 ㅠㅠ 따로 mac에 h2 설정이 필요한건가요??

**Comment by MinhoLee93** [comment]
@NDjust application.properties에 오타가 있으시네요! ㅎㅎ spring.h2.console.enable=true 에서 enable이 아니라 enabled로 작성하셔야 됩니다. :)

**Comment by NDjust** [comment]
@MinhoLee93 감사합니다!!

**Comment by jojoldu** [comment]
@MinhoLee93 민호님 답변 감사합니다 :)

@NDjust 님 고생하셨습니다!
