### ISSUE TITLE
[오타 제보] p.393

### ISSUE THREAD

**Issue by monkeyDugi** [jojoldu/freelec-springboot2-webservice#238]
switch.sh 파일의
echo "set \$service_url http://127.0.0.1:${IDLE_PORT};" | sudo tee /etc/nginx/conf.d/service-url.inc
부분이  책에서는 반드시 홀따옴표로 하라고 되어 있습니다. 홀 따옴표를 사용하면 변수를 찾아서 에러가 발생합니다. 쌍따옴표를 써야하며, 동욱님 소스에는 쌍따옴표로 되어 있습니다.

**Comment by jojoldu** [comment]
@monkeyDugi 님 안녕하세요!
말씀하신대로 홀따옴표는 오타가 맞습니다 ㅠ
해당 내용은 3쇄에 반영되어 나갈 예정입니다 :)
