### ISSUE TITLE
[오류] p.297 서버 테스트 케이스 오류

### ISSUE THREAD

**Issue by MristerWing** [jojoldu/freelec-springboot2-webservice#239]
### 어떤 오류인가요?

오류설명: 안녕하세요? 책을 보면서 실습을 진행하고 있던도중 검색해도 모르겠는 에러가 발생하여 이슈를 적어봅니다. 현재 aws에 제 git 프로젝트를 clone하여 ./gradlew test를 실행해 보았는데요. 계속해서 springSecurityFilterChain에서 에러가 발생합니다. 처음에 test/resources/applocation.properties가 없거나 잘못 작성된줄 알았는데 제가 확인했을때는 이거 문제는 아니더라구요. 에러는 PostsRepositoryTest 테스트의 테스트 케이스에서만 발생합니다. 해결을 못해서 도움을 요청합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/MristerWing/myProject

### 오류 로그
![image](https://user-images.githubusercontent.com/46372384/74091714-c4f82700-4afd-11ea-8a6e-dfa889358797.png)

![image](https://user-images.githubusercontent.com/46372384/74112754-9ef88280-4be2-11ea-9c88-f9192cefb045.png)

**Comment by MristerWing** [comment]
자체적으로 해결했습니다. 
서버쪽에 src/main/resources/application-oauth.properties생성하니까 해결되었습니다...

**Comment by leaf-hyeon** [comment]
와 감사합니다 덕분에 해결했습니다
