### ISSUE TITLE
p.207 application-oauth.properties 내용 오타인건가용

### ISSUE THREAD

**Issue by gracelove91** [jojoldu/freelec-springboot2-webservice#24]
spring.security.oauth2.client.provider.naver.**authorization_uri**=...........
책에는 이렇게 적혀있는데

자동완성에서는 **authorization-uri** 라고 나타납니다  (언더바 - 대시)
상관없는 건가용~~?
(지금 확인해보니까 그 밑에 있는 코드들도 자동완성에서는 '-' 로 되는데, 책에는 '_'로 되어있네용~)

**Comment by jojoldu** [comment]
@gracelove91 네! 둘다 동일하게 작동됩니다 :)
yml 특성상 언더스코어 , 대시가 동일하게 작동됩니다 :)

**Comment by gracelove91** [comment]
네! 감사합니다!
