### ISSUE TITLE
[오류] p.144 index.js를 추가하고 Application을 실행해보면 스크립트 에러가 발생합니다.

### ISSUE THREAD

**Issue by baekboys** [jojoldu/freelec-springboot2-webservice#243]
### 어떤 오류인가요?

오류설명: 
index.js를 추가하고 Application을 실행해서 크롬으로 localhost:8080접속 시 스크립트 오류가 납니다. 

index.js가 static에서 찾을수가 없는건지... 크롬 개발자모드로 열어보면 아래와 같은 에러가 납니다.

Uncaught SyntaxError: Unexpected token '<'

index.js가 응답에러를 내는지 보려고 개발자모드 네트워크 쪽을 살펴보면... 200으로 정상응답을 주고있고, 응답본문을 보면 index.mustache 의 내용으로 보입니다.. ㅠㅠ

뭐가 문제일까요..?

우선은 index.js에 있는 스크립트를 footer.mustache에 직접 넣어서 사용하고 있습니다.

JAVA : 1.8
IntelliJ IDEA community 2019.03
gradle 5.2.1

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/baekboys/SpringBoot-AWS-Webservice

### 오류 로그
크롬 : 
Uncaught SyntaxError: Unexpected token '<'
![image](https://user-images.githubusercontent.com/44945988/74104465-240a7a00-4b98-11ea-8bda-db3fd4ea915d.png)

IE : SCRIPT1002: 구문 오류
![image](https://user-images.githubusercontent.com/44945988/74104450-03422480-4b98-11ea-8009-4d3fe86e8384.png)

**Comment by skylogin** [comment]
관련하여 저도 동일하게 스크립트 에러가 나고있는데요. 그부분은 동작과 무관하게 mustache와 관련된 부분일거라 생각하고 넘겼습니다. (아시는분은 밑에 알려주세요~)

다만, 그 이후 static 자원을 못가져오는 부분이 있어 아래와 같이 두곳을 추가하였습니다.

IndexController.java의 index GetMapping을 지정하여 아래처럼 수정
```
 @GetMapping("/index")
  public String index() {
    return "index";
  }
```

config패키지를 만들고 WebMvcConfig.java를 새로 생성하여 아래와 같은 소스 적용
```
package com.skylogin.book.springboot.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.servlet.resource.PathResourceResolver;

@Configuration
public class WebMvcConfig implements WebMvcConfigurer {

  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry
        .addResourceHandler("/static/**")
        .addResourceLocations("classpath:/");
  }
}
```

이후 http://localhost:8080/js/app/index.js 들어가보시면 정상적으로 static 자원을 가져오는 걸 볼 수 있습니다.

**Comment by baekboys** [comment]
> 관련하여 저도 동일하게 스크립트 에러가 나고있는데요. 그부분은 동작과 무관하게 mustache와 관련된 부분일거라 생각하고 넘겼습니다. (아시는분은 밑에 알려주세요~)
> 
> 다만, 그 이후 static 자원을 못가져오는 부분이 있어 아래와 같이 두곳을 추가하였습니다.
> 
> IndexController.java의 index GetMapping을 지정하여 아래처럼 수정
> 
> ```
>  @GetMapping("/index")
>   public String index() {
>     return "index";
>   }
> ```
> 
> config패키지를 만들고 WebMvcConfig.java를 새로 생성하여 아래와 같은 소스 적용
> 
> ```
> package com.skylogin.book.springboot.config;
> 
> import org.springframework.context.annotation.Configuration;
> import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
> import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
> import org.springframework.web.servlet.resource.PathResourceResolver;
> 
> @Configuration
> public class WebMvcConfig implements WebMvcConfigurer {
> 
>   @Override
>   public void addResourceHandlers(ResourceHandlerRegistry registry) {
>     registry
>         .addResourceHandler("/static/**")
>         .addResourceLocations("classpath:/");
>   }
> }
> ```
> 
> 이후 http://localhost:8080/js/app/index.js 들어가보시면 정상적으로 static 자원을 가져오는 걸 볼 수 있습니다.

프로젝트의 빌드쪽을 보면 붉은색으로 보이면서 뭔가 제대로 인식하지 못하는거 같았습니다.
![image](https://user-images.githubusercontent.com/44945988/74960997-ae809280-5450-11ea-93a8-093618bd8d3c.png)

프로젝트를 새롭게 만들어서 해보았더니 이번에는 아래처럼 빌드쪽에 붉은색으로 안나오고 브라우져에서 URL 호출 시 리소스를 정상적으로 인식하네요..
빌드하는 과정에서 뭔가 설정이 안맞았거나 프로젝트가 꼬인게 아닌가 생각되네요..ㅠ
![image](https://user-images.githubusercontent.com/44945988/74961171-facbd280-5450-11ea-8316-5a27b3828b3f.png)

**Comment by skylogin** [comment]
말씀듣고 WebMvcConfig없이 단순리빌드해보니 저도 적용되네요.
맥기준 커맨드+f9입니다. (메뉴에서는 Build > Build Project)

**Comment by jojoldu** [comment]
@baekboys 님 안녕하세요 코드를 확인해보니 IndexController에 오타가 있으시네요 :)
**모든 컨트롤러의 메소드에는 주소가 매핑되어있어야만 합니다**
GetMapping에 주소가 매핑되되어 있지 않아서, index.js를 호출하는데도 **메인페이지 주소가 불려서** 그렇습니다.

![image](https://user-images.githubusercontent.com/7760496/75106325-be6dc180-565e-11ea-9bf0-5801e9b65c2e.png)

주소가 매핑되지 않은 컨트롤러 메소드가 있으면 모든 URL 요청이 해당 메소드로 가기 때문입니다 :)

**Comment by jojoldu** [comment]
@skylogin 님 답변 감사합니다 :)
다만, 하신 설정은 **스프링부트에서 자동으로 해주는 설정**입니다.
즉, 해당 코드가 없어도 src/main/resources/static 디렉토리는 자동으로 **정적파일 주소로 매핑됩니다**
제 깃헙에 있는 프로젝트 코드를 보셔도 확인하실수 있습니다 :)
