### ISSUE TITLE
[오류] p.118 브라우저로 API 조회가 안됩니다.

### ISSUE THREAD

**Issue by 2doSilver** [jojoldu/freelec-springboot2-webservice#244]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 118페이지 따라하는 도중 http://localhost:8080/api/v1/posts/1을 입력해 API조회 기능을 테스트해보려고 하는데 진행이 안됩니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/2doSilver/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/25738138/74110972-4326fd00-4bd4-11ea-8a53-2392631eca90.png)

**Comment by MinhoLee93** [comment]
@2doSilver PostsApiController에 오타가 있으시네요 :0

```
@GetMapping("/api/vi1/posts/{id}")
public PostsResponseDto findById(@PathVariable Long id) {
     return postsService.findById(id);
}
```
위에서 /api/vi1/posts/{id} 에 vi1을 v1으로 바꾸시면 될꺼에요 :)

**Comment by 2doSilver** [comment]
@MinhoLee93 설명 감사합니다~ 오타잡는다고 잡았는데 또 있었네요~ 감사합니다! :)
