### ISSUE TITLE
[오류] p.193 '글 등록'시 에러뜹니다.(중복이슈X)

### ISSUE THREAD

**Issue by ChulShin** [jojoldu/freelec-springboot2-webservice#248]
### 어떤 오류인가요?

오류설명: 192페이지에서 [그림 5-17, 5-18, 5-19]의 구글 로그인과 user 테이블 등록 확인은 잘 됩니다. 하지만 '글 등록'을 누르면 [그림 5-20]으로 가지 않고 아래와 같은 에러가 뜹니다.

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Feb 11 21:36:33 KST 2020
There was an unexpected error (type=Not Found, status=404).
No message available

어떻게 해야할까요...?

### 프로젝트 주소

* Github URL: https://github.com/ChulShin/freelec-springboot2-webservice

### 오류 로그
![Inked스크린샷 2020-02-11 21 42 54_LI](https://user-images.githubusercontent.com/45473374/74238230-b76ab900-4d18-11ea-8c71-fd93c32efb72.jpg)

**Comment by MinhoLee93** [comment]
@ChulShin 194p에 h2-console에서 사용자의 role을 변경하는 부분이 있는데, 해당부분 진행하신건가요??

**Comment by ChulShin** [comment]
> @ChulShin 194p에 h2-console에서 사용자의 role을 변경하는 부분이 있는데, 해당부분 진행하신건가요??

네. 해당 role 변경부분을 수행해도 여전히 상기한 Whitelabel Error Page가 뜹니다.

**Comment by MinhoLee93** [comment]
@ChulShin 소스확인해보니 IndexController에 아래부분 작성을 빼놓으셨어요! 
글 등록 <a> 태그 보시면 href="/posts/save"로 가도록 지정하고 있는데 
Controller에 "/posts/save"를 받는 곳이 없어서 에러가 발생한것 같아요 :)

```
@GetMapping("/posts/save")
    public String postsSave() {
        return "posts-save";
 }
```

**Comment by ChulShin** [comment]
> @ChulShin 소스확인해보니 IndexController에 아래부분 작성을 빼놓으셨어요!
> 글 등록 태그 보시면 href="/posts/save"로 가도록 지정하고 있는데
> Controller에 "/posts/save"를 받는 곳이 없어서 에러가 발생한것 같아요 :)
> 
> ```
> @GetMapping("/posts/save")
>     public String postsSave() {
>         return "posts-save";
>  }
> ```

앗 그렇군요. 말씀하신 부분 추가했더니 책처럼 잘 되네요. 제가 실수로 지웠던거같아요. 알려주셔서 감사합니다.
