### ISSUE TITLE
[질문] p.195 ~ 198 @LoginUser 커스텀 어노테이션 정의가 필수 인가요?

### ISSUE THREAD

**Issue by hwang11** [jojoldu/freelec-springboot2-webservice#252]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:
안녕하세요 공부하다가 궁금한 점이 생겨 질문드립니다. 
5.4 어노테이션 기반으로 개선하기를 공부하다가 @LoginUser 어노테이션이 필수인가 하는 생각이 들어서요  

class LoginUserArgumentResolver의 
supportsParameter가 resolver가 해당 파라미터를 지원하는지 판단하는 역할이라고 알고있습니다.
이 메소드에서 SessionUser.class.equals(parameter.getParameterType()); 만으로 resolver가 SessoinUser를 지원한다는 점을 확인할 수 있고, SessionUser 타입의 매개변수를 컨트롤러에서 사용한다면 @LoginUser없이도 메소드 인자로 세션값을 바로 받을 수 있지 않을까하는 생각이들었습니다. 

HandlerMethodArgumentResolver를 검색해보다가 
https://jhkang-tech.tistory.com/49 이 글을 참고했는데 해당 글에서는 커스텀 어노테이션 없이도 값이 바인딩되는 것 같아 질문 드립니다. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by jojoldu** [comment]
@hwang11 님 안녕하세요 :)
물론 어노테이션 없이 사용해도 됩니다만, 보통 그렇게 사용하진 않습니다 :)
위 블로그에서는 어노테이션 존재유무 판단 없이 특정 클래스가 메소드에서 선언되어있으면 다 리졸버의 대상으로 보도록 구성하였는데, 책에서는 무조건 어노테이션 체크를 하도록 되어있습니다.
이는 의도한것이기 때문인데요.

어노테이션 체크 없이 해당 클래스가 선언만 되어있으면 무조건 값이 바인딩 되도록 되어있으면 **메소드간 호출에서도 매번 세션 사용자값이 사용됩니다**

즉, 

```
Controller {
   public void a (LoginUser loginUser) {
       loginUser.updateLoginTime();
       service.save(loginUser);
   }
}

Service {
       save (LoginUser loginUser) {
          ~~~
      }
}
```

에서 Service는 **컨트롤러가 변경된 값을 강제로 넣어줘도 받질 못합니다**
리졸버에서 LoginUser 만 있으면 무조건 **현재 세션에 있는 값**을 반환하기 때문입니다.
개발자 입장에선 컨트롤러 접근할때마다 로그인 시간을 갱신하는 코드를 작성했는데, 서비스가 받질 못하는 케이스가 생기는 것이죠.

**상황에 따라 세션에 있는 값을 사용하기도, 혹은 호출하는 메소드에서 넣어준 값을 사용하기도** 해야하는데,
위 블로그 방식은 선택지가 아예 사라지게 됩니다 :)
그래서 책에서는 무조건 어노테이션 방법을 추천하고 있습니다 :)

**Comment by hwang11** [comment]
친절한 설명과 예시 감사합니다. 명확하게 이해되었습니다. 감사드려요 그리고 책도 정말 많은 도움이 되고있습니다!
