### ISSUE TITLE
[오류] p.291 ec2에서 rds에서 접근 확인

### ISSUE THREAD

**Issue by akima9** [jojoldu/freelec-springboot2-webservice#255]
오류설명: 
ec2에서 rds에 접속이 안됩니다
마스터계정 확인 했고, 비밀번호도 재설정해서 계정문제는 아닌것 같은데
어떤것 때문에 접속이 안되는지 모르겠습니다ㅠ

### 오류 로그

![image](https://user-images.githubusercontent.com/39448528/74411797-6de8ae00-4e7f-11ea-88e9-6d59a269e667.png)

**Comment by hoonpig** [comment]
보안그룹 확인해보셨나요..??

**Comment by akima9** [comment]
@hoonpig 
1. ec2의 보안그룹 아이디를 복사해서
![image](https://user-images.githubusercontent.com/39448528/74416573-b0fb4f00-4e88-11ea-9b21-fd5096eb0f4b.png)

2. rds의 보안그룹 인바운드에 추가하였습니다
![test](https://user-images.githubusercontent.com/39448528/74417091-8067e500-4e89-11ea-869b-2ccca36d1e79.png)

3. 책이랑 다른 이슈들 보고 해보려고 했는데 어떤 이유인지를 잘 모르겠네요;;

**Comment by MinhoLee93** [comment]
@akima9 음.. 혹시 public access open 되어있을까요??

rds 생성하실때 깜빡 하셨을 수도..

![image](https://user-images.githubusercontent.com/50879621/74435711-73a6b980-4ea8-11ea-9b63-4bb6d24292fc.png)

**Comment by KMSKang** [comment]
aws 서버 접속한 상태에서 접속시도해서 그렇습니다
서버 접속하지마시고
터미널 틀으시고 접속하세요

**Comment by Suhun0331** [comment]
혹시 해결 하셨을까요 ? 저도 이 부분에서 막혀서 진도를 못나가고 있습니다.
저는 2003이 아니라 2005 에러가 뜨네요
