### ISSUE TITLE
[오류] p.118 No Converter Found For ~~~Dto

### ISSUE THREAD

**Issue by gus-an** [jojoldu/freelec-springboot2-webservice#256]
![image](https://user-images.githubusercontent.com/53885543/74446529-5f1fec80-4ebb-11ea-8f60-ba8edc59b611.png)

1번 자료가 추가되어있는 상태에서 JSON 형식 반환을 확인하고싶은데,
저렇게 No Converter Found ~~~ 메세지가 뜹니다.

https://github.com/gus-an/first-project

**Comment by MinhoLee93** [comment]
@gus-an 깃헙 링크를 올려주셔야되요! :)

**Comment by gus-an** [comment]
> 셔야
 추가했습니다!

**Comment by gus-an** [comment]
추가했습니다!

**Comment by MinhoLee93** [comment]
@gus-an 
PostsResponseDto class에 @Getter 어노테이션을 빠트리셨네요!
@Getter 작성후 정상작동 확인했습니다 :)

**Comment by gus-an** [comment]
@MinhoLee93 
감사합니다!
