### ISSUE TITLE
[오류] p.150 IndexController에서 NullPointerException이 뜹니다...

### ISSUE THREAD

**Issue by 97e57e** [jojoldu/freelec-springboot2-webservice#258]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 150p까지 실습을 진행 하고 있습니다. 
Post  insert 하고 index 페이지에서 PostList를 불러 오려는데 IndexController에서 NullPointerException이 뜹니다... h2-console에서 아이템 잘 들어가 있는거 확인했는데 왜 그런지 이유를 못찾겠습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/97e57e/spring-boot-webservice

### 오류 로그
![image](https://user-images.githubusercontent.com/41745717/74583707-3f004280-500d-11ea-8564-6c996cbd5f55.png)

어떤 오류인지 캡쳐해주세요.

**Comment by MinhoLee93** [comment]
@97e57e 

IndexController 상단에 @RequiredArgsConstructor 선언을 빼놓으셨어요!
데이터가 문제가 아니라, PostService가 null 이라서 NullPointerException 가 발생하신거에요.

또한 @RequiredArgsConstructor를 사용해 생성자 주입으로 의존성을 주입 받기 위해선
private final로 변수를 선언해야 합니다.

기존 : private PostsService postService
변경 : private final PostsService postService + @RequiredArgsConstructor 선언

위와 같이 변경후 정상작동 확인했습니다 :)

**Comment by 97e57e** [comment]
@MinhoLee93 아 .. 감사합니다.. 몇번 확인한다고 했는데도 빼먹은 부분이 있었네요 ㅠ :(
