### ISSUE TITLE
p.174 설명과 그림이 다름

### ISSUE THREAD

**Issue by hello-sangsik** [jojoldu/freelec-springboot2-webservice#26]
**그림 5-14** application-oauth.properties
=> 실제 그림은 application-google.properties로 되어있습니다.

**Comment by jojoldu** [comment]
@hello-sangsik 앗 감사합니다
초기 버전에서는 구글 로그인만 예제로 삼았다가 추가로 네이버 로그인이 생기다보니 파일에 오타가 생겼네요 ㅠ
확인 감사합니다!

**Comment by jojoldu** [comment]
그림이 틀렸으며
본문 내용과 마찬가지로
application-oauth.properties 이 맞습니다!

**Comment by hello-sangsik** [comment]
@jojoldu 엄청나게 빠른피드백! 사소한건데 감사합니다 ㅎㅎ

**Comment by jojoldu** [comment]
앗 아닙니다 ㅋㅋ 보시는데 오해가 생기기 시작하면 실습에 어려움이 있으시니 ㅠ 바로 이슈 올려주시면 됩니다.
지금 주말이라 작업실이다보니 피드백을 빨리 드릴수가 있네요 :)
