### ISSUE TITLE
[오류] 인텔리제이 커뮤니티에서 코드 실시간 반영이 안됩니다 ㅠ (live reload)

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#260]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 

**예전에 webapp으로 쓸때는 Run한 상태에서 코드 수정 후 크롬브라우저에서 새로고침 누르면 바로바로 수정된 코드로 갱신되었는데 현재 인텔리제이 커뮤니티에서는 안되네요**

**블로그에 나온 방법대로 devtools 의존성 추가, application.properties 설정, build project automatically, registry 설정 다 해줬는데도.. 실시간 반영이 안됩니다**

**현재 인텔리제이 버전입니다.**

![image](https://user-images.githubusercontent.com/48509269/74601059-e1d3c200-50dc-11ea-8033-4b6a474a4c1a.png)

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by skyer9** [comment]
[https://www.jetbrains.com/help/idea/updating-applications-on-application-servers.html](https://www.jetbrains.com/help/idea/updating-applications-on-application-servers.html)

유료 버전이 아니라 그럴 것 같습니다.

**Comment by skyer9** [comment]
헐. 썸네일 이미지를 저하고 같은걸 사용하시는군요.

**Comment by skyer9** [comment]
[https://aterilio.tistory.com/74](https://aterilio.tistory.com/74)

혹시나 하고 찾아보니, 공식적인 지원은 아니지만 실시간 컴파일 기능이 있네요.

실제로 테스트해보니 정상 작동했습니다.

혹시나 해서 말씀 드리는데.... 저장을 했을때 작동했습니다. 물론 컴파일시간도 필요하고요.

**Comment by kalkin2** [comment]
> https://aterilio.tistory.com/74
> 
> 혹시나 하고 찾아보니, 공식적인 지원은 아니지만 실시간 컴파일 기능이 있네요.
> 
> 실제로 테스트해보니 정상 작동했습니다.
> 
> 혹시나 해서 말씀 드리는데.... 저장을 했을때 작동했습니다. 물론 컴파일시간도 필요하고요.

음..저도 커뮤니티 버전 쓰는데 위 설정 적용해도 실시간 반영이 안되네요...ㅠㅠ

**Comment by skyer9** [comment]
> > https://aterilio.tistory.com/74
> > 혹시나 하고 찾아보니, 공식적인 지원은 아니지만 실시간 컴파일 기능이 있네요.
> > 실제로 테스트해보니 정상 작동했습니다.
> > 혹시나 해서 말씀 드리는데.... 저장을 했을때 작동했습니다. 물론 컴파일시간도 필요하고요.
> 
> 음..저도 커뮤니티 버전 쓰는데 위 설정 적용해도 실시간 반영이 안되네요...ㅠㅠ

참고로... 저는 실시간 컴파일 기능 사용하지 않습니다.
10번에 1-2번 빈도로 비정상적으로 컴파일(아마도 일부 클래스 컴파일 누락인듯)이 발생해서...
그냥 톰캣 재실행하도록 하고 있습니다.

**Comment by jojoldu** [comment]
@skyer9 @zhtmr 인텔리제이커뮤니티라도 서버템플릿엔진 (머스테치)를 쓴다면 가능한것으로 알고 있는데요!
요거는 관련해서 정리한번 해놓겠습니다!
