### ISSUE TITLE
[오타 제보] p.190

### ISSUE THREAD

**Issue by gus-an** [jojoldu/freelec-springboot2-webservice#262]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):

SessionUser user = (User) httpSession.getAttribute("user");

* to-be (교정):

SessionUser user = (SessionUser) httpSession.getAttribute("user");

**Comment by jojoldu** [comment]
@gus-an 님 안녕하세요 :) 오타 제보 정말 감사합니다 ㅠ
해당 이슈가 이미 올라와있어서 중복 제보로 남겨놓겠습니다 :)
불편을 드려 정말 죄송합니다 ㅠ
