### ISSUE TITLE
[오류] p.116

### ISSUE THREAD

**Issue by cjsxorud111** [jojoldu/freelec-springboot2-webservice#265]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 안녕하세요 application.properties 에 옵션을 추가했으나 /h2-console로 접속시 페이지 에러입니다. 기존에 올라온 질문이지만 그 질문의 해결방법으로 해결되지 않아 질문드립니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/cjsxorud111/calculator

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/32443642/74632311-689ea280-51a2-11ea-95bd-16dae8614ab4.png)

**Comment by jikimee64** [comment]
어떻게 해결하셨나요??
