### ISSUE TITLE
[오류] 오류라기 보다는 질문 입니다

### ISSUE THREAD

**Issue by kimbushik** [jojoldu/freelec-springboot2-webservice#267]
스프링부트와 aws로 혼자 구현하는 웹 서비스라는
책을 사서 공부해보소 있는데요

게시판 예제를 따라하던 중에 파일업로드나
파일다운로드에 관한 내용이 없던데요
혹시 파일업로드나 다운로드에 대한 예제가 있을까요?

**Comment by MinhoLee93** [comment]
@kimbushik 

aws s3를 활용한 이미지 업로드 내용은 
저자님의 블로그에 자세히 설명되어있습니다! :)

https://jojoldu.tistory.com/300

**Comment by jojoldu** [comment]
@MinhoLee93 님 답변 감사합니다 :)
