### ISSUE TITLE
[오류] p.285에서 Test Connection이 실패합니다

### ISSUE THREAD

**Issue by ChulShin** [jojoldu/freelec-springboot2-webservice#268]
### 어떤 오류인가요?

오류설명: p.285에서 설명하는 Test Connection이 계속 실패합니다
EC2의 보안그룹의 그룹ID를 복사해서 RDS 보안그룹의 인바운드로 추가했는데 왜이럴까요?
혹시 제가 EC2의 보안그룹의 그룹ID 부분을 잘못 찾았을까 싶어서 관련사항을 구글로 검색해서 제가 생각한 그룹ID가 EC2의 보안그룹의 그룹ID가 맞는지 다시 확인해봤습니다.
그리고 p.283에서 엔드포인트도 정확히 입력했는지 다시 확인했는데도 안되네요.
마스터암호와 마스터사용자이름도 이전에 저장했던것을 그대로 입력했는데도 실패합니다.
어떡하죠?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
* Github URL: https://github.com/ChulShin/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
<img width="960" alt="스크린샷 2020-02-17 22 38 43" src="https://user-images.githubusercontent.com/45473374/74659152-217ed480-51d7-11ea-9e8e-bd88ff38f251.png">

**Comment by MinhoLee93** [comment]
@ChulShin 

캡처해주신 이미지 내용은 로컬에서 RDS 연결에 실패하신거라..
EC2의 보안그룹을 RDS에 추가하는것과는 관련이 없습니다. 

혹시 RDS의 보안그룹에 본인 local IP를 추가하셨나요?? 
EC2의 보안그룹만 추가하셨다면, 아래와 같이 My IP도 추가해주셔야 
로컬에서 IntellJ를 통해서 RDS에 접속할 수 있습니다. :)

![image](https://user-images.githubusercontent.com/50879621/74663523-4414eb80-51df-11ea-8377-bbea0c765808.png)

매번 네트워크(집->카페) 옮기실때마다 귀찮으시더라도
My IP를 추가하셔야 로컬(인텔리제이)에서 접속할 수 있습니다.

**Comment by ChulShin** [comment]
> @ChulShin
> 
> 캡처해주신 이미지 내용은 로컬에서 RDS 연결에 실패하신거라..
> EC2의 보안그룹을 RDS에 추가하는것과는 관련이 없습니다.
> 
> 혹시 RDS의 보안그룹에 본인 local IP를 추가하셨나요??
> EC2의 보안그룹만 추가하셨다면, 아래와 같이 My IP도 추가해주셔야
> 로컬에서 IntellJ를 통해서 RDS에 접속할 수 있습니다. :)
> 
> ![image](https://user-images.githubusercontent.com/50879621/74663523-4414eb80-51df-11ea-8377-bbea0c765808.png)
> 
> 매번 네트워크(집->카페) 옮기실때마다 귀찮으시더라도
> My IP를 추가하셔야 로컬(인텔리제이)에서 접속할 수 있습니다.

감사합니다. IP를 넣지 않아서 연결이 되지않았던 것이 맞습니다. 지금은 잘 됩니다.
