### ISSUE TITLE
p.208 오타

### ISSUE THREAD

**Issue by hello-sangsik** [jojoldu/freelec-springboot2-webservice#27]
```java
private static OAuthAttributes ofNaver(...){
...
     .picture((String) response.get("profileImage")) 
...
```
```java
    .picture((String) response.get("profile_image")) 
```
로 수정되어야 할 것 같습니다.

**Comment by jojoldu** [comment]
@hello-sangsik 앗 바꾸지 않으면 안되시나요?
현재 실행했을때는 둘다 작동이 되어서요!

![image](https://user-images.githubusercontent.com/7760496/70389188-6b8d5200-19ff-11ea-96c9-2f053f012c11.png)

**Comment by hello-sangsik** [comment]
@jojoldu 작동은 가능한테 해당 값의 키가 profile_image라서 이미지경로를 가져오지 못합니다. (책에서 사용하진 않으니 크게 상관없을까요?

**Comment by jojoldu** [comment]
@hello-sangsik 앗!! 아닙니다 ㅋㅋ 사용하진 않지만 그래도 선언된 필드라서 필드명을 바꾸는게 맞는것 같습니다!
profile_image로 수정하겠습니다!
제보 감사합니다 :)
