### ISSUE TITLE
[오류] p.156 : 게시글 "수정"기능 관련

### ISSUE THREAD

**Issue by chp320** [jojoldu/freelec-springboot2-webservice#270]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:
- 게시글 전체 목록에서 '글 제목' 클릭 > 수정 후 '수정 완료' 버튼 클릭 시 반응 없음
- '수정 완료' 버튼 클릭 시 팝업창 뜨지 않아 index.js 의 update 펑션 잘못 작성하였나 싶어서 올려주신 소스코드 복붙하여 수행해봐도 이벤트 발생하지 않습니다..

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/chp320/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/47440517/74756675-45661700-52b8-11ea-817e-8dba3b323b52.png)

**Comment by MinhoLee93** [comment]
@chp320 

혹시 해결되신건가요??
현재 @chp320님 Github에 올라와있는 소스로는 잘 작동하네요 :)

![image](https://user-images.githubusercontent.com/50879621/74786736-cc36e600-52f0-11ea-9d5d-fcee2996010c.png)

**Comment by slowCoyle** [comment]
웹 콘솔창에 보시면 
![image](https://user-images.githubusercontent.com/34959979/80207359-f4342400-8668-11ea-8cb4-7fa69ad05ae4.png)
위와 같이 Source 탭의 index.js 파일을 확인해보세요! js 파일의 변경사항이 적용되지 않을 수도 있습니다.
웹은 스크립트 파일의 내부 수정 시 캐시에 저장하고 사용 시에 불러오게 되는데 캐시에 있는 파일이 갱신이 안될 때도 있더라구요.

footer.mustache 파일에서 `<script src="/js/app/index.js?ver=1"></script>`로 변경해주면 됩니다.

**Comment by jojoldu** [comment]
@slowCoyle @MinhoLee93 님 답변 감사합니다 :)

**Comment by syleemk** [comment]
저도 똑같은 오류네요 뭐가 문제인지

**Comment by Kwon770** [comment]
제 경우에는 똑같은 오류였는데, @slowCoyle 님의 답변이 정확하네요. index.js의 캐시로 인해 업데이트가 안되었나보네요.

**Comment by jmd5314** [comment]
개발자 도구창에서 네트워크 탭의 캐쉬 사용중지를 체크한뒤 새로고침 하여 해결하는 방법도 있습니다.

**Comment by chp320** [comment]
늦었지만 상기 오류 확인되어 close 합니다^^;;
좋은 지식 공유 주셔서 감사합니다!
