### ISSUE TITLE
[오류] indexController 폴더 변경후 bean중복 오류

### ISSUE THREAD

**Issue by cjsxorud111** [jojoldu/freelec-springboot2-webservice#271]
### 어떤 오류인가요?

오류설명: 
안녕하세요
indexController 클래스위치를 src.main.java.com.cocicalc.web.dto 로 잘못되어 있어서 src.main.java.com.cocicalc.web 로 옮겼는데 이후로 Application.java를 구동하면 
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.socicalc.Application]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'indexController' for bean class [com.socicalc.web.dto.IndexController] conflicts with existing, non-compatible bean definition of same name and class [com.socicalc.web.IndexController]
라는 오류가 납니다. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/cjsxorud111/calculator

### 오류 로그

![image](https://user-images.githubusercontent.com/32443642/74791705-9993ea00-52fe-11ea-9716-d9eb17e61c21.png)

![image](https://user-images.githubusercontent.com/32443642/74791736-ae707d80-52fe-11ea-8d18-20a675c186c1.png)

어떤 오류인지 캡쳐해주세요.

**Comment by MinhoLee93** [comment]
@cjsxorud111 

저도 비슷한 경우가 종종 발생하는데

폴더중에 out 이라는 폴더 지우고

![image](https://user-images.githubusercontent.com/50879621/74792287-59356b80-5300-11ea-8f9a-6693fa6e805c.png)

gradle에서 clean -> build 순서대로 진행한뒤에 

![image](https://user-images.githubusercontent.com/50879621/74792337-7d914800-5300-11ea-8f81-cd07c44545b9.png)

어플리케이션 실행하면 해결이 되더라구요 :) 
한번 해보시겠어요??

**Comment by cjsxorud111** [comment]
@MinhiLee93
답변 감사드립니다😁
프로젝트에 out폴더가 없어서 clean, build만 하고 재실행 했더니 정상작동합니다.

**Comment by jojoldu** [comment]
@MinhoLee93 님 답변 감사합니다 :)

**Comment by planetdoy** [comment]
@MinhoLee93 오! 감사합니다.!

**Comment by developerkjm** [comment]
와 정말 감사합니다!!!
