### ISSUE TITLE
[오류] 77.p 테스트 결과 질문입니다.

### ISSUE THREAD

**Issue by mewoojal** [jojoldu/freelec-springboot2-webservice#273]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 
dto API 테스트를 해보면 패스했다고는 나오는데요 책하고 내용이 약간달라서 질문 올립니다.
책에서는 결과가
HelloControllerTest라고 나오고 Test passed 내용을 보면 [main] DEBUG 이렇게 나오는데
제꺼는 
Test Results라고 나오고  Test passed 내용을 보면 [Test worker] DEBUG 이런식으로 나옵니다 상관없는건가요 ? 제생각엔 버전 다운시킨 다음부터 이렇게 나오는것 같습니다.
아래에 캡쳐사진 올려봅니다 .. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![test](https://user-images.githubusercontent.com/55725809/74798808-298f5f00-5312-11ea-8dc5-833468043401.PNG)

**Comment by jojoldu** [comment]
@mewoojal 넵 스프링부트 버전 혹은 인텔리제이의 구동 방식 (인텔리제이 모드로 실행하느냐 / 그레이들 모드로 실행하느냐) 에 따라 차이가 발생할 수 있습니다.

https://jojoldu.tistory.com/450 에서 소개하고있는것처럼 인텔리제이가 실행 방법을 2가지로 나눠서 저와 화면이 다를 수 있습니다 ^^
