### ISSUE TITLE
[오류] p.276, p.289 Character Set과 Collation 항목 변경 오류

### ISSUE THREAD

**Issue by ChulShin** [jojoldu/freelec-springboot2-webservice#274]
### 어떤 오류인가요?

오류설명: p.276과 p.289의 그림 7-37에 지시된 대로 RDS에서 character set과 collation 항목을 수정했는데요. p.289까지 진행한 시점에서
show variables like '%c';
로 확인해보니 저는 여러 항목들 중에서 두개만 utf8mb4와 utf8mb4_general_ci로 바뀌어있고 다른건 바뀌어있지 않네요.
분명 p.276에서 책대로 변경하고 그 파라미터 그룹을 데이터베이스에 연결했는데도 이러네요. 왜 이럴까요?
혹시나해서 다시 RDS로 들어가서 문제의 파라미터의 항목을 다시 변경하고 수정사항 반영하고 데이터베이스와 다시 연결하고 했지만 여전히 SQL으로 조회해보니 변경이 안되어 있습니다.
character set database, collation database를 제외한 다른 항목을 SQL문을 이용해서 변경하려면 어떻게 해야하는지 알려주세요. 그렇지 않다면 RDS에서 파라미터로 변경한 것들이 반영이 되지 않는 이유는 무엇일까요?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/ChulShin/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
<img width="955" alt="스크린샷 2020-02-19 23 19 27" src="https://user-images.githubusercontent.com/45473374/74843897-ef54aa80-536f-11ea-8350-db3def46093c.png">

**Comment by MinhoLee93** [comment]
@ChulShin 

음.. 혹시 RDS 파라미터 그룹 변경후 reboot 해보셨나요?? :)
저도 반영 안될때 있었는데 reboot하니깐 해결이 되더라구요.
혹시 몰라 제 rds 상태 스샷 남겨드립니다. 😅

# 파라미터 그룹 
![image](https://user-images.githubusercontent.com/50879621/74890951-e2b07080-53c8-11ea-97d5-f458f6b8f3a4.png)

# rds에 적용된 파라미터 그룹
![image](https://user-images.githubusercontent.com/50879621/74891058-3458fb00-53c9-11ea-8d7c-9a06a2ea877a.png)

**Comment by ChulShin** [comment]
말씀하신대로 파라미터 변경 후에 '재부팅' 해보니 잘 되네요.
조언 감사드립니다.
