### ISSUE TITLE
[오류] p.287

### ISSUE THREAD

**Issue by Livenow14** [jojoldu/freelec-springboot2-webservice#275]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 내 PC에서 RDS접속하기 하는 중에
InteliJ로 DB Connection 맺은 후 Schemas에 기본으로 생성된 것 외에 추가로 생성이 안되요. 
해결 방안좀 알려주세요.
RDS에서 데이터 베이스 파라메타 그룹 설정 등 책에서 한대로 다 했어요. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/48986787/74909982-c8908580-53fc-11ea-8223-4d652d5c3fb5.png)

**Comment by MinhoLee93** [comment]
@Livenow14 

음.. 제가보기에는 RDS 생성시에 database 이름을 작성을 안하셔서
db 스키마 자체가 생성이 안된 것 같아요.

RDS 생성하실때 보면 아래 사진처럼 접혀진 부분이 있는데요. 
 
![image](https://user-images.githubusercontent.com/50879621/75039121-52267d00-54fb-11ea-9d44-7cf3dac679a5.png)

위부분을 클릭해서 아래 빈 부분에다가 사용하실 DB 이름을 입력해주셔야되요
책 272p 그림 7-7에 설명되어 있어요!

![image](https://user-images.githubusercontent.com/50879621/75039236-96b21880-54fb-11ea-9768-31ebfd829aaa.png)

**Comment by syleemk** [comment]
저도 똑같은 오류네요 
미쳐버리겟음

**Comment by syleemk** [comment]
> @Livenow14
> 
> 음.. 제가보기에는 RDS 생성시에 database 이름을 작성을 안하셔서
> db 스키마 자체가 생성이 안된 것 같아요.
> 
> RDS 생성하실때 보면 아래 사진처럼 접혀진 부분이 있는데요.
> 
> ![image](https://user-images.githubusercontent.com/50879621/75039121-52267d00-54fb-11ea-9d44-7cf3dac679a5.png)
> 
> 위부분을 클릭해서 아래 빈 부분에다가 사용하실 DB 이름을 입력해주셔야되요
> 책 272p 그림 7-7에 설명되어 있어요!
> 
> ![image](https://user-images.githubusercontent.com/50879621/75039236-96b21880-54fb-11ea-9768-31ebfd829aaa.png)

오오오오오ㅗ오 생성시에만 저게 보이는군요 ㅜㅜㅜ
수정에서 삽질하다가 해결했네요 
감사합니다 ㅜㅜ

**Comment by Livenow14** [comment]
확인했습니다. 감사합니다.
