### ISSUE TITLE
[오류] p.291 putty로 EC2에 ssh 접속 오류

### ISSUE THREAD

**Issue by ChulShin** [jojoldu/freelec-springboot2-webservice#277]
### 어떤 오류인가요?

오류설명: 책 291페이지에서 EC2에 ssh접속 하라고 되어있는 부분이 있어서 6장으로 다시 돌아가서 6장에 나와있는대로 windows 운영체제에서 putty로 다시 접속하려고 하는데요. 이전에는 잘 되던 것이 지금은 아래 스크린샷과 같이 timed out이라고 뜨면서 잘 안되고 있네요. 왜 이럴까요? 

참고로 보안그룹의 인바운드에서 내 IP는 다시 등록했습니다.

### 프로젝트 주소

* Github URL: https://github.com/ChulShin/freelec-springboot2-webservice

### 오류 로그
<img width="512" alt="스크린샷 2020-02-22 22 16 03" src="https://user-images.githubusercontent.com/45473374/75093137-8b75f000-55c2-11ea-91ec-42d62a4b0ae3.png">
<img width="349" alt="스크린샷 2020-02-22 22 16 32" src="https://user-images.githubusercontent.com/45473374/75093141-90d33a80-55c2-11ea-9a94-4175ee963055.png">

**Comment by skyer9** [comment]
느낌상 EC2 인스턴스 아이피가 바뀌었을 것 같은데요.
확인해 보심이. ㅋㅋ

**Comment by ChulShin** [comment]
> 느낌상 EC2 인스턴스 아이피가 바뀌었을 것 같은데요.
> 확인해 보심이. ㅋㅋ

바뀌었다는게 만약 탄력적IP를 말씀하시는거라면, 저는 그 IP를 다시 조회해서 putty에 기입해서 접속했는데 여전히 저렇게 나옵니다.

**Comment by skyer9** [comment]
https://cupjoo.tistory.com/51

탄력적IP 로 서버 아이피 고정했고...
내 PC 아이피도 바뀌지 않았다면...

EC2 서버 상태가 정상인지가 의심스럽네요.
서버에 특별히 설치한것 없으시면 삭제후 재생성하심이...

**Comment by MinhoLee93** [comment]
@ChulShin 

음.. 제생각에는 번거로우시더라도 다시한번 EC2 보안그룹의 
IP를 확인해보시는게 좋을것 같아요.
저 에러는 그부분으로 밖에 설명이 안되서..

저는 매일매일 IP 새로 등록하면서 진행하고 있어요 :)
자주 옮겨 다녀서..
![image](https://user-images.githubusercontent.com/50879621/75102163-9bc1b580-562a-11ea-9ef0-866828162e05.png)

**Comment by mspark109** [comment]
저도 접속이 안되는데 혹시 집에서 무선(wifi)인터넷 연결로 사용하는게 영향이 있을까요 ??
