### ISSUE TITLE
[오타 제보] p.몇페이지

### ISSUE THREAD

**Issue by skyer9** [jojoldu/freelec-springboot2-webservice#278]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):
[P.147] @Query(value = "SELECT p FROM posts p ORDER BY p.id DESC")

* to-be (교정):
[P.147] @Query(value = "SELECT p.* FROM posts p ORDER BY p.id DESC", nativeQuery = true)

p.* 는 오타인 듯 하고요.
nativeQuery 는 왜 필요한지 모르겠네요.
개발환경은 JDK11, gradle-5.6.4 로 약간 다릅니다.

**Comment by jojoldu** [comment]
@skyer9 앗 아닙니다 ㅠ 작성해주신 to be는 실제 sql 쿼리를 표현할때 쓰는데, 지금 책에서 얘기하는 쿼리는 **JPQL**입니다.
JPQL에서는 **테이블이 아닌 엔티티 기반으로 합니다.**
그래서 엔티티 클래스인 **Posts** 로 선언하고 ```select p```는 네이티브 쿼리 기준으로 ```select p.*```가 됩니다.
그래서 이건 오타가 아니라 맞는 코드라서 반영하지 않겠습니다.

**Comment by skyer9** [comment]
`@Query(value = "SELECT p FROM Posts p ORDER BY p.id DESC")`

단순 SQL 이 아니었군요.
`Posts` 를 대소문자 상관없겠지 하면서 `posts` 로 했는데...
오히려 에러 원인이 이쪽이었군요 ;;;;
