### ISSUE TITLE
[오류] p.188 - 구글 로그인 연동하기 오류

### ISSUE THREAD

**Issue by chp320** [jojoldu/freelec-springboot2-webservice#281]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:
1) CustomOAuth2UserService 내 loadUser() 메소드에서 user.getRoleKey() 인식 불가
    - 실제 User클래스에서 getRoleKey() 메소드 내 hint메세지를 보면 해당 메소드를 "safe delete" 한다는 메세지가 나타납니다.
2) CustomOAuth2UserService 클래스와 User 클래스를 작성 시 오타가 있나 여러번 찾아보았지만 오타는 없는 것 같은데.. 왜 오류가 나타나는지... 원인을 못찾겠습니다.. T-T

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/chp320/freelec-springboot2-webservice

### 오류 로그
![200224_err1](https://user-images.githubusercontent.com/47440517/75115087-fc8ad580-569e-11ea-95df-c78732df71b5.JPG)

어떤 오류인지 캡쳐해주세요.

**Comment by hyun-jii** [comment]
혹시 User 클래스 private Role role 이 부분에서 Role import가 어떻게 되어있는지 확인해보세용
저도 비슷한 문제가 있었는데 Role 경로가 javax.~~로 잘못 되어있더라구요..!!

**Comment by Wooojiin** [comment]
> @chp320
> 혹시 User 클래스 private Role role 이 부분에서 Role import가 어떻게 되어있는지 확인해보세용
> 저도 비슷한 문제가 있었는데 Role 경로가 javax.~~로 잘못 되어있더라구요..!!

확인해봤는데 Role 잘 들어가있네요혹시 User 클래스 private Role role 이 부분에서 Role import가 어떻게 되어있는지 확인해보세용
> 저도 비슷한 문제가 있었는데 Role 경로가 javax.~~로 잘못 되어있더라구요..!!

확인해봤는데 Role 잘 들어가있네요ㅠㅠ 조언 감사합니다

**Comment by chp320** [comment]
단순 오타였네요... ㅠㅠ
getRoleKey() 로 작성했어야 했는데... getRolekey()로 작성되어 있었네요...;;
