### ISSUE TITLE
[오류] p.113 findById 메소드에서 람다식 부분을 생성자 참조 방식으로 바꿀수도 있나요??

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#283]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 
![image](https://user-images.githubusercontent.com/48509269/75150469-c6edf700-5747-11ea-84d5-7fdf4a0b2bd9.png)

책 페이지 149에서 좀 다르게 람다식이 쓰이는걸 보고 113페이지에서 만들었던 findById 메소드에 있는 람다식도 149페이지 처럼 바꿀수 있는지 궁금합니다.. 
첨부 사진처럼 IllegalArgumentException::new 까지하니까 컴파일 오류는 안뜨는데 메시지 설정을 어떻게 해야되는지 모르겠습니다

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by jojoldu** [comment]
@zhtmr 님 안녕하세요 
2번째 케이스를 보고 **메소드 참조** 라고 합니다.
메소드 참조는 다음과 같은 경우에만 됩니다.

1. 인스턴스::인스턴스메소드 : 인스턴스 메소드에 인자를 넣어 호출한다.

```
number -> System.out.println(number) = System.out::println
```

2. 클래스::정적메소드 : 정적메소드에 인자를 넣어 호출한다.

```
number -> Math.sqrt(number) = Math::sqrt
```

3. 클래스::인스턴스메소드 : 첫번째 인자는 인스턴스가 되고, 두번째 인자부터는 인스턴스 메소드의 인자로 넣어 호출한다.

```
(a, b) -> a.compareTo(b) = Integer::compareTo
```

4. 생성자 레퍼런스

```
() -> new TreeMap<K,V>() = TreeMap<K,V>::new
len -> new int[len] = int[]::new
```

즉, 별도로 메세지를 넣기 위해서는 메소드참조 방식을 사용할 순 없습니다.
값을 넣으려면 람다식 인자값에 있는 것들만 가능합니다 :)

**Comment by jojoldu** [comment]
@zhtmr 답변이 없으셔서 해당 이슈는 종료하겠습니다 :)
