### ISSUE TITLE
[오류] p.290

### ISSUE THREAD

**Issue by cjsxorud111** [jojoldu/freelec-springboot2-webservice#286]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: data navigator 로 create 문을 작성하면 실행되긴 하지만 빨간줄이 뜹니다. expected one of the following:algorithm definer sql view 빨간줄에 커서를 대고 있으면 이렇게 뜨는데 무슨의미인지 잘 모르겠습니다. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/cjsxorud111/calculator

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/32443642/75224707-564ce600-57ec-11ea-9afe-c8c36ee755b0.png)

**Comment by jojoldu** [comment]
@cjsxorud111 님 안녕하세요!
해당 빨간줄은 IntelliJ가 커뮤니티 버전이라 SQL을 지원하지 않는 상태라서 구문을 분석할수 없어 발생한 메세지입니다.
문법체크 등 SQL Support 기능이 지원하지 않는다는 경고 메세지로 보시면 됩니다.
커뮤니티 버전에서는 해결하기가 어려워 플러그인에서 별도의 지원 방법이 나오지 않는 이상은 해결이 어려울것 같습니다 ㅠ
