### ISSUE TITLE
[오류] p.356-357 travis 배포 오류입니다

### ISSUE THREAD

**Issue by hwang11** [jojoldu/freelec-springboot2-webservice#296]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:
codedeploy설정 후 push하니 travis에서 아래와 같은 오류가납니다 
아래의 s3주소에서 ap-northeast 부분이 ap-northest로 되어있어 오류가 나는거같은데
.travis.yml을 수정해도 반영이 되지 않습니다 ㅠㅠ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/hwang11/springboot-webservice

### 오류 로그
Logging in with Access Key: ****************IL6B
NEWER VERSION AVAILABLE: Please upgrade to AWS SDK For Ruby V3
/home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to hsa-springboot-build.s3.ap-northest-2.amazonaws.com:443 (getaddrinfo: Name or service not known) (Seahorse::Client::NetworkingError)
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/net/http.rb:882:in `start'
	from /home/travis/.rvm/rubies/ruby-2.4.9/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/net_http/handler.rb:119:in `session'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/net_http/handler.rb:45:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/plugins/content_length.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_request_signer.rb:88:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_request_signer.rb:23:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_host_id.rb:14:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_request_signer.rb:65:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:108:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:139:in `retry_request'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:122:in `retry_if_possible'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/retry_errors.rb:110:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_dualstack.rb:32:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_accelerate.rb:49:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_md5s.rb:31:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/rest/handler.rb:7:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/endpoint_pattern.rb:27:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/endpoint_discovery.rb:67:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/aws-sdk-core-2.11.456/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-code_deploy-1.10.15/lib/dpl/provider/code_deploy.rb:46:in `revision_version_info'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-code_deploy-1.10.15/lib/dpl/provider/code_deploy.rb:63:in `s3_revision'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-code_deploy-1.10.15/lib/dpl/provider/code_deploy.rb:40:in `revision'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-code_deploy-1.10.15/lib/dpl/provider/code_deploy.rb:82:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.15/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.15/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.15/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.15/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.15/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.9/gems/dpl-1.10.15/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.9/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.9/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
dpl.3
Deploying application
failed to deploy
어떤 오류인지 캡쳐해주세요.

**Comment by BingSuYam** [comment]
혹시 어떤문제로 해결 되어는지 궁금합니다. 
저도 같은무제로 고생중인데 ....

**Comment by hwang11** [comment]
저는 travis.yml에 오타가 있어서 트레비스 트리거가 작동하지 않아 발생한 오류였습니다

**Comment by BingSuYam** [comment]
시간이 괜찮으시다면,, yml 파일 내용에 필수요소들이 제대로 맞는지 확인 가능할까요 ??


2020년 3월 24일 (화) 오후 7:46, Seonah Hwang <notifications@github.com>님이 작성:

**Comment by BingSuYam** [comment]
자가 해결 되었습니다. ........

문제는 appspec.yml <-- 여기서 디렉토리 정해주는 부분을 문법 에러로 계속 실패했네요 ..
