### ISSUE TITLE
p.99 그림 3-11 이 잘못 첨부된것 같습니다..

### ISSUE THREAD

**Issue by bin-e** [jojoldu/freelec-springboot2-webservice#3]
p.99에 `그림 3-11 쿼리 로그 확인` 그림에 중간에 메시지가 `Hibernate: create table posts (id bigint not null auto_increment, author varchar(255), cont ...`로 나와있는데, 해당 부분까지 코드 실행했을때나, 도서 하단의 설명에 따르면 `id bigint generated by default as identity`라는 옵션이 나오는게 정상..?! 같습니다ㅠ

혹시나 제가 따라오다가 뭘 잘못쳤나 하고, 올려주신 예제 코드 clone후 [이부분 스냅샷](https://github.com/jojoldu/freelec-springboot2-webservice/tree/a7ee6576dcb8f9783e3ad52799abf30997cbf6ca)까지 Checkout 한 뒤에, 동일한 테스트코드 실행해도 `Hibernate: create table posts (id bigint generated by default as identity,`라는 메시지가 발생 해서 혹시나 하고 이슈 올려봅니다..!

엉뚱한걸 찾아서 이슈올린거라면 바쁘신데 죄송합니다...

**Comment by jojoldu** [comment]
@bin-e 앗!! 맞습니다 해당 그림의 캡쳐가 잘못되어있으며, **설명부분의 내용**이 맞습니다!
제보감사합니다 ㅠ

**Comment by jojoldu** [comment]
그리고 책 구매하셨기 떄문에 언제든 편하게 이슈 남겨주시면 됩니다 :)
전혀 불편하지 않습니다!
제보해주신 덕분에 다음 인쇄할떄는 해당 부분 수정해서 진행하겠습니다!
정말 고맙습니다!

**Comment by bin-e** [comment]
뭔가 오픈소스에 기여한 것처럼 기쁘네요..! 좋은 책 감사합니다~!

**Comment by jojoldu** [comment]
제가 더 감사드리죠! :) 
적극적으로 기여해주셔서 고맙습니다 :)

**Comment by jojoldu** [comment]
@bin-e 님 이슈 제보해주신 건에 대해서 제가 할수 있는게 새로 교정된 책을 전달드리는것 밖에 없는데요 ㅠ 
제 메일 주소 jojoldu@gmail.com로 주소를 보내주시면 교정된 책으로 한부 전달드리겠습니다.
제보 해주셔서 정말 감사드립니다 :)

**Comment by bin-e** [comment]
@jojoldu 오잉..! 생각해주시는 마음 너무 감사하고, 다시 보내주신다는 말씀도 감사하지만! 저는 오히려 평소에 블로그를 통해 도움만 받다가 이런 작은 도움이라도 드릴 수 있게 되어 너무 기쁩니다 ㅋㅋ 이걸로 벌써 보상받은 것 같네요..! 그리고 "초판 1쇄"가 저한테 뭔가 뜻깊어서..ㅋㅋ 교정본 대신 마음만 받겠습니다..! 정말 감사합니다~!

**Comment by jojoldu** [comment]
@bin-e 아 ㅠ 넵 그렇게 말씀해주시니 더더욱 감사드립니다 ㅠ
혹시나 제가 다른 방법으로 보답할게 있다면 다시 의견을 여쭙겠습니다.
다시한번 정말 감사드립니다!
