### ISSUE TITLE
P.276 collation_server

### ISSUE THREAD

**Issue by thingsbrain-joonho** [jojoldu/freelec-springboot2-webservice#30]
collation_server 와 collation_connection은 utf8mb4_unicode_ci 로 변경하면 되나요?

**Comment by jojoldu** [comment]
@thingsbrain-joonho 앗! 아닙니다.
utf8mb4_general_ci 를 선택하셔야 합니다.

![image](https://user-images.githubusercontent.com/7760496/70419364-a1d2dc00-1aa8-11ea-827f-aa325c987bec.png)

**Comment by thingsbrain-joonho** [comment]
감사합니다.

**Comment by thingsbrain-joonho** [comment]
추가 질문 드립니다. 
파라미터 편집에서 utf8mb4로 변경 후 쿼리를 해보면 변경이 안된 변수들이 있는데요. 왜 그런지요? 
![Screen Shot 2019-12-09 at 11 42 18 PM](https://user-images.githubusercontent.com/54837645/70444760-c4cbb300-1add-11ea-8026-fa620cf21104.png)

**Comment by thingsbrain-joonho** [comment]
GUI 편집기마다 다르게 나오네요. 최종 확인한 IntelliJ Database Browser에서는 잘 확인이 됩니다.

**Comment by jojoldu** [comment]
앗 감사합니다 :)
