### ISSUE TITLE
[오타 제보] p.270

### ISSUE THREAD

**Issue by JayStory4u** [jojoldu/freelec-springboot2-webservice#300]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타): 그림7-5
인스턴스 식별자
freelect-sp~~

* to-be (교정):
freelec-sp~~

t 가 빠져야 결이 맞습니다~~

**Comment by jojoldu** [comment]
@JayStory4u 앗 맞습니다 ㅠㅠ 제보 감사합니다!
