### ISSUE TITLE
[오타 제보] p.272

### ISSUE THREAD

**Issue by JayStory4u** [jojoldu/freelec-springboot2-webservice#301]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):
그림7-7
데이터베이스이름에 
freelec_springboot2_webservice

* to-be (교정):
freelec-springboot2-webservice

언더바가 아니라 대쉬로 해야 결이 맞지 않을까요? ^^;

**Comment by JayStory4u** [comment]
언더바밖에 안되는군요

**Comment by jojoldu** [comment]
@JayStory4u 네 맞습니다 ㅎㅎ;
