### ISSUE TITLE
[오류] redirect_uri_mismatch 오류 

### ISSUE THREAD

**Issue by dmstjd1024** [jojoldu/freelec-springboot2-webservice#304]
### 어떤 오류인가요?

오류설명 : 

책 따라 코딩 다 하고서는 한달? 정도 지난 후에 다시 로그인 해봤는데 mismatch 오류가 납니다. google oauth랑 naver developer는 정상적으로 적어놨구요 어디가 문제인지 모르겠네요ㅠㅠ nginx에 따라 8081, 8082로 잘 나눠지는데 localhost가 서버의 localhost로 인식이 안되는거 같기도 하고요

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/dmstjd1024/aloneWebService.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![image](https://user-images.githubusercontent.com/54055200/76185765-8300f480-6213-11ea-8590-0fd8418c90d7.png)

**Comment by AYoungSn** [comment]
uri 등록할 때 http://localhost ~~~하셨으면 127.0.0.1로 바꿔보세요
