### ISSUE TITLE
[오류] p.115 PostApiControllerTest의 update test 실패

### ISSUE THREAD

**Issue by sdo1991** [jojoldu/freelec-springboot2-webservice#305]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: Update 실습을 테스트해보면 파싱에러가 납니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 
https://github.com/sdo1991/test

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![1](https://user-images.githubusercontent.com/56330932/76194654-f1e94800-6229-11ea-8059-3df8d8a6dfd8.PNG)
![2](https://user-images.githubusercontent.com/56330932/76194673-f9a8ec80-6229-11ea-8eff-b06734b5b72d.PNG)

https://github.com/sdo1991/test/compare/master...sdo1991-patch-1?quick_pull=1#diff-fb0fe4cc87adddff7536a02e12e4f968

**Comment by Bammuri** [comment]
저 또한 같은 오류입니다.

**Comment by Bammuri** [comment]
해결했습니다. 역시 오타 문제 였습니다.

**Comment by sdo1991** [comment]
String url="http://localhost:"+port+"/api/v1/ports/"+updateId;//1
String url="http://localhost:"+port+"/api/v1/posts/"+updateId;//2

저도 오타문제 같아서 샅샅이 뒤져보니 url이 틀렸었네요.
이것때문에 5시간 헤멨는데... 허무합니다.
Bammuri님 덕분에 그나마 빨리 해결한 것 같습니다. 감사합니다.

**Comment by Bammuri** [comment]
거의 숨은그림찾기 수준...

**Comment by hanguk0726** [comment]
같은 이슈였는데 답글들보고 바로 오타부터 의심해서 금방 잡았네요. 고맙습니다.

**Comment by hyuuny** [comment]
덕분에 해결했습니다 ㅠㅠ

**Comment by jalhagosipuda** [comment]
정말 감사합니다. 대체 어디가 잘못된건지 한참을 찾았었는데 덕분에 해결했습니다.

**Comment by minju7346** [comment]
감사합니다....
