### ISSUE TITLE
[오타 제보] p.330 그림9-8

### ISSUE THREAD

**Issue by JayStory4u** [jojoldu/freelec-springboot2-webservice#307]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):

사용자 이름에 

freelect-travis-deploy

* to-be (교정):

freelec-travis-deploy

일관성있게 t 를 빼는게 좋을거 같습니다.

**Comment by jojoldu** [comment]
@JayStory4u 넵 제보 감사합니다!
t 가 계속 들어가있었네요 ㅠ
