### ISSUE TITLE
P.281 보안그룹

### ISSUE THREAD

**Issue by thingsbrain-joonho** [jojoldu/freelec-springboot2-webservice#31]
그림 7-24 EC2의 보안 그룹 복사라고 되어 있는데요.

보안 그룹메뉴로 들어가면 default VPC security group 이라고만 되어 있고 Name은 Blank로 되어 있는데요. 이 부분을 EC2 보안 그룹으로 보면 되나요?

**Comment by jojoldu** [comment]
@thingsbrain-joonho 아! 하나밖에 없으시면 EC2가 확실할텐데요 :)
혹시 모르니 EC2에 등록된 보안그룹이 해당 보안그룹이 맞는지 확인 꼭 해보시고요 :)

![image](https://user-images.githubusercontent.com/7760496/70419703-52d97680-1aa9-11ea-9412-a243c481f928.png)


위와 같이 EC2 선택해서 할당된 보안그룹 보시고 맞으면 그대로 복사하시면 됩니다.
Name은 미등록된 상태시면 아래 연필표시를 클릭해서 추가해주시면 됩니다 :)

![image](https://user-images.githubusercontent.com/7760496/70419771-83b9ab80-1aa9-11ea-9ed7-3314e30d7ed4.png)

**Comment by thingsbrain-joonho** [comment]
RDS 보안그룹을 따로 생성 했어야 하는군요. 생성후 연결하니 잘 되네요. 감사합니다.

**Comment by jojoldu** [comment]
@thingsbrain-joonho 넵 감사합니다 :)
