### ISSUE TITLE
[오타 제보] p.384 파일생성위치

### ISSUE THREAD

**Issue by JayStory4u** [jojoldu/freelec-springboot2-webservice#311]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):

* to-be (교정):

*.properties 의 위치를 물론 프로젝트 내려받아서 찾아보거나
스프링부트에 익숙한 사람이면 감이 오겠지만^^;

어디에 생성하는지 한줄 써준다면 참 좋을것 같단 생각이 들었습니다~

**Comment by jojoldu** [comment]
@JayStory4u 좋은 제안 감사합니다 :)
