### ISSUE TITLE
[오류] p.105 테스트코드 오류    [해결완료]

### ISSUE THREAD

**Issue by BingSuYam** [jojoldu/freelec-springboot2-webservice#312]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 작성자 : 본 실습 책 은 2쇄본 

오류설명:  
#####################첫번째#########################
Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
#####################두번째#########################
 expected:<[200 OK]> but was:<[302 FOUND]> 에러
#####################################################
에러를 발생하네요 ... 혼자 해결하다 지쳐서 작성해봅니다. ㅠㅠ

### 프로젝트 주소
#####################첫번째#########################
PostsApiControllerTest 에서 사용되는 "Posts_등록된다()" 메소드의 
assertThat(all.get(0).getTitle()).isEqualTo(title);  < --- 이부분이 
#####################두번째#########################
mvc.perform(post(url)                             
                .contentType(MediaType.APPLICATION_JSON_UTF8)
                .content(new ObjectMapper().writeValueAsString(reDto)))
                .andExpect(status().isOk());
#####################################################

### Github 주소 
* Github URL: https://github.com/BingSuYam/soloWebService_Sync.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![캡처](https://user-images.githubusercontent.com/51504975/76300436-0e57b400-6300-11ea-8876-72d60ac261c2.PNG)

**Comment by BingSuYam** [comment]
제가 책의 내용을 제대로 읽지 않고  저작자님의 코드만 보고 안되는것들을 무작정 끼워넣기 형식으로 공부를 하다보니  저러한 에러가 나온것같습니다. 

아래 내용에 따라 수정 을 했습니다. 

1. 소스 중 import org.springframework.security.test.context.support.WithMockUser; 사용하는 어노테이션들 삭제
2. test 프로젝트 폴더 중 application.properties 삭제.
3. build.gradle 중 책내용에 따라 쓰지않은 dependencies 항목들 삭제

=============================================================
* 해결완료

**Comment by jojoldu** [comment]
@BingSuYam 해결되셔서 다행입니다 :)
