### ISSUE TITLE
[오타 제보] p.310 deploy.sh nohup 오타?

### ISSUE THREAD

**Issue by darren9352** [jojoldu/freelec-springboot2-webservice#316]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):
nohup java -jar \
   -Dspring.config.location=classpath:/application.properties, /home/ec2-user ....
* to-be (교정):
nohup java -jar \
   -Dspring.config.location=classpath:/application.properties, **classpath:/application-real.properties** /home/ec2-user ....

deploy.sh 의 nohup 쪽에 classpath:/application-real.properties를 추가해 줘야 하지 않나요? 
application-real.properties가 없을 때는 오류가 났었는데, 저걸 넣으니까 제대로 되었습니다.

**Comment by Bammuri** [comment]
왘ㅋㅋㅋ저 10분전에 알아내서 오타추가하려고 보니 벌써 올려 놓으셨네요^^ 중요한 오타인것 같네요

**Comment by hwangikjae** [comment]
안녕하세요.
nohup java -jar \-Dspring.config.location=classpath:/application.properties, classpath:/application-real.properties, /home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \-Dspring.profiles.active=real \ $REPOSITORY/$JAR_NAME 2>&1 &

뭐가 잘못된걸까요..
Error: Unable to access jarfile classpath:/application-real.properties,
이 오류가 납니다.

**Comment by dkaskgkdua** [comment]
안녕하세요 혹시 질문 좀 할수 있을까요 ㅠ
nohup java -jar \ -Dspring.config.location=classpath:/application.properties, classpath:/application-real.properties/home/ec2-user/app/application-oauth.properties, /home/ec2-user/app/application-real-db-properties \ -Dspring.profiles.active=real \ $REPOSITORY/$JAR_NAME 2>&1 &

인데 에러가 계속 뜨네요 뭐가 문제일까요 ㅠ

**Comment by jojoldu** [comment]
@darren9352  와 중요한 제보 정말 감사합니다 ㅠ

**Comment by jojoldu** [comment]
@dkaskgkdua 님 안녕하세요! application-real.properties와 application-oauth.properties사이에 콤마(,)가 빠진것 같은데요
아래 코드로 하면 어떠신가요?
```
nohup java -jar \
 -Dspring.config.location=classpath:/application.
properties, /home/ec2-user/app/application-oauth.properties,
/home/ec2-user/app/application-real-db.properties, classpath:/application-real.properties \
 -Dspring.profiles.active=real \
 $REPOSITORY/$JAR_NAME 2>&1 &

```
