### ISSUE TITLE
[오류] p109 : No HttpMessageConverter 오류가 발생합니다

### ISSUE THREAD

**Issue by neho-jooool** [jojoldu/freelec-springboot2-webservice#318]
PostsApiControllerTest 실습 중 오류가 발생해 문의드립니다 ㅠㅠ

1. 오류발생파일주소 :

https://github.com/neho-jooool/neho-springboot2-webservice/blob/master/src/test/java/com/neho/book/springboot/web/PostsApiControllerTest.java

![오류](https://user-images.githubusercontent.com/62065925/76643581-b1c2f600-6598-11ea-9e77-386e98fa67e7.jpg)

**Comment by MelRanG** [comment]
어떻게 해결하셨나요?
