### ISSUE TITLE
Spring Security & OAuth2 구현 코드 관련 질문

### ISSUE THREAD

**Issue by dasistHYOJIN** [jojoldu/freelec-springboot2-webservice#32]
현재 이 코드를 참고하고 있는데요,
https://github.com/jojoldu/freelec-springboot2-webservice/blob/master/src/main/java/com/jojoldu/book/springboot/config/auth/CustomOAuth2UserService.java
의문이 들었던 부분은, Service에게 명령을 내리는 주체가 Controller가 아닌 Security라는 점이었습니다.

저에게 익숙한 구조는 Controller가 Serivce의 메서드를 구현함으로써 로직을 수행하는 것인데
1. DispatcherServlet보다 외곽에 위치한 Security Filter가 직접적으로 Service 레이어에 접근하고
2. Repository 등 프로그램의 내부 상태에 영향을 미치는 구조가 보안에는 문제가 없는 것일까라는 의문이 들었습니다.

이렇게 구현을 한다면 Resource 서버가 가진 User의 상태 변화를 즉각적으로 반영할 수 있다는 장점이 있을 것 같습니다.
하지만 위에 말씀드린 의문이 해결되지는 않아 혹시 다른 이유나 생각이 있다면 의견을 들어보고 싶습니다!

**Comment by jojoldu** [comment]
안녕하세요 @dasistHYOJIN :)
메일보시고 이슈로 남겨주셔서 정말 감사드립니다.
메일로 보내드린 답변 여기에도 똑같이남길게요 :)
다른분들도 같은 궁금증이 있으실것 같아서 부탁드렸는데 남겨주셔서 정말 감사드립니다.

1) Controller -> Service의 계층 구조가 깨지는데 괜찮은지?
- Security 역시 Controller와 같은 **WEB** 계층입니다.
image.png
(https://www.petrikainulainen.net/software-development/design/understanding-spring-web-application-architecture-the-classic-way/)

보시는것처럼 Filter 역시 Advice, Controller와 같은 계층에 위치하고 있기 때문에 꼭 Controller만 Web 계층이라고 볼수는 없을것 같습니다.
- 추가로. @Service가 아닌 @Component가 붙었다면 구조에 문제가 없었을까요?
- @Component는 서비스 계층이 아닌걸까요?

CustomOAuth2UserService는 이유 없이 Service가 된 것은 아니며, **Spring Security**에서 공식적으로 확장 포인트로 열어놓은 OAuth2UserService 를 사용한거라서요 :)
그래서 Service 계층으로 사용중입니다.

2) Security Filter가 Repository에 접근하면 보안에 문제가 없는지?
음... Controller에서 Repository에 바로 접근하면 보안에 문제가 없을까요?
SQL 인잭션, XSS 와 같은 문제는 Security Filter 보다 앞단 필터에서 처리를 해야한다고 생각을 합니다.
- 보안이슈라는게 어떤 이슈가 있을지 얘기해주시면 더 답변드리기 편할것 같다는 생각이 드네요 :)

그리고 Security Filter와 Repository에 다른 계층을 둔다 해도 (ex: UserService?? 같은?)
Security Filter와 Repository 간에 열려있는건 마찬가지라고 생각이 되어요 :)

언제든 편하게 질문 주세요 :)
