### ISSUE TITLE
[오류] 194p.몇페이지

### ISSUE THREAD

**Issue by shyn7708** [jojoldu/freelec-springboot2-webservice#324]
### 어떤 오류인가요?
글 등록버튼이 작동되지 않습니다. localhost:8080에 접속하여 로그인하고 글 등록으로 넘어가서 등록 버튼을 누르면 반응이 없습니다. 그 전에는 잘 되었는데 구문을 추가하다보니 안되네요.
오류설명:

### 프로젝트 주소
Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/shyn7708/freelec-springboot2-webservice22222
현재 application-oauth.properties까지 추가한 상태입니다.
### 오류 로그

어떤 오류인지 캡쳐해주세요.
오류 로그는 처음에 
Process 'command 'C:/Program Files/Java/jdk1.8.0_241/bin/java.exe'' finished with non-zero exit value 1 이렇게 표기되었지만 자바를 재설치하거나 Rebuild하는 방식으로 해결하였습니다.

**Comment by jojoldu** [comment]
@shyn7708 앗 네 해결되셨으니 다행입니다 ㅠ
