### ISSUE TITLE
[오타 제보] p.388 profile.sh

### ISSUE THREAD

**Issue by doorisopen** [jojoldu/freelec-springboot2-webservice#327]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!
### 오타

profile.sh 코드 중 `echo "${IDLE_PROFILE}" `에서 (3)이 아닌 (2)로 써있습니다.

* as-is (오타):
else
      IDLE_PROFILE=real1
    fi

    `echo "${IDLE_PROFILE}" (2)`

* to-be (교정):
else
      IDLE_PROFILE=real1
    fi

   `echo "${IDLE_PROFILE}" (3)`

**Comment by jojoldu** [comment]
@doorisopen 앗 제보 감사합니다 :)
