### ISSUE TITLE
[오류] p.291 페이지

### ISSUE THREAD

**Issue by YOOKIJUN** [jojoldu/freelec-springboot2-webservice#330]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:  7.4 EC2에서 RDS 에서 접근 확인(p.291)

mysql -u ~~~~~ -p -h ~~~~ 명령어를 실행하면 password는 묻지만 한참후에 접속이 않된다고 
메세지가 나옵니다. 아마도 앞부분에 설정을 잘못한것 같은데(RDS 보안 그룹 부분)

별거아닌 작업같은데  AWS 설정화면이 브라우져(크롬,IE11)마다 조금씩 다르게 나오고

책에 있는 부분을 따라해보려고 해도 잘않되네요

7.3 내 PC 에서 RDS 에서 접속해보기 부분을 최신 버젼으로 보충해주실수 있는지요?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by KMSKang** [comment]
지금 고객님께서는 내부에서 접속하려고 시도하고 있습니다.
aws를 접속하지 마시고
터미널 초기 상태에서 접속하시길 바랍니다.

**Comment by KMSKang** [comment]
https://open.kakao.com/o/grG5fSO

그래도 안되시면
이쪽 카톡방으로 오셔서
@lugi 입력하시고 불러주세요
