### ISSUE TITLE
[오류] p.88

### ISSUE THREAD

**Issue by graylobo** [jojoldu/freelec-springboot2-webservice#331]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?
그대로 따라오다가
import javax.~ 이 부분에서부터 cannot resolve symbol 에러가 발생합니다
jar파일이 없어서 그런거같은데 책 본문중에는 관련해서 설명이 없어서요
어떻게 해결하면 될까요?
### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/graylobo/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/37823841/77221979-58f3ee80-6b92-11ea-825d-5c76b09dfa66.png)

**Comment by WISUNGWON** [comment]
아직도 막히시나요?

저도 같은 오류가 발생해서 StackoverFlow를 통해 알아봤는데요

86p따라서 dependencies에 의존성 입력하실때 아마 오타를 내셨을 수도 있어요 

    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('com.h2database:h2')

위에 있는 코드 2줄 확인해보시고 Posts 클래스 다시 한번 시도해보세요!

**Comment by jojoldu** [comment]
@graylobo 님 안녕하세요 :)
아마 책을 다시 차례로 진행해보시면 문제가 없으실텐데요 :)
보시면 현재 프로젝트에 필요한 의존성이 없습니다

![image](https://user-images.githubusercontent.com/7760496/80859936-56131000-8c9f-11ea-98e2-eb9c80db084c.png)

spring-boot-starter-data-jpa 의존성이 있어야하며, 이건 책에서 차례로 등록하는과정이 있으니 꼭 다시 참고해주세요 :)
