### ISSUE TITLE
[오류] p.63 테스트가 실패합니다.

### ISSUE THREAD

**Issue by ev001** [jojoldu/freelec-springboot2-webservice#334]
### 어떤 오류인가요?

오류설명: 책의 예제를 따라 하였으나 Tests failed가 발생합니다. 

### 프로젝트 주소

* Github URL:  https://github.com/ev001/springboot2-webservice

### 오류 로그

![error_1](https://user-images.githubusercontent.com/47404603/77230322-bad64780-6bd6-11ea-9b96-533640a46691.JPG)
![error_2](https://user-images.githubusercontent.com/47404603/77230327-bf9afb80-6bd6-11ea-9164-6f2bac8c46b7.JPG)

**Comment by ev001** [comment]
자체해결했습니다.
문제점이 두가지 있었습니다.
1. web 패키지 위치 문제.
    위치를 java / com.~.springboot 내로 수정해주었습니다.
2. 테스트 실행시 반응없음 
    test events were not received라는 문구와 함께 log를 보면 test pass가 0으로 나오는 문제였습니다.
    https://stackoverflow.com/questions/57795263/test-events-were-not-received-when-run-tests-using-intellij/58796344#58796344 를 참고하여 해결하였습니다.

**Comment by Yjzoe** [comment]
감사합니다.
같은 현상이었는데 덕분에 해결했어요:)

**Comment by ev001** [comment]
도움이 됐다니 기쁘네요 ㅎㅎ
