### ISSUE TITLE
[개선요청] p.130 Plugin 설치

### ISSUE THREAD

**Issue by codelabor** [jojoldu/freelec-springboot2-webservice#338]
### 개선요청
* 위치: p.130 그림 4-4
* as-is (오타): 다음과 같이 'mustache'를 검색해서 해당 플러그인을 설치하시면 됩니다.
* to-be (교정): File > Settings > Plugins에서  'mustache'를 검색해서 해당 플러그인을 설치하시면 됩니다.

초반에는 인텔리제이를 처음 사용하는 사람을 감안하고 쓰여진 듯한데 (인텔리제이를 권하므로)
플러그인 설치를 어디서 하는지에 대한 언급이 없습니다.
검색 가능한 위치까지 진입하는 정보를 추가하면 좋겠습니다.

**Comment by jojoldu** [comment]
@codelabor 오 넵넵! 제안 감사드립니다! 
이건 5쇄에 반영해놓겠습니다!
