### ISSUE TITLE
[오타 제보] p.149 import

### ISSUE THREAD

**Issue by codelabor** [jojoldu/freelec-springboot2-webservice#341]
### 오타
* 위치: 149페이지 소스코드 첫 번째 줄
* as-is (오타): import com.fasterxml.jackson.annotation.JsonFormat;
* to-be (교정): import com.jojoldu.book.springboot.domain.posts.Posts;

해야할 임포트가 빠지고
안 해도될 암포트가 있네요.

**Comment by jojoldu** [comment]
@codelabor 헉 제보 감사합니다!
