### ISSUE TITLE
[오류] p.116 h2-console 페이지가 안열립니다.

### ISSUE THREAD

**Issue by jong4876** [jojoldu/freelec-springboot2-webservice#348]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: spring.h2.console.enable=true 설정을 application.properties에 추가했는데  http://localhost:8080/h2-console 접근시 페이지가 안열리네요. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/jong4876/freelec-springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by jikimee64** [comment]
어떻게 해결하셨나요?

**Comment by jong4876** [comment]
@jikimee64  이유는 모르겠으나, 저는 디폴트로 h2콘솔 접근이 안되서 https://projectjt.tistory.com/4 블로그 참고해서 설정파일을 새로 만들었어요.

**Comment by jikimee64** [comment]
정말 감사합니다!! 잘해결되었습니다.
