### ISSUE TITLE
P.188 google 로그인 연동 에러

### ISSUE THREAD

**Issue by HyeonbinSa** [jojoldu/freelec-springboot2-webservice#35]
안녕하세요!!! 

chapter 5에서 구글 로그인 연동하는 부분 따라하는 중인데 
아래와 같은 에러가 뜨더라구요 ㅠㅠ 

gradle 버전의 문제인가해서 버전을 4.대로 수정해보기도 했지만 계속 같은 에러가 발생해서 질문드립니다 ㅠㅠ

***************************
APPLICATION FAILED TO START
***************************

Description:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'clientRegistrationRepository' in 'OAuth2ClientRegistrationRepositoryConfiguration' not loaded because OAuth2 Clients Configured Condition registered clients is not available

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.

> Task :Application.main() FAILED

Execution failed for task ':Application.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

아직 책을 마무리 짓지 못했지만 정말 많은 걸 배우고 있습니다.

정말 감사합니다.

**Comment by jojoldu** [comment]
@HyeonbinSa 님 안녕하세요 :)
질문 감사합니다!
음 일단은 스프링 시큐리티 설정을 못읽어 오는것 같고요.

1) application-oauth.properties 파일이 있으신지,
2) 있다면 아래와 같이 구글 정보가 등록되어있는지

```
spring.security.oauth2.client.registration.google.client-id=구글클라이언트ID
spring.security.oauth2.client.registration.google.client-secret=구글클라이언트시크릿
spring.security.oauth2.client.registration.google.scope=profile,email
```

확인해보시면 될것 같습니다 :)

**Comment by HyeonbinSa** [comment]
빠른 답변 정말 감사드립니다!! ㅠㅠ

말씀해주신대로 다시 한번 확인해보았는데 해당 파일도 생성해뒀고 구글 정보도 등록 완료했습니다.

하지만 같은 에러가 발생하는데 혹시 새로운 dependencies를 추가해야하는게있을까요??
![Uploading image.png…]()
현재 이렇게 등록해두었습니다 ㅠㅠ 

감사합니다

**Comment by jojoldu** [comment]
@HyeonbinSa 만드신 프로젝트를 잠깐 구경했는데요 :)
확인해보니 application-oauth.properties를 못가져오는것을 확인했습니다
아래와 같이 application.properties 에 코드를 추가하시면 됩니다!

![image](https://user-images.githubusercontent.com/7760496/70512237-212ce200-1b73-11ea-9b28-632eeac72e03.png)

```
spring.profiles.include=xxx
```

라는 설정은 application-xxx.properties 파일의 설정을 가져오라는 의미입니다.
즉, 그냥 설정에서는 기본적으로 제외되며, 저렇게 옵션을 추가해야만 외부 파일의 옵션을 가져옵니다.

> 자세한 설명은 p.175에서 소개하고 있습니다 :)

**Comment by HyeonbinSa** [comment]
정말 감사합니다.

해당 코드 추가 후에 정상적으로 작동됩니다!!!

책에 있는 내용인데 제대로 안보고 여쭤봤네요;; 죄송합니다!!

더 자세히 훑어보도록하겠습니다.

책을 보며 새로운 것에 대해 많이 알아가고 있습니다. 정말 감사합니다.

**Comment by jojoldu** [comment]
@HyeonbinSa ㅎㅎ 아닙니다 :) 처음하시면 그럴수있다고 봐요 :)
재밌게 봐주셔서 감사합니다!
언제든 편하게 이슈 남겨주세요!
