### ISSUE TITLE
[오류] p.212 전체 테스트 실행이 4개밖에 실행되지 않습니다

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#350]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 책에서는 gradle > test 실행하면 전체 테스트가 실행되면서 모든 테스트 결과가 뜨는데 저는 사진과같이 테스트가 4개만뜨네요.. 왜 이런건지 모르겠습니다

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/zhtmr/freelec-springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/48509269/77846310-4318a600-71f0-11ea-87eb-390500fe931e.png)

**Comment by dnjsdyd345** [comment]
이문제 해결 어떻게 해결하셨는지요??
