### ISSUE TITLE
[오타 제보] p.217 private MockMvc mvc; 위에 @autowired 어노테이션 없어도 되는건가요?

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#352]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):

![image](https://user-images.githubusercontent.com/48509269/77913545-67977f80-72cf-11ea-8d1e-a3680eda8dd9.png)

PostsApiControllerTest 화면인데 의존성 주입할때 전부 @Autowired로 되어있는데 MockMvc 만 그냥 필드로 적혀있고 어노테이션이 없는데 이건 왜 그런건가요??
* to-be (교정):

**Comment by jojoldu** [comment]
@zhtmr 안녕하세요 :)
아마 코드를 보시고 종료하셨겠지만
setup 에서 mockMvc 객체를 추가하고 있어서 그렇습니다 :)
