### ISSUE TITLE
[오류] p.281 에서 RDS 보안그룹 ip 추가할때 카페ip, 집ip 둘다 등록해야되나요?

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#355]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

1쇄 기준 240페이지에서 ec2 인바운드 규칙에 "카페와 같이 집 외에 다른 장소에서 접속할 때는 해당 장소의 IP를 다시 SSH 규칙에 추가하는 것이 안전합니다" 라고 하셨는데
![image](https://user-images.githubusercontent.com/48509269/78343370-b4cc6780-75d5-11ea-831e-73367dc84688.png)

281페이지에서도 RDS 인바운드 규칙에 ip 추가할때 카페ip만 추가했는데.. 집 ip도 추가하는게 좋을까요??
![image](https://user-images.githubusercontent.com/48509269/78343521-e9402380-75d5-11ea-85a4-d93381dfc91b.png)

**Comment by jojoldu** [comment]
@zhtmr 님 안녕하세요 :) 
집에서도 개발 하실 계획이시라면 집 IP도 같이 등록하시면 좀 더 편하게 개발하실 수 있으십니다 ^^;
