### ISSUE TITLE
[오류] p.395

### ISSUE THREAD

**Issue by Huhsway** [jojoldu/freelec-springboot2-webservice#356]
nginx 무중단 배포 하는데 여기서 failed to deploy 뜨네요 ㅠㅠ

![image](https://user-images.githubusercontent.com/35622185/78346217-aed88580-75d9-11ea-99a5-7501a8b04857.png)

![image](https://user-images.githubusercontent.com/35622185/78346248-be57ce80-75d9-11ea-81f6-7ded8d540e24.png)

**Comment by Huhsway** [comment]
appspec.yml에서
![image](https://user-images.githubusercontent.com/35622185/78350468-3c1ed880-75e0-11ea-83f2-85c7ad5fef68.png)

dest

**Comment by slo-ow** [comment]
잘 보고갑니당
