### ISSUE TITLE
[질문] 사용자 관리 Security Session, Http Session 2개 중복?

### ISSUE THREAD

**Issue by hyun001** [jojoldu/freelec-springboot2-webservice#359]
현재 프로젝트에서 oauth2 인증을 받고 사용자 정보를 Session에 담아서 사용중인데

시큐리티에 대해 공부해보니 인증을 받은 후면 시큐리티가 인증을 받은 사용자를 세션에 자동으로 넣어 주더라구요

실제로 SecurityContextHolder.getContext().getAuthentication().getPrincipal() 을 디버깅 해보니 유저가 들어 있었습니다.

근데 왜 따로 httpSession 으로 세션을 만들어서 user를 넣어주신 건지 궁금합니다.

시큐리티가 만든 유저 세션 하나, 제가 만든 유저 세션 하나 

이렇게 세션 두개가 중복 되는것 같은데 아닌가요?ㅜㅜ

**Comment by jojoldu** [comment]
@hyun001 님 안녕하세요 :) 
아마 제가 메일로 답변드린 분인것 같습니다.
혹시 다른분들도 비슷한 고민을 하실것 같아서 여기에 메일 답변도 함께 남기겠습니다 ^^;

말씀해주신 세션을 강제로 사용한 이유는 **세션 정보에 커스텀한 정보를 쉽게 추가하기 위함**이였습니다 :)
(제가 기억하기로는 ) 해당 getPrincipal() 로 반환되는 정보는 아래와 같이 loadUser 메소드에서 반환된 DefaultOAuth2User 객체인데요.

![image](https://user-images.githubusercontent.com/7760496/79758179-03a92980-8358-11ea-8cd7-86f2eb6f6be8.png)

여기서 세션 객체의 필드값에 해당 하는 부분은 OAuthAttributes의 getAttributes() 를 사용합니다.
보통 이 Map의 경우에는 구글 혹은 네이버에서 준 로그인 정보를 모두 담고있다보니, 여기서 **세션에 담고 싶지 않은 Key를 제거 하는 작업**을 한번더 수행해야 합니다.

![image](https://user-images.githubusercontent.com/7760496/79758192-09067400-8358-11ea-8f40-c4b8ea89f679.png)
 

일단은 Map을 통해 추가/제거는 일반 클래스를 쓰는 것에 비해 단점이 명확하다는 장점이 있었습니다.
(어떤 값이 필수이고, 아니고를 Map은 제어가 안되지만 클래스는 멤버변수가 선언되어있고 final 변수 혹은 생성자로  필수값을 표현하기가 상대적으로 편합니다)

그리고 로그인 과정에서 필요한 값과 세션에 담을 정보를 분리하기에 코드가 지저분해질 수 있다고 판단했습니다.
return new DefaultOAuth2User 라는 코드가 결국 세션 정보와 로그인 결과값 반환 2가지 역할을 하고 있기에 이를 좀 분리하자라는 생각이였습니다 :)

둘다 큰 이유는 아니라서 판단하시기에 굳이 httpSession 코드 쓰는게 더 불편하다 싶으시다면 말씀해주신대로 SecurityContextHolder.getContext().getAuthentication().getPrincipal()로 표현하시면 됩니다 :)
getPrincipal 을 통해서 @LoginUser를 구현하고 싶으시다면 
LoginUserArgumentResolver에서 아래 처럼 코드를 작성해주시면 됩니다.

![image](https://user-images.githubusercontent.com/7760496/79758204-0e63be80-8358-11ea-862e-bc464c8ba854.png)

반환된 ObjectPrincipal을 각 컨트롤러가 필요한 값만 담은 SessionUser 클래스로 전환하는 코드까지 넣어주시면 원하는 필드만 가진 세션 객체가 될것 같습니다 :)

감사합니다.
