### ISSUE TITLE
P111 PostsUpdateRequestDto 누락건

### ISSUE THREAD

**Issue by seongho89** [jojoldu/freelec-springboot2-webservice#36]
안녕하세요~ 1쇄 구매자입니다

    @PutMapping("/api/v1/posts/{id}")
    public Long update(@PathVariable Long id, @RequestBody PostsUpdateRequestDto requestDto){
        return postsService.update(id, requestDto);
    }

여기에서 PostsUpdateRequestDto  클래스를 찾을 수 없네요 ㅠㅠ
git code에서 따와서 실습 하고있습니다.

**Comment by jojoldu** [comment]
@seonghohong 님 안녕하세요! :)
해당 코드가 책에선 누락되었네요 ㅠ
아래 이슈를 참고하시면 Dto가 있습니다!

https://github.com/jojoldu/freelec-springboot2-webservice/issues/15

불편을 드려 죄송합니다 ㅠ

**Comment by seongho89** [comment]
@jojoldu #15에 있었네요~ 조금 더 검색해볼걸 그랬네요

**Comment by jojoldu** [comment]
앗 아닙니다 ㅠ 책이 잘나왔어야했는데 놓친 제잘못입니다 ㅠ
언제든 편하게 이슈 올려주세요!
고맙습니다 :)
