### ISSUE TITLE
P71 HelloResponseDto 클래스명 오타 

### ISSUE THREAD

**Issue by Rok93** [jojoldu/freelec-springboot2-webservice#37]
본문에서 (그림2-27 바로 위) 이 패키지에 HelloReponseDto를 생성합니다. 라고 적혀있고 
그림 2-27에서는 HelloResponseDto 클래스를 생성했네요!  

단순한 오타인것 같습니다. 아마 본문의 글이 's'를 빼먹은 단순한 오타인것 같지만 !! (글 읽는데에는 문제가 없었습니다) 혹시나 싶어 글 남깁니다. 

현재 책 읽으면서 많은 도움 받고있습니다. 완전히 제것으로 만들어서 다른 웹사이트도 만들어보고싶습니다.

**Comment by jojoldu** [comment]
@Rok93 헉 제보 감사합니다 :)
s가 있는게 맞습니다 :)
책이 도움이 되셨다니 정말 다행이네요 ㅎㅎㅎ;; 마지막까지 재밌게 봐주세요!
