### ISSUE TITLE
[오류] p.383 /profile 로 접속하면 oauth 인증하라고 뜹니다

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#379]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: SecurityConfig 클래스에 "/profile" 추가하고 유닛테스트 전부 통과했는데도 배포후에 /profile 주소로 접속하면 oauth 인증 화면이 계속 뜹니다. 네이버, 구글에 8080뺀 주소도 전부 등록했습니다

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/zhtmr/freelec-springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/48509269/80272131-b46d4b00-8701-11ea-844d-8dc05eaac65d.png)

**Comment by zhtmr** [comment]
자체해결했습니다.
deploy.sh 에 현재 구동중인 애플리케이션 이름이 잘못되어 있어서 찾지못하는 문제였습니다

**Comment by SK9604** [comment]
@zhtmr 혹시 어떤 deploy.sh 에 어떤 부분을 고치셨는지 여쭤봐도 될까요?
