### ISSUE TITLE
P.146 오타

### ISSUE THREAD

**Issue by seongho89** [jojoldu/freelec-springboot2-webservice#38]
안녕하세요. 1쇄 구독자입니다. 
코드설명에 
1) {#posts}} 
라고 쓰여져 있는데요. {{#posts}} 가 아닐까 합니다.

2) {id}} 등의 {{변수명}} 
이것도 {{id}} 가 아닐까 하네요.

**Comment by jojoldu** [comment]
@seongho89 네! 맞습니다
{{ << 이게 워드파일로 변환하는 과정에서 생략된것 같습니다 ㅠ 
제보 감사합니다!
