### ISSUE TITLE
[오류] p.396 무중단 배포가 계속 8081 포트로만 배포가 됩니다

### ISSUE THREAD

**Issue by zhtmr** [jojoldu/freelec-springboot2-webservice#381]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:
![image](https://user-images.githubusercontent.com/48509269/80500659-69756100-89a9-11ea-9c61-4a1c093051bd.png)

배포를 계속해봐도 8081로만 배포가 됩니다. 다시 배포하면 8081에서 실행중인 애플리케이션 종료하고  다시 8081로 배포됩니다

/profile 주소로 들어가도 계속 real 만 나오는데 원래 이런가요?? real1, real2 번갈아가면서 나와야 되는거 아닌가요?
![image](https://user-images.githubusercontent.com/48509269/80500929-c8d37100-89a9-11ea-9035-4fe9d2c0b6b7.png)

현재 실행중인 애플리케이션도 step2에 있는거하고 step3에 있는거 이렇게 각각 하나씩 실행중으로 뜹니다...
![image](https://user-images.githubusercontent.com/48509269/80501487-747cc100-89aa-11ea-9636-1285889d28d0.png)

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/zhtmr/freelec-springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by zhtmr** [comment]
자체해결했습니다. 
application.properties 에 include=real 되어있던거를 include=oauth로 바꾸고 
ec2 재부팅해서 step2에서 실행중인 어플 종료시키고 다시 배포 두번하니까 real1, real2 번갈아가면서 연결됩니다.
![image](https://user-images.githubusercontent.com/48509269/80527292-1a422700-89cf-11ea-9f95-bf4a4beb0ed2.png)

**Comment by kimingyo071** [comment]
ec2 재부팅 해서 step2에서 실행중인 어플 종료는 어떻게 하셨나요?
