### ISSUE TITLE
[오타 제보] p142.페이지 

### ISSUE THREAD

**Issue by ehj0529** [jojoldu/freelec-springboot2-webservice#388]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

index.js  스크립트작성  마지막 부분 

index.init();  이 있어 js 오류가 발생되어 게시글등록 버튼이 무반응이었네요.

main.init(); 으로 수정 후 정상 등록 되는것 확인 하였습니다.

* as-is (오타):
index.init(); 
* to-be (교정):
main.init();

**Comment by yjaeseok** [comment]
개인적인 생각으로는 142 page의 main.init() 보다는 141 page의 변수명이 변경되는 게 좀더 좋은 것 같습니다. main이라는 이름이 갑자기 나오는게 어색한 것 같아요.

as-is
```
var main = {
 ...
}
index.init();
```

to-be
```
var index = {
 ...
}
index.init();
```

**Comment by yjaeseok** [comment]
위와 비슷한 내용이 153, 154 페이지에도 나오는군요! 
여기서는 main.init(); 을 하고 계신것을 보니.. @ehj0529 님께서 의견주신대로 main으로 수정되어도 될것 같습니다

**Comment by ehj0529** [comment]
변수명은 크게 상관은 없을거 같고 선언과 초기화의 변수가 달라 저와 같이 초보로 따라하는 경우는 좀 혼란이 있을수 있어서 어느쪽이든 수정이 되면 될듯 합니다.

**Comment by jojoldu** [comment]
@yjaeseok 님 제보 감사합니다! 해당 오타는 3쇄에 적용되었습니다 오타 제보 정말 감사합니다 ㅠ
@ehj0529 님 불편드려서 정말 죄송합니다 ㅠ 말씀하신대로 처음 시작하시는 분들께서는 오타인지 아닌지 인지하기가 어려운데 오타를 내서 정말 죄송합니다 ㅠ

**Comment by yjaeseok** [comment]
감사합니다 :)
