### ISSUE TITLE
p.153 오타

### ISSUE THREAD

**Issue by enhakkore** [jojoldu/freelec-springboot2-webservice#39]
안녕하세요:)
(#38)과 비슷한 오타가 p.153에도 있어서 제보드립니다.

코드설명 ①에 {post.id}} 라고 되어있는데 { 가 하나 빠진 것 같습니다:)

좋은 책 만들어 주셔서 감사합니다!

**Comment by jojoldu** [comment]
@enhakkore 아고 감사합니다 :)
{{ << 로 들어간 부분들이 다 하나씩 빠졌네요 ㅠㅠ
책 잘 봐주셔서 정말 감사합니다 ㅠㅠ
