### ISSUE TITLE
[프로젝트 환경 점검] Gradle 버전 체크 질문

### ISSUE THREAD

**Issue by Joonsawon** [jojoldu/freelec-springboot2-webservice#395]
안녕하세요.

제 intelliJ 버전(2020.1.1)이 너무 높아서 그런지 설명해주신 것과 차이가 많아서 질문드립니다.

![스프링부트 책 질문 p 0 초기설정](https://user-images.githubusercontent.com/65351077/81942590-4697ad80-9635-11ea-9e67-fd32f078a222.png)

제가 생성한 프로젝트 하위 항목에는  gradle-wrapper.properties 파일이 없어서 버전을 체크하지 못했습니다.

느낌상으로는 6.1버전인 것 같은데

alt+F12 로 터미널까지는 열었는데

![스프링부트 책 질문 p 0 초기설정2](https://user-images.githubusercontent.com/65351077/81942754-81014a80-9635-11ea-85e3-e4135134c3b4.png)

gradlew 명령어를 인식하지 못하네요.

무엇이 잘못된걸까요?

감사합니다!

**Comment by hyunah-kim** [comment]
저도 같은 현상이 있었고 아래와 같이 수행해서 해결했습니다.
올바른 해결방법이 아니라면 코멘트 부탁드려요.

1. gradle-wrapper 생성하기
Gradle 탭에서 build setup 내 init, wrapper를 실행하면
gradle/wrapper 폴더 하위에 gradle-wrapper.properties, gradle-wrapper.jar가 생성됩니다.

2. gradle-wrapper.properties 확인하기
저 같은 경우에는 gradle 6.x 버전이 깔려 있어서 터미널에서 아래 명령어를 입력했습니다.
저도 gradlew 명령어는 수행이 되지 않아서 gradlew 대신 gradle로 입력했습니다.

gradlew wrapper --gradle-version 4.10.2

**Comment by Joonsawon** [comment]
![image](https://user-images.githubusercontent.com/65351077/85499141-048e5e00-b61c-11ea-9583-14e54b75254c.png)

Gradle 탭에서 build setup 내 init, wrapper를 실행하면 

--> 이부분을 좀더 자세히 설명해주실 수 있을까요?

맨땅에 헤딩하듯이 하다보니 모르는게 너무 많네요 ㅜㅠ

**Comment by HyunAh-iia** [comment]
![image](https://user-images.githubusercontent.com/56185741/85640714-7f608300-b6c7-11ea-964e-adf921e64277.png)

1번 : gradle 탭 선택
2번 : build setup 하위에 init, wrapper를 실행

**Comment by Joonsawon** [comment]
답변 감사드립니다.

**1.** 보내주신 캡쳐본과 비교해보니 제 gradle 탭에 Task 폴더가 없더라구요.
다시 초기설정 값부터 확인해보니 project sdk 설정하지 않아서 그랬던 것 같습니다.

Java 1.8 설치 후 project sdk를 1.8로 설정해주니 gradle 탭의 Task 및 하위 폴더와 gradle/wrapper 폴더 하위에 gradle-wrapper.properties, gradle-wrapper.jar가 형성된 것을 확인할 수 있었습니다.

그래도 안되서 멘붕 왔었다가 환경변수 설정 해주니 잘 작동됬습니다 ㅜㅠ

![image](https://user-images.githubusercontent.com/65351077/85658734-9e264000-b6ee-11ea-942d-980783c26887.png)

몇달만에 해결한건지..ㅜㅠ 감사합니다!

**Comment by sunyoong** [comment]
진짜 감사합니다 ㅠㅠ 저도 저것땜에 이틀을 고생했는데.... 덕분에 해결했습니다 ㅠㅠㅠㅠ 감사합니다ㅠㅠㅠㅠㅠㅠ
