### ISSUE TITLE
P74 AssertJ 설명 부분 오타

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#4]
안녕하세요! P.74

QR코드 옆 assertJ의 자세한 설명 참고 부분에  

백기선님의 유투브 'ssertJ가 JUnit의....' 로 **a**가 빠져있습니다.  

사소한 오타라 조심스럽게 공유드립니다.

**Comment by jojoldu** [comment]
@RATSENO 헛! 제보 감사합니다 ㅠㅠ

**Comment by RATSENO** [comment]
아닙니다! ㅎㅎ 블로그 보며 많은 도움을 얻어서 
조금이라도 보탬이 되고싶습니다.
추가 오타가 보이면 Issues 올려드리면 될까요??

**Comment by jojoldu** [comment]
@RATSENO 아고 그럼 너무나 감사드리죠 ㅠㅠ
정말 감사드립니다!
