### ISSUE TITLE
[오타 제보] p.389

### ISSUE THREAD

**Issue by monkeyDugi** [jojoldu/freelec-springboot2-webservice#408]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

### 오타

* as-is (오타): 
ABSDIR=$(dirname $ABSPATH) 이전에 코드 한 줄이 없음

* to-be (교정):

ABSPATH=$(readlink -f $0) -> 추가
ABSDIR=$(dirname $ABSPATH)

**Comment by jojoldu** [comment]
@monkeyDugi 제보 감사합니다 :) 해당 내용 4쇄에 반영 되었습니다!
다시한번 감사드려요!
