### ISSUE TITLE
p101. 비지니스 로직 처리에 대한 궁금증

### ISSUE THREAD

**Issue by evan-hwang** [jojoldu/freelec-springboot2-webservice#41]
[블로그에 올렸던 질문을 옮겨 왔습니다.]

너무 초보적인 질문이어서 죄송합니다! 책에서 비즈니스 로직을 도메인(Entity 클래스)에 담아야 한다는 말씀은 너무나 이해가는데, 혹시 redisTemplate를 사용하는 코드는 어디에 넣으시나요? persistence 레이어 접근이라 Service에 넣어야 할 것 같기도 하고 자세한 로직은 도메인(Entity 클래스)에 담아야 할 것 같기도 해서 헷갈려 질문드려봅니다.

**Comment by jojoldu** [comment]
@id1992 질문 옮겨주셔서 고맙습니다 :) 
redisTemplate은 persistence 레이어 접근자이긴하지만, 
실질적인 외부와의 접점이 있는 영역이라 도메인 레이어에 두진 않습니다. 
도메인 레이어에서 비지니스 로직을 다 수행후 최종 결과값을 redisTemplate이 받아서 반영하는 형태로 가야하기 때문에 서비스 레이어에 두시면 될것 같습니다 :)
