### ISSUE TITLE
[오류] p.210

### ISSUE THREAD

**Issue by NIck0526** [jojoldu/freelec-springboot2-webservice#411]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 네이버 로그인버튼 후 동의 화면 까지 잘 작동하나 그 이후에 에러가 발생합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/NIck0526/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![K-001](https://user-images.githubusercontent.com/31129605/83969162-47a4bd80-a909-11ea-8c6c-5296cf900980.png)

![K-002](https://user-images.githubusercontent.com/31129605/83969163-4c697180-a909-11ea-81bf-bc0ad6e65deb.png)

아직 미숙하지만 책 보면서 공부하고 있습니다. 감사합니다.

**Comment by MinKeumKim** [comment]
지금은 해결하셨는지 모르겠지만~저도 같은 에러가 나서요 ㅎㅎ

**Comment by NIck0526** [comment]
답변 감사합니다. 해당 properties 에서 오타가 있던것 같더라고요 ㅜㅜ..
그 부분에서 에러가 나서 같은 오류가 난것 같네요!
