### ISSUE TITLE
[오류] p.298 테스트 오류

### ISSUE THREAD

**Issue by ssunaa** [jojoldu/freelec-springboot2-webservice#415]
### 어떤 오류인가요?

오류설명:

EC2에서 ./gradle2 test 실행시 오류가 발생합니다.
처음에 오류가나서 application-oauth.properties 파일이 누락된것같아 다시 push 후에 pull 하고 진행하였습니다.
그런데 다른 오류가 나는데 어떤 오류인지 감이 안옵니다.
코멘트 주시면 감사하겠습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/ssunaa/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/10174272/84172029-77dd8f00-aab6-11ea-9664-9490ad3cb247.png)

**Comment by ssunaa** [comment]
[cannot allocate memory error]

구글링으로 찾아보니 AWS에서는 초기에 SWAP메모리를 디폴트 0으로 잡아준다하여
발생한 문제인것같습니다. 

(free -h 로 swap 메모리 확인 할것)
아래의 사이트를 참고하였습니다.
https://aws.amazon.com/ko/premiumsupport/knowledge-center/ec2-memory-swap-file/

문제없이 빌드가 잘 되네요.

**Comment by lillywind** [comment]
저도 SWAP메모리를 디폴트 0 문제였네요. 큰 도움이 되었습니다. 감사합니다!
