### ISSUE TITLE
[오타 제보] p.206~207

### ISSUE THREAD

**Issue by kbk456** [jojoldu/freelec-springboot2-webservice#418]
### 오타
registration, provider 설정에서
- 하이픈이 _ 언더바로 표기된것이 일부 있음

* as-is (오타): 
spring.security.oauth2.client.registration.naver.authorization_grant_type=authorization_code
spring.security.oauth2.client.provider.naver.authorization_uri=https://nid.naver.com/oauth2.0/authorize
spring.security.oauth2.client.provider.naver.token_uri=https://nid.naver.com/oauth2.0/token
spring.security.oauth2.client.provider.naver.user_name_attribute=response
* to-be (교정):
spring.security.oauth2.client.registration.naver.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
spring.security.oauth2.client.provider.naver.user-name-attribute=response

**Comment by jojoldu** [comment]
@kbk456 님 제보 감사합니다 👍 
현재 예제에서는 -와 _가 구분없이 동일하게 작동하기 때문에 오타로 보기는 어려울것 같습니다 :)
제보 다시한번 감사드립니다!
