### ISSUE TITLE
[오류] p.193에 나오는 403 (권한거부)에 대한 질문입니다.

### ISSUE THREAD

**Issue by JYPs** [jojoldu/freelec-springboot2-webservice#419]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 오류는 아니고 질문입니다.

현재 210p 네이버 로그인까지 실습을 진행 하였습니다.

책대로 진행 하였고 193p에서 로그인 이후에 게시글 등록을 하면 403 권한거부 에러가 발생하고 이후  h2-console에서 update 쿼리를 통해서 권한 부여 후 403 권한거부 에러를 제거하는데 혹시 이후의 실습을 진행하면 자동으로 게시글 등록시 403 권한거부 에러가 없애는 
코드로 개선? 변경을 하는지 지금 이 시점에서 궁금해서 질문을 드립니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/JYPs/springBoot_jyp_v1.git

### 오류 로그

어떤 오류인지 

> [캡쳐해주세요.]
![캡처](https://user-images.githubusercontent.com/47133194/85031997-46ea1200-b1ba-11ea-8bd4-28025addc4fe.PNG)

**Comment by YoungJunSohn** [comment]
아닙니다.
저도 공부하는 입장이지만 저도 같은 고민을 했고 해결한 경험을 바탕으로 말씀드리자면
책대로 그대로 만들면 만든대로 계속 console에 데이터를 수정해주어야 했어요
만약 작성자분이 로그인 시 바로 글을 작성할 수 있도록 하고 싶으시다면, 로그인 시 부여되는 권한을 GUEST가 아니라 USER로 변경하시면 됩니다.

**Comment by JYPs** [comment]
같은 고민자 분이 있었군요 네. 일단 책 후반부를 계속 봤는데 제가 생각한 부분에 대한 내용은 없더군요 답변 감사합니다. 일단 USER로 바꾸고 좋은 방법을 계속 생각해봐야겠네요!
