### ISSUE TITLE
p.299 deploy.sh 생성경로 오타

### ISSUE THREAD

**Issue by siathus** [jojoldu/freelec-springboot2-webservice#42]
책 잘 보고 있습니다!

다름이 아니라 299페이지 14번째 줄

vim ~/app/**git**/deploy.sh를

바로 윗 줄에 쓰여진 대로 
vim ~/app/**step1**/deploy.sh로 바꿔야 될 것 같습니당

**Comment by jojoldu** [comment]
@siathus 아고!! ㅠㅠ 제보 감사합니다!
