### ISSUE TITLE
[오류] p.357 배포오류

### ISSUE THREAD

**Issue by kimjeongae** [jojoldu/freelec-springboot2-webservice#420]
### 어떤 오류인가요?

오류설명: .travis.yml 코드 수정하고 appspec.yml  파일을 업로드했습니다.
travis.ci에서 확인해보니까 에러가 나네요

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/kimjeongae/springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![제목 없음](https://user-images.githubusercontent.com/17589405/85209816-d982e080-b375-11ea-8e11-dd7f2076dfbe.png)

**Comment by kimjeongae** [comment]
다른분 올려주신것 보고 해결했네요, 자답입니다.

appspec.yml 파일에서 들여쓰기를 잘못했습니다.

<수정전-오류났을때>
version: 0.0
os: linux
files:
  - source: /
        destination: /home/ec2-user/app/step2/zip/
        overwrite: yes

<수정 후-정상처리됨>
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

**Comment by Yubron** [comment]
안녕하세요, 완전히 똑같이 에러가 발생하여 참고하려 하는데 
<수정 전> 과 <수정 후> 차이점을 모르겠습니다. 마크다운 문법으로 들여쓰기가 제대로 표기되지 않는거 같은데
혹시 한번 더 설명해주실 수 있을까요 ?

**Comment by kimjeongae** [comment]
![캡처](https://user-images.githubusercontent.com/17589405/90396910-fe73a580-e0d1-11ea-8588-95515231b4bc.PNG)



네^^ 수정전, 후가 차이가 안나게 표시되네요
위에 화면 캡쳐한 부분이 수정 후 상태입니다. 저는 들여쓰기를 캡쳐한 뒤로 하고 나서 오류 수정되어서요, 들여쓰기 확인해보시면 좋을거 같습니다^^

> 안녕하세요, 완전히 똑같이 에러가 발생하여 참고하려 하는데
> <수정 전> 과 <수정 후> 차이점을 모르겠습니다. 마크다운 문법으로 들여쓰기가 제대로 표기되지 않는거 같은데
> 혹시 한번 더 설명해주실 수 있을까요 ?

**Comment by ghost** [comment]
작성자님 감사합니다.
들여쓰기 하나하나 신경쓰면서 하는게 정말 중요하군요.
에러 수정과 소중한 교훈 알아갑니다.
