### ISSUE TITLE
[오류] p.96~97

### ISSUE THREAD

**Issue by tjrdlf08** [jojoldu/freelec-springboot2-webservice#421]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: save, deleteAll, findAll  method가 인식이 안됩니다..!!

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/tjrdlf08/springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![캡처](https://user-images.githubusercontent.com/29229774/85219159-58126900-b3dc-11ea-9913-2c1431ea80c2.PNG)

**Comment by alittlenation** [comment]
저도 인식이 안되는데 어떻게 해결하셨나요
PostsRepository 가 상속하고 있는 JpaRepository 들아가보면 deleteAll 함수가 없는데 버젼이 달라진건가..

**Comment by CHAHANS** [comment]
음 시간은 좀 오래 지났지만 관련해서 오류해결한것 이야기 드릴게요.
@cosmoscodee 님처럼 저도 별도 상속이 필요하다고 뜨는게 이상하다 생각했어요.
저희는 @Autowired를 붙였으니까요..

그래서 천천히 관찰했더니 패키지위치가 잘못된 것이 원인이었어요.
정상적으로 Autowired가 적용되지 않은것이지요.

비슷한 내용으로 이글을 본다면,
com.jojodu.book.springboot 아래에 domain.posts 순으로 잘 위치하고 있는지 확인해보세요.
위에 언급된 애러들이 함께 해결될 가능성이 높습니다.
