### ISSUE TITLE
[오류] p.210 네이버 로그인 추가하고 나서 서버에러 발생

### ISSUE THREAD

**Issue by jiho5993** [jojoldu/freelec-springboot2-webservice#428]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

210페이지에서 네이버 로그인까지 추가하고 시도해봤는데 사진과 같이 서버에러가 뜹니다...
구글 로그인도 해봤는데 역시 똑같은 오류가 발생합니다.
혹시나 해서 USER 테이블을 확인해봤더니 사용자 정보는 잘 들어가있었지만 계속 먹통입니다.
구글 로그인 추가만 했을때는 잘 실행되었지만, 네이버 로그인을 추가하고나니 아예 실행되지도 않네요

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/jiho5993/jojoldu-book

### 오류 로그
![image](https://user-images.githubusercontent.com/42717320/85533789-cb6de200-b64b-11ea-8efe-8d7e907be04c.png)

**Comment by jiho5993** [comment]
어디서부터 오류가 나는지 확인해봤더니 202p에 의존성 등록할 때부터 발생합니다...
![image](https://user-images.githubusercontent.com/42717320/85569199-4dbace00-b66d-11ea-8a12-967b4a3af964.png)

**Comment by Ryureka** [comment]
저도 비슷한 에러가 났었는데 알고보니 Session User.java 여기에 implements Serializable를 안적어서 발생했던 것 같습니다.
책으로는 p.187에 Session User.java 참조하셔서 Session User.java 부분 다시 확인해보시면 좋을 것 같습니다.
혹시나해서 깃허브 들어가 봤는데 그 부분이 안적혀있어서 혹시 도움 될까 싶어서 남깁니다.

**Comment by jiho5993** [comment]
@Ryureka 제 실수에 지적해주셔서 감사합니다 ㅠㅠㅠ 덕분에 잘 해결되었습니다!!!
@jojoldu 아 그리고 동욱님 좋은 책 내주셔서 감사합니다!!!
