### ISSUE TITLE
p198. 오타

### ISSUE THREAD

**Issue by evan-hwang** [jojoldu/freelec-springboot2-webservice#43]
다음과 같이 바꾸는 것이 읽기 편한 것 같아요!
LoginUserArgumentResolver가 스프링에서 인식할 수 있도록
-> LoginUserArgumentResolver **'를'** 스프링에서 인식할 수 있도록
-> LoginUserArgumentResolver가 스프링에서 인식 **'될'** 수 있도록

**Comment by jojoldu** [comment]
@id1992 오 네 좋은 제안 감사합니다 :)
편집부와 이야기해보겠습니다!
