### ISSUE TITLE
[오류] p.144 '등록' 버튼 관련 

### ISSUE THREAD

**Issue by heesunlee9** [jojoldu/freelec-springboot2-webservice#432]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: p 144 쪽 그림 처럼 양식에 내용을 넣고 등록 버튼을 눌러도 아무일도 일어나지 않습니다. 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/heesunlee9/freelec-springboot2-webservice

### 오류 로그 
딱히 에러로그가 나는 것은 아니고 '등록'버튼을 눌렀을 때 아무 동작이 없습니다. 

이 게시판에 p144 로 검색하면 나오는 두 개의 이슈는 모두 점검한 상태입니다. 

아예 아무 동작이 없는 걸 보면 뭔가를 안 한 것 같기는 합니다. 그런데 책 하고 똑같이 따라 타이핑 했기 때문에 어디가 원인인지는 모르겠습니다. 

개발자 도구로 확인해보면 footer.mustache 에 
<script src="index.js"></script> 에 문제가 있는 거 같기는한데 역시 무엇이 문제인지는 모르겠습니다. 

어떤 오류인지 캡쳐해주세요.

![image](https://user-images.githubusercontent.com/47602454/85857271-7caf7c00-b7f4-11ea-8438-57219b53e874.png)

감사합니다.

**Comment by kimhanui** [comment]
@heesunlee9 안녕하세요! 같은 문제로 헤메고 있는데 혹시 해결하셨나요??ㅠ    
저도 intellij에는 아무 로그도 안 뜨고 chrome 개발자도구로 보니 `footer`쪽 `<script src="index.js"></script>`에 문제 있는걸로 확인돼서요.

**Comment by kimhanui** [comment]
경로 설정 관련 문자오탈자 확인  
`/static/js.app`으로 패키지 잘못 생성  
-> `/static/js/app`으로 수정 후 정상 작동
