### ISSUE TITLE
[오타 제보] p.300 deploy.sh 코드 syntex 에러

### ISSUE THREAD

**Issue by Korea-subinpark** [jojoldu/freelec-springboot2-webservice#434]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타): CURRENT_PID=${pgrep -f ${PROJECT_NAME}.*.jar)

* to-be (교정): CURRENT_PID=$(pgrep -f ${PROJECT_NAME}.*.jar)

중괄호가 소괄호로 바뀌어야 합니다.

**Comment by SeongjinOliver** [comment]
감사합니다

**Comment by jojoldu** [comment]
@Korea-subinpark 앗 감사합니다! ㅠㅠ 해당 오타는 4쇄에 반영되었습니다! ㅠ
제보 감사합니다 :)

**Comment by aidsfintech** [comment]
오타수정 반영안된듯합니다.  21년 6월경에 책 구매했고, 책에
초판 1쇄 2019년 11월 29일
        4쇄 2020년   5월   6일
이라고 적혀있는데,
여전히 
as-is (오타): CURRENT_PID=${pgrep -f ${PROJECT_NAME}.*.jar)
네요. 저자님은 알아두시면 좋을듯합니다.

**Comment by chrisjhkim** [comment]
6쇄 구입하였습니다
6쇄에 반영 안되었습니다
