### ISSUE TITLE
[오류] p.203 session jdbc 설정 시 IllegalArgumentException 에러

### ISSUE THREAD

**Issue by davidch8784jazz** [jojoldu/freelec-springboot2-webservice#439]
오류설명: session jdbc 사용 설정을 하지 않으면 구글 로그인이 잘되나 session jdbc 설정하고 시도하면 에러가 발생합니다.

* Github URL: 
https://github.com/davidch8784jazz/hf2

### 오류 로그
![image](https://user-images.githubusercontent.com/51708752/86369081-ee863a80-bcb8-11ea-87aa-a2ab8ff2110e.png)

![image](https://user-images.githubusercontent.com/51708752/86369096-f34aee80-bcb8-11ea-95e5-91c602c677ee.png)

![image](https://user-images.githubusercontent.com/51708752/86369116-f7770c00-bcb8-11ea-87ec-12aabac7a0fc.png)

**Comment by SeongjinOliver** [comment]
저도 같은 현상이네요 해결하셨나요??

**Comment by davidch8784jazz** [comment]
> 저도 같은 현상이네요 해결하셨나요??

아뇨 ㅠㅠ 해결하신 분 있으면 알려주세요.

**Comment by dlwlgh9412** [comment]
SessionUser클래스부분에서 뒤에 implements Serializable 입력하셨나요??

**Comment by davidch8784jazz** [comment]
> SessionUser클래스부분에서 뒤에 implements Serializable 입력하셨나요??

헉... 감사합니다.  임플리먼츠를 안했었네요. ㅠㅠ 해결되었습니다!!
