### ISSUE TITLE
p.190,195 코드 오타

### ISSUE THREAD

**Issue by snh15978** [jojoldu/freelec-springboot2-webservice#44]
190 페이지 IndexController 클래스 수정하는 부분에서,

SessionUser user = (User) httpSession.getAttribute("user");
-> SessionUser user = (SessionUser) httpSession.getAttribute("user");

타입 캐스팅이 잘못됐습니다.

195 페이지도 가운데 인용문 부분에서 User -> SessionUser로 바뀌어야 될 거 같습니다.

**Comment by jojoldu** [comment]
@snh15978 님 제보 감사합니다 :)
https://github.com/jojoldu/freelec-springboot2-webservice/issues/22 와 같은 이슈라 중복 라벨로 등록하겠습니다!
고맙습니다!
