### ISSUE TITLE
63page 테스트 오류가 뭔지 모르겠습니다.

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#45]
![image](https://user-images.githubusercontent.com/49624922/70644436-58d87e80-1c86-11ea-98ca-e7ec951e4905.png)

환경은 window 10, intellij ultimate입니다.

gradle 4.12로 다운그레이드를 하였고, SETTIING에서 인코딩도 UTF8로 하였는데

빌드창에 한글 깨짐으로 나오는데 이유가 뭘까요 ㅜㅜ

**Comment by jinyeanseok** [comment]
![image](https://user-images.githubusercontent.com/49624922/70644638-c71d4100-1c86-11ea-9c82-c5fc708cbe2f.png)

code 입니다.

**Comment by jinyeanseok** [comment]
그리고 혹시나 해서 영어로 실행해보았는데 같은 오류가 나왔습니다.

**Comment by jojoldu** [comment]
@jinyeanseok 님 안녕하세요 :)
질문 감사합니다.
음 일단 제가 봤을떄 404 에러가 발생하는 것은 URL주소가 잘못되었기 떄문인데요.

![image](https://user-images.githubusercontent.com/7760496/70669416-b0441200-1cb9-11ea-9e41-31ce9697a849.png)

200 (OK) 를 기대했지만, 404 (Not Found Exception)이 발생한 케이스 라서 호출하시는 URL주소를 확인해보시면 좋을것 같습니다.
지금 보면 호출 주소가 ```hello``` 이신데,
```/hello```가 되어야하지 않을까 싶습니다 :)

**Comment by jojoldu** [comment]
그리고 한글이 꺠지는 것은 스프링 설정의 문제라기 보다는 IntelliJ의 문제로 보이는데요 :)

아래와 같이 VM Option 페이지로 이동해보셔서

![image](https://user-images.githubusercontent.com/7760496/70669634-45dfa180-1cba-11ea-9d5d-8949422c032d.png)

아래 옵션이 있는지 확인해보시겠어요?

![image](https://user-images.githubusercontent.com/7760496/70669652-53952700-1cba-11ea-8383-1000c637e12d.png)

```
-Dfile.encoding=UTF-8
```

**Comment by jinyeanseok** [comment]
감사합니다 말씀하신대로 다 해본결과 UTF-8 설정은 되었는데 테스트가 아직 안되네요 ㅜ

죄송하지만 한번 더 봐주실수 있을까요?

![image](https://user-images.githubusercontent.com/49624922/70684048-1fd0f600-1ce8-11ea-91be-9ba71670c6b4.png)


![image](https://user-images.githubusercontent.com/49624922/70684010-ec8e6700-1ce7-11ea-86ee-780ca51ade87.png)


에러를 보았는데 위 그림 속 HelloControllerTest 30번째 줄
.andExpect(status().isOk()) 이쪽에서  에러가 걸리는거 같습니다

해결방법 알려주시면 감사하겠습니다!

**Comment by jinyeanseok** [comment]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

이 에러도 발생하는데

그레이들 4.12버전으로 다운그레이드 하였는데 이유를 모르겠습니다 ㅜㅜ

**Comment by jojoldu** [comment]
@jinyeanseok 님 :)
제가 만드신 프로젝트를 확인해보았는데요 :)
패키지가 아래처럼 되어있으시네요!

![image](https://user-images.githubusercontent.com/7760496/70686766-a25db380-1cf0-11ea-8f6d-bc63bc76a9a0.png)


SpringBoot를 비롯해 스프링 프로젝트들은 **프로젝트의 모든 Controller**를 자동으로 읽어오지 않습니다.
@SpringBootApplication 이 있는 위치를 기준으로 가져옵니다.
현재 프로젝트에 @SpringBootApplication는 com/jojoldu/book/springboot 에 있는데
HelloController는 web 패키지에 있으니 당연히 못읽어오게 됩니다.
web 패키지를
com/jojoldu/book/springboot 아래에 두셔서
com/jojoldu/book/springboot/web/HelloController가 되면 정상적으로 될거에요!

**Comment by jinyeanseok** [comment]
정말 감사합니다 ㅜㅜㅜ 오랫동안 구글링해보며 다하다가 
말씀하신대로 하니까 됐습니다.
제가 위치설정을 실수 했군요 ㅜ 
질문에 빠르게 답해주셔서 정말 감사합니다!
