### ISSUE TITLE
[오류] p210 NAVER와 GOOGLE 로그인 후 index.js 페이지로 넘어가네요.

### ISSUE THREAD

**Issue by LEE-JANGWO** [jojoldu/freelec-springboot2-webservice#452]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: naver와 google login api 연동해서 로그인 하면 resource/static/js/app/index.js 페이지 화면이 나옵니다.
google login api 연동하고 했을 떄는 안떴는데,  naver login api 연동 후에는 google 과 naver 둘다 resource/static/js/app/index.js 
의 화면이 나오네요. 주소넘기는게 잘못된거라 생각해서 다 찾아봤는데.. 제 눈에는 딱히 보이지가 않아서 어느부분을 봐야하는지 부탁드릴게요.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 
https://github.com/LEE-JANGWO/JPAboard

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/52903548/87762964-e1d41b80-c84e-11ea-8c31-42396c0cbb55.png)

**Comment by ssooya90** [comment]
저도 그러네요 ㅠㅠ

**Comment by mangdo** [comment]
이거 지금 저도 그런데 혹시 어떻게 해결하셨나요?ㅜㅜ
+) 해결했습니다!
혹시 같은 오류 있으신 분들 SecurityConfig.java 파일 확인해주세요!
