### ISSUE TITLE
[Google Login 사용자명 출력 p.190

### ISSUE THREAD

**Issue by sangwoo-98** [jojoldu/freelec-springboot2-webservice#459]
### 어떤 오류인가요?
구글 로그인이 세션을 초기화했을 때는 로그인 화면으로 넘어가나, index.mustache 에서 `IndexController`에서 `Model` 객체에 추가한 loginUserName을 참조하지 못하는것 같습니다. 
```java
@GetMapping("/")
    public String index(Model model) {
        model.addAttribute("posts", postsService.findAllDesc());

        SessionUser user = (SessionUser)httpSession.getAttribute("loginUser");
        if(user != null) {
            System.out.println("user is not null");
            model.addAttribute("loginUserName", user.getName());
        }
        else {
            System.out.println("user is null");
        }
        return "index";
    }
```

위와 같이 디버깅용 코드를 작성했는데, Login 버튼 클릭 시 콘솔에 `user is null`이 계속 출력됩니다.

### 프로젝트 주소
https://github.com/ssura1/Study/tree/master/Spring%20Boot

**Comment by ssura1** [comment]
이틀동안 책 코드와 이 레포에 있는 코드를 비교하면서 다 확인해봤으나 오류 원인을 찾지 못했습니다.. 
API Key나 `*.gradle`, 그리고 `*.properties` 파일도 몇번이고 다시 봤습니다..
