### ISSUE TITLE
(1쇄 p.111) Posts 등록 API 테스트 결과

### ISSUE THREAD

**Issue by TDCIAN** [jojoldu/freelec-springboot2-webservice#46]
안녕하세요 개발자님!
1판 사서 열심히 따라 치고 있었는데 
p.111 그림 3-15 Posts 등록 API 테스트 결과가 책이랑 다르더라구요...ㅜㅜ
![image](https://user-images.githubusercontent.com/52792962/70673554-4847f880-1cc6-11ea-8095-d8e54d434571.png)
이것은 제가 작성한 코드와 테스트 결과입니다.
![image](https://user-images.githubusercontent.com/52792962/70673665-9ceb7380-1cc6-11ea-9501-0cfc32251833.png)

이것은 개발자님께서 올려주신 코드입니다.

개발자님께서 깃허브에 올려주신 코드를 확인해보니 책에 나와 있는 코드하고 다르던데

앞으로도 그냥 책보다는 깃허브에 있는 코드를 보고 따라하는 것이 맞을까요?ㅜㅜ
따라가다가 갑자기 안 되니까 어느 것을 따라가야 할 지 모르겠네요ㅜㅜ

**Comment by enhakkore** [comment]
(#6) 전에 올라왔던 이슈인 것 같습니다:)

실습하다가 막혔을 때 답답함을 알기에 답변남깁니다ㅎㅎ

**Comment by TDCIAN** [comment]
> (#6) 전에 올라왔던 이슈인 것 같습니다:)
> 
> 실습하다가 막혔을 때 답답함을 알기에 답변남깁니다ㅎㅎ

우왕 감사합니다!

**Comment by jojoldu** [comment]
@enhakkore 답변 감사합니다! :)

**Comment by TDCIAN** [comment]
> @enhakkore 답변 감사합니다! :)

개발자님
책 보다가 뭔가 안 맞는다 싶으면 개발자님께서 올려주신 깃허브 코드를 보는 것이 가장 정확 할까요?

**Comment by jojoldu** [comment]
@TDCIAN 아고 죄송합니다 ㅠ
일단은 현재 이 코드는 모두 **최종 완료 상태의 코드**입니다.
각 챕터별로 쓰기엔 무리가 있습니다.
그래서 지금처럼 
1) 이슈로 올려주시거나
2) 기존에 올라온 이슈들을 검색해보시는것을 추천드립니다.

**Comment by TDCIAN** [comment]
> @TDCIAN 아고 죄송합니다 ㅠ
> 일단은 현재 이 코드는 모두 **최종 완료 상태의 코드**입니다.
> 각 챕터별로 쓰기엔 무리가 있습니다.
> 그래서 지금처럼
> 
> 1. 이슈로 올려주시거나
> 2. 기존에 올라온 이슈들을 검색해보시는것을 추천드립니다.

아하 빠른 피드백 감사합니다 다시 열심히 해보겠습니다!

**Comment by jojoldu** [comment]
@TDCIAN 넵 고맙습니다 :)
