### ISSUE TITLE
[궁금한점] p.134 테스트는 통과하는데, 8080 포트로 접속을 하면 해당 페이지가 뜨지 않습니다

### ISSUE THREAD

**Issue by JihoonNa** [jojoldu/freelec-springboot2-webservice#465]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

안녕하세요!! 책을 보고 재밌게 공부를 해나가고 있습니다!
실습을 따라하던 중 머스테치를 활용하는 부분에서 테스트는 통과하였는데,
8080포트로 접속을 하면 책의 내용처럼 스프링부트로 시작하는 웹서비스가 출력되지 않고

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Jul 27 20:46:58 KST 2020
There was an unexpected error (type=Not Found, status=404).
No message available

라는 내용이 출력됩니다.

오타를 열심히 찾아보았지만 찾지 못하였고

p.131에 index.js파일이 있는 것 같던데 혹시 해당 파일을 작성해야 뜨는건가요?

책의 설명에 의하면 index라고 return을 하면 그 뒤에 .mustache가 자동으로 붙는다고 말씀하신걸로 보아서는 index.js가 없어도 되는 것 같던데.. 너무 간단한 실수 일 수 있지만 다른 질문들에서도 찾아볼 수 없어서 여쭤보게 되었습니다 읽어주셔서 감사합니다!

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/JihoonNa/springbootstart

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![image](https://user-images.githubusercontent.com/15344075/88542289-26cb2f80-d051-11ea-83b8-7fc94154ad35.png)

![image](https://user-images.githubusercontent.com/15344075/88542335-3a769600-d051-11ea-9edd-64a0265b3a6e.png)

![image](https://user-images.githubusercontent.com/15344075/88542367-45c9c180-d051-11ea-9026-a31176021377.png)

**Comment by jojoldu** [comment]
@JihoonNa s님 안녕하세요 :) 
이미 이유를 찾으신것 같아서 해당 이슈는 종료하겠습니다 ^^;

![image](https://user-images.githubusercontent.com/7760496/90329028-33053580-dfdc-11ea-8731-b07ce32bc6dc.png)
