### ISSUE TITLE
[오류] p.283 Database Navigator 플러그인을 검색해도 찾을 수 없습니다.

### ISSUE THREAD

**Issue by yeongunheo** [jojoldu/freelec-springboot2-webservice#466]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: p283에서 마켓플레이스에서 Database Navigator 플러그인을 검색해도 찾을 수 없습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 깃허브 주소가 필요없기에 생략합니다.

### 오류 로그

어떤 오류인지 캡쳐해주세요.

### 해결 방법

인텔리제이 커뮤니티를 2020.1.2 이후 버전으로 업데이트해서 생긴 문제였습니다. 2020.1.2 버전으로 롤백하면 플러그인에 검색할 시 Database Navigator 플러그인을 찾을 수 있습니다. 이와 같은 원인으로 업데이트 후 .ignore 플러그인이 새로운 버전과 맞지 않았습니다.

**Comment by syleemk** [comment]
저도 같은문제입니다

**Comment by Highjune** [comment]
저도 같은 문제입니다. 유료 ultimate 버젼을 쓰고 있는데 말씀하신 플러그인이 없네요 ..

**Comment by syleemk** [comment]
@Highjune 저도 ultimate버전 쓰고있는데 유료버전은 플러그인 설치할 필요없이 database tool이 기본적으로 제공되네요! 이거 사용하면 되요 ㅎㅎ

**Comment by Highjune** [comment]
@syleemk 찾았어요 감사합니다!
혹시 모르시는 분들 있을까봐 적어둡니다.

'database tools and sql' 이라는 기본 플러그인(ultimate버전시)이며 사용은
view - tool windows - database 입니다.

**Comment by jojoldu** [comment]
@yeongunheo 님 안녕하세요!
현재 인텔리제이 데이터베이스 네비게이터 플러그인이 2020.2 버전을 지원하지 않습니다 ㅠ
그래서 사용하실려면 2020.1.4 이하의 버전으로 사용하셔야 할것 같습니다.

> 물론 인텔리제이 얼티메이트 버전은 젯브레인사의 DataGrip 기반이라서 모든 버전을 지원합니다.
