### ISSUE TITLE
[오류] p190 소셜 로그인 실행.

### ISSUE THREAD

**Issue by jokerKwu** [jojoldu/freelec-springboot2-webservice#467]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: #253 해결방법으로 해봤지만 에러 결과가 똑같아서 올립니다... 
아무리 찾아봐도 해결 방법을 못찾겠네요.
빈객체를 못찾는거 같아서 라인에서 쓰던 빈을 생성해봤더니 홈페이지가 정상적으로 작동되는 것을 확인만 한 상태입니다.
주석으로 처리한 부분처럼 구글이랑 네이버도 해줘야되는건지 궁금해서 글올려봅니다. ㅠ.ㅠ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/jokerKwu/springboot-webchatting

### 오류 로그

![ScreenClip](https://user-images.githubusercontent.com/35329247/89100476-2c01f300-d432-11ea-87e7-689afe687bba.png)

**Comment by jokerKwu** [comment]
추가적으로 완성된 소스코드 다운받아서 실행해도 똑같은 에러가 발생합니다..

**Comment by jojoldu** [comment]
@jokerKwu 님 안녕하세요!
책 내용과 다른 오타가 있으시네요 ^^

**google이 아니라 oauth를 쓰셔야 합니다**.

application-oauth.properties 를 호출한다는 의미이기 떄문입니다 ^^

![image](https://user-images.githubusercontent.com/7760496/90329226-b3786600-dfdd-11ea-9884-cc271a17a666.png)
