### ISSUE TITLE
질문 - save() vs Transactional

### ISSUE THREAD

**Issue by evan-hwang** [jojoldu/freelec-springboot2-webservice#47]
@Transactional에 대해 찾아보던 중 의문이 생겨 질문드립니다!

1.
JPA 엔티티를 업데이트할 때 Dirty Checking을 지원해 트랜잭션 안에서는 save를 명시적으로 호출하지 않아도 commit 시에 판단해서 업데이트해준다고 알고 있습니다.

```java
@Transactional
public Notice update(Long noticeId, String content) {
    Notice notice = noticeRepository.findById(noticeId).get();
    notice.setContent(content);
}
```
위의 코드와 아래의 코드의 차이가 뭔지 궁금합니다. (여러 repository를 접근하는 코드가 있을 시 Transactional을 명시해주지 않으면 해당 접근하는 코드마다 트랜잭션 단위가 설정되나 어노테이션을 선언하면 해당 메소드 내의 명령문을 원자적으로 처리해준다고 이해했는데 맞는 것인지..)

```java
public Notice update(Long noticeId, String content) {
    Notice notice = noticeRepository.findById(noticeId).get();
    notice.setContent(content);
    noticeRepository.save(notice);
}
```

2. 생성 코드에서 save를 하고 있는데도 Transactional을 붙이신 이유가 궁금합니다.
```java
@Transactional
public Long save(PostsSaveRequestDto requestDto) {
    return postsRepository.save(requestDto.toEntity()).getId();
}
```

3. 목록 조회 시 Transactional을 붙이면 조회 속도가 왜 개선되고 트랜잭션 범위를 유지해야 하는 이유는 무엇인지 궁금합니다!
```java
@Transactional(readOnly = true)
public PostsResponseDto findById(Long id) {
    Posts entity = postsRepository.findById(id)
            .orElseThrow(() -> new IllegalArgumentException("해당 사용자가 없습니다. id=" + id));

    return new PostsResponseDto(entity);
}
```

**Comment by jojoldu** [comment]
일단 오해를 하나 푸셔야하는데요 :)
JPA의 더티체킹은 **save를 대체하지 않습니다**

**영속성 컨텍스트에 포함된 엔티티들의 변경을 감지**하는 것입니다.
처음 만들어진 엔티티들은 아직 영속성 컨텍스트 대상에 포함되지 않습니다.

1) 트랜잭션 범위 내에서 save하거나
2) 트랜잭션 범위 내에서 save된 엔티티를 조회해온 경우

에만 해당됩니다.

1. 두 코드 모두 **테이블의 최종 상태는 동일**합니다.
다만, 객체의 관점에서 **난 내 상태를 변경했어**에서 **변경했지만 디비에도 반영은 또 따로 해줘야한단다** 가 2번의 코드입니다.
1번은 객체가 자기 할일만 하는 코드로 끝난 상태이고요.
그래서 객체지향적인 관점에서 2번은 사실 좋은 형태로 보긴 힘듭니다.

2. 2번은 트랜잭션이 없을 경우 **save하다가 잘못될 경우 롤백이 안되서 그렇습니다**
save할때 연관관계에 의해 다른 엔티티들도 save/update 되야 한다거나
여러 엔티티를 한번에 저장해야한다거나
단일 엔티티를 저장하지만 저장후 update가 한번더 이루어져야한다거나
등등 다양한 케이스에서 **전체 반영되거나 전체 취소**되는 상황이 필요합니다.

결국 **최종적으로 부분반영을 막기 위해** 사용합니다.

3. 일단은 트랜잭션 어노테이션이 없으면 ```@OneToMany```, ```@ManyToMany```와 같은 **레이지 로딩**이 필요한 엔티티들이 정상조회되지 않습니다.
JPA를 사용하다보면 부모-자식 관계 (@OneToMany)를 많이 사용하는데
이 옵션이 트랜잭션이 없으면 정상작동 하지 않습니다.
LazyInitializationException 가 바로 그런 경우입니다.
그래서 OneToMany나 ManyToMany와 같이 레이지 로딩을 지원하면서 롤백 기능이 없어 성능 향상이 어느정도 되어있는 readOnly 옵션을 사용한 것입니다.

**Comment by id1992** [comment]
아! 명확히 이해갔습니다!! 친절하게 답변해주셔서 너무 감사합니다 ^^!

**Comment by jojoldu** [comment]
@evan-hwang 넵 감사합니다 :) 이후에도 편하게 질문 남겨주세요!
