### ISSUE TITLE
[오류] p.307 스프링 세션 테이블이 인텔리제이에서 검색이 안되요.

### ISSUE THREAD

**Issue by rktldhkd** [jojoldu/freelec-springboot2-webservice#470]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명:RDS에 엔티티 테이블 생성하고 스프링 세션 테이블 생성하기위해 schema-mysql.sql 파일을 검색하는데, 해당 파일이 검색이 되지않습니다.(no files found) 뭐가 문제일까요??ㅠㅠ 프로젝트 실행해서 h2웹콘솔로 보면 SPRING_SESSION, SPRING_SESSION_ATTRIBUTES 테이블이 잘있고, 프로젝트도 에러없이 잘 수행되는데 뭐가 문제인지 모르겠어요 ㅠㅠ 
mysql.sql 로만 검색하면 파일 하나 나오는데 여기에는 logging_event_... 테이블밖에 없네요
인텔리제이 버전은 1.3 쓰고 있습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/rktldhkd/springboot2-webservice.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/16818176/89988661-d55ea980-dcba-11ea-8029-65b7ffcf7e67.png)
![image](https://user-images.githubusercontent.com/16818176/89988765-f8895900-dcba-11ea-89aa-3e7f3315c422.png)

**Comment by jojoldu** [comment]
@rktldhkd 님 안녕하세요!
음 일단 인텔리제이 2020.1.4 에서는 정상적으로 검색이 되고 있습니다!
아래처럼 All Places 로 검색하신것인지 한번 확인해보시겠어요?

![image](https://user-images.githubusercontent.com/7760496/90329095-9becad80-dfdc-11ea-9332-8318b2e95759.png)

**Comment by hwk0911** [comment]
이게 정답일진 모르겠는데 저도 같은 에러가 발생해서

build.gradle에 
    compile('org.springframework.session:spring-session-jdbc:2.1.6.RELEASE')
의존성을 추가해 해결했습니다.

**Comment by rktldhkd** [comment]
2버전대 쓰다가 검색안되서 1.3까지 낮췄는데 안나오더라고요ㅠㅠ 걍 책에 있는 create문으로 하드코딩했어요 ㅎㅎ 잘 되네요

**Comment by jammama** [comment]
똑같은 상황이었어서(h2에서 세션테이블도 잘 나타남)
build.gradle에서
compile('org.springframework.session:spring-session-jdbc')를 주석처리하고 reload, 
그리고 다시 주석 풀고 reload 했더니 거짓말처럼 나타나더군요
오히려 이후 gradle reload하고도 나타나지 않는 현상을 재현하지 못했습니다ㅎ..

**Comment by Belnut** [comment]
저도 동일한 문제가 있었는데 @hwk0911 님이 올려주신 방법으로 해결했습니다.
감사합니다.
