### ISSUE TITLE
[오류] p.298 ./gradlew test 실행 시 오류

### ISSUE THREAD

**Issue by BahngJH** [jojoldu/freelec-springboot2-webservice#472]
### 어떤 오류인가요?

오류설명:
EC2에서 ./gradlew test 실행 시 오류가 발생합니다. 실패가 뜨길래 인텔리제이 켜서 다시 테스트 돌려보면 모두 성공으로 나오고
중간에 어디서 잘못된건지 찾기가 너무 어렵네요ㅠ  

### 프로젝트 주소

* Github URL: https://github.com/BahngJH/aloneProjectWithAWS

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![1](https://user-images.githubusercontent.com/40817593/90019809-e2df5800-dce9-11ea-9467-42fd6ac72646.PNG)
![2](https://user-images.githubusercontent.com/40817593/90019815-e4a91b80-dce9-11ea-94a1-580c13c08ee6.PNG)

**Comment by Highjune** [comment]
저도 마찬가지네요.

**Comment by jojoldu** [comment]
@BahngJH @Highjune 님 안녕하세요
책에서도 언급하고 있지만, src/test/resources 에는 아래 링크처럼 application.properties가 있어야 합니다 ^^

https://github.com/jojoldu/freelec-springboot2-webservice/blob/master/src/test/resources/application.properties

**Comment by BahngJH** [comment]
아.. 해당 파일이 깃허브에 올라가 있는줄 알았네요 ㅋㅋㅋ감사합니다!

**Comment by JaeHyeonKim19** [comment]
로컬환경에서는 src/test/resources/application.properties없이도 테스트가 통과되는데 ec2환경에서는 fail하는 이유가 뭔지 알 수 있을까요??

#192 에서 언급하신바와 같이 책에서는 src/test/resources/application.properties를 설정해줘야 통과한다고한 테스트들이 로컬환경에서는 바로 통과가 되어 굳이 설정안해줘도 되겠다고 생각을 했는데, ec2환경에서는 또 통과가 안되네요. 환경으로인한 차이인거 같은데 정확하게는 어떤 이유때문인지 알 수 있을까요?
