### ISSUE TITLE
[오류] p.311 deploy.sh실행시 에러

### ISSUE THREAD

**Issue by Highjune** [jojoldu/freelec-springboot2-webservice#473]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보
찾아봤는데 같은 에러를 다룬 것은 없는 듯 합니다.

### 어떤 오류인가요?  git pull 오류?...

오류설명:  p309의 깃허브로 푸시까지는 다 성공했습니다. 그 후에 p309밑의 application-real-db.properties 와 p310의 deploy.sh 수정(real profile사용 위한) 까지 다 하고 p311에서 './deploy.sh' 를 실행하니 git pull에서 에러가 뜨고 'vim nohup.out' 를 실행해서 확인해보니 에러가 또 나왔습니다.

### 프로젝트 주소
https://github.com/Highjune/freelec-springboot2-webservice

* Github URL: https://github.com/Highjune

### 오류 로그
![application-real-dbproperties](https://user-images.githubusercontent.com/57219160/90269285-5f616a80-de93-11ea-9633-187da79a8122.jpg)
![deploysh](https://user-images.githubusercontent.com/57219160/90269329-6d16f000-de93-11ea-90a3-26f6847d66c9.jpg)
<img width="484" alt="deploy sh실행" src="https://user-images.githubusercontent.com/57219160/90269332-6e481d00-de93-11ea-977a-8d931082bae4.PNG">
<img width="950" alt="vimnohupout" src="https://user-images.githubusercontent.com/57219160/90269336-6e481d00-de93-11ea-9ad2-7be52e0d971d.PNG">

시도 및 상황 : intelliJ 에서의 git status 에는 add할 대상이 없고, 프로젝트 실행시 아무런 에러도 없이 tomcat도 잘 돌아갑니다.

그리고 vim 에서 git 명령어가 먹히지 않아서 deploy.sh 에서 제일 위 명령어인 git pull 이전에 git status 등 이런저런 명령어들로 시도 했지만 잘 되지 않네요 ㅠ.ㅜ

부탁드립니다! 감사합니다.

**Comment by jojoldu** [comment]
@Highjune 님 안녕하세요! 
인텔리제이에 변경 사항이 없다고 하여 EC2에 받은 코드가 변경사항이 없다고 볼수는 없습니다.
EC2에서 아래 명령어를 입력해보시면 @Highjune 님께서 **EC2에 클론 받고 EC2에서만 수정한 코드들이 있을 수 있습니다**
(아래처럼)

![image](https://user-images.githubusercontent.com/7760496/90328800-42837f00-dfda-11ea-9528-9e36d317f6e8.png)

깔끔하게 하실려면 clone 받으신 디렉토리를 다 삭제하시고 다시 해보시면 좋을것 같습니다.

이와 별개로 EC2에서 나온 에러 메세지만 보면 **세션 관련 정보**를 생성할수 없다고 나왔는데요 (보여주신 에러 메세지가 **nohup.out의 제일 하단**이 맞다면)
이는 아마도 Database 와 서버간 연결에 문제가 있기 떄문일겁니다.

1) DB에 세션 관련 테이블을 생성하지 않으셨거나 (SPRING_SESSION, SPRING_SESSION_ATTRIBUTES)
2) EC2에서 DB 연결이 아예 안되거나

위 2가지 문제중 하나로 추측 됩니다 :)

**Comment by Highjune** [comment]
확인했습니다!! 그런데 저는 ec2 에서는 git 명령어들을 독립적으로는 (스크립스 사용말고) 안 먹히더라구요!
.git폴더가 생성된 곳의 상위폴더에서 했는데도 안 먹혀서 확인을 할수가 없어서 그냥 repository 날리고 재클론 했습니다.

여튼 해결했습니다
감사합니다!

**Comment by Highjune** [comment]
완료
