### ISSUE TITLE
[오류] p.356~357 travis ruby version

### ISSUE THREAD

**Issue by Yubron** [jojoldu/freelec-springboot2-webservice#474]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: travis ci , s3, codeDeploy 연동이 실패합니다. appspec.yml 파일과 .travis.yml 파일 푸쉬 후
[
            Version 2 of the Ruby SDK will enter maintenance mode as of November 20, 2020. To continue receiving service updates and new features, please upgrade to Version 3. More information can be found here: https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/
]
travis 에서 이러한 오류로 deployment fail 이 뜨는데 이유를 못찾겠습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/Yubron/springboot

### 오류 로그

<img width="1024" alt="스크린샷 2020-08-16 오후 8 40 27" src="https://user-images.githubusercontent.com/42029230/90333444-cbadac80-e000-11ea-9929-38c7f360f27a.png">

비슷한 이슈(#420) 에 따르면 appspec.yml 파일 내 들여쓰기가 문제가 되었다고 하는데 깃랩에 저장되어 있는 appspec.yml 을 그대로
복붙도 해보았고 직접 작성도 해보았는데 도저히 이유를 모르겠습니다.

![image](https://user-images.githubusercontent.com/42029230/90333899-92773b80-e004-11ea-91b1-365f824cd563.png)

AWS CODE DEPLOY 에서는의 메세지는 이러합니다.

**Comment by Yubron** [comment]
자답합니다 마지막 사진에 힌트가 있었네요 !
CodeDeploy 환경구성에 Amazon EC2 인스턴스 설정을 잘못했었네요
태그가 중요한지 처음알았습니다

**Comment by Juyeon-Lee** [comment]
@Yubron 소름돋네요... 저는 이 이유는 아니겠지 하면서 다른거 막 삽질하면서 반나절을 보내다가
다시 이 글로 돌아와서 설마,,, 하면서 확인해보니까 저도 그래서 안되고 있었습니다!!!ㅜㅜ 감사해요!

**Comment by Yubron** [comment]
@Juyeon-Lee 
해결되었다니 다행이네요 ! 저 사실 깃허브에 댓글 달린게 처음이라 후다닥 뛰어왔습니다 ㅋㅋㅋㅋㅋ
앞으로 더 많은 자답을 남겨야겠어요 ! 남은 부분도 문제 없이 완결내시길 기원합니다 !

**Comment by jack2718-dr** [comment]
저도 같은문제인데 태그이름을 애플리케이션 이름으로 하는거 아닌가요? 저는 제대로 돼있는것 같은데 잘 모르겟네요 ㅠ

**Comment by leaf-hyeon** [comment]
@Yubron 좀더 정확히 설명해 주실수 있나요? ㅠㅠ

**Comment by Yubron** [comment]
@kssrcn 
시간이 꽤 지나서 정확히 기억나진 않는데요, EC2 > 인스턴스 들어가시면 하단에
세부정보, 보안, 네트워킹, ... , 태그 라고 있거든요
여기 태그에 Key : Value 값에 오타가 있었거나 , Value 값이 프로젝트 명인데 올바른 프로젝트 명으로 기입이 되어있는지
한번 확인해보세요 !
