### ISSUE TITLE
p.115 // when부분 HttpMehod.PUT 오타

### ISSUE THREAD

**Issue by JihyeHwang09** [jojoldu/freelec-springboot2-webservice#48]
p.115
```java 
// when
 ResponseEntity<Long> responseEntity = restTemplate.exchange(url, 
HttpMethod.PUT, requestEntity, Long.class);
```

HttpMethod.PUT으로 적혀있습니다. -> HttpMethod.POST로 정정 부탁드립니다:)

항상 블로그 잘 보고 있습니다. 책에 설명이 쉽게 되어 있어서 이해가 잘됩니다. 감사합니다!

**Comment by jojoldu** [comment]
앗? 이건 PUT이 맞습니다
업데이트용 컨트롤러이기 때문에 Controller에도 @PutMapping이 선언되어있고,
테스트에서도 HTTP 메소드인 PUT을 사용해야 합니다.

p.110 의 등록 컨트롤러 코드의 오타를 제보하시려는것이실까요?

https://github.com/jojoldu/freelec-springboot2-webservice/issues/13

**Comment by JihyeHwang09** [comment]
앗 제가 헷갈렸네요ㅜ 혼란을 드려서 죄송합니다ㅜ
