### ISSUE TITLE
[오류] p.108 postapicontrollertest

### ISSUE THREAD

**Issue by tedli94** [jojoldu/freelec-springboot2-webservice#480]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: postapicontrollertest의 posts_등록된다 메소드 실행시 
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost51510/api/v1/posts": localhost51510; nested exception is java.net.UnknownHostException: localhost51510
라면서 테스트가 통과되지 않습니다.
구글 검색시 HttpComponentsClientHttpRequestFactory가 없어서 그렇다고 하거나 방화벽에 막혀있다고 나오는데 전자의 경우 해당 버전에선 문제없을것 같고 후자의 경우 idea64는 앱에서 통과하게 되어있습니다. 프로젝트도 방화벽 풀어야하나요? 아니면 다른 방법이 있을까요?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/tedli94/spring00

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/45871656/90962692-e6928c00-e4ec-11ea-90fc-d5792cf54535.png)

**Comment by tedli94** [comment]
해결됬습니다 신경쓰게해서 죄송합니다

**Comment by hhhminme** [comment]
어떻게 해결한건가요? 저도 동일 에러 발생합니다.
