### ISSUE TITLE
[오류] p.345 ec2 재부팅 후 

### ISSUE THREAD

**Issue by jokerKwu** [jojoldu/freelec-springboot2-webservice#482]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

p345 교재보면서 진행도중 재부팅 후 putty 접속 시 네트워크 타임아웃이 발생해서 접속을 못하고 있습니다.

iam 역할추가하기 전까지만 해도 제대로 접속이 됐었는데 

이후 접속이 안됩니다.

무언가 조치를 취해야되나요?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/jokerKwu/springboot-webchatting

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![ScreenClip](https://user-images.githubusercontent.com/35329247/90982362-accf8d00-e5a1-11ea-942e-ed91b77c10d8.png)

**Comment by jokerKwu** [comment]
서버의 보안 그룹 설정에 의해 현재 위치에서 해당 서버에 접속이 블록된 경우로

해당 인스턴스에 설정된 보안그룹에

2가지 룰을 추가해줘서 해결했습니다.

**Comment by keunoh** [comment]
EC2 인스턴스에서 검사가 모두 완료된 다음 putty 접속하면 활성화됩니다. 즉, EC2 리부팅하시고 좀 기다리셔야해요
