### ISSUE TITLE
[오류] nginx 오류

### ISSUE THREAD

**Issue by jaelyangChoi** [jojoldu/freelec-springboot2-webservice#489]

**Comment by cjl0701** [comment]
> 기존에 올라온 질문이 아닌지 먼저 검색해주세요!
> 
> ## 가장 자주 나온 제보
> * [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
> * [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)
> 
> ### 어떤 오류인가요?
> 오류설명:
> 책으로 배운 내용을 활용해서 저만의 웹사이트를 만들고 무중단 배포까지 완료했습니다.
> 그런데 오랫만에 접속해보니 다음과 같은 에러가 떳습니다.
> ![image](https://user-images.githubusercontent.com/55947154/91859801-d4131200-eca5-11ea-890b-fd682fb4c229.png)
> 
> 그래서 로컬에서 서버를 켜서 localhost:8080으로 접속해보니 정상 작동합니다.
> 그리고 모바일로 접속했을 경우에도, 다른 친구의 컴퓨터로 접속했을 때도 정상 작동합니다.
> 얼마전에는 제 컴퓨터에서도 정상 작동했는데 말이죠..대체 왜 그럴까요?
> nginx에 뭔가가 바뀐걸까요?
> 코드는 건드린게 없는데 이전에 정상 작동하던 사이트가 갑자기 왜 이런걸까요?
> 
> 주소는 다음과 같습니다
> http://ec2-52-79-207-60.ap-northeast-2.compute.amazonaws.com/
> 
> ### 프로젝트 주소
> Github에 오류가 난 프로젝트를 올려주세요.
> **Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**
> 
> * Github URL: https://github.com/cjl0701/hibuddy-springboot2-webservice
> 
> ### 오류 로그
> 어떤 오류인지 캡쳐해주세요.
> nginx 관련 오류 로그를 어떻게 확인해야할지 모르겠습니다.
> 다음과 같은 명령어를 실행했을 때는 문제가 없습니다.
> ![image](https://user-images.githubusercontent.com/55947154/91867621-ce6dfa00-ecae-11ea-8bcf-175af0157d87.png)
