### ISSUE TITLE
P276 오타

### ISSUE THREAD

**Issue by seongho89** [jojoldu/freelec-springboot2-webservice#49]
중간에 8가지 나열(중복1개 포함)을 보면 전부 바로 표시되어 있는데요.
- character-set-client

라고 적혀있는데요.

아래 스크린샷에서 보면 언더바로 표시되어 있습니다.
character_set_client

aws 가보니 언더바가 맞는것 같아요.

**Comment by jojoldu** [comment]
@seongho89 넵 제보 감사합니다 :) 언더바 표기가 맞습니다!
