### ISSUE TITLE
[오류] p.364 도메인 입력

### ISSUE THREAD

**Issue by kimingyo071** [jojoldu/freelec-springboot2-webservice#495]
### 어떤 오류인가요?

오류설명: 
Travis CI와 CodeDeploy 성공까지 확인했습니다.
허나 도메인을 입력해보니 아래 사진과 같은 결과가 뜨네요
해결 방법이 있을까요?

### 프로젝트 주소
* Github URL: https://github.com/kimingyo071/freelec-springboot2-webservice

### 오류 로그
[도메인 입력 후 웹 화면 1번사진]
![그림1](https://user-images.githubusercontent.com/67263684/92385017-15933980-f14c-11ea-8d12-e4cc7f7a8aca.png)

[nohup.out 콘솔 로그 2번사진] - 드래그 부분에 warn이 있습니다.
![그림2](https://user-images.githubusercontent.com/67263684/92385022-16c46680-f14c-11ea-89db-c5a3e78f2218.png)

[nohup.out 콘솔 로그 3번사진] - 2번 사진에 드래그한 warn과 3번 사진의 초록 warn은 같은 부분입니다.
![그림3](https://user-images.githubusercontent.com/67263684/92385024-17f59380-f14c-11ea-9ae6-d82c2420333a.png)

[nohup.out 콘솔 로그 4번사진] - 3번과 4번 사진의 드래그한 Hibernate는 같은 부분입니다.
![그림4](https://user-images.githubusercontent.com/67263684/92385026-188e2a00-f14c-11ea-8d43-f6cccda08f61.png)

**Comment by JPWon-1** [comment]
어떻게 해결하셨는지 알 수 있나요?
