### ISSUE TITLE
[오류] p.99 쿼리로그 출력안됨/application.properties

### ISSUE THREAD

**Issue by musemy4** [jojoldu/freelec-springboot2-webservice#498]
기존에 올라온 질문인것 같지만 적당한 답이 안나오는것같아 다시 올립니다!
### 어떤 오류인가요?

오류설명:

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/58456250/92735122-16c69f80-f3b4-11ea-8503-36e23615a708.png)
전혀 발동이 안되고 있는듯한 application.properties..
![image](https://user-images.githubusercontent.com/58456250/92735180-28a84280-f3b4-11ea-8fd5-b056c19d6e58.png)
Application을 작동시켜보라고 하셨지만 안움직입니다

**Comment by kimingyo071** [comment]
어떻게 해결하셨나요?
