### ISSUE TITLE
P.134 3번째 줄 오타

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#5]
오타부분 : HTML도 결국은 규칙이 있는 문자열입니다. **estRestTemplate**를 통해...

**T**가 누락되었습니다.

**Comment by jojoldu** [comment]
@RATSENO 님 제보 감사합니다 :)
해당 건은 사전에 발견되어 2쇄부터는 반영될 예정입니다 :)
감사합니다!
