### ISSUE TITLE
[오류] p.74

### ISSUE THREAD

**Issue by smkyoyo** [jojoldu/freelec-springboot2-webservice#508]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: HelloResponseDto.java 와 관련하여 HelloResponseDtoTest.java를 실행하는 도중, 아래와 같은 오류가 발생합니다. 
`private final String name;
 private final int amount;` 
**_error: variable name not initialized in the default constructor private final String name;_**
@RequiredArgsConstructor가 선언된 모든 final 필드가 포함된 생성자를 생성해 준다고 되어 있는데, 
default constructor에서 초기화 되지 않았다고 하는 것은, 
@RequiredArgsConstructor 어노테이션이 먹히지 않아서 일까요?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/smkyoyo/MyFirstSpringProejct.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/20315222/96577194-3d122000-130e-11eb-80c1-f08314594f5b.png)

**Comment by smkyoyo** [comment]
저자님이 남겨주신 Gradle4로 변경하는 방법을 수행하였더니 해당 이슈가 해결되었습니다.

**Comment by smkyoyo** [comment]
메인화면에 저자님께서 남겨주신 대로 Gradle 4로 변경하도록 수행하였더니 이슈가 해결 되었습니다.
Gradle 5에서부터는 `@RequiredArgsConstructor` 를 선언한 서비스에서 Default 생성자를 사용하도록 변경되었기 때문이라고 하네요. 
아래 블로그를 참조하였습니다.
https://kkambi.tistory.com/155

**Comment by Qyuee** [comment]
https://jojoldu.tistory.com/539
위 링크에 나와있는 build.gradle의 lombok으로 설정하시면 gradle 5.X 이상에서도 정상동작 가능합니다.
(테스트에 사용한 버전은 gradle 6.7.1)
