### ISSUE TITLE
p.393 switch.sh 홑따옴표 사용 시 오류

### ISSUE THREAD

**Issue by siathus** [jojoldu/freelec-springboot2-webservice#51]
안녕하세요.

echo 'set \$service_url http://127.0.0.1:${IDLE_PORT};' | sudo tee /etc/nginx/conf.d/service-url.inc

이 부분 설명을 보면 홑따옴표를 사용해야 한다고 되어 있는데 홑따옴표를 사용했을 시 오류가 납니다. 그래서 쌍따옴표로 하니까 제대로 되네요. 깃허브 소스에도 쌍따옴표로 돼있구요... 

 확인 부탁드립니다. ㅜㅜ

**Comment by jojoldu** [comment]
@siathus 헉 죄송합니다
말씀하신대로 
* 쌍따옴표 (") : 변수의 실제 값을 출력
* 홀따옴표 (') : 변수명을 그대로 출력
하기 때문에 쌍따옴표가 맞습니다
오타 정말 죄송합니다 ㅠ

**Comment by namjunemy** [comment]
등록된 다양한 이슈 내용들 확인 하는게 너무 어려우실것 같네요 ㅜㅠ
그러나 독자입장에서는 책 보면서 오타 & 오류 제보를 이슈탭에서 확인하면서 볼 수 있어서 너무 편하고 좋습니다:)

**Comment by jojoldu** [comment]
@namjunemy 아고 아닙니다 ㅠㅠ
오타가 많아서 아무래도 더 자주 이슈 봐야하는것 같습니다 :)
남준님 잘 봐주셔서 감사합니다 :)
