### ISSUE TITLE
[오류] p.192  GooleLogin후  userName 오류

### ISSUE THREAD

**Issue by swwony08** [jojoldu/freelec-springboot2-webservice#513]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:  **구글 로그인 후 Logged in as :  ' 이름 ' 이 나오지 않고 계속 User로 노출 됩니다.
하지만 h2-console 에는 이름이 제대로 저장 되어있습니다.** 

![image](https://user-images.githubusercontent.com/31182446/97297432-65ad9300-1895-11eb-9411-2db846a936ac.png)
![image](https://user-images.githubusercontent.com/31182446/97297758-c89f2a00-1895-11eb-88b5-df180676558a.png)

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/wony08/project-springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by suin0730** [comment]
안녕하세요. 저도 같은 문제가 발생했는데 어떻게 해결하셨는지 알려주실 수 있을까요..?
