### ISSUE TITLE
[오류] p.260, 261

### ISSUE THREAD

**Issue by ghost** [jojoldu/freelec-springboot2-webservice#517]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: AWS에서 hostname을 변경해야하는데 여기서 어떻게 해야하는지를 모르겠습니다. hostname을 적고 어떤 행동을 해도 저기서 넘어가질 않네요.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/CooNiHong/springboot-webservices

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/66965622/97971991-3b188880-1e07-11eb-9de4-5db41fbdd901.png)

**Comment by ghost** [comment]
> 기존에 올라온 질문이 아닌지 먼저 검색해주세요!
> 
> ## 가장 자주 나온 제보
> * [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
> * [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)
> 
> ### 어떤 오류인가요?
> 오류설명: AWS에서 hostname을 변경해야하는데 여기서 어떻게 해야하는지를 모르겠습니다. hostname을 적고 어떤 행동을 해도 저기서 넘어가질 않네요.
> 
> ### 프로젝트 주소
> Github에 오류가 난 프로젝트를 올려주세요.
> **Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**
> 
> * Github URL: https://github.com/CooNiHong/springboot-webservices
> 
> ### 오류 로그
> 어떤 오류인지 캡쳐해주세요.
> ![image](https://user-images.githubusercontent.com/66965622/97971991-3b188880-1e07-11eb-9de4-5db41fbdd901.png)

**Comment by Pearlmoon997** [comment]
esc누르고 :wq 입력하시면 됩니당
