### ISSUE TITLE
p.105  return postsService.save(requestDto);  오류

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#52]
![image](https://user-images.githubusercontent.com/49624922/70731842-c0580200-1d4a-11ea-8dc3-7929413a7c12.png)

사진과 같이 save에 에러가 나서 PostsService에 들어가봤더니 값이 없다고 에러가 나는것 같습니다.
105페이지 전에는 PostsService class에 대한 설명이 없는거 같은데 혹시 제가 못찾는것일까요?

**Comment by jojoldu** [comment]
@jinyeanseok 앗 이문제 해결되신걸까요?
