### ISSUE TITLE
[오타 제보] p.152 > post.id 아니고 posts.id 입니다. 이하 필드 모두 동일 오타(냉무)

### ISSUE THREAD

**Issue by team-softgrid** [jojoldu/freelec-springboot2-webservice#523]
기존에 올라온 제보가 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 오타

* as-is (오타):

* to-be (교정):

**Comment by jojoldu** [comment]
@bigpi-factory 님 안녕하세요 :) 
해당 내용은 오타가 아니며 post.id가 맞습니다 :)
