### ISSUE TITLE
[오타 제보] 아래 p.152 문의 관련하여 재수정이 필요하지 않을까요..

### ISSUE THREAD

**Issue by hungryo-dev** [jojoldu/freelec-springboot2-webservice#524]
이전글에서
[오타 제보] p.152 > post.id 아니고 posts.id 입니다. 이하 필드 모두 동일 오타(냉무) 
이렇게 나와있는데
post.id가 맞는거 같은데요.

업데이트 화면에서 단건에 대한 dto를 post로 넘기는데 화면단에서 post.id로 받는게 맞지 않나요...
@GetMapping("/posts/update/{id}")
    public String postsUpdate(@PathVariable Long id, Model model) {
        PostsResponseDto dto = postsService.findById(id);
        model.addAttribute("post", dto);

        return "posts-update";
    }

4쇄 책 보고 있는데 ~ git에 올라온 소스 IndexController나 posts-update도 모두 post로 정상 작동합니다.

뭐가 잘못돼서 5쇄 반영됐다는지 이해하려 노력하고 있습니다...

**Comment by hungryo-dev** [comment]
아 저 5쇄반영 라벨이 자동으로 붙는구나...

**Comment by jojoldu** [comment]
@hungry87 님 확인 감사합니다 :) 말씀하신대로 posts.id가 아니라 post가 맞습니다 :) 
라벨의 경우 반영 예정으로 변경하여서 오해가 없도록 하겠습니다 ^^;
