### ISSUE TITLE
[오류] p.329 AWS Key 발급 후 github에 올려도 되나요?

### ISSUE THREAD

**Issue by haebin-lee** [jojoldu/freelec-springboot2-webservice#527]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

코드 배포를 위해서 IAM>사용자 에서 AWS 액세스 키와 비밀키를 .travis.yml 파일에 명시하는데 
이게 문제가 되서 AWS에서 연락이 왔었어요. 

급히 키를 삭제하고 레포지토리도 비공개 처리를 했는데 
레포지토리를 비공개 처리를 해서 그런지 travis CI 화면에서 아무것도 뜨지 않네요ㅠㅠ

방법이 있을까요?

메일의 일부를 공개합니다 

Hello,

This is Ivan from Amazon Web Services. I trust this email finds you well.

Unfortunately we have been unable to reach you by phone. We have become aware that the AWS Access Key 제 ACCESS KEY, belonging to IAM User board-travis-deploy, along with the corresponding Secret Key is publicly available online at 제 레포지토리/.travis.yml

**Comment by whdals7337** [comment]
혹시 travis.yml에 액세스 키와 비밀키를 적어두신거 아닌가요?
책에서는 travis에서 액세스키와 비밀키를 travis setting 에서 등록하고
travis.yml에는 등록된 변수값인 $AWS_ACCESS_KEY, $AWS_SECRET_KEY을 적어서 사용하게 되어 있습니다.
제 책 기준 p/333에 travis 키 등록이라고 있는데 확인해 보시면 좋을거 같습니다.

1. travis페이지 변수 셋팅
![image](https://user-images.githubusercontent.com/55545105/101144263-6509d880-365b-11eb-9363-5088200c462f.png)

2. travis.yml에서 변수 사용
![image](https://user-images.githubusercontent.com/55545105/101144411-a1d5cf80-365b-11eb-9bce-1dddca7402be.png)

**Comment by whdals7337** [comment]
![image](https://user-images.githubusercontent.com/55545105/101144215-51f70880-365b-11eb-9001-c5077fc4b440.png)

**Comment by haebin-lee** [comment]
아아아ㅏㅏ.. 저는 저기 변수를 쓰지 않고 그대로 AWS_ACCESS_KEY랑 AWS_SECRET_KEY를 입력해서 문제가 되었던 것 같습니다. 
바로 맵핑하지 않고 변수 사용해서 해볼게요~! 도움주셔서 감사합니다
