### ISSUE TITLE
p.112 /src/test/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#53]
112페이지에는 PostResponseDto 경로가

 /src/test/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto

이렇게 되어있는데 jojolduo님 깃허브에는 저 파일이 없는데 혹시 제가 착각하고 있는걸까요?

**Comment by jinyeanseok** [comment]
오타인것 같습니다!

**Comment by jojoldu** [comment]
앗 네 src/**main** 입니다 ㅠ
오타 제보 감사드립니다 ㅠ
