### ISSUE TITLE
P.110 PostApiControllerTest의 게시글 등록 테스트 코드에서 에러가 납니다.

### ISSUE THREAD

**Issue by yerin-0318** [jojoldu/freelec-springboot2-webservice#54]
public void PostsSave() throws Exception{
        //given
        String title="title";
        String content="content";

        PostsSaveRequestDto requestDto = PostsSaveRequestDto.builder()
                .title(title)
                .content(content)
                .author("author")
                .build();
        String url="http://localhost:"+port+"/api/v1/posts";

        //when
        ResponseEntity<Long> responseEntity = restTemplate
                .postForEntity(url,requestDto,Long.class); //Long 데이터 변환 에러남

        //then
        assertThat(responseEntity.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(responseEntity.getBody()).isGreaterThan(0L);
        List<Posts> all = postsRepository.findAll();
        assertThat(all.get(0).getTitle()).isEqualTo(title);
        assertThat(all.get(0).getContent()).isEqualTo(content);
    }

----
-@Test를 추가하니 이 글에서 코드 형식으로 쓰여지지 않아 뺐습니다. 
-실제 코드에는 당연히 @Test를 적용했습니다.

해당 코드의
ResponseEntity<Long> responseEntity = restTemplate
                .postForEntity(url,requestDto,Long.class);
부분에서 에러가 납니다.

org.springframework.web.client.RestClientException: Error while extracting response for type [class java.lang.Long] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token
 
전체 에러 코드는 이러하고요.

구글링 + 대충 해석해 본 결과 json객체를 전달하는 과정에서 문제가 있는 것 같은데
Long으로 지정된 값에 문제가 있나봅니다.

해당 테스트 코드 대신 이전에 블로그에 올려주신 아래의 코드는 성공합니다.
public void DtoSaveContent(){
        //given
        PostsSaveRequestDto dto = PostsSaveRequestDto.builder()
                .author("글쓴이")
                .content("테스트")
                .title("테스트 타이틀")
                .build();

        //when
        postsService.save(dto); //PostsApiController - save테스팅 통과함

        //then
        Posts posts = postsRepository.findAll().get(0);
        assertThat(posts.getAuthor()).isEqualTo(dto.getAuthor());
        assertThat(posts.getContent()).isEqualTo(dto.getContent());
        assertThat(posts.getTitle()).isEqualTo(dto.getTitle());
    }

또한 게시글을 수정할 때 사용된 테스트 코드 내의
 ResponseEntity<Long> responseEntity = restTemplate
                .exchange(url, HttpMethod.PUT, requestEntity, Long.class);
해당 부분도 위의 에러와 유사한 형식을 지녔으나 성공합니다.

원인을 모르겠네요. 답변 기다리겠습니다.

**Comment by yerin-0318** [comment]
뒷 페이지에 같은 내용으로 질문하신 글에서 답변을 찾았습니다~~~

**Comment by jojoldu** [comment]
@yerin-0318 앗 감사합니다 :)
오타 정말 죄송합니다 ㅠ

**Comment by zxzl** [comment]
`yerin-0318`님이 말씀주신 이슈는 https://github.com/jojoldu/freelec-springboot2-webservice/issues/19 입니다. 저처럼 찾는 분이 있으실까해서 링크 올립니다 :)

**Comment by ming-AA** [comment]
저도 책의 update 코드가 위에 글처럼 json 에러가 나는데 이유가 무엇인가요?

**Comment by Java2-2011034174** [comment]
저는 3판을 사용하고있고, PostsApiController 가 PostMapping으로 되어 있는 것도 확인하였으나 동일한 에러가 발생합니다. 혹시 이유를 알수 있습니까?
Error while extracting response for type [class java.lang.Long] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token

이렇게 나오는군요...

**Comment by faholoreach** [comment]
저도 3쇄본을 사용하고 있지만 @Java2-2011034174 님과 같은 오류가 발생하고 있습니다. 무슨 이유인지 알수가 없네요...;; 답변이 시급합니다... 진도를 나갈 수가 없네요.. ㅎㅎ ㅜㅜ

**Comment by jojoldu** [comment]
@Java2-2011034174 , @faholoreach  님 안녕하세요 :)
두분다 프로젝트 코드를 올려주셔야 정확히 원인을 알수있을것 같습니다!

**Comment by faholoreach** [comment]
> @Java2-2011034174 , @faholoreach 님 안녕하세요 :)
> 두분다 프로젝트 코드를 올려주셔야 정확히 원인을 알수있을것 같습니다!
> 
> 신규 이슈로 제보를 부탁드립니다
> 아래 양식에 맞춰서
> 
> ### 어떤 오류인가요?
> 오류설명:
> 
> ### 프로젝트 주소
> Github에 오류가 난 프로젝트를 올려주세요.
> **Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**
> 
> * Github URL:
> 
> ### 오류 로그
> 어떤 오류인지 캡쳐해주세요.

저의 경우에는 제가 빼먹은 코드가 있어 그랬습니다. 지금 다시 찾아보고 테스트 됐습니다.
감사합니다.^^

**Comment by Tocktock** [comment]
> @Java2-2011034174 , @faholoreach 님 안녕하세요 :)
> 두분다 프로젝트 코드를 올려주셔야 정확히 원인을 알수있을것 같습니다!
> 
> 신규 이슈로 제보를 부탁드립니다
> 아래 양식에 맞춰서
> 
> ### 어떤 오류인가요?
> 오류설명:
> 
> ### 프로젝트 주소
> Github에 오류가 난 프로젝트를 올려주세요.
> **Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**
> 
> * Github URL:
> 
> ### 오류 로그
> 어떤 오류인지 캡쳐해주세요.


저도 3판에 같은 오류가 계속 떠서 코드가 잘못됬나 뭐가 잘못됬나 싶어서 이것저것 찾아보다가 테스트 로그를 봤는데 DB에 테이블 생성이 안되고 있더라구요.. 그 전에 PostsRepostory 테스트 때는 오류 없이 무사 통과하다가 PostsRepostory 테스트도 안되길래 SQL 문제인가 싶어서 application.properties 에서 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
이 문구를 삭제하니까 모든 테스트가 통과 하더라구요.

찾아보니 springboot 버전에서 저 문구가 depreciate 된 거 같더라구요. 그냥 지우고 진행해도 괜찮을까요?
