### ISSUE TITLE
[오류] p.291 ec2에서 rds 접속하기

### ISSUE THREAD

**Issue by jeongeunnn-e** [jojoldu/freelec-springboot2-webservice#548]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

sudo

### 어떤 오류인가요?

오류설명:

putty에서 6장에서 만들어둔 session을 open하고 들어가서 mysql -u ~ -p -h ~~ 라고 치면 enter password : 가 나오지만 아무것도 쳐지지가 않고 한참 후에 연결할 수 없다고 합니다.

어디서 오류가 있는 걸까요??

도와주셔서 감사합니다ㅠㅠ!

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by YH191** [comment]
같은 오류 해결해서 댓글 남깁니다.
데이터베이스 - 연결&보안 - VPC 보안 그룹에 접속하려 하는 보안 그룹이 있는지 확인하고 없으면 추가하면 됩니다

**Comment by Imadeveloperrr** [comment]
원래 아무ㅡ것도 안떠요 그 상태로 그냥 비밀번호치고 엔터누르시면 로그인되요
