### ISSUE TITLE
[1판 질문]  p.161 질문 드립니다

### ISSUE THREAD

**Issue by TDCIAN** [jojoldu/freelec-springboot2-webservice#55]
![image](https://user-images.githubusercontent.com/52792962/70777866-33ea2580-1dc4-11ea-8529-d73308d0f91d.png)

안녕하세요 개발자님. 염치 불구하고 질문 드립니다 ㅜㅜ

다른 분들께서 올려주신 거 참고해서 오타나 누락된 부분 다 챙겨가면서 타이핑하고
확인까지 다 했는데 수정까지는 문제 없다가 삭제 버튼을 누르니까 저렇게 에러가 뜨네요...ㅜㅜ

프로젝트 새로 갈고 처음부터 다시 만들었는데도 같은 오류가 발생해 부득이하게 개발자님께 직접 질문드립니다ㅜㅜ

**Comment by enhakkore** [comment]
안녕하세요!
팝업 내용을 보면
status : [404](https://namu.wiki/w/404%20Not%20Found)을 봤을 때 서버에서 파일을 찾을 수 없다는 것을 알 수 있는데요,
path : /api/v1/posts1 이라고 되어있습니다.

책 p.160의 PostsApiController에서 @DeleteMapping("/api/v1/posts/{id}")을 부분을 제대로 따라하셨는지 확인해보셨으면 좋겠습니다. 마지막 / 을 빠뜨리지 않고 제대로 따라하셨다면 path : /api/v1/posts/1 이라고 나와야 합니다:)

**Comment by jojoldu** [comment]
@TDCIAN 이미 @enhakkore 님께서 잘 언급해주셨는데요 :)
삭제 요청하신 주소를 보시면 posts1로 되어있습니다
책에서는 posts/1에 대해 이야기하고 있습니다 :)

![image](https://user-images.githubusercontent.com/7760496/70842741-9ac21a00-1e6a-11ea-90e7-488e30532b21.png)

js 코드를 한번 다시 보시면 좋을것 같습니다 :)

> 질문하시는건 전혀 잘못된 일이 아니고
> 제 책에 오타가 많은것이라 제가 더 죄송합니다 ㅠ
> 언제든 편하게 질문 남겨주세요!

**Comment by TDCIAN** [comment]
> 안녕하세요!
> 팝업 내용을 보면
> status : [404](https://namu.wiki/w/404%20Not%20Found)을 봤을 때 서버에서 파일을 찾을 수 없다는 것을 알 수 있는데요,
> path : /api/v1/posts1 이라고 되어있습니다.
> 
> ~책 p.160의 PostsApiController에서 @DeleteMapping("/api/v1/posts/{id}")을 부분을 제대로 따라하셨는지 확인해보셨으면 좋겠습니다. 마지막 / 을 빠뜨리지 않고 제대로 따라하셨다면 path : /api/v1/posts/1 이라고 나와야 합니다:)~
> 
> 아래 @jojoldu님 답변 참고하세요!!ㅎㅎ

크으 도움 주셔서 감사합니다 ㅜㅜㅜㅜ

**Comment by TDCIAN** [comment]
> @TDCIAN 이미 @enhakkore 님께서 잘 언급해주셨는데요 :)
> 삭제 요청하신 주소를 보시면 posts1로 되어있습니다
> 책에서는 posts/1에 대해 이야기하고 있습니다 :)
> 
> ![image](https://user-images.githubusercontent.com/7760496/70842741-9ac21a00-1e6a-11ea-90e7-488e30532b21.png)
> 
> js 코드를 한번 다시 보시면 좋을것 같습니다 :)
> 
> > 질문하시는건 전혀 잘못된 일이 아니고
> > 제 책에 오타가 많은것이라 제가 더 죄송합니다 ㅠ
> > 언제든 편하게 질문 남겨주세요!

감사합니다 개발자님! 다시 살펴보면서 차근차근 해보겠습니다!

**Comment by jojoldu** [comment]
@TDCIAN 넵 화이팅입니다 :)
