### ISSUE TITLE
[오류] p.311

### ISSUE THREAD

**Issue by hyuuny** [jojoldu/freelec-springboot2-webservice#552]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 

안녕하세요!

311페이지 까지 잘 따라해보았는데.. 에러가 나서 진행이 안되네요.. 인터넷도 검색해봤으나.. 한계입니다.

### -  ./deploy.sh 실행시 오류
![image](https://user-images.githubusercontent.com/69466533/104444111-b0a88e00-55da-11eb-98a4-98fe6161da37.png)

### **-  vim ~/app/step1/deploy.sh 파일**
![image](https://user-images.githubusercontent.com/69466533/104444232-d7ff5b00-55da-11eb-9e0f-464ce20374f5.png)

### **- vim nohup.out**
![image](https://user-images.githubusercontent.com/69466533/104444576-4e03c200-55db-11eb-8880-99bb336353bf.png)

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by ByungjooYang** [comment]
우선 deploy.sh에 CURRENT_PID=$(pgrep -f ${PROJECT_NAME}.*.jar) 이거 입니다. pgrep 앞에 중괄호가 붙어있네요.
그리고 위에 캡쳐 보니까 ./gradlew test 하면 에러 났을거 같은데 안나셨었나요?

**Comment by hyuuny** [comment]
감사합니당!!

**Comment by ByungjooYang** [comment]
해결되셨나요?

**Comment by hyuuny** [comment]
이번엔 다른문제가 생겨서요 ㅋㅋㅋ 쉽지 않네요

**Comment by ByungjooYang** [comment]
> 이번엔 다른문제가 생겨서요 ㅋㅋㅋ 쉽지 않네요

ㅋㅋㅋ 올려주세요.

저도 이 문제로 며칠 씨름하다 방금 다 해결했습니다

**Comment by hyuuny** [comment]
![image](https://user-images.githubusercontent.com/69466533/104890790-65fc8c80-59b3-11eb-8d05-0a38630deb10.png)

309~310 페이지 입니다 ㅠㅠ

**Comment by ByungjooYang** [comment]
nohup.out 보면 실행은 잘 되나요?
