### ISSUE TITLE
[오류] p.383 /profile 리다이렉트

### ISSUE THREAD

**Issue by heejicat** [jojoldu/freelec-springboot2-webservice#555]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:  퍼블릭 도메인에 /profile로 접속하면 /login화면으로 넘어갑니다

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/heejicat/springboot-webservice.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.

SecurityConfig에 "/profile" 추가해주고 테스트도 잘 되는데 profile 페이지가 302 에러가 떠서 profile.sh에서 오류가 납니다.

```
LifecycleEvent - ValidateService
Script - health.sh
[stderr]/opt/codedeploy-agent/deployment-root/e6b6d273-69f5-4a28-9ac7-19f058a3fea1/d-8D8JNBBT7/deployment-archive/profile.sh: line 17: [: ==: unary operator expected
[stdout]> Health Check Start!
[stdout]> IDLE_PORT: 8082
[stdout]> curl -s http://localhost:8082/profile
[stderr]/opt/codedeploy-agent/deployment-root/e6b6d273-69f5-4a28-9ac7-19f058a3fea1/d-8D8JNBBT7/deployment-archive/profile.sh: line 33: [: too many arguments
[stdout]> Health check의 응답을 알 수 없거나 혹은 실행 상태가 아닙니다
[stdout]> Health check:
[stdout]> Health check 연결 실패 재시도..
[stdout]> Health check의 응답을 알 수 없거나 혹은 실행 상태가 아닙니다
```

왜 인증없이 호출되지 않는지 모르겠습니다.

**Comment by MJ-0701** [comment]
같은오류인데 혹시 해결하셨나요?
