### ISSUE TITLE
p.84 실무에서 JPA 설명하는 내용 중 오타

### ISSUE THREAD

**Issue by loverman85** [jojoldu/freelec-springboot2-webservice#56]
이런것도 이슈로등록해도 될지 모르겠는데
한번 써봐요!!
84페이지 밑에서 4번째줄에
"대용량 데이터를 처리를 경험해~" 
에서 '를' 을 빼는게 맞는것 같습니다.
감사합니다~

**Comment by jojoldu** [comment]
앗 제보 감사합니다 :)
