### ISSUE TITLE
[오류] p.191 Google Login 테스트에서 cannot find symbol method 오류 관련

### ISSUE THREAD

**Issue by madirony** [jojoldu/freelec-springboot2-webservice#560]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: CRUD 게시판 기능 다 만들어보고 테스트까지 잘되었는데 구글 로그인을 만들고 나서부터 테스트 페이지가 안되고 있습니다. 정확히는 191쪽 이전까지 코드를 작성하고 Google Login 테스트를 하려고 했는데 자꾸 메소드를 찾을 수 없다는 오류가 뜹니다. 혹시 코드를 덜 작성했나 싶어서 202쪽까지 작성을 했는데도 해결이 안됩니다 ㅜㅜ
저자님 깃코드랑 비교를 해도 .. 붙여넣기해서 씌워봐도 getName()이건 getEmail()이건 메소드를 찾을 수 없다고 뜹니다..ㅜㅜ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/madirony/sprbtest

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![화면 캡처 2021-01-18 211927](https://user-images.githubusercontent.com/48685874/104915494-11b5d480-59d4-11eb-9650-2829d59de5fc.png)

**Comment by beomth** [comment]
혹시 어떻게 해결하셨나요...?? 저도 똑같은 오류를 2일째 못고치고 있습니다..ㅠ

**Comment by JaeKang20** [comment]
Select Build->Rebuild Project will solve it
해보시면 좋을것 같습니다!
