### ISSUE TITLE
[오류] p.303~304 vim nohup.out 정상실행

### ISSUE THREAD

**Issue by 9b2n** [jojoldu/freelec-springboot2-webservice#565]
오류설명: P.303에서는 ClientRegistrationRepository를 찾을 수 없다는 에러가 발생하고 애플리케이션 실행에 실패한다고 나와있는데.. 저는 오류가 안 뜨고 정상 실행이 되네요 ,, 왜 이런지 알 수 있을까요?
아래에 캡쳐 사진에 확인되는 오류는 단지 gradle을 version up하라는 오류고 애플리케이션은 정상실행 된겁니다

### 프로젝트 주소
* Github URL: https://github.com/9b2n/springboot-webservice

### 오류 로그

<img width="486" alt="303~304" src="https://user-images.githubusercontent.com/58130501/105473880-f8b56800-5ce0-11eb-999c-002cfd52a016.PNG">

**Comment by jack2718-dr** [comment]
저도 정상실행이 되네요...
