### ISSUE TITLE
p.39 그림 1-25

### ISSUE THREAD

**Issue by devmwlee** [jojoldu/freelec-springboot2-webservice#57]
코드에는 
`springBootVersion = '2.1.7.RELEASE'`
로 되어 있는데 그림 1-25 버전을 보면 2.0.5.RELEASE로 되어 있습니다.

**Comment by jojoldu** [comment]
@devmwlee 앗 네 맞습니다
책을 쓸때는 2.0.5였으나, 출간 직전에 2.1.7로 업그레이드 후에 진행하다보니 누락된 사진이였습니다
제보 감사합니다!
