### ISSUE TITLE
[오류] p.105 PostsApiController 의 save 빨간줄

### ISSUE THREAD

**Issue by ZZAMBAs** [jojoldu/freelec-springboot2-webservice#579]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: return PostsService.save(requestDto); 에서 save 에 빨간줄이 가 있으며 non-static method save(com.jojoIdu.book.springboot.web.dto.PostsSaveRequestDto) cannot be referenced from a static context 로 뜹니다. 
아무리 생각해도 static이 아닌데 왜 이런 컴파일 에러를 뿜는지 알 수 있을까요?

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/ZZAMBAs/freelec-springboot2-webservice/blob/master/src/main/java/com/jojoIdu/book/springboot/web/PostsApiController.java

### 오류 로그

어떤 오류인지 캡쳐해주세요.

IdeaProjects\freelec-springboot2-webservice\src\main\java\com\jojoIdu\book\springboot\web\PostsApiController.java:18:28
java: non-static method save(com.jojoIdu.book.springboot.web.dto.PostsSaveRequestDto) cannot be referenced from a static context

**Comment by ahyz0569** [comment]
18번째 줄 ``PostsService.save(requestDto);`` 에 PostsService를 postsService로 고쳐보세요(맨 앞 P를 소문자로)

**Comment by ZZAMBAs** [comment]
> 18번째 줄 `PostsService.save(requestDto);` 에 PostsService를 postsService로 고쳐보세요(맨 앞 P를 소문자로)

감사합니다. 좀 부끄럽네여... 오타였다니
