### ISSUE TITLE
P276.RDS character set 관련 에러

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#58]
안녕하세요. P276부분 셋팅중에
collation_server
collaction_client 항목 셋팅중에

다른 항목들과는 다르게 Utf8mb4가 없길래
utf8mb4_unicode_ci로 대체 수정을 해보았지만

collation_client는 정상적으로 수정이 되지만
collation_server는 계속

저장 중 오류: collation_server 'utf8_general_ci' is not valid for character_set 'latin1' (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 04c87699-824c-45ad-b95d-0417b9d69f99)

를 뱉내요 ㅠㅠㅠ 혹시 해결방법 아실지 궁금합니다.
(PS. 어떤 characterSet을 선택해도 동일하게 수정이 안되네요 ㅠㅠ)

**Comment by jojoldu** [comment]
@RATSENO 
utf8mb4_general_ci 를 선택하시면 되는데요 :)
아래와 같이 항목들을 설정하면 됩니다.

![image](https://user-images.githubusercontent.com/7760496/70862533-fbdc1180-1f80-11ea-9a44-2413f14628fe.png)

만약 계속해서 안되시면,
새로운 파라미터 그룹을 만드셔서 RDS에 할당하시면 됩니다.

**Comment by RATSENO** [comment]
ㅠㅠ aws 콘솔에서는 자꾸 저 오류가 나오길래
올려주신 사진을 보고 책장을 좀 더 넘겨보니
쿼리로 설정하는 부분이 있었네요.
쿼리로 직접 변경하니 잘 적용되었습니다.
감사합니다!

**Comment by jojoldu** [comment]
@RATSENO 아고 잘되셨다니 다행입니다 ㅠㅠㅠ
고생하셨습니다! :)
