### ISSUE TITLE
[오류] p.306  외부 security 파일 등록하기

### ISSUE THREAD

**Issue by SieunKiim** [jojoldu/freelec-springboot2-webservice#582]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 보안 파일을 등록했는데도 clientRegistrationRepository를 찾을 수 없다는 에러가 여전히 발생합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/sieun960513/springboot2Boook.git

### 오류 로그

어떤 오류인지 캡쳐해주세요.

app 디렉토리
![app 디렉토리](https://user-images.githubusercontent.com/39111133/107482491-192b6080-6bc3-11eb-92e5-900588d60236.PNG)

application-oauth.properties 
![application-oauth-properties 내용](https://user-images.githubusercontent.com/39111133/107482692-63acdd00-6bc3-11eb-8803-2af4e4ddcb92.PNG)

deploy.sh 파일
![deploy sh 파일](https://user-images.githubusercontent.com/39111133/107482737-732c2600-6bc3-11eb-8f77-c9c7a06fb37c.PNG)

실행과 오류내용
![실행](https://user-images.githubusercontent.com/39111133/107482793-84753280-6bc3-11eb-9383-173573dea7c0.PNG)

**Comment by woo00oo** [comment]
혹시 해결하셨나요?

**Comment by SieunKiim** [comment]
저랑 같은 문제를 띄고 계신지는 모르겠지만 저는 nohup에 대한 지식이 부족했었어요!!
 사진이 내용처럼 매번 빌드 할 때 마다 nohup 파일을 지우고 하시는걸 추천드려요.


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "woo00oo"<notifications@github.com>
받는사람: "jojoldu/freelec-springboot2-webservice"<freelec-springboot2-webservice@noreply.github.com>
참조: "sieun960513"<sieun960513@naver.com>, "Manual"<manual@noreply.github.com>
날짜: 2021. 2. 27 오후 2:03:40
제목: Re: [jojoldu/freelec-springboot2-webservice] [오류] p.306 외부 security 파일 등록하기 (#582)

혹시 해결하셨나요?

**Comment by woo00oo** [comment]
> 저랑 같은 문제를 띄고 계신지는 모르겠지만 저는 nohup에 대한 지식이 부족했었어요!! 사진이 내용처럼 매번 빌드 할 때 마다 nohup 파일을 지우고 하시는걸 추천드려요. 네이버 메일앱에서 보냈습니다. -----Original Message----- 보낸사람: "woo00oo"<notifications@github.com> 받는사람: "jojoldu/freelec-springboot2-webservice"<freelec-springboot2-webservice@noreply.github.com> 참조: "sieun960513"<sieun960513@naver.com>, "Manual"<manual@noreply.github.com> 날짜: 2021. 2. 27 오후 2:03:40 제목: Re: [jojoldu/freelec-springboot2-webservice] [오류] p.306 외부 security 파일 등록하기 (#582) 혹시 해결하셨나요? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

글쓴이 분과 똑같이 외부 시큐리티 파일을 등록해줘도 사진처럼 오류가 뜨고 있거든요 ㅠㅠ nohup파일을 지워도 실행해도 똑같이 오류가 뜨네요 ..

**Comment by SieunKiim** [comment]
저 오류의 의미가 해당되는 jar파일이 없거나 제대로 가져오지 못하는 경우에 발생하는거같더라구요
저도 하면서 느끼게 된 것을 초보지만 조심스럽게 말씀드려보자면 
일단 오타가 가장 주된 요인이라 생각되고 오타도 없다면 deploy에 있는 커맨드들을 한줄씩 직접 쳐보면서 의도대로 수행되는지, 빌드 후에 jar 파일이 생성되고 원하는 위치에 복사되는지(cp) 를 한번 확인해보세요!! 저는 이렇게 하니까 감이 조금 잡히더라구요..


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "woo00oo"<notifications@github.com>
받는사람: "jojoldu/freelec-springboot2-webservice"<freelec-springboot2-webservice@noreply.github.com>
참조: "sieun960513"<sieun960513@naver.com>, "Manual"<manual@noreply.github.com>
날짜: 2021. 2. 27 오후 3:45:14
제목: Re: [jojoldu/freelec-springboot2-webservice] [오류] p.306 외부 security 파일 등록하기 (#582)


저랑 같은 문제를 띄고 계신지는 모르겠지만 저는 nohup에 대한 지식이 부족했었어요!! 사진이 내용처럼 매번 빌드 할 때 마다 nohup 파일을 지우고 하시는걸 추천드려요. 네이버 메일앱에서 보냈습니다. -----Original Message----- 보낸사람: "woo00oo"notifications@github.com 받는사람: "jojoldu/freelec-springboot2-webservice"freelec-springboot2-webservice@noreply.github.com 참조: "sieun960513"sieun960513@naver.com, "Manual"manual@noreply.github.com 날짜: 2021. 2. 27 오후 2:03:40 제목: Re: [jojoldu/freelec-springboot2-webservice] [오류] p.306 외부 security 파일 등록하기 (#582) 혹시 해결하셨나요? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

글쓴이 분과 똑같이 외부 시큐리티 파일을 등록해줘도 사진처럼 오류가 뜨고 있거든요 ㅠㅠ nohup파일을 지워도 실행해도 똑같이 오류가 뜨네요 ..

**Comment by woo00oo** [comment]
네 알겠습니다 답변 감사해요 ^^
