### ISSUE TITLE
p.257 putty SSH 접속 방법

### ISSUE THREAD

**Issue by SeokRae** [jojoldu/freelec-springboot2-webservice#59]
p.257 첫번째 줄에
"[Load] 버튼을 클릭하면 다음과 같이 SSH 접속 알림이 등장합니다."
에서 Putty 창 보면 "[Load]" 버튼이 아닌 "[**Open**]"을 눌러 접속 하는 내용인 것 같아 적어봅니다. ~

**Comment by jojoldu** [comment]
@SeokRae 앗 맞습니다
Load 버튼을 누른후 Open 버튼을 클릭하시면 됩니다
로 가야하는데 이부분이 잘못되었네요 ㅠ
제보 감사합니다!

**Comment by SeokRae** [comment]
@jojoldu 확인 감사합니다. 
정말 좋은 책 잘 보고 있습니다. ㅎㅎ

**Comment by jojoldu** [comment]
@SeokRae 앗 칭찬 감사합니다 ㅎㅎ;; 남은 내용도 재밌게 봐주세요!
