### ISSUE TITLE
P.105 @PutMapping("/api/v1/posts")

### ISSUE THREAD

**Issue by shbaek** [jojoldu/freelec-springboot2-webservice#6]
페이지 144 게시글 등록 실습 하다보니 오타가 있는거 같습니다~ 

P.105 PostsApiController 
@PutMapping("/api/v1/posts")
 -> @**PostMapping**("/api/v1/posts")

**Comment by jojoldu** [comment]
@shbaek 헉 제보 감사합니다
save 메소드의 Mapping은 @PostMapping("/api/v1/posts")이 맞습니다 ㅠ
정말 감사합니다 ㅠ

**Comment by gracelove91** [comment]
와.. p.109 테스트 돌리다가, `Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token` 같은 에러 뜨길래.. 뭔 소린가했더니.. PostMapping으로 바꾸니까 되네요 감사합니다

**Comment by gracelove91** [comment]
오지랖인 거 같지만.. 이건 2쇄반영으로 가야되지않을까요.. PostMapping이 아니면 테스트코드가 통과를 못합니당.. (참고. #13 )

**Comment by jojoldu** [comment]
@gracelove91 아고 ㅠㅠ 네 저도 2쇄가 맞다고 생각하는데 ㅠ 
2쇄가 벌써 인쇄가 시작되었습니다 ㅠ
금주 수요일 (12/04) 부터 인쇄가 시작되어서 이미 지나버려서요 ㅠ
정말 죄송합니다 ㅠ

**Comment by dkaskgkdua** [comment]
덕분에 해결했습니다 ㅠ
한참 찾았네요

**Comment by GitDaun** [comment]
[오타제보]
PostsService 생성위치가 다릅니다.
p104 에선  패키지가 springboot/service/posts 에 생성하라고 되어있는데
P105에선 제목에 springboot/service 라고 되어있어요
