### ISSUE TITLE
p.276 character_set 변경

### ISSUE THREAD

**Issue by SeokRae** [jojoldu/freelec-springboot2-webservice#60]
#58 동일한 이슈 - 내용 추가

동일한 오류가 aws console에서 일어나서 이슈 확인하고 올려주신 스샷 확인해보니
character_set_server도 utf8mb4로 변경되어있는거 같아서

character_set_server를 먼저 utf8mb4로 변경한 뒤에 
collation_server의 설정을 utf8mb4_general_ci로 바꾸니 오류 없이 잘 되는 것 같습니다.

**Comment by jojoldu** [comment]
@SeokRae 앗 제보 감사합니다 :)
