### ISSUE TITLE
travisci

### ISSUE THREAD

**Issue by thingsbrain-joonho** [jojoldu/freelec-springboot2-webservice#61]
travisci 의 무료 버전으로 github의 private repository 와 연동이 안되나요?

 private repository 와 연동 될 수 잇는  CI/CD 툴을 추천 부탁드립니다.

**Comment by jojoldu** [comment]
@thingsbrain-joonho 님 안녕하세요 :)
일단 TravisCI의 경우 private 저장소는 비용을 지불해야되어서 선택하지 않았습니다.
private 저장소를 사용하시려면

* 별도의 ec2에 젠킨스를 설치해서 배포하시거나
	* 같은 ec2에 설치하시면 아마 t2.micro 로는 메모리가 부족할거에요

제가 써보진 않았지만 private 저장소를 **선택적으로 무료로 사용 가능한** CI툴은 다음 정도가 있을것 같습니다.

* 최근 출시된 Github Action
* circleci

정도가 있을것 같습니다!
둘다 제가 사용해본건 아니라서 자세한 가격정책과 사용법은 별도로 확인해보셔야 할것 같습니다 :)
