### ISSUE TITLE
[오류] p.105 PostsApiController.java 에서 save 에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by jaeyeonme** [jojoldu/freelec-springboot2-webservice#617]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/JaeYeon33/spring-boot-aws/blob/main/src/main/java/com/jaeyeon/book/springboot/web/PostsApiController.java

### 오류 로그

어떤 오류인지 캡쳐해주세요.

Cannot resolve method 'save' in 'PostsService' 라는 에러가 발생합니다.

**Comment by anthem53** [comment]
지금은 해결하신 것 같지만 코멘트를 달아보면,

뒤에 추가로 2개 더 함수를 구현해야하는데요. 그걸 구현하고 나면 그 save 구현 이슈도 해결됩니다.
