### ISSUE TITLE
P.299 오타 질문

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#62]
depoly.sh 파일 생성 설명중에

~/app/step1/에  deploy.sh 파일을 하나 생성합니다.

vim ~/app/git/deploy.sh 가
vim ~/app/step1/deploy.sh 로

되어야 하는것이 아닌지 문의드립니다!

**Comment by jojoldu** [comment]
@RATSENO 님 제보 감사합니다 :)
말씀하신대로 step1이 맞습니다
동일 제보로 등록하겠습니다!

https://github.com/jojoldu/freelec-springboot2-webservice/issues/42
