### ISSUE TITLE
p.88 패키지 생성, 패키지 계층구조로 보기

### ISSUE THREAD

**Issue by wonjin-do** [jojoldu/freelec-springboot2-webservice#63]
p.88 안내에 따라 domain패키지를 만들었습니다. 
그 이후에 posts 패키지를 만드려고 하니 domain.posts로 표기된 패키지가 만들어 졌습니다.
이 패키지에 new > java class 로 클래스를 생성하면 posts 패키지 하위에 생성이 됩니다. 

질문) 패키지가 domain.posts 인 상황이며 posts 패키지에 이미 많은 java 파일이 들어가 있을때, domain 패키지 하위에 클래스파일을 추가하고 싶다면 어떻게 해야하는지 알고싶습니다.

아래 사진은 보시면 dto패키지를 만들기전에 HelloController를 먼저 만들어, 계층적으로 패키지가 보여지는 반면, posts패키지는 domain.posts로 보여지고 있습니다.
<img width="180" alt="20191217_001819" src="https://user-images.githubusercontent.com/54175950/70919195-c3613400-2063-11ea-9f68-bc43875bc8f4.png">

(추가)
실험삼아 posts 패키지를 만들기전 domain패키지에 Temp.java를 먼저 만들고 posts 패키지를 추가하니
domain 
   ┕  posts
   ┕  Temp.java 
형태로 만들어 졌습니다. 그러나, Temp.java를 삭제하면 다시 
domain.posts 로 패키지가 돌아오게 됩니다.

**Comment by jojoldu** [comment]
@wonjin-do 님 질문 감사합니다 :)
인텔리제이에서는 기본 구조가 말씀하신대로 1 depth가 계속 유지되는데요 :)
이 구조는 같은 레벨의 패키지나 클래스가 하나더 있으면 자동으로 해제됩니다.

* posts 패키지에서 원하시는 파일을 만들어서
* 좌측 사이드바에서 해당 클래스를 선택후 move (단축키 F6)를 하신뒤 refactor 버튼을 클릭하시면
* domain 패키지로 이동하게되고 자동으로 구조가 변경 됩니다.

![image](https://user-images.githubusercontent.com/7760496/70996577-6b373a00-2116-11ea-864f-83aa5e71238f.png)

![image](https://user-images.githubusercontent.com/7760496/70996621-87d37200-2116-11ea-95d6-19c20e28c01e.png)

**Comment by wonjin-do** [comment]
감사합니다!
