### ISSUE TITLE
[공유] p.356-357 S3 성공 후에도 Codedeploy로 배포가 안되는 문제

### ISSUE THREAD

**Issue by 1eedaegon** [jojoldu/freelec-springboot2-webservice#630]
복잡한 삽질경험을 공유합니다.

**상황**
- Travis 빌드 시에 모든 과정이 성공 후 Done.
- CodeDeploy agent is running으로 에이전트는 정상
- S3에서 zip파일이 발견되나 EC2나 Codedeploy는 무응답 상태

**원인** 
1. Codedeploy가 간혹 EC2 인식을 하지 않음.
2. Travis CI가 브랜치를 읽지않음

**해결방법**
1. Codedeploy application 삭제 후 다시생성
2. 브랜치 옵션 추가 
```
- provider: codedeploy
   on:
      all_branches: true
```

** 참고파일 **
`/var/log/aws/codedeploy-agent/codedeploy-agent.log`

** 실패 시 **
<img width="1092" alt="Screen Shot 2021-04-21 at 3 04 41 PM" src="https://user-images.githubusercontent.com/37583495/115506522-e6ce6b80-a2b5-11eb-8da0-ff9ab00143e0.png">

** 성공 시 **
<img width="1058" alt="Screen Shot 2021-04-21 at 3 05 20 PM" src="https://user-images.githubusercontent.com/37583495/115506654-14b3b000-a2b6-11eb-9d9d-5b66e4a673dd.png">

코드 디플로이 앱 재생성도 해보고 브랜치 옵션도 줘보고 서비스 재실행도 해봤다가 좌절했었는데
드디어 되는 기쁨에 공유해봅니다.

**Comment by dkstm95** [comment]
저는 브랜치 옵션만 추가해줬더니 되네요 ㅎㅎ 감사합니다

**Comment by hyeonjeong-ko** [comment]
짱입니다 덕분에 해결했어요^^ 감사합니다!
