### ISSUE TITLE
[공유] p.383 / 접속 시 HTTP status 500 및 /profile 접속 시 OAuth인증페이지 뜨는 문제

### ISSUE THREAD

**Issue by 1eedaegon** [jojoldu/freelec-springboot2-webservice#631]
오늘도 복잡한 삽질경험을 공유합니다. =]

### 상황
Travis 성공 후 Codedeploy까지 배포 성공했으나

1. 실제 EC2 접속 시 Http status 500이 뜨는 상황
2. /profile 접속 시 Oauth2 인증페이지 반환

### 원인
deploy.sh에서 현재 실행 중인 Spring boot 프로세스 아이디를 가져오지 못해 같은 웹서버 중복 실행 

### 해결방법
```bash
# 여기 부분을
CURRENT_PID=$(pgrep -fl ${PROJECT_NAME} | grep jar | awk '{print $1}')
# 이렇게 수정
CURRENT_PID=$(ps -ef | grep ${PROJECT_NAME} | grep jar | awk '{print $2}')
```

### 참고파일
/home/ec2-user/app/step2/nohub.out

### 실패 시
<img width="965" alt="Screen Shot 2021-04-22 at 4 30 29 PM" src="https://user-images.githubusercontent.com/37583495/115675519-9f191400-a389-11eb-915a-13d3b5a511d3.png">

<img width="1121" alt="Screen Shot 2021-04-22 at 4 30 46 PM" src="https://user-images.githubusercontent.com/37583495/115675417-8577cc80-a389-11eb-949d-7092e394e897.png">

### 성공 시
**nohub.out의 맨 밑줄**
<img width="1128" alt="Screen Shot 2021-04-22 at 4 50 17 PM" src="https://user-images.githubusercontent.com/37583495/115676801-e522a780-a38a-11eb-873c-d841e73e06e9.png">

끙끙앓고있다가 `nohub.out`를 뚫어지게 보고 찾아냈습니다.
이미 주소와 포트를 사용하고 있다는 로그를 보고 이상하다 싶어 
직접 스크립트를 쳐보고 수정했습니다.
```bash
PROJECT_NAME=practice-spring-boot
pgrep -fl ${PROJECT_NAME} | grep jar | awk '{print $1}' # 동작하지 않습니다.
ps -ef | grep ${PROJECT_NAME} | grep jar | awk '{print $2}' # 동일한 로직의 스크립트를 작성해봤더니 정상출력됩니다.
```

**Comment by way4425** [comment]
공유 감사합니다 ㅜㅜ
덕분에 해결했습니다.

**Comment by tipsyboy** [comment]
감사합니다.
