### ISSUE TITLE
[오류] p.200 SessionUser 널포인터익셉션

### ISSUE THREAD

**Issue by KangChanSong** [jojoldu/freelec-springboot2-webservice#636]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:  구글 로그인 구현 이후 어노테이션과 HandlerMethodArgumentResolver 를 이용해
  코드를 개선한 후 애플리케이션을 재시작해서 / 에 접근하니 NullPointerExeption이 떳습니다.
SessionUser를 초기화하지 못했다는 예외가 발생했습니다. 
아무리 봐도 코드에는 문제가 없는데.. 뭐가 문제일까요

답변해주시면 감사하겠습니다 

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:  https://github.com/KangChanSong/freelec-springboot2-webservice/commit/0e3a4da3cca302cb970153d4ce59f1a801732bb9

### 오류 로그
Failed to instantiate [com.jojoldu.book.springboot.config.oauth.dto.SessionUser]
 Constructor threw exception; nested exception is java.lang.NullPointerException] with root cause

**Comment by KangChanSong** [comment]
다시 프로젝트 새로 만들어보면서 해결했습니다. 아마 어딘가에 오타가 있었던 것 같습니다

**Comment by taeseong** [comment]
WebConfig의 addArgumentResolvers 메소드를 제대로 구현해야 이 문제가 생기지 않습니다.
다른분들 참고하시라고 코멘트 남겨둡니다.
