### ISSUE TITLE
183p userNameAttributeName에 대해서 궁금합니다.

### ISSUE THREAD

**Issue by sa1341** [jojoldu/freelec-springboot2-webservice#64]
안녕하세요. OAuth2.0을 스프링 시큐리티와 처음 써봐서.. 책으로만 봐서 이해가 안되는 점이 있어서 질문드렸습니다.

CustomOAuth2UserService 클래스 파일에서 해당 변수가 어떻게 사용되는지 찾아봐도 이해가 안됩니다.

  String userNameAttributeName = userRequest.getClientRegistration().getProviderDetails()
                .getUserInfoEndpoint().getUserNameAttributeName();

로그인 진행시 키가 되는 필드값이라고 하는데.. 이게 무슨말인지 알수 있을까요 ? 구글에서는 기본 코드가 sub라고 하는데 어디에 쓰이는지를 모르겠습니다. 그리고  해당 CustomOAuth2UserService 클래스의 역할은 소셜로그인 인증 후에 인증 성공 후에  redirect_url로 권한 코드를 받고 나서  client id, client secret 코드를 함께 전송하여 access token을 받은 후에 다시 resource server에 전송하여  스코프에 해당하는 정보를 받도록 요청하는 역할을 하는 클래스인가요?

**Comment by jojoldu** [comment]
@sa1341 님 질문 감사합니다 :)
해당키는 OAuth를 지원하는 소셜 서비스들간의 약속이라고 보시면 되는데요.

```
userRequest.getClientRegistration().getProviderDetails()
.getUserInfoEndpoint().getUserNameAttributeName();
```

에는 **어떤 소셜서비스든 그 서비스에서 각 계정마다의 유니크한 id값을 전달**해주겠다는 의미입니다.

* 구글은 sub이라는 필드가 유니크 필드이며
* 네이버는 id라는 필드가 유니크 필드입니다.

구글

![image](https://user-images.githubusercontent.com/7760496/70997283-0aa8fc80-2118-11ea-988d-91bd2ee24e4a.png)

![image](https://user-images.githubusercontent.com/7760496/70997461-7e4b0980-2118-11ea-8f44-84f8777a076d.png)


네이버

![image](https://user-images.githubusercontent.com/7760496/70997398-578cd300-2118-11ea-94d2-23cdb6486f47.png)

각 소셜서비스들간에 id필드가 무조건 유니크 필드라고 정해지면 이렇게 할 필요가 없지만
서로 유니크필드명이 다르므로 위에서 얘기하신 userRequest.getClientRegistration().getProviderDetails()
.getUserInfoEndpoint().getUserNameAttributeName();를 통해 그 필드명을 찾고
해당 필드명의 값을 가져오도록 구성한 것입니다 :)

제가 설명이 부족할 수 있습니다.
혹시 부족했다면 편하게 말씀주세요!
