### ISSUE TITLE
[오류] p.204 - 210 네이버 아이디로 로그인

### ISSUE THREAD

**Issue by jeonka1001** [jojoldu/freelec-springboot2-webservice#646]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?
네이버 아이디로 로그인 실습 중 발생한 오류입니다.

오류설명:
구글 이메일 후 세선 데이터베이스 저장 까지 완료. 그 후 네이버 아이디로 로그인 시 아래 사진과 같은 오류 발생합니다 ㅠㅠ

- 같은 현상  
[[오류] p.210 네이버 로그인 오류 #610](https://github.com/jojoldu/freelec-springboot2-webservice/issues/610)  

- 참고했지만 같은 원인이 아닌 이슈  
[[오류] p.210 네이버 로그인 추가하고 나서 서버에러 발생 #428](https://github.com/jojoldu/freelec-springboot2-webservice/issues/428)  
[[오류] p.210 #411](https://github.com/jojoldu/freelec-springboot2-webservice/issues/411)  
[[오류] 208p ~210p 네이버/Naver Login with OAuth 2.0 오류 해결 #339](https://github.com/jojoldu/freelec-springboot2-webservice/issues/339)  
[p.206 네이버 로그인 application-oauth.properties 관련 #11](https://github.com/jojoldu/freelec-springboot2-webservice/issues/11)  
[네이버 로그인이 안됩니다. ㅠㅠ #121](https://github.com/jojoldu/freelec-springboot2-webservice/issues/121)

![스크린샷 2021-05-21 오후 6 04 39](https://user-images.githubusercontent.com/52381846/119112535-23c98180-ba5f-11eb-95a5-a8ecc53478da.jpg)

### 프로젝트 주소

https://github.com/jeonka1001/Study/tree/main/springboot/study_springboot_jeonka

* Github URL: https://github.com/jeonka1001

###### 오류 상황 사진
![스크린샷 2021-05-21 오후 6 03 15](https://user-images.githubusercontent.com/52381846/119112578-2e841680-ba5f-11eb-88e8-feadd0d914c3.jpg)

###### 오류 관련 클래스 사진
![스크린샷 2021-05-21 오후 6 03 30](https://user-images.githubusercontent.com/52381846/119112645-42c81380-ba5f-11eb-98cc-bc86a3bbe4ba.jpg)

###### ofNaver 함수 
![스크린샷 2021-05-21 오후 6 03 38](https://user-images.githubusercontent.com/52381846/119112680-4eb3d580-ba5f-11eb-921c-cc43c29d48cd.jpg)

어떤 오류인지 캡쳐해주세요.

**Comment by KangChanSong** [comment]
attributes.get("response") 에서 response라는 요소를 못찾는 것 같아 보여요
다른 코드들에 문제없으면
application-oauth.properties 파일에 user_name_attribute=response 설정 돼있는지 한번 확인해보세요

**Comment by jeonka1001** [comment]
답변 감사합니다! 
말씀해주신 spring.security.oauth2.client.provider.naver.user_name_attribute=response 에는 문제가 없어보입니다 ㅠ 
다른 코드 혹시 어느부분 확인하면 좋을지 조언 해주실 수 있으신가요 ?

**Comment by KangChanSong** [comment]
저도 아직 공부하는 중이라...
response가 없다니 그 문제만 해결하면 될 것 같은데 확실히 어디서부터 문제가 생겼는지는 모르겟네요ㅠㅠ

**Comment by KangChanSong** [comment]
저도 아직 공부하는 중이라...
response가 없다니 그 문제만 해결하면 될 것 같은데 확실히 어디서부터 문제가 생겼는지는 모르겟네요ㅠㅠ

**Comment by jeonka1001** [comment]
오타발견했어요!!!! 대박 application-oauth.properties 에서 user-info-uri 값에 오타가 있었습니다. ㅜㅜ 조언 감사합니다
