### ISSUE TITLE
p. 365 ...templates/index.hbs 파일 확장자

### ISSUE THREAD

**Issue by SeokRae** [jojoldu/freelec-springboot2-webservice#65]
p.365 첫 번째 줄에 src/main/resources/templates/index.hbs
index.hbs -> index.mustache 인듯 하여 제보 드립니다. ~

혹시 다른 의미가 있는데, 잘못 이해한 걸까요 ?

**Comment by SeokRae** [comment]
이제 완독했습니다. 
좋은 책 써주셔서 무지 감사합니다. ~

**Comment by jojoldu** [comment]
@SeokRae 앗!! 제보 감사합니다
mustache가 맞습니다.
제가 처음 책 쓸때는 Handlebars를 뷰 템플릿으로 했다가
공식 스타터가 있는 머스테치로 전환하는 과정 중에 남았었네요 ㅠ
제보 감사합니다!
