### ISSUE TITLE
[오류] 구글로그인에서 계정 선택 후 client_secret is missing. 에러가 뜹니다 p.192 

### ISSUE THREAD

**Issue by im-gnar** [jojoldu/freelec-springboot2-webservice#652]
### 어떤 오류인가요?

오류설명: 
구글로그인에서 계정 선택 후 client_secret is missing. 에러가 뜹니다.
클라우드에서 ID와 SECRET 전부 확인해봤는데 일치합니다만... 뭔가 과정을 빼먹은 걸까요?ㅠㅠ

### 프로젝트 주소

https://github.com/rachel5004/SpringBootAWS

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by Gom3rye** [comment]
혹시 어떻게 해결하셨는지 알려주실 수 있나요? 저도 똑같은 에러가 나서요ㅜㅠ

**Comment by lew0205** [comment]
혹시 어떻게 해결하셨는지 알수있을까요??
