### ISSUE TITLE
[오류] p.395 deploy가 안됩니다

### ISSUE THREAD

**Issue by Dokkabei97** [jojoldu/freelec-springboot2-webservice#654]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: P395 무중단 배포 마지막 하고있는데 계속 오류가 나면서 배포가 안됩니다....

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/Dokkabei97/studySpringboot

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![e2](https://user-images.githubusercontent.com/69792585/120294493-35354800-c301-11eb-839b-349103156d2d.PNG)
![e1](https://user-images.githubusercontent.com/69792585/120294579-4aaa7200-c301-11eb-9b6b-1c60551a024e.PNG)

**Comment by Dokkabei97** [comment]
properties 부분 전체적으로 수정하니 해결됐습니다!

**Comment by fpzk5656** [comment]
제가 딱 님이 올린 화면과 똑같은 상황인데
님 깃헙 링크의 코드를 봐도 먼가 딱히 해결이 안되네요...

스크립트들이랑 프로퍼티 전부 따라 쳐봤는데...
