### ISSUE TITLE
[오류] p.219 오류로 질문드립니다.

### ISSUE THREAD

**Issue by JeanYoungPark** [jojoldu/freelec-springboot2-webservice#656]
### 오류설명
안녕하세요. 책으로 공부하다 이것저것 찾아봤는데 답이 나오지 않아서 질문 남깁니다. 
223페이지까지 실습을 진행하였는데

Error creating bean with name 'securityConfig' defined in file [C:\Users\jeanf\IdeaProjects\freelec-springboot2-wevservice\build\classes\java\main\com\jojoldu\book\springboot\config\auth\SecurityConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.jojoldu.book.springboot.config.auth.CustomOAuth2UserService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

이 오류가 해결되지 않아서 질문 남깁니다.
보통 어노테이션 문제라고 그러던데 제 눈에는 영 보이지 않아서ㅠㅠ 부탁드립니다!

### 프로젝트 주소
https://github.com/JeanYoungPark/freelec-springboot2-wevservice

### 오류 로그
![1](https://user-images.githubusercontent.com/70056958/120923708-e45f8e00-c70a-11eb-82a2-2db5013c457a.PNG)

**Comment by JeanYoungPark** [comment]
오류 해결했습니다!
SecurityConfig.class <- 이 부분에서 제가 다른 걸 선택해서 넣었었네요!

**Comment by juuxx** [comment]
@JeanYoungPark 어느부분 고치셨는지 알 수 있을까요? 저도 똑같이 오류가 나는데 어디를 수정해야될지 모르겠습니다..
