### ISSUE TITLE
[질문] p.182-184: @Transactional 없이 User 엔터티를 업데이트 할 수 있는 이유는 무엇인가요?

### ISSUE THREAD

**Issue by binchoo** [jojoldu/freelec-springboot2-webservice#659]
연관 이슈: https://github.com/jojoldu/freelec-springboot2-webservice/issues/47

[문의 내용]
`CustomOAuth2UserService`에서 `@Transactional` 메서드 없이 User 엔터티를 업데이트 할 수 있는 이유는 무엇인가요?

[문의 상세 내용]
`CustomOAuth2UserService.loadUser(userRequest)`는 `User` 엔터티의 `name`과 `picture` 필드를 갱신하고 있습니다.

https://github.com/jojoldu/freelec-springboot2-webservice/blob/f3b54082ceaeca2503e8f3ccf191cbfc2cf06c01/src/main/java/com/jojoldu/book/springboot/config/auth/CustomOAuth2UserService.java#L47-L50

https://github.com/jojoldu/freelec-springboot2-webservice/blob/f3b54082ceaeca2503e8f3ccf191cbfc2cf06c01/src/main/java/com/jojoldu/book/springboot/domain/user/User.java#L46-L51

`User` 엔터티의 필드를 Dirty하게 만들어서 저장소에 자동으로 갱신하는 것으로 이해했습니다.
이 방법은 챕터3의 `PostsService.update()`에서 채용한 방법과 동일하고요.

https://github.com/jojoldu/freelec-springboot2-webservice/blob/f3b54082ceaeca2503e8f3ccf191cbfc2cf06c01/src/main/java/com/jojoldu/book/springboot/service/PostsService.java#L26-L31

본인은 챕터3을 실습할 때, @Transactional을 선언하지 않으니 저장소에 값이 갱신되지 않는 이슈를 경험했습니다.
https://github.com/binchoo/spring-boot-210523/issues/7

하지만 챕터5에서 `CustomOAuth2UserService`가 @Transactional 없이 정상적으로 `User`의 `name`과 `picture`를 갱신하는 것도 실습으로 확인했구요.

아마 제가 @Transactional에 대해 오해를 갖고 있는 것 같습니다. 개념을 정확히 짚어주실 분의 도움이 필요합니다!

**Comment by soulduo** [comment]
트랜잭션은 실제 데이터 갱신(DB UPDATE) 자체와는 무관한 개념입니다.

업데이트 등에서 오류 발생시 처리등을 대신하는 역활이라고 해야할까요.

데이터베이스의 트랜잭션 부분을 공부해보시면 개념을 잡으실 수 있을겁니다.

데이터베이스의 트랜잭션 을  @Transactional  어노테이션으로 대신한 부분이라고 보시면 될 겁니다.

데이터베이스 트랜잭션을 검색해 보시면 좋을거 같네요.

**Comment by zhtmr** [comment]
혹시 문제 해결이 되셨나요?? 저도 궁금해서 찾는중인데.. 제 생각엔 해당 코드는 @Transactional 하에서 엔티티 갱신에 따른 jpa 업데이트 로직이 아니라 바로 아랫줄에 있는 return 부분에서 save를 호출해서 insert 되는것 아닐까 생각중인데.. 혹시 해당 문제 결론을 어떻게 내셨는지 궁금합니다!

**Comment by binchoo** [comment]
@zhtmr 안녕하세요, 타래 및 메일로 문의 주셔서 감사합니다.

해당 내용은 직접 SQL 구문을 공부해 보면서 개념 구분이 가능하게 되어 해결되었습니다.
- SET AUTOCOMMIT = FALSE 에서 부터 COMMIT을 실행하기 까지...
- 그러나 SET AUTOCOMMIT = TRUE를 사용할 수도 있는 것이죠.

다음 사고과정으로 생각해 보시면 될 것 같습니다.
- JPA 트랜잭션을 열었을 경우, Dirty가 된 내용은 트랜잭션이 끝나면 DB로 반영된다. (참)
- 함정은, "이 명제"가 참이라고 생각하는 것입니다. JPA 트랜잭션을 열지 않았다고 해서, DB에 변경 값 반영이 불가한 것은 아닙니다.

PostsService.update()와 CustomOAuth2UserService.loadUser()의 소스 코드 차이점을 확인해 보십시오. 
전자의 경우 repository.save를 호출하지 않으나, 후자는 호출합니다.

즉 전자는 트랜잭션 종료에 따른 Dirty 내용 반영을 이용한 것이며
후자는 직접 변경 내용을 저장한 것입니다.

피드백 주시면 이슈 종료하도록 하겠습니다. 감사합니다.
