### ISSUE TITLE
p.113 post.update() 문의

### ISSUE THREAD

**Issue by hkleev2** [jojoldu/freelec-springboot2-webservice#66]
- PostService
. . .
post.update(requestDto.getTitle(), requestDto.getContent())

domain.posts.Posts 클래스에 update 메소드 작성하는 부분이 빠진거같아용..

**Comment by jojoldu** [comment]
@hkleev2 님 안녕하세요!
누락되어 정말 죄송합니다 ㅠ
해당 코드는 아래 이슈에 등록되어있습니다
불편을 드려 정말 죄송합니다 ㅠ

https://github.com/jojoldu/freelec-springboot2-webservice/issues/15
