### ISSUE TITLE
[오류] p.116 H2 콘솔 접속 불가

### ISSUE THREAD

**Issue by khs50851** [jojoldu/freelec-springboot2-webservice#664]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요? h2 db 연결 불가

오류설명: JDBC URL에 기존 jdbc:h2:~/test라고 써있던거 jdbc:h2:mem:testdb로 바꾸고 했는데 안되서 이슈 찾아보니 같은 이슈 있어서 프로퍼티스에 아래 캡쳐와 같이 spring.datasource.url=jdbc:h2:mem:testdb 코드 추가 했습니다.

![image](https://user-images.githubusercontent.com/72734075/122929130-8aff8c00-d3a5-11eb-8b59-1279179d89a2.png)

하지만 여전히 아래 오류 사진과 같이 Database "mem:testdb" not found, and IFEXISTS=true, so we cant auto-create it [90146-199] 90146/90146 (Help) 이렇게 오류가 납니다.. 도와주세요 ㅜㅜ

### 프로젝트 주소
https://github.com/khs50851/spring_test

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/khs50851/spring_test

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/72734075/122929252-b1252c00-d3a5-11eb-9a5a-eab020e1c775.png)

**Comment by Syon0303** [comment]
url 에 jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL 를 입력해서 접속해보세요
저는 이렇게 해결했습니다만 맞는방법인지는 모르겠습니다.

**Comment by khs50851** [comment]
안녕하세요~ 해결했습니다! 답변 감사합니다
​
-----Original Message-----

**Comment by Syon0303** [comment]
제가 올려드린 방법으로 해결하신건가요? 아니면 어떻게 해결하셧는지 알 수 있을까요.?

**Comment by khs50851** [comment]
안냥하세요. 올려주신 방법으로 해결했습니다! 감사합니다 ㅎㅎ
​
-----Original Message-----
