### ISSUE TITLE
[오류] p.357 codedeploy 배포실패 오류

### ISSUE THREAD

**Issue by 3bgdragon** [jojoldu/freelec-springboot2-webservice#678]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/3bgdragon/shop

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![4](https://user-images.githubusercontent.com/65847681/125039458-7a535380-e0d1-11eb-9485-6a5df6819e09.PNG)

![3](https://user-images.githubusercontent.com/65847681/125039490-850de880-e0d1-11eb-9a3d-6606e79c0a85.PNG)

![2](https://user-images.githubusercontent.com/65847681/125039756-cd2d0b00-e0d1-11eb-9a66-5e98c27bb4ac.PNG)

위와 같이 s3버킷에 연동을 성공하여서 다음단계인 codedeploy를 적용할떄 다음과 같이 에러가 생깁니다
![1](https://user-images.githubusercontent.com/65847681/125039716-c2727600-e0d1-11eb-9a4c-3ec7d04a362d.PNG)
![5](https://user-images.githubusercontent.com/65847681/125039813-dddd8100-e0d1-11eb-8c5b-782e0abde36c.PNG)

tag의 이름의 철자가 다른가 싶어서 확인해봤지만 특별한 문제를 찾을수 없었습니다

![8](https://user-images.githubusercontent.com/65847681/125040012-18471e00-e0d2-11eb-8100-8f6259f08464.PNG)

![11](https://user-images.githubusercontent.com/65847681/125040879-13369e80-e0d3-11eb-81ff-572cfc12170d.PNG)

![6](https://user-images.githubusercontent.com/65847681/125040075-2d23b180-e0d2-11eb-82aa-ae07f089dc9a.PNG)

![12](https://user-images.githubusercontent.com/65847681/125041114-5e50b180-e0d3-11eb-9241-054b297bf147.PNG)

** 참고파일 **
/var/log/aws/codedeploy-agent/codedeploy-agent.log
![13](https://user-images.githubusercontent.com/65847681/125041627-eb940600-e0d3-11eb-897b-e2d23f37a4f4.PNG)

틀린 철자가 있어서 오류가 생기는건가요? 계속해서 해결방법을 찾고있지만 방법이 안나옵니다.. ㅠㅠ

**Comment by 3bgdragon** [comment]
step2 폴더의 zip 폴더에 들어가봤지만 아무런 파일도 생성이 되지않았습니다

**Comment by 3bgdragon** [comment]
인스턴스를 오하이오주에서 생성해서 생긴문제 같습니다 천천히 다시해보겠습니다

**Comment by 3bgdragon** [comment]
해결했습니다 https://woomin.netlify.app/Posts/2020-05-12-CodeDeploy/ 에서  “0개의 일치하는 고유 인스턴스” 라는 것이 나올때 해결방법을 적용시켜서 해보니 "1개의 일치하는 고유 인스턴스" 가 나와 성공하였고 push해보니 정상적용 되었습니다.

**Comment by s-ryuri** [comment]
@3bgdragon 안녕하세요 저도 0개의 일치하는 고유 인스턴스가 뜨는 데 해결방법을 알 수 있을까요?

**Comment by s-ryuri** [comment]
@3bgdragon 올려주신 블로그는 이제 볼 수가 없어서 궁금하네요
