### ISSUE TITLE
./gradlew wrapper --gradle-version 4.10.2 질문

### ISSUE THREAD

**Issue by goneone** [jojoldu/freelec-springboot2-webservice#68]
윈도우 기준으로 
alt+f12 눌러서
./gradlew wrapper --gradle-version 4.10.2
해당 명령어 입력하면

'.'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

라고 나오는데요 윈도우는 실행 방법이 다른건가요??

**Comment by jojoldu** [comment]
아고 ㅠ 윈도우는 ```./```를 빼시면 됩니다!

```
gradlew wrapper --gradle-version 4.10.2
```
