### ISSUE TITLE
[질문] p.200 @LoginUser를 통해 로그인할 때 질문이 있습니다.

### ISSUE THREAD

**Issue by frtt0608** [jojoldu/freelec-springboot2-webservice#682]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 질문인가요?

질문설명: @LoginUser로 로그인하는 과정까지 진행했습니다.
디버깅하는 과정에서 LoginUserArgumentResolver 클래스의 httpSession 변수를 final로 선언하지 않고 어플리케이션을 실행할 때,  resolveArgument 메서드에서 null 에러가 발생했습니다.
 final 변수는 초기값을 변경할 수 없는 특징이 있는 것으로 알고 있는데, final로 선언하지 않았을 때 왜 null 에러가 뜨는지 궁금합니다.

 로그인하지 않은 경우, 세션에는 "user"라는 key가 없으니까 httpSession.getAttribute("user")는 null이 나오는게 맞다고 생각합니다. 근데 final이라는 키워드에 따라 해당 사항이 바뀌는 건지... 이해가 안갑니다ㅠㅠ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by soulduo** [comment]
@RequiredArgsConstructor 

책 내용중에 찾아보시면 위 어노테이션이 초기화를 시켜주며 초기화를 위해 final로 선언해야지 된다고 나와있었던 걸로 기억 되네요.

해당 어노테이션으로 검색해서 상세 내역을 찾아보시면 될 거 같습니다.


https://webdevtechblog.com/requiredargsconstructor-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%A3%BC%EC%9E%85-dependency-injection-4f1b0ac33561

**Comment by frtt0608** [comment]
@soulduo 
감사합니다ㅠㅠ 안그래도 복습하면서 @RequiredArgsConstructor의 역할을 다시 확인하다가
해당 이슈에 대해 이해할 수 있게됐습니다!

코멘트 감사합니다👍
