### ISSUE TITLE
P.300 코드 블럭에 숫자 주석 누락

### ISSUE THREAD

**Issue by skyhills13** [jojoldu/freelec-springboot2-webservice#69]
안녕하세요 동욱님 책 잘 읽고 있습니다. 감사합니다.

이 전에 나온 코드 블럭들로 미루어 보아, 숫자 주석이 있어야할 것 같은데, 
설명에 나오는 숫자 주석이 이 코드 블럭에는 없습니다.
쉘 스크립트 코드라서 혹시 의도한 것이라면 이슈 닫아주세용!

**Comment by jojoldu** [comment]
@skyhills13 앗 소은님 안녕하세요 :)
잘지내시죠? ㅎㅎ
제보 감사합니다!
말씀하신대로 코드블럭에 넘버링이 누락된것 같습니다 ㅠㅠ
3쇄엔 반영해놓겠습니다!
감사합니다 :)
