### ISSUE TITLE
[오류] p.110 PostsApiControllerTest 오류

### ISSUE THREAD

**Issue by Hanseunghoon** [jojoldu/freelec-springboot2-webservice#690]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?
오류설명: 등록 테스트시 오류가 발생합니다. 어떤 오류인지, 해결책을 알 수 있을까요?

### 프로젝트 주소
* Github URL: https://github.com/Hanseunghoon/freelec-springboot2-webservice

### 오류 로그
![image](https://user-images.githubusercontent.com/50897259/126519577-397791b8-a37d-4391-90b9-b9ab246cd28a.png)
![image](https://user-images.githubusercontent.com/50897259/126519599-aff73d3d-8a3e-43d2-9722-7891e9588dde.png)

**Comment by frtt0608** [comment]
git 저장소에 postsApiController 관련 코드가 안보이네요. push까지 해주시면 에러 확인에 도움될 거에요.
에러코드만 보면 객체 생성 관련 Annotation이 빠진 것처럼 보입니다! 
각 클래스랑 메서드에 Annotation한번만 확인해주세요

**Comment by Hanseunghoon** [comment]
> git 저장소에 postsApiController 관련 코드가 안보이네요. push까지 해주시면 에러 확인에 도움될 거에요.
> 에러코드만 보면 객체 생성 관련 Annotation이 빠진 것처럼 보입니다!
> 각 클래스랑 메서드에 Annotation한번만 확인해주세요

답변 감사합니다. push 해두었습니다. 
안타깝지만 아직도 에러를 해결 못 하고 있습니다.. 확인해주시면 감사하겠습니다! :)

**Comment by frtt0608** [comment]
> > git 저장소에 postsApiController 관련 코드가 안보이네요. push까지 해주시면 에러 확인에 도움될 거에요.
> > 에러코드만 보면 객체 생성 관련 Annotation이 빠진 것처럼 보입니다!
> > 각 클래스랑 메서드에 Annotation한번만 확인해주세요
> 
> 답변 감사합니다. push 해두었습니다.
> 안타깝지만 아직도 에러를 해결 못 하고 있습니다.. 확인해주시면 감사하겠습니다! :)





혹시 에러코드가 이게 맞을까요?
requested bean is currently in creation is there an unresolvable circular reference

결론부터 말씀드리면! PostsApiController class의 14번째줄에 postsService라는 변수를 잘못 선언하셨습니다.
해당 부분을 PostsService postsService로 변경하시면 정상 작동합니다.


여기서 발생한 에러코드는 [스프링 bean의 순환 종속성]에서 발생한 이슈였습니다! 저도 해결하는 과정에서 알게됐네요.

제 예상으로는 이미 PostsApiController에서 @RequiredArgsConstructor로 생성자를 빈에 주입한 상태인데,
필드에서 같은 클래스의 객체를 만들면서 자기 자신을 참조하는(?) 상황이 발생한 것 같습니다.

저도 정확한 건 아니라, 자세한건 직접 찾아보시는 걸 추천드릴게요ㅠㅠ
참고 레퍼런스입니다.

https://hungrydiver.co.kr/bbs/detail/develop?id=90
https://perfectacle.github.io/2019/06/23/auto-scanning-annotation-based-bean/

**Comment by Hanseunghoon** [comment]
답변 감사합니다.
멍청하게 작성하고 별 질문을 다했네요.
컴퓨터를 너무 오래봐서 그런지.. 나이가 들어서 그런지.. 눈이 침침했나봅니다
덕분에 시간 줄였습니다 감사합니다 :)
