### ISSUE TITLE
[오류] p.308 SPRING_SESSION_ATTRIBUTES 생성이 안됩니다..

### ISSUE THREAD

**Issue by changjinpark** [jojoldu/freelec-springboot2-webservice#697]
### 어떤 오류인가요?

오류설명: 
schema-mysql.sql 파일에서 맨 마지막 테이블인 **SPRING_SESSION_ATTRIBUTES** 테이블을 복사하고 RDS에 반영하는데, SQL 문법 에러가 발생합니다. 
SPRING_SESSION 테이블은 정상적으로 잘 생성됩니다.

schema-my.sql에서 그대로 복사 붙여넣기 했는데 왜 에러가 계속 나오는지 모르겠습니다ㅠㅠ
```
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
```
**에러로그**
```
**Error executing DELETE statement. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC' at line 1 - Connection: Connection 1: 27ms**
```
### 프로젝트 주소
* Github URL: https://github.com/changjinpark/freelec-spring2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/64358371/127884989-257f4ff8-ecdc-42cd-b6cf-a709ae775e60.png)

**Comment by changjinpark** [comment]
ON DELETE CASCADE를 주석처리를 하니까 SPRING_SESSION_ATTRIBUTES 테이블 생성까지는 됩니다.
ON DELETE CASCADE를 빼고 테이블을 만들어서 나중에 에러가 또 발생할 것 같습니다.
ON DELETE CASCADE 가 안먹는 것 같은데, 그 이유를 모르겠네요..ㅠㅠㅠ

![image](https://user-images.githubusercontent.com/64358371/127887508-ca4ea909-186d-468d-87fa-b87699c22d16.png)

**Comment by changjinpark** [comment]
MySQL WorkBench를 설치해서 명령어를 입력하니까 테이블이 정상적으로 생성되었습니다. 


![image](https://user-images.githubusercontent.com/64358371/130078421-6261b1c0-f743-469e-9e4f-0abf6460c7f2.png)

**Comment by hyecozy** [comment]
이거 원인이 도대체 뭘까요? 저도 이렇게 되는데 책을 참고하시는 분들 모두가 MySQL WorkBench를 설치해서 하고 있을 것 같진 않아서 원인이 너무 궁금하네요

**Comment by alittlenation** [comment]
이거 뭐죠... 해답이 없네요 찾아봐도

**Comment by anthem53** [comment]
다른 곳에서 찾아보니 인텔리제이 커뮤니티 버전은 mysql 기능을 그렇게 지원하지 않아서 생기는 문제라고 하네요.

다른 문제가 있을 수 있지만 이게 원인이라고 하면 충분히 납득은 갑니다.
