### ISSUE TITLE
p.36~37 build.gradle 코드에 특이점이 있는것 같습니다..

### ISSUE THREAD

**Issue by bin-e** [jojoldu/freelec-springboot2-webservice#7]
`p.33`과 `p.34`에 `repositories{ }`에 `jcenter()`를 추가하도록 코드가 적혀있고, `p.35` 중간 문맥에 
>여기서는 mavenCentral, jcenter 둘 다 등록해서 사용하겠습니다.

로 되어있는데, `p.36~37`에 전체코드에서는 빌드스크립트 내부 및 하단 `repositories{ }`에는 `jcenter()`가 누락되어있네요..

**Comment by jojoldu** [comment]
@bin-e 앗!!!! 감사합니다 ㅠㅠㅠ 누락된게 맞습니다 ㅠ
감사합니다 ㅠ

**Comment by alittlenation** [comment]
교재에 나와있는대로 하니깐 죄다 그래들 빌드가 안되는데 
최신 자료가 있을까요?
아니면 start-io 로 시작해도 될까요 흑
