### ISSUE TITLE
구글, 네이버 로그인시 이름이 제대로 나오지 않는 문제

### ISSUE THREAD

**Issue by irerin07** [jojoldu/freelec-springboot2-webservice#70]
안녕하세요! 
좋은 책 정말 감사드립니다! 

다름이 아니라 네이버 로그인 기능을 추가하는 파트(초판 기준 페이지 211)까지 진행을 했는데 막힌 부분이 생겨서 질문 남깁니다.

IndexContoller에서 user.getName()을 사용하여 "userName"이란 이름으로 model에 값을 담아 전달해 주면 로그인을 했을시에 해당 값이 Logged is as: "유저이름"  이렇게 나와야 할텐데 저 같은 경우는 count라고 하는 값이 출력이 됩니다. 제 이메일의 앞부분이 잘려서 출력이 된 것으로 생각합니다만 왜 이런지 도통 알 방법이 없습니다.

이것저것 시도해보던 중 attributeName을"userName"에서 "user"로 변경을 하여 실행을 하니 이번에는 유저의 이름이 잘 출력이 되는것을 확인했습니다.
이런 현상이 발생하는 이유가 무엇일까요..?

추가적으로 구글로 로그인 한 뒤 로그아웃 하고 네이버로 로그인 한 뒤에 h2 데이터 베이스 콘솔을 사용하여 SELECT * FROM USER를 사용하면 다음과 같이 USER가 변경이 됩니다.

![image](https://user-images.githubusercontent.com/39554427/71054295-d58ebf80-2194-11ea-8d15-b0694c55ad2d.png)
구글로 로그인 후 h2 console

![image](https://user-images.githubusercontent.com/39554427/71054328-f9520580-2194-11ea-8387-9bb463afb67b.png)
로그아웃 한 뒤 네이버로 로그인 후 h2 console

NAME과 PICTURE값은 변경이 되는데 이상하게 EMAIL은 변경이 되지  않습니다.

혹시나 해서 다른 구글 이메일로 로그인을 해보니 다른 메일들은 정상적으로 잘 추가가 되는것을 확인했습니다.

왜 이런 현상이 나타나는 걸까요..?

두서없이 너무 긴 질문 글 죄송합니다 ㅜㅜ

**Comment by jojoldu** [comment]
@irerin07 님 질문 감사합니다!

하나씩 답변드리겠습니다 :)

1. 이건 irerin07님의 애플리케이션 코드에서 정상적으로 값을 만들고 있는지 확인해 보아야 하는데요.

* 인텔리제이 디버깅 기능을 이용해서 확인하시거나
* System.out.println (혹은 log) 등으로 user.getName 값이 뭔지 확인해보시는게 필요할것 같습니다.

결과적으로 

* user.getName()을 했을때 값이 정상이라면 index.mustache나 jquery와 같은 프론트 코드에 문제가 있는 것이고
* user.getName() 값이 다른 값이 있다면 User 객체에 값을 담는 코드에 문제가 있는것이라서요

어디가 문제인지 정확히 확인을 해보시는게 필요할것 같습니다.

![image](https://user-images.githubusercontent.com/7760496/71234888-c9923180-233d-11ea-9ae6-e51a0c3de882.png)
 

2. 구글/네이버 번갈아 로그인 하면 name이 수정되는 문제

스샷을 보시면 아시겠지만, 네이버 이메일 계정과 구글 이메일 계정이 같은 주소를 사용하시는데요 :)
이럴 경우 아래 코드에서 보시다시피, **같은 계정으로 판단하여 이름과 프로필 url 을 갱신합니다**
이메일 주소는 그 사용자를 나타내는 일종의 id입니다.
이를 변경할수는 없습니다.

![image](https://user-images.githubusercontent.com/7760496/71234596-e5e19e80-233c-11ea-9dab-5a8c82ae5034.png)

네이버메일 주소와 구글 메일 주소를 다르게 사용해서 로그인 하시면 2개의 사용자로 잘 구분되어서 관리 될거에요 :)

**Comment by irerin07** [comment]
친절하고 자세한 답변 정말 감사드립니다!
1번 문제의 경우 제가 System.out.println을 사용하여 user.getName()을 확인 해 본 결과 값은 정상적으로 받아지는걸 확인했습니다. 그렇다는건 Back단에서는 문제없이 값을 잘 읽고 있다는 것이고 아마  Front쪽에서 뭔가 문제가 있지 않나 생각합니다만 어디가 문제인지 도통 찾을수가 없네요. 제가 찾은 유일한 해결방법은 위에서도 말씀 드렸듯이 
![image](https://user-images.githubusercontent.com/39554427/71236441-550dc180-2342-11ea-8d71-b8e496838faa.png)

위의 코드를 
![image](https://user-images.githubusercontent.com/39554427/71236560-9ef6a780-2342-11ea-85db-d1f4a6e1048b.png)
이렇게 바꾸는 것입니다.
물론 IndexController에서도 
![image](https://user-images.githubusercontent.com/39554427/71236604-bafa4900-2342-11ea-9324-c203ff26be97.png)
위의 코드를
![image](https://user-images.githubusercontent.com/39554427/71236641-cb122880-2342-11ea-8e8f-cd294fd7eb2c.png)
이렇게 바꾸어 주었습니다.

이 방법 외에는 아직 해결방법을 찾지 못했습니다 ㅜㅜ

**Comment by irerin07** [comment]
2번 문제의 경우 제가 질문을 너무 모호하게 쓴것 같아 다시 질문드립니다.

구글이메일과 네이버 이메일은 둘 다 전혀 다른 메일 주소를 가지고 있습니다.
구글은 counterchord89@gmail.com, 네이버는 winterer_89@naver.com을 사용합니다.

어플리케이션을 실행 후 먼저 구글로 로그인 후에 h2 콘솔창을 확인하면 다음과 같은 화면이 보입니다.
![image](https://user-images.githubusercontent.com/39554427/71236901-77540f00-2343-11ea-9757-71c62a3686c4.png)

그후 로그아웃을 하여 네이버로 로그인을 한 뒤에 h2 콘솔창을 확인하면 다음과 같은 화면이 보입니다.

![image](https://user-images.githubusercontent.com/39554427/71236941-95ba0a80-2343-11ea-8874-d9fd5e79c113.png)

스크린샷에서 보이듯이 NAME값은 변경이 되는 반면, EMAIL값은 둘 다 counterchord89@gmail.com으로 유지가 되고 있습니다.

왜 이런 현상이 발생하는지 알 수가 없어서 질문 드립니다.

**Comment by jojoldu** [comment]
@irerin07 앗 음
그럼 제가 한번 프로젝트를 제 pc에 받아서 실행해보겠습니다 :)
https://github.com/irerin07/com.tistory.irerin07-webservice.git 프로젝트로 확인후에 다시 답변 남기겠습니다 :)

**Comment by jojoldu** [comment]
@irerin07 님 방금 사용하신 프로젝트를 제 pc에 clone 받아 진행해보았는데요 :)
아래와 같이 정상적으로 작동되는 것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/7760496/71251946-f7d83700-2366-11ea-8b54-b405593056fe.png)


로그인시 이름도 userName으로 잘되는것을 확인하였습니다.

![image](https://user-images.githubusercontent.com/7760496/71251973-0cb4ca80-2367-11ea-84f9-efd08c38a354.png)

![image](https://user-images.githubusercontent.com/7760496/71251987-13dbd880-2367-11ea-8c30-83ec8c9f6926.png)

(당연히 구글/네이버 다 로그인해보았습니다)

똑같은 프로젝트를 사용했으니 애플리케이션 코드는 동일한데 다르게 작동한다면
의심해볼만한 것은
**네이버와 구글에 등록된 리다이렉트 주소가 잘못되지 않았을까** 라고 의심해봅니다.

그림 5-11, 5-27을 참고하셔서 제대로 설정되어있는지 확인해보시겠어요?

**Comment by irerin07** [comment]
@jojoldu 빠른 답변 감사합니다.!!

세상에....문제를 찾았습니다.

![image](https://user-images.githubusercontent.com/39554427/71256558-6c65a280-2374-11ea-88f9-0eeae203c389.png)

위 이미지에서 연락처 이메일이 제 구글 이메일로 지정이 되어 있어서 생긴 문제였습니다...네이버 메일 비밀번호를 잃어버렸을 때를 대비해서 등록 해 둔 메일이었는데 이게 이런식으로 문제를 일으킬줄이야...

api를 사용해서 이메일을 불러오면 네이버에서는 연락처 이메일로 저장이 되어 있는 메일 주소를 보내주고있었나봅니다..

![image](https://user-images.githubusercontent.com/39554427/71256618-a46ce580-2374-11ea-942f-4fff3c9bd683.png)

위에서 연락처 이메일을 네이버로 변경하고 난 뒤에 확인해보니 문제없이 등록이 되는것을 확인했습니다.

이럴수가...ㅜㅜ

문제 해결해주시려고 너무 애써주셔서 감사합니다 ㅜㅜ

이제 남은건 1번 문제뿐인데...왜 제 쪽에서는 userName을 사용하면 
![image](https://user-images.githubusercontent.com/39554427/71256769-22c98780-2375-11ea-89c4-1769300b25a3.png)
여전히 이렇게 나오는걸까요...

**Comment by jojoldu** [comment]
@irerin07 님 안녕하세요!
이름 관련해서는 iumoum님이 언급해주신 이슈와 동일한것 같습니다 :)
참고해주세요!

https://github.com/jojoldu/freelec-springboot2-webservice/issues/169
