### ISSUE TITLE
안녕하세요 gradlew wrapper --gradle-version 4.10.2 관련 질문드립니다

### ISSUE THREAD

**Issue by zuctoma85** [jojoldu/freelec-springboot2-webservice#71]
안녕하세요 저도 교재보면서 따라해 보고 있는대요
인텔리J 터미널창 열어서  gradlew wrapper --gradle-version 4.10.2
명령어 실행하면 
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
라고 에러가 떠서요.. 윈도우 cmd창에서 실행하면 실행되거든요..
(윈도우 환경변수는 설정해 놓았습니다)

**Comment by zuctoma85** [comment]
재부팅하니까 되네요...;;;

**Comment by jojoldu** [comment]
앗 ㅎㅎㅎㅎ 감사합니다 :)
