### ISSUE TITLE
[오류] p.298  ./gradlew test를 했을 때 한개만 오류가 나요.

### ISSUE THREAD

**Issue by 93TEI** [jojoldu/freelec-springboot2-webservice#723]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:

./gradlew test를 했을 때 7개 통과를 했는데,
'메인페이지_로딩()'만 통과를 못합니다.

java.lang.AssertionError가 나는걸로 봐서는 assertthat의 문제인데
저자의 코드를 복붙해서 해봐도 자꾸 납니다.
문자열이 포함되는 것에 오타가 있는가 여러번 확인해도 이상없구요.

인텔리제이에서 테스트 돌리면 모두 통과하는데
왜 메인페이지_로딩()의 저 부분이 통과가 안될까요

며칠째 할 수 있는건 다 해봤습니다.
도움 부탁드립니다

### 프로젝트 주소

* Github URL:  https://github.com/93TEI/freelec-springboot2-webservice

### 오류 로그

![image](https://user-images.githubusercontent.com/43162525/132138628-dbceb7a1-5a03-43c4-a82b-000c1ffc4893.png)

**Comment by 93TEI** [comment]
WebConfig파일이 깃에 안올라간 것이었습니다.

**Comment by SuperRPM** [comment]
> 
같은 문제를 겪고있는데 WebConfig파일이 깃에 안올라간 것과 어떤관련이 있는지 잘 모르겠습니다.
혹시 어떻게 해결하셨는지 알려주실 수 있을까요?

**Comment by 93TEI** [comment]
@SuperRPM 저도 잘은 모르지만 당시 springboot에서 깃헙으로 플젝을 다 올리고 그랬었는데,
WebConfig파일만 깃헙에 올라가지 않도록 설정이 되어있더라구요.
그래서 파일명이 빨간색이었습니다. 수동으로 깃헙에 푸시하고 나니 바로 해결됐었습니다.
아마 같은 문제를 겪고 계시지만 저랑은 다른 이유에서 난 오류같은데 빠른 시일 내 해결되길 바랍니다!
