### ISSUE TITLE
[오류] p.364 p.365 업데이트 되지 않는 오류입니다.

### ISSUE THREAD

**Issue by JeongGod** [jojoldu/freelec-springboot2-webservice#724]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 현재 구동되어있는 app이 꺼지지 않고 실행되서 그런것 같아 nohup.out에 로그를 보니 맞았습니다.
```
Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.
```
그래서 왜 꺼지지 않나 살펴보니 밑에 사진처럼 `java`로 구동이 되고 있어서 실행중인 어플을 찾지 못한 이유더라구요.
    
![스크린샷 2021-09-07 오전 3 23 59](https://user-images.githubusercontent.com/22341452/132252292-4ae1a4f5-eb6b-4303-aa7d-44c7e6c87df3.png)
    
왜 `jar`로 구동이 안되고 `java`로 구동이 되는지.. 알려주시면 감사하겠습니다ㅠㅠ
결국 deploy.sh에서
```
CURRENT_PID=$(pgrep -fl springboot-webservice | grep jar | awk '{print $1}')
```

에서

```
CURRENT_PID=$(pgrep -fl springboot-webservice | grep java | awk '{print $1}')
```
로 변경하니 성공적으로 업데이트 되는것을 확인했습니다. 안되시는 분들 참고바랍니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/JeongGod/springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by 3210439** [comment]
글이 많은 도움이 되었습니다!! 감사합니다.
