### ISSUE TITLE
[오류] p.309 ~ p.311

### ISSUE THREAD

**Issue by dfdf0202** [jojoldu/freelec-springboot2-webservice#727]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: deploy.sh vim 으로 실행해서 application-oauth.properties, application-real-db.properties 경로 추가 해주고 했는데
책 처럼 결과가 안나오는데 뭐가 문젤까요..

<img width="1337" alt="스크린샷 2021-09-12 오전 4 13 01" src="https://user-images.githubusercontent.com/73690027/132959138-519ee4c2-11ae-4c72-a959-f118c2adcde5.png">

<img width="1065" alt="스크린샷 2021-09-12 오전 4 18 29" src="https://user-images.githubusercontent.com/73690027/132959145-211ef33f-843b-4cff-8218-2eb5fafcf5ba.png">

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by yanJuicy** [comment]
noup java 뒤에 \ 없애고 한 줄로 해보세요
