### ISSUE TITLE
[질문] 193p 기본권한 GUEST

### ISSUE THREAD

**Issue by sasca37** [jojoldu/freelec-springboot2-webservice#734]
오류는 아니고 궁금한 점이 있어 남깁니다..
Role 에 대한 Default 설정이 어디서 이루어지나요? 로그인 시 권한에 GUEST, USER 중 GUEST가 들어가게 된 원리가 궁금합니다.

**Comment by OR35** [comment]
class OAuthAttributes에서 
user entity 생성할 때 builder 값에서 role 을 guest로 지정해줘요.
가입할 때 기본 권한을 guest로 설정해서 그렇습니다.

@sasca37

**Comment by sasca37** [comment]
> class OAuthAttributes에서 user entity 생성할 때 builder 값에서 role 을 guest로 지정해줘요. 가입할 때 기본 권한을 guest로 설정해서 그렇습니다.
> 
> @sasca37

감사합니다!
