### ISSUE TITLE
P.338, P.379 코드 넘버링 누락

### ISSUE THREAD

**Issue by skyhills13** [jojoldu/freelec-springboot2-webservice#74]
오전에 올렸던 이슈와 마찬가지로 코드 넘버링이 누락되어있습니다.
제목에 적은 두 페이지는 큰 코드블럭이라서 의도치 않은 누락인 것 같은데 

아래의 페이지는 코드 블럭이 작아서 의도하신 것 같기도 해서, 혹시나 하는 마음에 본문에 달아둡니다.
P.305, P.361, P.366, P.377, P.379 입니다.  

한가지 더 아주아주아주 마이너한 이슈는 
P.346의 위에서 다섯번째 줄에 
> 설치가 끝나셨으면 Agent가 정상적으로

이 부분이 있는데, 책 전반에서 사용하신 말투와 차이가 있어서, 높임말을 사용하지 않으셔도 될 것 같아서 슬며시 말씀드려요. 

저는 잘 지냅니다 ㅎㅎ 
항상 동욱님 블로그, 깃허브 보면서 많이 배우고, 또 정말 많이 동기부여 받아서 말로 표현할 수 없을 만큼 항상 감사해요. 영한님 영호님 책보다 많이 팔려서 10쇄까지 가즈아아!!!!
동욱님 건강 꼭꼭 챙기시고 함께 오래오래 즐겁게 코딩해요.

**Comment by jojoldu** [comment]
@skyhills13 와 소은님 꼼꼼한 리뷰 감사합니다!
완전 감동입니다 ㅠㅠ
말씀하신 내용에 대해서는 100% 공감합니다.
3쇄에 반영해놓겠습니다!

ㅎㅎㅎ 요새 영호님,영한님과 책 순위로 겨루고 있습니다 ㅎㅎ
소은님도 항상 건강 잘 챙기시구요.
업계에서 정말 오래오래 뵈었으면 좋겠습니다 :)
