### ISSUE TITLE
P.326 Travis 빌드 실패 질문

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#75]
안녕하세요 해당 페이지 실습중 Travis에서

/home/travis/.travis/functions: line 350: ./gradlew: Permission denied

이러한 오류로 빌드 실패가 내려와서

구글링 해보았더니

before_install:
  - chmod +x gradlew
을 .travis.yml 에 추가하여 정상적으로 Build되는것을 확인하였는데요

이 내용이 왜 추가가 되어야 할까요???
왜 접근권한이 빠져있었을까요??

**Comment by jojoldu** [comment]
@RATSENO 님 안녕하세요!
음 일단 gradlew 는 실행 파일입니다.
리눅스 환경에서 실행 파일은 **실행 권한이 있어야만 실행 가능**한데요.
접근권한이 없어서 난 에러가 아니라,
**실행권한이 없어서** 발생한 에러입니다.

일반적으로는 gradlew 파일에는 실행권한이 프로젝트 생성시점에 부여되며,
**그 파일이 깃허브에 올라가기 때문에** 별도로 x 권한 (실행) 을 주지 않아도 되는데요.

> 이 프로젝트의 travis yml 파일 보시면 chmod +x gradlew 명령어가 없는게 확인되설거에요!

@RATSENO 님의 gradlew에는 실행권한이 자동 부여되지 않은것 같습니다!
해결책은 이미 언급하신대로 travis yml에 추가하는 방법이 있고,
이외에 프로젝트에 있는 gradlew에 **실행권한을 추가하고 github에 올리면** 이후에는 travis에서 매번 배포시마다 권한을 추가안해도 됩니다 :)

**Comment by Park-Joyeong** [comment]
안녕하세요 저자님 Windows 운영체제에서 개발하는 사람은 gradlew파일에 리눅스에서 기동시의 실행권한 추가할 방법이 없는거 맞는지 여쭤보고 싶습니다..

> 해결책은 이미 언급하신대로 travis yml에 추가하는 방법이 있고,
> 이외에 프로젝트에 있는 gradlew에 **실행권한을 추가하고 github에 올리면** 이후에는 travis에서 매번 배포시마다 권한을 추가안해도 됩니다 :)
