### ISSUE TITLE
[오류] p.357 배포 오류 

### ISSUE THREAD

**Issue by SUHYUNSHIM** [jojoldu/freelec-springboot2-webservice#750]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:
배포 도중 오류가 나서 질문합니다.

![image](https://user-images.githubusercontent.com/54768521/141444645-a3643b78-5ca7-4e9d-9a32-e033576789aa.png)
build 까지는 성공적으로 되었다고 하는데, deploy를 하면서부터 에러가 납니다. 
ruby의 버전을 올리라는 말과 함께 fail이 뜨는데, 찾아보니 ruby의 버전 문제라기보다는 오타인 경우가 많더군요.
몇 번을 봐도 오타도 못찾겠습니다. 도움을 요청합니다

aws 각 캡처화면입니다.

[codedeploy]
![image](https://user-images.githubusercontent.com/54768521/141444948-87ca54f8-40fe-463b-8d2a-cee2e1266b72.png)
![image](https://user-images.githubusercontent.com/54768521/141446008-b047a0e3-7b8a-4bdf-8660-cdde1132662a.png)
![image](https://user-images.githubusercontent.com/54768521/141445080-51a674c9-b599-4d7b-9be7-7e0a2f718a42.png)

에러 상세보기를 하면 
no implicit conversion of String into Integer 이렇게 써있습니다.
+codedeploy-agent.log 
![image](https://user-images.githubusercontent.com/54768521/141446806-278837e5-6d3a-40df-b435-487c9048256d.png)

[ec2]
![image](https://user-images.githubusercontent.com/54768521/141445810-c6cbaa8b-46ce-462c-94b0-3e22ce6ca18a.png)
![image](https://user-images.githubusercontent.com/54768521/141445852-ab847060-dc40-4231-b25a-b35cdc29a7ee.png)

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/SUHYUNSHIM/SHIM-s-Anatomy

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by LIMON029** [comment]
혹시 directory 수정해보셨나요??
.travis.yml 파일에서 cache부분에서 띄어쓰기가 없어야 하는 데 확인해보니까 있더라구요!
`'$HOME/ .m2/repository'`은 `'$HOME/.m2/repository'`로
`'$HOME/ .gradle'`은 `'$HOME/.gradle'`로 바뀌어야할 것 같습니다.

**Comment by SUHYUNSHIM** [comment]
@LIMON029 
아........ 그게 유일한 오타인것 같네요 
그 와중에 travis가 build를 혼자서 계속 했나봅니다. 크레딧을 다써서 결제하라는 알림이... 
나중에 깃헙 계정 새로 파서 시도해봐야겠습니다.  감사합니다!!😊
