### ISSUE TITLE
[오류] p.144 [등록] 버튼 클릭시 무반응

### ISSUE THREAD

**Issue by nykim12** [jojoldu/freelec-springboot2-webservice#755]
### 어떤 오류인가요?

오류설명 : [등록] 버튼 클릭시 무반응입니다ㅠㅠ

### 프로젝트 주소

* Github URL : https://github.com/nykim12/freelec-springboot2-webservice

### 오류 로그

![p144 등록 버튼 무반응](https://user-images.githubusercontent.com/91547976/145537247-34d177fc-8b23-4e74-8cd0-85e787ab9776.PNG)

**Comment by MoingXTwice** [comment]
index.js 만드셨나요?

**Comment by nykim12** [comment]
> index.js 만드셨나요?

네ㅠㅠ

**Comment by MoingXTwice** [comment]
footer.mustache 에서 index.js 를 추가한 경로가 <script src="/static/js/app/index.js"></script> 으로 되어있으시네요
/static을 빼시고
<script src="/js/app/index.js"></script>
로 수정해보시길 바랍니다

**Comment by nykim12** [comment]
> ### 어떤 오류인가요?
> 오류설명 : [등록] 버튼 클릭시 무반응입니다ㅠㅠ
> 
> ### 프로젝트 주소
> * Github URL : https://github.com/nykim12/freelec-springboot2-webservice
> 
> ### 오류 로그
> ![p144 등록 버튼 무반응](https://user-images.githubusercontent.com/91547976/145537247-34d177fc-8b23-4e74-8cd0-85e787ab9776.PNG)
