### ISSUE TITLE
p.287 쿼리 실행

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#76]
![image](https://user-images.githubusercontent.com/49624922/71116358-5bebe580-2217-11ea-9c79-c9cbe95ae05f.png)

갑자기 세션이 나오는데 어디가 문제인지 모르겠습니다 ㅜ

![image](https://user-images.githubusercontent.com/49624922/71116322-4bd40600-2217-11ea-8615-6c3e22750cd8.png)

**Comment by jinyeanseok** [comment]
혹시나 해서 use webservice; 이렇게 하면 실행이 되긴하는데 상관이 없을까요?

**Comment by jojoldu** [comment]
@jinyeanseok 네! 물론입니다.
use 라는 명령어는 현재 MySQL 서비스에 생성된 database (스키마)를 선택하는 명령어입니다.
use webservice; 로 하시는건 처음 MySQL 생성하시고 만드신 database를 선택하는것이라
보편적으로 사용되는 명령어입니다 :)

**Comment by jinyeanseok** [comment]
친절히 답변해주셔서 감사합니다 동욱님! ㅎㅎ

**Comment by jojoldu** [comment]
@jinyeanseok 넵 :) 언제든 편하게 질문주세요!
