### ISSUE TITLE
p.285 RDS 접속 정보 등록

### ISSUE THREAD

**Issue by TDCIAN** [jojoldu/freelec-springboot2-webservice#77]
![image](https://user-images.githubusercontent.com/52792962/71137820-ba7f8680-224c-11ea-9b4f-1015d7e5e319.png)

안녕하세요 개발자님!
개발자님 책 따라 나아가고 있다가

RDS 접속 정보 등록하는 곳까지 오게 되었습니다.

다름이 아니라
Host에 RDS의 엔드포인트에 복사해서 넣었고
유저 패스워드도 자격 증명 설정에 나와 있는대로 잘 맞춰서 넣었습니다.
![image](https://user-images.githubusercontent.com/52792962/71137873-f0bd0600-224c-11ea-9632-69adb9f8de9e.png)

그런데 계속 커넥션 에러가 발생하고, 혹시 될까 해서 그냥 Apply를 하고 OK를 했는데 그저 이렇게 빈 스키마가 나오네요...ㅜㅜ

![image](https://user-images.githubusercontent.com/52792962/71137960-3a0d5580-224d-11ea-9f65-990cc9369be6.png)

혹시 뭐가 잘못됐나 싶어서 AWS파트 처음부터 다시 차근차근 따라했는데 같은 곳에서 같은 문제가 생겼습니다... 혹시 무엇이 잘못됐을 때 이런 문제가 발생하는지 알 수 있을까요??ㅜㅜ

**Comment by jojoldu** [comment]
@TDCIAN 님 혹시 보안그룹 설정은 어떻게 되어있으신가요?
혹시 로컬 PC IP가 인바운드로 등록되어있으신지 확인이 되실까요?

**Comment by TDCIAN** [comment]
![image](https://user-images.githubusercontent.com/52792962/71238330-2cd49180-2347-11ea-884f-99d2e2ec9c85.png)

보안그룹 -> 인바운드에서 확인했을 때
제 PC IP가 SSH와 MySQL/Aurora의 소스로 입력되어 있는 상태입니다.

개발자님께서 확인해달라고 하신 내용이 이것이 맞았으면 좋겠네요ㅜㅜ

**Comment by TDCIAN** [comment]
> @TDCIAN 님 혹시 보안그룹 설정은 어떻게 되어있으신가요?
> 혹시 로컬 PC IP가 인바운드로 등록되어있으신지 확인이 되실까요?

![image](https://user-images.githubusercontent.com/52792962/71243231-3fed5e80-2353-11ea-856d-6f140a35fe7a.png)

보안그룹 -> 인바운드에서 확인했을 때
제 PC IP가 SSH와 MySQL/Aurora의 소스로 입력되어 있는 상태입니다.

개발자님께서 확인해달라고 하신 내용이 이것이 맞았으면 좋겠네요ㅜㅜ

+ 제가 맥북으로 장소를 옮겨가면서 책을 따라하는 경우도 있는데 혹시 그게 문제가 됐을 수도 있을까요??

**Comment by jojoldu** [comment]
@TDCIAN 음 해당 보안그룹이 RDS에 붙어 있는 보안그룹이신가요?
봤을때는 EC2에 붙은 보안그룹 같아서요!
보안그룹 하나로 RDS와 EC2 모두 사용하시나요?

* 보안그룹의 인바운드는 **와이파이를 사용하시면 계속 현재 IP가 변경되니 추가등록이 필요합니다**
