### ISSUE TITLE
[오류] p.304 ClientRegistrationRepository 오류

### ISSUE THREAD

**Issue by devmizz** [jojoldu/freelec-springboot2-webservice#772]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명:책의 설명을 따라 application-oauth.properties 파일도 등록하였고, deploy.sh 파일도 모두 수정했으나 여전히 ClientRegistrationRepository 에러가 발생합니다. 로컬에서는 잘 실행됩니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/beatoncheeze/springAws

### 오류 로그

어떤 오류인지 캡쳐해주세요.

- 오류 메세지
![image](https://user-images.githubusercontent.com/92210823/155297628-fc57aca7-bafa-4e16-927c-8d6a0a1e5311.png)

-deploy.sh 파일
![image](https://user-images.githubusercontent.com/92210823/155297761-520603c9-e4b8-4e6b-b10a-c2b7caf47f53.png)

-application-oauth.properties
![image](https://user-images.githubusercontent.com/92210823/155298350-0b1fff1b-77d7-4c31-8352-9c0782a6e7f4.png)

**Comment by KIMHAUN** [comment]
이거 해결하셨나요? ㅠㅠ

**Comment by devmizz** [comment]
아뇨.. 아쉽게도..

**Comment by KIMHAUN** [comment]
classpath:/를 절대경로로 하니까 에러가 바뀌긴 했어요
