### ISSUE TITLE
p.72 lombok constructor 생성 오류

### ISSUE THREAD

**Issue by mtreehouse** [jojoldu/freelec-springboot2-webservice#78]
생성자가 안만들어지고
lombok error: variable name not initialized in the default constructor private final String name;
이런 오류가 나서 확인해보니 gradle 5부터는 어노테이션을 구별해서 추가해줘야 한다고 하네요.

build.gradle에 기존 디펜던시 제거 후 아래 내용으로 업데이트 해주면 해결.
-----------------------------------------------------------
compileOnly 'org.projectlombok:lombok:1.18.10'
annotationProcessor 'org.projectlombok:lombok:1.18.10'

**Comment by jojoldu** [comment]
@mtreehouse 님 좋은 정보 감사합니다 :) ㅎㅎ
다만 이책은 그레이들 5 설정은 대상에 포함되지 않는데요 :)

예를 들어 위 코드에서 테스트 코드 실패가 될수있는데요 :)
그래서 실제로 필요한 설정은 

```
    dependencies {
        annotationProcessor 'org.projectlombok:lombok'
        implementation 'org.projectlombok:lombok'
        testAnnotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.projectlombok:lombok'
    }
    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }
```

다만 이 설정도 Querydsl 설정이 추가되면 또 변경이 필요하며,
스프링부트 버전이 추가로 올라가면서
혹은 인텔리제이 최신에서
추가로 설정이 또 필요하게 됩니다.

계속해서 추가 대응이 필요하기 때문에
개인적으로는 처음 실습은 그레이들 4로 하시는걸 권장드립니다 :)

**Comment by onlybj2** [comment]
책과 동일하게 실습하기 위해서는 최초에 인텔리제이를 설치한 후에 바로 아래 명령어로 버전을 책과 동일하게 맞춰주는것이 좋을 것 같습니다.

gradlew wrapper --gradle-version 4.10.2
