### ISSUE TITLE
[오류] p.316 401 invalid_client 오류

### ISSUE THREAD

**Issue by ssinsaram2** [jojoldu/freelec-springboot2-webservice#780]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 
책 따라서 코드 하나하나 확인해보면서 하고
모르는 부분은 구글링해가면서 했는데 아무리 해봐도 답이 안나옵니다 ㅠㅠ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/ssinsaram2/freelec-springboot2-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

![image](https://user-images.githubusercontent.com/19249641/157634427-462de2f8-c7a9-427b-90ab-5d3781c36c7e.png)

구글 EC2 주소 등록은 이렇게 했습니다.
![image](https://user-images.githubusercontent.com/19249641/157635360-b2ae6a32-d3fc-4b80-836a-d7d7f6c45b9f.png)

![image](https://user-images.githubusercontent.com/19249641/157635515-25f47409-e8c7-4614-ad68-4302858123ec.png)

네이버도 동일하게 등록하였습니다.

**Comment by ssinsaram2** [comment]
제가 스스로 해결하였습니다. 이슈 닫겠습니다!

**Comment by LeeJin0527** [comment]
어떻게 해결하셨나요..?

**Comment by ssinsaram2** [comment]
@LeeJin0527 저도 하다가 어떻게 되긴 했는데 챕터 8 부분을 다시 반복 했던 거 같습니다.
도움이 되지 못해서 죄송합니다 ㅠㅠ

**Comment by LeeJin0527** [comment]
감사합니다 ㅎㅎ
