### ISSUE TITLE
자동배포 deploy.sh deploy.sh permission denied 질문입니다.

### ISSUE THREAD

**Issue by chlwlgus4** [jojoldu/freelec-springboot2-webservice#79]
EC2에서 직접 zip파일까지 가서 chmod +x ./deploy.sh
치고 ./deploy.sh하면 실행은 됩니다만 
appspec으로 
![image](https://user-images.githubusercontent.com/44486865/71182678-d705d800-22b9-11ea-913b-32160a57df85.png)
실행이 안되는것같습니다.
![image](https://user-images.githubusercontent.com/44486865/71182696-e4bb5d80-22b9-11ea-80d0-e7e208afed75.png)
어디서 권한문제를 해결해야하죠

**Comment by nohseungrae** [comment]
Hi
