### ISSUE TITLE
p.19 필자 블로그 존재하지 않는 페이지 

### ISSUE THREAD

**Issue by jaeyeonling** [jojoldu/freelec-springboot2-webservice#8]
안녕하세요 많은 도움을 받고 있는 개발자입니다.

먼저 출간 축하드린다는 말씀 드리며, 제보할 내용이 있어 이슈 등록합니다!

p.19 아래

필자 블로그 (http://bit.ly/2OF8w8Y) 접속 시 https://jojoldu.tistory.com/category/IntelliJ 링크로 연결되며 

![image](https://user-images.githubusercontent.com/40811999/70240518-b5ccc400-17b0-11ea-99f2-9d36e5d72ece.png)

와 같이 나옵니다!

감사합니다.

**Comment by jojoldu** [comment]
@jaeyeonling 앗! 감사합니다 ㅠ
출간전에 카테고리명을 변경했더니 그렇게 되었네요 ㅠㅠ
제보 감사합니다 :)
블로그 카테고리명을 롤백해서 이제 정상 노출될거에요!
