### ISSUE TITLE
P.356-357 CodeDeploy 실패 [삽질해결]

### ISSUE THREAD

**Issue by RATSENO** [jojoldu/freelec-springboot2-webservice#80]
안녕하세요!
CodeDeploy까지 연동하여 자동 배포 시

The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.

로 failed to deploy 가 됩니다.

sudo service codedeploy-agent status
-The AWS CodeDeploy agent is running as PID 2632
까지 확인 하였으나 계속 저 오류로 배포가 실패되네요 ㅠ

바쁘신데 고생많으십니다.
시간 되실때 조언해주시면 많으 도움이 될것같습니다.
감사합니다.

**Comment by RATSENO** [comment]
![codedeploy](https://user-images.githubusercontent.com/36075136/71187757-0a009980-22c3-11ea-8772-a667d44ac919.PNG)

**Comment by RATSENO** [comment]
문제를 발견하여 해결하였습니다.

codedeploy-agent 로그 파일을 확인할 수 있다는것을 알게되어

푸티로 ec2 접속후
/var/log/aws/codedeploy-agent 경로에 위치한 로그 확인 결과

{\"error_code\":5,\"script_name\":\"\",\"message\":\"The specified key does not exist.\",\"log\":\"\"}"}
가 찍힌것을 확인하게 되었고

key라는 것은 s3 파일/디렉토리 명이었습니다.

그래서 .travis.yml 파일을 확인해보니
before_deploy:
부분의 zip파일을 옮기는 쪽에 파일명에 오타가 있는것을 확인하게 되었고

수정하여 정상적으로 배포되었습니다. ㅠㅠㅠㅠ 삽질 2시간 반만에 해결되어서 너무 기뻐
혹시나 제가 남긴 이슈를 보시는 분들께 도움이 되고자 히스토리 남깁니다.

**Comment by jojoldu** [comment]
@RATSENO 와! 해결하신것 멋지십니다!
자바와 다르게 이런 인프라와 관련된 문제는 정말 해결하는 경험 하나하나가 소중한데요 :)
그 경험을 얻으신것 같아서 정말 축하드립니다!

**Comment by blackarea** [comment]
감사합니다! 덕분에 codedeploy-agent 로그 파일이 있는 것을 알게되어서 문제 해결했습니다. 
저 같은 경우는 appspec.yml 파일 이름 오타였네요..

**Comment by kchung1995** [comment]
저도 비슷한 경우를 발견했는데 해결했습니다!
appspec.yml 파일의 위치가 잘못됐었네요 ㅠㅠ
appspec.yml이 존재하지 않거나 내용에 문제가 있는 경우에 해당 deploy error가 나오나 봅니다

**Comment by dkswnkk** [comment]
감사합니다. 저도 codedeploy-agent 부분에 로그 파일이 있는 걸 알게 되었고, 
마찬가지로 "The specified key does not exist." 부분에서 오류가 났는데 해결하게 되었습니다.

**Comment by f1v3-dev** [comment]
감사합니다!
오류가 발생해서 codedeploy-agent 로그 파일을 확인하였는데
>The deployment failed because the application specification file specifies only a source file ({\\\"destination\\\"=>\\\"/home/ec2-user/app/step2/zip/\\\", \\\"overwrite\\\"=>true}). 

이와 같은 오류가 발생하여 appspec.yml 코드를 고쳐서 해결하였습니다.
 
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/ 
    overwrite: yes
```
