### ISSUE TITLE
[오류] p.288 MySQL와 연결을 하였지만, 실행에서 질문이 있습니다.

### ISSUE THREAD

**Issue by leekyungchang** [jojoldu/freelec-springboot2-webservice#800]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

**오류설명: MySQL와 연결을 하였지만, 실행에서 질문이 있습니다.**

```sql
use spring_rds;
```

<img width="843" alt="스크린샷 2022-06-01 오후 2 26 01" src="https://user-images.githubusercontent.com/72541544/171333894-e4e35575-0389-4441-8fe9-121dc50c1b96.png">

를 입력할 시, 성공적으로 실행됩니다.

&nbsp;

다만, `character_set`, `collation` 설정을 하려고 명령어를 입력했을 때

```sql
show variables like 'c%';
```

를 입력한 후, Execute Statement를 클릭하여 실행할 시, 
DB Navigator - Multiple statement execution

<img width="1141" alt="스크린샷 2022-06-01 오후 2 20 33" src="https://user-images.githubusercontent.com/72541544/171333701-db7b947e-c784-4eb8-9c26-c0613bbeb5f9.png">

이와 같이 Execute All from Caret 또는 Execute All 선택 하는 상황이 발생합니다.

둘 중 아무거나 버튼을 클릭해도 아무런 변화 및 실행 결과를 볼수가 없는 상태입니다.

&nbsp;

**Execute Statement의 오른쪽에 있는 Execute sql Script을 클릭할시,** 

<img width="950" alt="스크린샷 2022-06-01 오후 2 29 13" src="https://user-images.githubusercontent.com/72541544/171334251-ca724ed6-d1bd-47db-b244-f06c2cefdee5.png">

- Cmd Line interface : mysql로

<img width="980" alt="스크린샷 2022-06-01 오후 2 29 21" src="https://user-images.githubusercontent.com/72541544/171334266-cb405627-3aab-4515-bd54-8c38029413f2.png">

DB Navigator - Script execution error가 발생합니다.

&nbsp;

제가 실행하는 방법이 잘못된 걸까요?

`Execute Statement`를 클릭했지만, 위와 같은 상황이 발생하여 적게 되었습니다.
현재 어떠한 상황인지 감이 오지를 않아 적게 되었습니다.
원래 이와 같이 실행되는걸까요..?

**Comment by leekyungchang** [comment]
아 제가 책 내용을 놓친것 같습니다.
그냥 실행이 아닌, 
책에서 설명하신 '드래그로 선택한 후 실행하면 된다.'를 실행하니 잘되네요!

**Comment by SteadyKim** [comment]
드래그로 선택한 후 실행하면 된다. 가 정확히 무슨 뜻인가요?? ㅠㅠ 저도 같은 오류를 겪고 있는데 책에 그 설명이 어디있는지 모르겠습니다

**Comment by kaitekang** [comment]
> 드래그로 선택한 후 실행하면 된다. 가 정확히 무슨 뜻인가요?? ㅠㅠ 저도 같은 오류를 겪고 있는데 책에 그 설명이 어디있는지 모르겠습니다

말 그대로 "show variables like 'c%';" 쿼리를 실행할 때는 쿼리문을 드래그 하여 블록 처리한 후 실행하시면 됩니다.
"show variables like 'c%';" 쿼리를 실행할 때마다 "DB Navigator - Multiple statement execution" 오류가 발생했는데
해당 쿼리문을 드래그 하고 실행하니 테이블이 잘 뜨네요.
<img width="707" alt="Screen Shot 2023-01-24 at 14 18 47 PM" src="https://user-images.githubusercontent.com/40019739/214217494-d69e13ec-426d-45dd-a4f7-46cbeaa9aa95.png">

**Comment by sihyunjojo** [comment]
감사합니다.. 저도 한참 해매다가 발견했네요
