### ISSUE TITLE
p.75~76 static import 관련 문의입니다.

### ISSUE THREAD

**Issue by joshua-qa** [jojoldu/freelec-springboot2-webservice#81]
동욱님 안녕하세요, 책보고 가볍게 한번씩 실습해보고 있는데요~

한 가지 궁금한게 생겨서 질문 드립니다.

책 버전 : 초판
환경 구성 : Boot 2.1.7 RELEASE, Gradle 4.10.2, Java 8

75~76 페이지의 테스트 코드 작성중, `import static org.hamcrest.Matchers.is` 가 있는데요.
이 부분이 자동완성 추천으로 노출되지 않는 이슈가 있어서, 혹시 제가 설정을 빼먹은건지 궁금해졌습니다.
(이 Repo를 참고하여 환경 구성을 진행했습니다)

![image](https://user-images.githubusercontent.com/18359200/71184105-922f7080-22bc-11ea-818e-1e79e7d003c3.png)
저에게 보여지는 자동완성 추천 리스트는 이렇습니다.

사실 이 부분은 직접 입력하면 간단하게 해결되는 문제입니다만, Alt + Enter를 이용해서 자동완성 추천을 보고 채워넣는 경우 약간의 혼동이 발생할 수 있을 것 같아서요~
바쁘시지 않을 때 확인 부탁드립니다~!

### 번외
74페이지의 문장 중 ..... 자세한 설명은 백기선님의 유튜브 **ssertJ가** JUnit의 ......... 이 부분에 오타가 있는데 2쇄 이후에는 수정 되었는지 궁금합니다.
(71페이지의 HelloReponseDto도 HelloResponseDto 로 수정되어야 할 것 같은데, 이건 이미 수정하셨을거 같네요)

**Comment by mtreehouse** [comment]
is() 괄호상태에서 alt+Enter누르면 뜹니다~ assertThat 같은 경우도 assertThat() 까지 입력 후 alt+Enter 입력하면 import static method가뜹니다.

**Comment by jojoldu** [comment]
@joshua-qa 님 구매해주셔서 감사합니다!
인텔리제이에서 assertThat으로 선언된 문장에서 is 할 경우에는 coreMatcher가 자동완성목록에 등장하는데,
mvc 선언문에서는 자동완성 목록에 등장하지 않습니다 ㅠ
별도로 설정이 필요하면 될것 같긴한데 아직 찾아보진 못한 상태입니다 ㅠ
말씀해주신 김에 한번 설정방법을 찾아보겠습니다.

말씀해주신 오타는 2쇄에 반영되어서 나갑니다 :)
제보 다시한번 감사드립니다!
