### ISSUE TITLE
p.311 Permission denied

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#82]
![image](https://user-images.githubusercontent.com/49624922/71194630-a92b8e00-22cf-11ea-9041-260287f9e704.png)

![image](https://user-images.githubusercontent.com/49624922/71194679-be082180-22cf-11ea-9aa0-6c66eba35080.png)

혹시 틀린곳이 있을까요? 

-Dspring.profiles.active=real \ 이 부분에서 오가 계속나서 

application-real-db.properties와 관련된 파일 다 보았는데

모르겠습니다 ㅜㅜ

**Comment by jinyeanseok** [comment]
nohup 파일입니다.
![image](https://user-images.githubusercontent.com/49624922/71197260-9071a700-22d4-11ea-8737-31de855de8ac.png)

**Comment by jojoldu** [comment]
음 맨밑에 nohup을 보시면 아시겠지만
접근하려는 파일명이 application-oauth.properties**,** 입니다.
콤마 (,)가 추가되어있는데요.

아래 코드를 그대로 사용하시면 잘되는지 확인해보시겠어요?

```
nohup java -jar \
    -Dspring.config.location=classpath:/application.properties,classpath:/application-$IDLE_PROFILE.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \
    -Dspring.profiles.active=$IDLE_PROFILE \
    $JAR_NAME > $REPOSITORY/nohup.out 2>&1 &
```

**Comment by jinyeanseok** [comment]
댓글 남겨주신 코드 그대로 사용해보았는데 
![image](https://user-images.githubusercontent.com/49624922/71253716-01b06900-236c-11ea-8acf-b029b573a955.png)

이런 오류가 발생했습니다. 

그리고 

curl localhost:8080 명령어를 실행해보니

![image](https://user-images.githubusercontent.com/49624922/71253782-39b7ac00-236c-11ea-9894-be85af8c2fe7.png)

![image](https://user-images.githubusercontent.com/49624922/71253800-4936f500-236c-11ea-8607-772def67a276.png)

다음과 같은 오류가 발생했습니다.

**Comment by jinyeanseok** [comment]
삽질 끝에 해결했습니다!!!

동욱님 혹시 궁금한게 있는데요

책에 있는 코드랑 위 댓글에 알려주신 코드랑 왜 다른건가요?

둘 중에 아무거나 적용해도 상관 없는건가요??

**Comment by jojoldu** [comment]
@jinyeanseok 앗? 아닙니다 위에서 제가 드린 코드는 책의 10장에서 진행되는 **무중단 배포시에 사용되는 코드**입니다.
현재 이슈로 얘기해주신 코드는 8장인 배포 자동화 코드라서 둘이 다르게 보인거라고 생각하시면 됩니다:)
제가 드린 코드가 왜 사용되는지 8~10장까지 차례로 소개됩니다.

8장에서 사용하신 스크립트 코드가 책 실습시에 문제가 없었는데 혹시 어떤게 원인이셨을까요?

**Comment by jinyeanseok** [comment]
아하 알겠습니다 더 공부하겠습니다
감사합니다 동욱님!

**Comment by IMHOJEONG** [comment]
혹

> 삽질 끝에 해결했습니다!!!
> 
> 동욱님 혹시 궁금한게 있는데요
> 
> 책에 있는 코드랑 위 댓글에 알려주신 코드랑 왜 다른건가요?
> 
> 둘 중에 아무거나 적용해도 상관 없는건가요??
> 
> 책에 있는 코드를 사용하면 오류가 나오긴 합니다.

@jinyeanseok 님 혹시 어떻게 해결하셨는지 알려주실 수 있나요?
저도 같은 에러가 발생한 상태에서 해결 방법이 궁금해서요...

**Comment by jinyeanseok** [comment]
@IMHOJEONG 

삽질한 결과

\ 가 색이 변해야 인식이 되었다는 뜻인데요

이 코드 그대로 한번 해보시겠어요?

```
nohup java -jar \
    -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \
    -Dspring.profiles.active=real \
    $REPOSITORY/$JAR_NAME 2>&1 &
```

**Comment by IMHOJEONG** [comment]
![chertestsets](https://user-images.githubusercontent.com/11308147/71316118-2ad91280-24ae-11ea-8945-2824217cbce2.PNG)

네 저도 같은 코드로 작성했는데, Error starting tomcat context 오류가 뜨는 상태라서요

**Comment by IMHOJEONG** [comment]
@jinyeanseok 덕분에 해결했습니다.
제 오타가 너무 많았네요... 도와주셔서 정말 감사합니다.
오늘 하루 이 오류만 찾아봤는데... 오타 때문에 시간을 다 날렸네요..
감사합니다!

**Comment by Juyeon-Lee** [comment]
저도 같은 오류가 나서 여기 보고 도움 받았습니다! 
**저는 properties 사이에 콤마 다음 공백을 넣었더니 오류가 나더라고요.**
저처럼 오류 나는 사람들을 위해서 한마디 남깁니다ㅎㅎ
