### ISSUE TITLE
[1판] p.220 SeucrityConfig 오타 수정  

### ISSUE THREAD

**Issue by IMHOJEONG** [jojoldu/freelec-springboot2-webservice#83]
안녕하세요, 스프링을 공부중인 학생입니다.
다름이 아니라, 1판의 p.220의 8번째, 9번째 줄의 SeucrityConfig를 SecurityConfig로 오타 수정해야 한다고 생각합니다.

**Comment by jojoldu** [comment]
@IMHOJEONG 악!
제보 감사합니다 ㅠㅠㅠ
수정해놓겠습니다!

**Comment by IMHOJEONG** [comment]
아닙니다. 이렇게 모두가 책을 만들어 가는 거 같아 매우 기분이 좋습니다.

**Comment by jojoldu** [comment]
@IMHOJEONG 앗 네 맞습니다 :)
해당 오타를 제보 받아서 3쇄에는 반영해서 나갈 예정입니다!
제보 고맙습니다 :)
