### ISSUE TITLE
[오류] p.305페이지

### ISSUE THREAD

**Issue by Hotmintchoco** [jojoldu/freelec-springboot2-webservice#830]
### **오류설명:**

application-oauth.properties파일을 생성하고 작성을 완료했습니다. 
기존의 파일에서 가져와서 그대로 붙여넣기한 내용 입니다.
![oauth파일](https://user-images.githubusercontent.com/95326550/190415798-1f273aa6-6c41-4150-9664-315792a37cf4.png)

이후에 deploy.sh파일도 수정하였습니다.
![오류1](https://user-images.githubusercontent.com/95326550/190416350-3952bb57-5d98-4a58-9d5b-974242c41742.png)

하지만 아래의 캡쳐본처럼 마지막에 
[ec2-user@springboot2-webservice step1]$ nohup: appending output to ‘nohup.out’ 에러가 발생합니다.
![오류2](https://user-images.githubusercontent.com/95326550/190416778-02b31e9b-75cc-4fa4-8a76-989dcc1a4184.png)

이외에 문제가 있었던 내용은 303페이지에서 vim nohup.out을 실행하였지만 ClientRegistrationRepository를 찾을 수 없다는 에러가 발생하지 않고 아래와 같은 모습으로 실행이 되었습니다.
![vim nohup out 작동시](https://user-images.githubusercontent.com/95326550/190417374-0e3dddfd-5a50-4f11-a357-528a93d98cc8.png)

기존과 차이점은 Amazon Linux 1이 아닌 2를 사용하였습니다. jdk 버전은 11버전이고 인텔리제이는 현재 Ultimate버전으로 사용하고 있습니다. 
이외에 프로젝트명 정도만 변경해서 실습하고 이외에는 다 책의 내용대로 했습니다. 많이 바쁘시겠지만 도움을 주셨으면 합니다.

* Github URL: https://github.com/Hotmintchoco/springboot-webservice

### 오류 로그

어떤 오류인지 캡쳐해주세요.

**Comment by SeolYoungKim** [comment]
$JAR_NAME > $REPOSITORY/nohup.out 2>&1 &

위와 같이 jar 파일의 출력이 > $REPOSITORY/nohup.out 으로 지정되어야 하는데
스크립트 맨 마지막 부분을 책이랑 조금 다르게 작성한 것 같습니다. 한번 확인해보시면 좋을 것 같아요!

**Comment by Hotmintchoco** [comment]
> 

![변경한 deploy](https://user-images.githubusercontent.com/95326550/190532072-1fc1aa98-1b96-42bc-aafc-94ef03567262.png)
와 같이 변경을 했습니다. 말씀하신 내용대로 한지는 모르겠지만.. 그래도 따라 변경했는데 오류는 발생하지 않지만,

![deploy sh 실행화면](https://user-images.githubusercontent.com/95326550/190532156-0fd9147f-e16f-4e97-936c-f8e0b35e0e67.png)

해당 화면처럼 책에서 작동해야 한다고 하는 tomcat서버 실행은 하지 않습니다.

**Comment by SeolYoungKim** [comment]
그렇게 수행하시고 난 후, `vim nohup.out` 명령 을 이용해서 nohup.out 파일에 서버 실행내역이 있는지 확인해주실 수 있을까요..?!

**Comment by Hotmintchoco** [comment]
![화면 캡처 2022-09-16 114347](https://user-images.githubusercontent.com/95326550/190545506-123abf0b-7577-4cdb-b8e1-d41a68697ea6.png)
이렇게 나옵니다.

**Comment by SeolYoungKim** [comment]
두 번째 로그를 보니 `No active profile set...` 이라고 적혀있습니다.

이는 프로필 파일(설정 파일)이 제대로 적용이 안 된 것으로 보입니다..! 그래서 선생님께서 올려주신 deploy.sh 파일을 보니 오탈자가 약간 있는 것 같습니다.

-Dspring.config.location으로 설정 파일 옵션을 넣어준 곳에 `application.properries` -> `application.properties` 로 변경해주셔야 할 것 같고, `classpath:/application.properties,/home/ec2...` 이렇게 서로 다른 설정 파일은 `.` 이 아닌 `,(콤마)`로 바꿔보셔야 할 것 같습니다. 

책이랑도 한번 비교를 해보시면 좋을 것 같아요!

**Comment by Hotmintchoco** [comment]
감사합니다. 말씀하신대로 오타를 수정하니까 프로필 파일에는 적용이 되었습니다. 톰캣 서버가 실행된다는 부분 외에는 정상적으로 작동하는 듯 합니다.
