### ISSUE TITLE
p.171 맨 아래 문단 오타 

### ISSUE THREAD

**Issue by Rok93** [jojoldu/freelec-springboot2-webservice#85]
p.171 그림 5-10 아래에 

여기서 [승인된 리디렉션 URL] 항목만 .... (X)-> 여기서 [승인된 리디렉션 URI] 항목만 (O)

URL이 아닌 URI 인 것 같습니다. (사소한 오타)

**Comment by jojoldu** [comment]
@Rok93 헉 ㅠㅠ 오타 제보 감사합니다 ㅠㅠ 
사소하지만 치명적인 오타였습니다 :)
제보 감사드립니다!
