### ISSUE TITLE
p.181 antMatchers("/api/v1/**").hasRole ... 설명 관련 질문이 있습니다.

### ISSUE THREAD

**Issue by iumoum** [jojoldu/freelec-springboot2-webservice#86]
'설명에는 POST 메소드 이면서 /api/vi/** 주소를 가진' 이라고 설명되어있는데 그러기 위해서는 HttpMethod.POST가 인자로 추가되어야 하지 않는지 궁금합니다.

**Comment by jojoldu** [comment]
@iumoum 아! 넵 맞습니다.
말씀하신대로 POST 값이 설정값에 있으면 설명대로 POST 메소드이면서 특정 주소를 가진 API만 차단이 되는데,
이는 설명이 오타입니다 ㅠ
POST 메소드만 허용하는 설정을 초기 책 설정에 넣었다가,
불필요할것같다고 하여 설정을 제거했는데 설명은 수정을 반영 못했습니다 ㅠ
제보 감사합니다!
