### ISSUE TITLE
305p deploy.sh 명령어 코드 질문있습니다. 

### ISSUE THREAD

**Issue by sa1341** [jojoldu/freelec-springboot2-webservice#87]
아래처럼 oauth 설정파일 추가하고 deploy.sh 수정을 하였습니다.

![스크린샷 2019-12-21 오전 3 05 35](https://user-images.githubusercontent.com/22395934/71280594-fcb8dd00-239e-11ea-904f-e5b550fd1cd5.png)

계속 이렇게 jar 파일에 접근할 수 없다고 에러가 발생하는데.. 혹시 제가 위에 배포 쉘에 넣은 명령어가 틀렸을까요? 

![스크린샷 2019-12-21 오전 3 05 18](https://user-images.githubusercontent.com/22395934/71280573-ef035780-239e-11ea-9251-c7ec66a0d676.png)

**Comment by IMHOJEONG** [comment]
저도 그 부분 하고 있는데, 
혹시 -Dspring.config.location 옵션 추가하실 때 양쪽에 \ 기호들 없애서 진행해보셨나요?
제 생각에는 저기에 추가해야 한다는 것을 표현하기 위해서 넣은 느낌이 들어서요....

**Comment by jinyeanseok** [comment]
nohup java -jar \
    -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \
    -Dspring.profiles.active=real \
    $REPOSITORY/$JAR_NAME 2>&1 &

이대로 한번 해보시겠어요?

**Comment by jinyeanseok** [comment]
<nohup java -jar \
    -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \
    -Dspring.profiles.active=real \
    $REPOSITORY/$JAR_NAME 2>&1 &>

**Comment by jinyeanseok** [comment]
`nohup java -jar \
    -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \
    -Dspring.profiles.active=real \
    $REPOSITORY/$JAR_NAME 2>&1 &`

**Comment by jinyeanseok** [comment]
저도 삽질하다가 안건데 

java -jar \ 하고 다음줄로 넘어가서 -Dspring~~ 이렇게 하셔야 적용 되는 것 같아요.

\ 다음에는 다음줄부터 코드작성 해야 하는 것 같습니다!

**Comment by jinyeanseok** [comment]
java -jar \ 하고 다음줄로 넘어가시면
\이 하얀색 말구 다른색으로 변하시는지 확인해보실 수 있나요?

**Comment by jinyeanseok** [comment]
```
nohup java -jar \
    -Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \
    -Dspring.profiles.active=real \
    $REPOSITORY/$JAR_NAME 2>&1 &
```

**Comment by sa1341** [comment]
감사합니다. jinyeanseok님 말씀대로 \ 하고 다음줄로 넘어가도 접근이 안된다고해서.. 다시 지우고 \ 했는데 갈색으로변해서 다시 실행해보니 잘됩니다. IMHOJEONG님도 관심가져주셔서 감사합니다 ㅠㅠ 잘돌아가네요

**Comment by IMHOJEONG** [comment]
> 감사합니다. jinyeanseok님 말씀대로 \ 하고 다음줄로 넘어가도 접근이 안된다고해서.. 다시 지우고 \ 했는데 갈색으로변해서 다시 실행해보니 잘됩니다. IMHOJEONG님도 관심가져주셔서 감사합니다 ㅠㅠ 잘돌아가네요

네 저도 다시 해보니 잘 되네요 ㅎㅎ;; @jinyeanseok , @sa1341 님들 덕분에 오늘도 하나 배우고 갑니다. 감사합니다!

**Comment by jojoldu** [comment]
@sa1341 @IMHOJEONG @jinyeanseok 님 모두들 감사드립니다.

```
\ 기호는 한줄 띄어쓰기 인지라 \ 이후에는 다음줄에 코드를 써주시면 됩니다!
```
