### ISSUE TITLE
p.352 로드밸런서 활성화

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#88]
![image](https://user-images.githubusercontent.com/49624922/71295277-917f0300-23be-11ea-87c9-c6b9f9fddb76.png)

사진과 같이 로드 밸런서 활성화를 선택하면

아래 대상 그룹을 선택해야하는데  옵션 없음으로 표시되며

대상 그룹을 선택하지 않으면 배포 그룹이 생성되지 않습니다.

어디서 잘못된것일까요?

**Comment by jojoldu** [comment]
@jinyeanseok 앗 이 책에서는 로드밸런서는 다루지 않습니다!
체크를 제거해주시면 됩니다:)
