### ISSUE TITLE
[오류] p.316 한글깨짐 오류

### ISSUE THREAD

**Issue by milkbottle0305** [jojoldu/freelec-springboot2-webservice#881]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: curl 명령어를 통해 확인하면 한글이 잘나오는데 로컬에서 접속하면 ??로 한글이 깨져서 출력됩니다. 왜 이런건지 알고싶습니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 

### 오류 로그

어떤 오류인지 캡쳐해주세요.
![image](https://user-images.githubusercontent.com/52454255/227959755-4c7d64fa-0e56-449b-91ad-a1b94ebb110d.png)
![image](https://user-images.githubusercontent.com/52454255/227960109-68bf7a03-5e36-4189-a475-091d312b950f.png)

**Comment by anthem53** [comment]
인코딩 문제인 것 같습니다.
