### ISSUE TITLE
p.357

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#89]
![image](https://user-images.githubusercontent.com/49624922/71307990-ce3c1000-2439-11ea-848e-48c521276da3.png)
travis, s3 연동 시 이런 에러 발생합니다.

무슨 문제인가요? ㅜ

**Comment by jinyeanseok** [comment]
때려 죽어도 안됐었는데 

동욱님이 2018년도에 블로그에 작성하는 자료에는

.travis.yml파일에

on:
      repo: jojoldu/springboot-webservice
      branch: master

다음과 같은 코드를 작성하고 푸시하니까

성공이 되는데 이렇게 해도 되는건가요..?

**Comment by jinyeanseok** [comment]
travis에서는 성공이라고  표시되어있는데

codedeploy에서는 

![image](https://user-images.githubusercontent.com/49624922/71314049-36641380-2485-11ea-94de-24b8d07f6b3b.png)

위 사진과 같이 계속 돌고만 있는데 어디서부터 잘못된걸까요?

알고싶습니다 ㅜㅜ

**Comment by jinyeanseok** [comment]
ec2환경에서 로그를 찍어보니

이런 로그가 찍혔습니다 성공은 했는데 

어디서 막힌건지...

![image](https://user-images.githubusercontent.com/49624922/71328365-5b29bb00-2559-11ea-8a20-a470795c9d2d.png)
![image](https://user-images.githubusercontent.com/49624922/71328366-5b29bb00-2559-11ea-97f0-9f8861a4f618.png)

**Comment by jojoldu** [comment]
@jinyeanseok 일단 첫번째 에러는 s3에 접근권한이 없다고해서 발생한 에러입니다.

![image](https://user-images.githubusercontent.com/7760496/71351223-7971d400-25b6-11ea-987b-a90aa3d4760e.png)

그리고 travis yml 설정은 현재 프로젝트걸 보셔도 아시겠지만,
별도로 저장소 위치를 지정안해도 가능합니다 :)

**Comment by jojoldu** [comment]
음 일단 해당 에러는 처음보는 형태라 조금 확인해서 추가 답변남기겠습니다!

**Comment by jojoldu** [comment]
@jinyeanseok 혹시 해당 이슈 아직 진행중이신가요?

**Comment by jojoldu** [comment]
답변이 없으셔서 해당 이슈는 클로즈하겠습니다.
