### ISSUE TITLE
p.53 톰캣 오타 

### ISSUE THREAD

**Issue by jaeyeonling** [jojoldu/freelec-springboot2-webservice#9]
아래에서 5번째 줄 "왜 계속 톰갯을 내렸다가 다시 실행하는 일을 반복할까요?" 에서 "톰갯" 오타인 것 같습니다!

**Comment by jojoldu** [comment]
@jaeyeonling 헉 ㅠㅠㅠ 넵넵 진짜 감사합니다! 3쇄에 바로 반영하겠습니다!

**Comment by jaeyeonling** [comment]
책을 읽으며 발견되는 내용에 대해 하나 씩 올리면 이슈가 많아지는 것 같은데 책을 다 읽고 정리해서 올리는게 보기 편하실까요!?

**Comment by jojoldu** [comment]
앗! 아닙니다 ㅎㅎ 바로바로 올려주시면 더 좋습니다 :)
편집자분과 실시간으로 얘기중이라서요!

**Comment by jaeyeonling** [comment]
넵 감사합니다 :)

**Comment by jojoldu** [comment]
크! 넵 정말 감사드립니다 :)
