### ISSUE TITLE
[오류] p.115

### ISSUE THREAD

**Issue by alswns1201** [jojoldu/freelec-springboot2-webservice#908]
### 어떤 오류인가요?
오류설명: 
PUT 수정 TEST 중에 오류입니다 .
 ResponseEntity<Long> responseEntity = restTemplate.exchange(url,HttpMethod.PUT,requestEntity,Long.class);
Error while extracting response for type [class java.lang.Long] and content type [application/json];

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL:   https://github.com/alswns1201/springboot/blob/main/src/test/java/com/java/effective/study/web/PostApiControllerTest.java

### 오류 로그
![image](https://github.com/jojoldu/freelec-springboot2-webservice/assets/150923177/d27e44cc-5b4f-40f2-8724-e3f4c3b55fa9)

**Comment by Gomdollee** [comment]
저도 똑같은 오류납니다 ㅠㅠ

**Comment by Gomdollee** [comment]
저는 해결하긴했는데 
Controller 쪽에서 PathVariable에 name을 지정해줬습니다 
   @PutMapping("posts/{id}")
    public Long update(@PathVariable(name = "id") Long id, @RequestBody PostsUpdateRequestDto requestDto){
        return postsService.update(id, requestDto);
    }
    이런식으로요 혹시나해서 댓글 남겨드립니다!

**Comment by linxizhu1209** [comment]
> 저는 해결하긴했는데 Controller 쪽에서 PathVariable에 name을 지정해줬습니다 @PutMapping("posts/{id}") public Long update(@PathVariable(name = "id") Long id, @requestbody PostsUpdateRequestDto requestDto){ return postsService.update(id, requestDto); } 이런식으로요 혹시나해서 댓글 남겨드립니다!

저도 name="id" 붙였더니 오류해결됐습니다!! 감사합니다

**Comment by alswns1201** [comment]
저도 해결 했습니다 저는 url /api/v1/posts 관련하여 오타가 있었습니다.
