### ISSUE TITLE
[1판] p.389 stop.sh에 누락된 부분이 있습니다.

### ISSUE THREAD

**Issue by iltaek** [jojoldu/freelec-springboot2-webservice#91]
stop.sh 의 첫 부분이
ABSDIR=$(dirname $ABSPATH) 로 시작하는데요,
이 앞에 ABSPATH=$(readlink -f $0) 이 추가되어야 할 것 같습니다. :)

**Comment by iltaek** [comment]
누락된 부분 포함하여 앞에 부분은 다음과 같이 고치면 될 것 같네요.
재미있게 책 잘 봤습니다! :)
```sh
#!/usr/bin/env bash

ABSPATH=$(readlink -f $0)
ABSDIR=$(dirname $ABSPATH)
source ${ABSDIR}/profile.sh
...
```

**Comment by jojoldu** [comment]
@iltaek 헉 제보 감사합니다!
