### ISSUE TITLE
p.352 CodeDploy 로드밸런서 설정

### ISSUE THREAD

**Issue by jinyeanseok** [jojoldu/freelec-springboot2-webservice#92]
ci 까지는 다 되었고 CodeDploy연동 중인데 삽질한 결과

책에는 로드밸런서 설정에 대한 정보가 없어서 

구글링을 통해 설정했지만

로드밸런서 쪽에 문제가 있다고 생각이 들었고,

구글링한 정보와 동욱님이 하신 설정과 다르지 않을까라는 생각이 들어서 그런데

혹시 로드밸런서 설정을 어떻게 하셨는지 알려주실 수 있으실까요?

**Comment by jinyeanseok** [comment]
구글링으로 로드밸런서 설정하고 

git push 시  Travis CI에서는 다음과 같은 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/49624922/71321670-7e744c00-2500-11ea-9fb5-0b487ca94c90.png)

**Comment by RATSENO** [comment]
안녕하세요 로드밸런서 부분은 모르겠지만
저는 책에 있는 내용 그대로 진행하였습니다.
Traivs에서 해당 오류가 난적이 있어서 도움이 되고자 제가 올렸던 이슈 공유 드립니다.
도움이 되셨으면 좋겠네요

https://github.com/jojoldu/freelec-springboot2-webservice/issues/80

**Comment by jinyeanseok** [comment]
로그밸런서 부분은 설정안하시고 되신건가요?
아직도 삽질중이지만 도움주셔서 감사합니다ㅎㅎ

**Comment by jojoldu** [comment]
앗 이미 아래 이슈에 댓글을 남겼지만,
이 책에서는 전혀 로드밸런서를 다루고 있지 않습니다.
체크해제하시면 됩니다.
아래 댓글 참고해주세요.

https://github.com/jojoldu/freelec-springboot2-webservice/issues/88#issuecomment-568426138

**Comment by jinyeanseok** [comment]
앗.... 책에는 선택하라고 되어 있어서 하는건줄 알았습니다 ㅜ

**Comment by jojoldu** [comment]
앗 **미체크된 이미지**를 함께 첨부해서 어떻게 선택하면 되는지 책에 기록했는데,
무조건 체크 하는 선택으로 보일수 있겠네요
오타로 제보해놓겠습니다!
감사합니다!

**Comment by jinyeanseok** [comment]
넵 감사합니다 ㅎㅎ
