### ISSUE TITLE
p.189 코드설명부분 번호 누락

### ISSUE THREAD

**Issue by Rok93** [jojoldu/freelec-springboot2-webservice#93]
p.189 ~ p.190 의 코드설명 4번 부분  코드에 넘버링이 안되어있습니다. 

넘버링이 가독성에 도움이 많이 됐기에 사소한 누락이지만 제보드립니다!!

**Comment by jojoldu** [comment]
@Rok93 제보 감사합니다! 3쇄에 반영해놓겠습니다 :)
