### ISSUE TITLE
395p 무중단 배포 테스트 질문있습니다.

### ISSUE THREAD

**Issue by sa1341** [jojoldu/freelec-springboot2-webservice#94]
책에 나와있는 배포 스크립트를 작성하고... 똑같이 작성했는데도 travis ci에서 계속 배포 실패가 나왔는데 혹시 무엇이 문제인지 알수 있을까요? 혹시 오타가 있을수도 있을거같아서 깃허브에 소스를 그대로 복붙해봐도 똑같은 이슈가 발생해서요 아래 로그를 보긴했지만.. 무슨 문제인지 막혀서 올리게되었습니다.

![스크린샷 2019-12-22 오후 10 06 00](https://user-images.githubusercontent.com/22395934/71322128-618f4700-2507-11ea-8b4c-3679aa1af081.png)

![스크린샷 2019-12-22 오후 10 06 10](https://user-images.githubusercontent.com/22395934/71322131-6522ce00-2507-11ea-8efa-5c32ff009375.png)

**Comment by jinyeanseok** [comment]
저랑 똑같으신데 p.357은 되셨나요??
저는 357page에서 같은 에러가 나서요 ㅜ

**Comment by sa1341** [comment]
아 혹시 배포 자동화 구성말씀하시는건가요? 저도 삽질 몇번하다보니 일단 ... step2 까진 배포 자동화 구성은 되긴했는데  deploy.sh에 있는 jar 파일 실행 명령어 nohup쪽 코드가 문제인건가 ㅠㅠ 일단 s3와 codedeploy쪽을 공부를 안해서 게속따라해보기만했는데 뭐가 문제인지 모르겠네요 ㅋㅋ

**Comment by jinyeanseok** [comment]
배포 자동화 할 때 deploy.sh도 바꿔줘야 하나요?

**Comment by jinyeanseok** [comment]
근데 제가 자동화 전에 s3 deploy연동에서 막혀서요 ㅜ

**Comment by jojoldu** [comment]
@sa1341 안녕하세요 :) 혹시 Code Deploy 로그는 어떻게 되어있으신가요?

**Comment by Huhsway** [comment]
저도 여기서 막혔는데 해결하셨나요?
