### ISSUE TITLE
[질문] p122. JPA Auditing

### ISSUE THREAD

**Issue by thingsbrain-joonho** [jojoldu/freelec-springboot2-webservice#96]
저는  도메인 클래스에 아래처럼 Hibernate annotation을 사용였었는데요.
@CreationTimestamp
private Timestamp regdate;
	
@UpdateTimestamp
private Timestamp updatedate;

책처럼 BaseTimeEntity를 만들어서 사용하면 어떤 장점이 있을가요?

**Comment by jojoldu** [comment]
@thingsbrain-joonho 님 질문 감사합니다 :)
일단 Hibernate annotation 을 저는 선호하진 않는데요.
그 이유는 여러 ORM 중에 꼭 하이버네이트만 쓸거라고 확정지을수 없기 때문입니다.

Hibernate는 여러 JPA 구현체 중에 하나일 뿐입니다.

* EclipseLink
* OpenJPA
* TopLink 
* Essentials

등 여러 구현체가 있고, 앞으로도 추가적으로 등장할 수 있습니다.

제가 웬만해선 Hibernate Annotation 을 선호하진 않는 이유가 혹시나 다른 구현체로 교체해야 될 경우 JPA 어노테이션 혹은 Spring 어노테이션이면 라이브러리외에 교체할게 없지만,
Hibernate 어노테이션을 쓰고 있다면 어노테이션들을 모두 대체가능한 다른 어노테이션으로 다 교체해야만 합니다.

굳이 같은 기능을 하는데, 명확한 단점을 갖고 있는 코드를 쓸 필요가 없기 때문에 사용하진 않습니다 :)

**Comment by thingsbrain-joonho** [comment]
답변 기다리고 있었는데 기다린 보람이 있네요 :)

**Comment by jojoldu** [comment]
@thingsbrain-joonho 넵 :) 감사합니다.
언제든 편하게 질문 남겨주세요!
