### ISSUE TITLE
외부 Security 파일 등록하지 않아도 오류 메세지가 나오지 않는 현상

### ISSUE THREAD

**Issue by irerin07** [jojoldu/freelec-springboot2-webservice#97]
안녕하세요.

초판 기준으로 304 페이지까지 진행을 했습니다.

진행을 하던중에 페이지 303~304에서 애플리케이션 실행에 실패하면서 나온다는 에러 메세지가 제 nohup.out에는 출력이 되어 있지 않습니다.

파일의 가장 아래로 가면 

Tomcat started on port(s): 8080 (http) with context path''
Started Application in 14.243 seconds (JVM running for 15.334)

이 두줄이 있고 에러 메세지는 찾아볼 수가 없네요.
![image](https://user-images.githubusercontent.com/39554427/71360133-2279f800-25d2-11ea-8a81-b5355939e950.png)

혹시 application-oauth.properties가 모르는 사이에 들어가 있는지 확인해봤지만 보이지는 않고..
![image](https://user-images.githubusercontent.com/39554427/71360018-bdbe9d80-25d1-11ea-9e2d-bfed73e6a5c9.png)

왜 이런 현상이 생기는 걸까요..?

**Comment by jojoldu** [comment]
@irerin07 님 제가 프로젝트 코드를 잠깐 보았는데요 :)
아래처럼 이미 properties에 **테스트용 값**을 넣어주셨습니다

![image](https://user-images.githubusercontent.com/7760496/71462671-600b9a80-27f7-11ea-8044-37d647962a87.png)

저처럼 아래 3개 값이 아예 없으셔야 합니다.

![image](https://user-images.githubusercontent.com/7760496/71462695-74e82e00-27f7-11ea-9d3f-f4cc86ea881c.png)

테스트용 값은 **테스트 properties**에 등록하셔야 합니다.
(책에서도 그렇게 되어있으실거에요!)

![image](https://user-images.githubusercontent.com/7760496/71462723-93e6c000-27f7-11ea-930d-ce7a68573098.png)

**Comment by irerin07** [comment]
@jojoldu 
앗! 그렇군요!
정말정말 감사합니다!!

**Comment by jojoldu** [comment]
@irerin07 넵 :) 또 안되시면 말씀주세요!
