### ISSUE TITLE
[1판] p.353 CodeDeployDefault.AllAtOnec 오타 수정

### ISSUE THREAD

**Issue by IMHOJEONG** [jojoldu/freelec-springboot2-webservice#98]
! 부분의 CodeDeployDefault.AllAtOnec를 AllAtOnce로 수정해야 할 거 같습니다.

**Comment by jinyeanseok** [comment]
@IMHOJEONG 님 혹시 352page에 로드밸런서 설정 어떻게 하셨나요??

**Comment by jojoldu** [comment]
@IMHOJEONG 제보 감사합니다 :)

**Comment by jojoldu** [comment]
@jinyeanseok 이미 아래 이슈에 댓글을 남겼지만,
이 책에서는 전혀 로드밸런서를 다루고 있지 않습니다.
체크해제하시면 됩니다.
아래 댓글 참고해주세요.

https://github.com/jojoldu/freelec-springboot2-webservice/issues/88#issuecomment-568426138

**Comment by IMHOJEONG** [comment]
@jinyeanseok 님 저도 지금 그 부분에서 고생중이라 @jojoldu 님 께서 알려주셔서 바로 다시 설정 후 해보려고 합니다 ㅠㅠㅠ

**Comment by IMHOJEONG** [comment]
> @IMHOJEONG 님 혹시 352page에 로드밸런서 설정 어떻게 하셨나요??

저는 원래 공식 문서 !(https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-getting-started.html) 를 참고해서 로드밸런서를 만든 다음에 했는데 안 되서 다른 방법을 찾아 보고 있었습니다.

**Comment by jinyeanseok** [comment]
@IMHOJEONG 
저도 로드밸런서 사용하는줄 알았는데 동욱님이 로드 밸런서 체크해제 하면 된다고 하십니다.
다시 저도 해보려구요!

**Comment by IMHOJEONG** [comment]
@jinyeanseok, @jojoldu 님 감사합니다.
덕분에 배포 자동화까지 해결 했네요.. 오타 때문에 ㅠㅠㅠ

@jinyeanseok 님 도움이 될 지 모르겠지만,
제 경우에는 The deployment failed because a specified file already exists at this location 이 오류 때문에 sudo rm -rf를 통해 app/step2/zip 파일을 새로 만들어서 해보니 작동합니다.

P.S 구글링 중 overwrite 옵션이 작동하는지 잘 하는지 잘 모르겠어서 지금은 overwrite: true로 두어서 실행하고 있습니다.

**Comment by mtreehouse** [comment]
mkdir ~/app/step2 && mkdir ~/app/step2/zip
이부분도 
mkdir -p ~/app/step2/zip
로 개선하면 좋을것같아요 ㅎㅎ

**Comment by jojoldu** [comment]
@mtreehouse 앗 제보 감사합니다 :)
