### ISSUE TITLE
[질문] deploy.sh 기동시의 rds 연동 질문 드립니다.

### ISSUE THREAD

**Issue by likerdo** [jojoldu/freelec-springboot2-webservice#99]
안녕하세요 책 재미있게 잘 보고 있습니다.

다름이 아니라 현재 310페이지까지 진행을 했는데요.

인텔리제이의 Database 뷰에서는 Maria DB와의 연동도 잘되고 다른 사용자도 생성이 가능합니다.

![ard](https://user-images.githubusercontent.com/8459344/71395691-4ed95700-265a-11ea-93bb-d279a2a6204e.png)

![sec](https://user-images.githubusercontent.com/8459344/71395795-d7f08e00-265a-11ea-9800-3fae8c4d0fd6.png)

다만 deploy.sh 기동시의 rds 연동에 관하여 다음의 에러 로그 등이 출력이됩니다.

![err_log](https://user-images.githubusercontent.com/8459344/71395735-9b249700-265a-11ea-8491-7a1552519cfa.png)

해결방법을 알 수 있을까요?

**Comment by IMHOJEONG** [comment]
이거 그 application-real-db.properties 오타거나 잘못 되었을 때 나오는 오류인데.... 
저도 일단 거기까지 밖에는...

**Comment by jojoldu** [comment]
@likerdo 님 질문 감사합니다 :)
일단 확인해볼 것은

1. ec2에서 mariadb 접근 체크
* 챕터 7.4를 참고해서 접근 체크를 해봅니다.
* 특히 사용자명,비밀번호,접속 주소를 다시 확인해봐주세요.

2. profile 체크
* -Dspring.profiles.active=real 옵션이 실행시 포함되었는지 확인합니다.

추가로 real-db 옵션이 포함되어있는지도 확인합니다.
nohup.out 최상단에 아래와 같은 로그가 있는지 확인합니다.

![image](https://user-images.githubusercontent.com/7760496/71463317-508d5100-27f9-11ea-9d8a-7573a1dce4b7.png)

```
The following profiles are active: real-oauth,oauth,real-db,real
```

위 옵션들은 모두 application-real.properties에 포함되어있는데

![image](https://user-images.githubusercontent.com/7760496/71463290-394e6380-27f9-11ea-84af-6f446ad4b67b.png)


한번 이 옵션들이 잘 되어있는지 확인해보시면 도움이 될것 같습니다.

혹시나 실행된 스프링 애플리케이션 상태가 궁금하시다면

```
ps -ef | grep java
```

![image](https://user-images.githubusercontent.com/7760496/71463378-8599a380-27f9-11ea-9935-60dfee453935.png)

로 확인해보시면 됩니다.

**Comment by likerdo** [comment]
친절하고 상세한 답변 감사합니다. 

일단 언급하신 부분들에 대하여 확인 해 보았습니다.

![spb-real](https://user-images.githubusercontent.com/8459344/71464776-f6db5580-27fd-11ea-921b-38dac0dff2f2.png)

![ec2-maria-conn](https://user-images.githubusercontent.com/8459344/71464788-ffcc2700-27fd-11ea-9f6e-c9595fd23f27.png)

![app-real](https://user-images.githubusercontent.com/8459344/71464789-0064bd80-27fe-11ea-8bf5-9e86b7bb5769.png)

![profile-real](https://user-images.githubusercontent.com/8459344/71464791-0064bd80-27fe-11ea-97f8-ccd931255a00.png)

실례가 안된다면 혹시 또 다른 의심이 되는 곳이 있을지 봐 주실 수 있을까요?

그리고 EC2와 RDS의 보안 그룹의 개념이 명확하게 이해가 안되어서 그런데 둘의 VPC ID가 서로 달라야 하는지요. 그리고 서브넷에 대한 구성도 달리 해줘야 하는지가 궁금합니다.

좋은 책과 빠른 피드백에 감사합니다.

**Comment by jojoldu** [comment]
@likerdo 님 위에서 언급하신것 로그에서 **real-db** profile이 계속 빠져있는것 같은데요 :)

![image](https://user-images.githubusercontent.com/7760496/71465182-39516200-27ff-11ea-811f-8055e2911421.png)

![image](https://user-images.githubusercontent.com/7760496/71465186-3ce4e900-27ff-11ea-9549-6ce46c4e8a9f.png)

정상적으로 실행될때는 아래와 같이 real-db도 포함되어야 해서요.

![image](https://user-images.githubusercontent.com/7760496/71465322-a107ad00-27ff-11ea-931b-87d17d7166d2.png)

오타가 있는지 좀 찾아보겠습니다.

**Comment by likerdo** [comment]
일단 RDS 를 재설치(5번 정도...) 해봤는데 해결이 안되서 퇴근하면 EC2 재설치 부터 해보려고 합니다. ㅠㅠ

**Comment by jojoldu** [comment]
@likerdo 음 일단 제가 봤을때는
applciation-real-db를 계속 사용하지 못하는것 같은데요!
(로그에서 active profile 에 oauth와 real만 존재, 정상적으로라면 oauth, real, real-db 3개가 출력되어야함)

properties 위치가 잘못된건지 혹은 다른 이유가 있는지 확인해보면 좋으것 같은데요.
일단 application-oauth.properties는 정상적으로 로드 하는것 같아 보이니,
application-oauth.properties 에 real-db 정보도 함께 추가해서 실행해보시는건 어떠실까요?
즉, application-oauth.properties 파일 최하단에
아래 정보 (@likerdo 님의 application-real-db.properties 정보) 를 추가로 등록하는것입니다.
(아래는 **샘플**입니다)

```
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:mariadb://rds주소:포트명(기본은 3306)/database명
spring.datasource.username=db계정
spring.datasource.password=db계정 비밀번호
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
```

**Comment by likerdo** [comment]
말씀하신 부분을 테스트 해보았으나 결과는 동일 했습니다. 
로그를 보면 프로파일의 활성화 여부와는 무관하게 
real-db의 계정 정보와 host를 읽어오는 것(붉게 가린 부분)을 확인이 되는 것 같습니다. 

![001](https://user-images.githubusercontent.com/8459344/71542444-10b99b80-29aa-11ea-9bca-be527153f71f.jpg)
![002](https://user-images.githubusercontent.com/8459344/71542446-12835f00-29aa-11ea-9bfb-7ce9201c7da5.jpg)

일단 현재 상황은 이러합니다. 계속 꾸준히 살펴 주셔서 감사합니다. 연말 잘 보내세요! ㅠㅠ

**Comment by likerdo** [comment]
본 이슈는 해결되었습니다. 
원인은 설정파일의 오타였는데 진도가 막혀서 이것저것 해보던 와중에 
putty의 폰트를 교체하고 배경을 비롯한 색상 들을 보기 편하게 바꾸니 바로 보이더라구요. 

바보같은 저의 실수 ㅠㅠ
다른 부분은 크게 문제가 없어서 책 끝까지 진행했습니다.
다시 한번 좋은 책을 집필 해 주셔서 감사합니다.

**Comment by jojoldu** [comment]
@likerdo 앗 해결되셔서 정말 다행입니다! ㅎㅎ

**Comment by rktldhkd** [comment]
저도 똑같이 real-db.properties 인식 안되는 문제에, 오탈자까지 다 검사해봤는데 도저히 안되서, EC2 인스턴스를 재부팅하고 putty로 다시 접속해서 deploy 파일 실행하니까 잘 되더라고요^^
